const { chromium } = require('playwright');
const assert=require('node:assert/strict');
const base=process.env.PT_TEST_URL||'http://127.0.0.1:8765/';
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.PT_CHROME||undefined,args:['--no-sandbox']});const ctx=await browser.newContext({viewport:{width:1440,height:1050}});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await ctx.route('**/pt-analytics.js',r=>r.fulfill({body:''}));await ctx.route('**/api/analytics',r=>r.fulfill({body:'{}'}));
 const go=async path=>{console.log('Route',path);await page.goto(base+'apps/'+path,{waitUntil:'domcontentloaded'});};
 await go('signal-audit/');await page.locator('#signal-form').waitFor();await page.locator('#signal-refresh').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#signal-refresh')&&!document.querySelector('#signal-refresh').disabled);
 await page.locator('[name=original]').fill('Test bot says $NVDA bullish, publication retained.');await page.locator('#signal-extract').click();assert.equal(await page.locator('[name=symbol]').inputValue(),'NVDA');await page.locator('[name=bot]').fill('QA BOT');await page.locator('[name=publishedAt]').fill(new Date(Date.now()-8*86400000).toISOString().slice(0,16));await page.locator('[name=horizon]').selectOption('1');await page.getByRole('button',{name:'核对并保存原始记录'}).click();await page.getByRole('heading',{name:'QA BOT · NVDA · 看多'}).waitFor();assert.equal(await page.locator('[data-s-archive]').count(),1);await page.locator('[data-s-archive]').click();assert.match(await page.locator('#decision-app').innerText(),/已归档/);await page.reload();await page.locator('[data-s-archive]').waitFor();
 await go('watch-inbox/');await page.locator('#watch-add').click();await page.locator('[name=name]').fill('QA Monitor');await page.locator('[name=url]').fill('https://example.com/test');await page.locator('[name=intent]').fill('Wait until registration opens');await page.locator('[name=rule]').selectOption('contains');await page.locator('[name=value]').fill('OPEN');await page.getByRole('button',{name:'保存等待条件'}).click();
 async function capture(text){await page.locator('[data-w-capture]').click();await page.locator('#watch-capture [name=text]').fill(text);await page.getByRole('button',{name:'保存并比较'}).click();}
 await capture('closed');assert.match(await page.locator('#decision-app').innerText(),/已建立基线/);await capture('OPEN now');assert.match(await page.locator('#decision-app').innerText(),/新近满足/);await capture('OPEN now, details updated');assert.match(await page.locator('#decision-app').innerText(),/尚未处理/);await page.locator('[data-w-done]').click();assert.match(await page.locator('#decision-app').innerText(),/这次变化已处理/);
 await page.locator('[data-w-ask]').click();await page.locator('#ask-form').waitFor();await page.locator('#ask-build').click();await page.waitForFunction(()=>document.querySelector('#ask-output').value.includes('Wait until registration opens'));assert.ok((await page.locator('#ask-output').inputValue()).includes('https://example.com/test'));await page.locator('#ask-save-packet').click();await page.locator('[data-ask-load]').waitFor();
 await go('stock-alert/');await page.locator('#holding-add').waitFor();await page.waitForFunction(()=>document.querySelector('#holding-refresh')&&!document.querySelector('#holding-refresh').disabled);
 assert.ok((await page.locator('[data-decision=holdings]').boundingBox()).y<240,'Portfolio must start near the top, ahead of fixed option grid');await page.locator('#holding-add').click();for(const [name,value] of Object.entries({symbol:'NVDA',quantity:'10',cost:'100',lower:'9999',upper:'20000',note:'QA thesis'}))await page.locator('#holding-form [name='+name+']').fill(value);await page.getByRole('button',{name:'保存持仓',exact:true}).click();await page.locator('[data-h-review]').waitFor();assert.match(await page.locator('[data-decision=holdings]').innerText(),/触及复查下界/);await page.locator('[data-h-review]').click();await page.locator('#holding-review-form [name=note]').fill('Evidence reviewed, keep observing');await page.locator('#holding-review-form [name=reviewDate]').fill(new Date(Date.now()+90*86400000).toISOString().slice(0,10));await page.getByRole('button',{name:'保存复查',exact:true}).click();
 await go('thesis-lab/?symbol=NVDA');await page.locator('[data-h-edit]').waitFor();assert.match(await page.locator('[data-decision=holdings]').innerText(),/NVDA/);await page.locator('[data-h-ask]').click();await page.locator('#ask-build').waitFor();await page.locator('#ask-build').click();assert.ok((await page.locator('#ask-output').inputValue()).includes('QA thesis'));
 await go('3c-scout/');await page.locator('#purchase-add').waitFor();await page.waitForFunction(()=>document.querySelector('#purchase-refresh')&&!document.querySelector('#purchase-refresh').disabled);await page.locator('#purchase-add').click();for(const [name,value] of Object.entries({name:'QA Headphone',keyword:'headphone',variant:'v2',target:'100',need:'Open design',requirement:'USB desktop',evidence:'Manufacturer document checked'}))await page.locator('#purchase-form [name='+name+']').fill(value);await page.locator('#purchase-form [name=compatibility]').selectOption('yes');await page.getByRole('button',{name:'保存候选',exact:true}).click();await page.locator('[data-p-price]').click();await page.locator('#purchase-price-form [name=price]').fill('90');await page.locator('#purchase-price-form [name=url]').fill('https://example.com/price');await page.getByRole('button',{name:'保存价格证据'}).click();assert.match(await page.locator('[data-decision=shopping]').innerText(),/满足候选购买条件/);
 await go('meal-orbit/');await page.locator('#meal-plan-form').waitFor({state:'visible'});await page.locator('#meal-plan-form [name=exclude]').fill('鸡蛋,虾');await page.getByRole('button',{name:'生成今晚菜单',exact:true}).click();const meals=await page.locator('#meal-options').innerText();assert.ok(!meals.includes('鸡蛋'));assert.ok(!meals.includes('虾仁'));await page.locator('[data-meal-pick]').first().click();assert.match(await page.locator('[data-decision=meal]').innerText(),/已选安排 · 1/);
 await go('eastside-weekend/');await page.locator('#weekend-plan-form').waitFor();await page.waitForFunction(()=>document.querySelector('[data-decision=weekend]').textContent.includes('活动快照')&&!document.querySelector('[data-decision=weekend]').textContent.includes('活动快照 未提供'));
 await page.locator('#weekend-plan-form [name=date]').fill('2026-10-03');await page.locator('#weekend-plan-form [name=start]').selectOption('9');await page.locator('#weekend-plan-form [name=hours]').selectOption('6');await page.getByRole('button',{name:'生成半日方案'}).click();if(await page.locator('[data-weekend-pick]').count()){await page.locator('[data-weekend-pick]').first().click();assert.match(await page.locator('[data-decision=weekend]').innerText(),/已选安排 · 1/);}
 for(const slug of ['signal-audit','watch-inbox','ask-gpt','stock-alert','thesis-lab','3c-scout','eastside-weekend','meal-orbit']){
  await go(slug+'/');await page.waitForTimeout(250);await page.screenshot({path:'/tmp/pt-'+slug+'.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(150);const over=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);assert.equal(over,false,slug+' mobile overflow');await page.screenshot({path:'/tmp/pt-'+slug+'-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1050});
 }
 // Scope registration and persistence are checked without creating real user data.
 await page.goto(base,{waitUntil:'domcontentloaded'});for(const name of ['Signal Audit','Watch Inbox','Ask GPT'])assert.ok((await page.locator('body').innerText()).includes(name));
 assert.deepEqual(errors,[]);console.log('Browser flows passed: 8 routes, shared holdings, signal immutability/archive, pending monitor alerts, GPT handoff, purchase evidence, meal filters, weekend planning, mobile overflow.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
