import assert from 'node:assert/strict';
import {metric,thesisState,holdingReview,purchaseState,watchCheck,diffLines,signalResult,signalSummary,planEvents,fresh} from '../../apps/_decision/models.mjs';
const now=Date.parse('2026-09-30T22:00:00Z');
assert.equal(metric({quarters:[]},'margin'),null);
assert.equal(metric({quarters:[{end:'2026-07-31',revenue:null,operatingIncome:10}]},'margin'),null);
const c={updatedAt:'2026-09-30T10:00:00Z',quarters:[{end:'2025-07-31',revenue:100},{end:'2026-07-31',revenue:120,operatingIncome:24}]};
assert.ok(Math.abs(metric(c,'revenueYoY')-20)<1e-8);
assert.equal(thesisState({metric:'margin',op:'gte',threshold:21},c,now).state,'broken');
assert.equal(thesisState({metric:'margin',op:'gte',threshold:10},{...c,stale:true},now).state,'unknown');
assert.equal(fresh('garbage',36,now),false);assert.equal(fresh('2027-01-01',36,now),false);
const h={symbol:'ABC',quantity:5,cost:50,lower:70,movePct:5,reviews:[{price:100,quarter:'2026-04-30'}]};
assert.ok(holdingReview(h,{price:60,lastTradeAt:'2026-09-30T20:00Z'},c,[],null,now).reasons.some(x=>x.key==='lower'));
assert.equal(holdingReview(h,{price:60,lastTradeAt:'2026-08-01'},c,[],null,now).price,null);
const p={target:100,currency:'USD',variant:'v2',compatibility:'yes',observations:[{price:90,currency:'USD',variant:'v2',at:'2026-09-30T20:00Z'}]};
assert.equal(purchaseState(p,now).state,'ready');
assert.equal(purchaseState({...p,currency:'JPY'},now).state,'unknown');
assert.equal(purchaseState({...p,variant:'v1'},now).state,'unknown');
assert.equal(purchaseState({...p,compatibility:'unknown'},now).state,'unknown');
assert.equal(purchaseState({...p,observations:[{...p.observations[0],at:'2025-01-01'}]},now).state,'unknown');
assert.equal(watchCheck({rule:'contains',value:'open'},null,{text:'open'}).state,'baseline');
assert.equal(watchCheck({rule:'contains',value:'open'},{text:'closed'},{text:'OPEN now'}).state,'matched');
assert.equal(watchCheck({rule:'contains',value:'open'},{text:'open'},{text:'still open'}).state,'noise');
assert.equal(watchCheck({rule:'absent',value:'waitlist'},{text:'join waitlist'},{text:'join now'}).state,'matched');
assert.equal(watchCheck({rule:'lte',value:'100'},{text:'120'},{text:'99'}).state,'matched');
assert.equal(watchCheck({rule:'lte',value:'100'},{text:'120'},{text:'price 99 2026'}).state,'unknown');
assert.deepEqual(diffLines('old\nsame','new\nsame'),{added:['new'],removed:['old']});
const market={symbols:{ABC:{history:[{d:'2026-09-24',o:80,h:90,l:70,c:85},{d:'2026-09-25',o:100,h:110,l:90,c:105},{d:'2026-09-28',o:106,h:120,l:102,c:115}]},SPY:{history:[{d:'2026-09-25',o:100,c:102},{d:'2026-09-28',o:102,c:104}]}}};
const s={symbol:'ABC',publishedAt:'2026-09-24T15:00Z',recordedAt:'2026-09-24T15:01Z',horizon:2,direction:'long',method:'next-open'};
const r=signalResult(s,market,now);assert.equal(r.entryDate,'2026-09-25');assert.equal(r.state,'complete');assert.ok(Math.abs(r.returnPct-15)<1e-8);assert.ok(Math.abs(r.adverse+10)<1e-8);assert.equal(r.retrospective,false);assert.ok(Math.abs(r.benchmarkReturn-4)<1e-8);
assert.ok(signalResult({...s,direction:'short'},market,now).returnPct<0);
assert.equal(signalResult({...s,publishedAt:'2026-09-28T20:00Z'},market,now).state,'pending');
assert.equal(signalResult({...s,publishedAt:'2025-01-01T10:00Z'},market,now).state,'missing');
assert.equal(signalResult({...s,method:'observe'},market,now).state,'unscored');
assert.equal(signalResult({...s,recordedAt:'2026-09-28T22:00Z'},market,now).retrospective,true);
const stats=signalSummary([{signal:s,result:r},{signal:{...s,archived:true},result:{...r,returnPct:-5}},{signal:s,result:{...r,retrospective:true}},{signal:s,result:{state:'missing'}}]);assert.equal(stats.total,4);assert.equal(stats.completed,2);assert.equal(stats.wins,1);assert.equal(stats.retrospective,1);
const ev=[{start:'2026-10-03T10:00:00',city:'Kirkland',free:true},{start:'2026-10-03T13:00:00',city:'Kirkland',free:true},{start:'2026-10-03',city:'Seattle',free:true},{start:'2026-10-03',city:'Kirkland',free:true,stale:true}];
assert.equal(planEvents(ev,{date:'2026-10-03',city:'Kirkland',freeOnly:true,start:10,hours:4}).length,1);
console.log('Decision rules: all assertions passed');
