
import {$,esc,link,money,read,save,toast,json,meta,boot,backups,safeURL,stamp} from '../_lab/core.js';
boot();let data,personal=read('games',{}),tab='discover',remote=[],filter='';
const API='https://www.cheapshark.com/api/1.0/';
function all(){const map=new Map((data?.games||[]).map(g=>[g.id,g]));for(const p of Object.values(personal))if(p.game&&!map.has(p.game.id))map.set(p.game.id,p.game);for(const g of remote)map.set(g.id,g);return [...map.values()]}
function targetHit(g){const p=personal[g.id];return p?.wish&&!p.owned&&Number.isFinite(p.target)&&Number.isFinite(g.price)&&g.price<=p.target}
function write(){save('games',personal)}
function render(){
 $('#app').innerHTML='<div class="notice">PC 游戏 · USD。快照价格可能已变化；地区、兑换平台、DLC 与版本内容请在购买前核对商店页面。价格数据由 CheapShark 提供。</div><div class="toolbar tabs">'+[['discover','发现'],['wishlist','愿望单'],['target','到价'],['owned','已拥有']].map(([k,v])=>'<button data-tab="'+k+'" aria-pressed="'+(tab===k)+'">'+v+'</button>').join('')+'<button id="refreshWish">更新愿望单报价</button></div><div class="toolbar"><input id="query" type="search" placeholder="搜索游戏名称（全库搜索建议使用英文名）" aria-label="游戏名称" value="'+esc(filter)+'"><button id="searchRemote">全库搜索</button><label>最高价 USD<input id="maxPrice" type="number" min="0" step="1" placeholder="不限" style="width:120px"></label><label>排序<select id="sort"><option value="discount">折扣最高</option><option value="price">价格最低</option><option value="rating">评价最高</option></select></label></div><p id="searchStatus" class="status"></p><div id="games" class="grid"></div><dialog id="gameDialog"></dialog>';
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();window.scrollTo({top:0,behavior:'smooth'})});
 $('#query').oninput=e=>{filter=e.target.value;cards()};$('#maxPrice').oninput=cards;$('#sort').onchange=cards;
 $('#searchRemote').onclick=search;
 $('#query').onkeydown=e=>{if(e.key==='Enter')search()};
 $('#refreshWish').onclick=async()=>{const ids=Object.keys(personal).filter(id=>personal[id].wish&&!personal[id].owned);if(!ids.length){toast('先将游戏加入愿望单');return}$('#refreshWish').disabled=true;let ok=0;for(const id of ids){try{const g=await details(id);personal[id].game=g;remote=remote.filter(x=>x.id!==id).concat(g);ok++;cards()}catch{}await new Promise(r=>setTimeout(r,350))}write();$('#refreshWish').disabled=false;toast('已更新 '+ok+'/'+ids.length+' 个报价；失败项目保留旧数据')};
 cards();
}
async function details(id){const x=await json(API+'games?id='+encodeURIComponent(id));if(!x.info||!Array.isArray(x.deals))throw new Error('未取得有效报价');const offers=x.deals.map(o=>({id:String(id),dealID:o.dealID,price:Number(o.price),regular:Number(o.retailPrice),discount:Number(o.savings||0),store:data.stores?.[o.storeID]||'商店 '+o.storeID,url:'https://www.cheapshark.com/redirect?dealID='+encodeURIComponent(decodeURIComponent(o.dealID))})).sort((a,b)=>a.price-b.price);const old=all().find(g=>g.id===String(id))||{};return {...old,...offers[0],id:String(id),title:x.info.title,steamID:x.info.steamAppID,thumb:x.info.thumb,offers,price:offers[0]?.price??null,providerLow:x.cheapestPriceEver?.price!==undefined?Number(x.cheapestPriceEver.price):null,checkedAt:new Date().toISOString()}}
async function search(){const q=$('#query').value.trim();if(q.length<2){toast('请输入至少两个字符');return}$('#searchRemote').disabled=true;$('#searchStatus').textContent='正在查询完整游戏库…';
 try{const rows=await json(API+'games?title='+encodeURIComponent(q)+'&limit=30');if(!Array.isArray(rows))throw new Error('搜索结果格式异常');remote=rows.map(g=>({id:String(g.gameID),title:g.external,price:Number(g.cheapest),regular:null,discount:0,thumb:g.thumb,steamID:g.steamAppID,offers:[],url:g.cheapestDealID?'https://www.cheapshark.com/redirect?dealID='+encodeURIComponent(decodeURIComponent(g.cheapestDealID)):'https://www.cheapshark.com/',checkedAt:new Date().toISOString()}));tab='discover';cards(true);$('#searchStatus').textContent='全库搜索找到 '+rows.length+' 个结果 · 打开「管理／比价」查看报价'}
 catch(e){$('#searchStatus').textContent='全库搜索暂不可用：'+e.message+'。仍可筛选已缓存游戏。'}finally{$('#searchRemote').disabled=false}}
function cards(onlyRemote=false){const q=filter.toLowerCase().trim(),max=$('#maxPrice').value,sort=$('#sort').value;let list=(onlyRemote?remote:all()).filter(g=>(!q||g.title.toLowerCase().includes(q))&&(max===''||Number.isFinite(g.price)&&g.price<=Number(max))&&(tab==='discover'||tab==='wishlist'&&personal[g.id]?.wish&&!personal[g.id]?.owned||tab==='owned'&&personal[g.id]?.owned||tab==='target'&&targetHit(g)));list.sort((a,b)=>sort==='price'?(a.price??Infinity)-(b.price??Infinity):sort==='rating'?(b.rating||0)-(a.rating||0):(b.discount||0)-(a.discount||0));
 $('#games').innerHTML=list.length?list.map(g=>{const p=personal[g.id]||{};return '<article class="card '+(targetHit(g)?'target':p.wish?'saved':'')+'">'+(g.thumb?'<img class="thumb" src="'+esc(safeURL(g.thumb))+'" loading="lazy" alt="">':'')+'<div class="row"><span class="tag">'+esc(g.store||'最低报价')+'</span><span class="tag">'+(p.owned?'已拥有':targetHit(g)?'已到目标价':p.wish?'愿望单':Math.round(g.discount||0)+'% OFF')+'</span></div><h3>'+esc(g.title)+'</h3><div class="price">'+money(g.price)+' <span class="old">'+(g.regular?money(g.regular):'')+'</span></div><small>'+((g.reviews||0)>0?'Steam 好评 '+g.rating+'% · '+g.reviews+' 条':'暂无评价数据')+'</small><p class="muted">'+(Number.isFinite(p.target)?'目标价 '+money(p.target):'未设置目标价')+(g.observedLow!==undefined?'<br>本站观察低价 '+money(g.observedLow)+' · 自 '+esc(g.observedSince):'')+'</p><div class="toolbar"><button data-wish="'+esc(g.id)+'">'+(p.wish?'取消愿望':'＋ 愿望单')+'</button><button data-detail="'+esc(g.id)+'">管理／比价</button>'+link(g.url,'查看优惠')+'</div></article>'}).join(''):'<div class="empty">没有符合条件的游戏。可切换筛选，或搜索完整游戏库。</div>';
 document.querySelectorAll('[data-wish]').forEach(b=>b.onclick=()=>{const g=all().find(g=>g.id===b.dataset.wish),p=personal[g.id]||{};personal[g.id]={...p,wish:!p.wish,game:g};write();cards();toast(personal[g.id].wish?'已加入愿望单':'已移出愿望单')});
 document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>manage(b.dataset.detail));
}
async function manage(id){let g=all().find(g=>g.id===id);const d=$('#gameDialog');d.style.cssText='width:min(680px,94vw);max-height:90vh;border:1px solid var(--line);border-radius:18px;background:var(--card);color:var(--ink);padding:24px';d.innerHTML='<p>正在读取报价…</p>';d.showModal();
 try{g=await details(id);remote=remote.filter(x=>x.id!==id).concat(g)}catch{toast('实时查询失败，显示最后快照')}
 const p=personal[id]||{};d.innerHTML='<div class="row"><h2>'+esc(g.title)+'</h2><button id="closeDetail" aria-label="关闭">×</button></div><form id="manageForm"><div class="form-grid"><label>目标价 USD<input name="target" type="number" min="0" step=".01" value="'+esc(p.target??'')+'"></label><label>已拥有版本／平台<input name="edition" maxlength="200" value="'+esc(p.edition||'')+'" placeholder="例如 Steam 本体；缺少 DLC"></label><label class="check"><input name="wish" type="checkbox" '+(p.wish?'checked':'')+'>加入愿望单</label><label class="check"><input name="owned" type="checkbox" '+(p.owned?'checked':'')+'>已拥有</label><label class="wide">购买笔记<textarea name="notes" maxlength="2000">'+esc(p.notes||'')+'</textarea></label></div><button type="submit" class="primary">保存设置</button></form><h3 style="margin-top:20px">商店报价</h3><p class="muted">'+(g.checkedAt?'查询时间 '+esc(stamp(g.checkedAt)):'快照时间 '+esc(stamp(data.updatedAt)))+'</p>'+((g.offers||[]).length?g.offers.map(o=>'<p class="row"><span>'+esc(o.store||'商店')+' · '+money(o.price)+'</span>'+link(o.url,'前往优惠')+'</p>').join(''):'<p>当前无详细报价。</p>')+(Number.isFinite(g.providerLow)?'<p>CheapShark 记录历史低价：'+money(g.providerLow)+'</p>':'')+'<small>同名游戏仍可能有地区和版本限制；“已拥有”按你手工登记判断，不自动读取 Steam 账户。</small>';
 $('#closeDetail').onclick=()=>d.close();$('#manageForm').onsubmit=e=>{e.preventDefault();const x=new FormData(e.target),target=x.get('target');personal[id]={wish:x.has('wish'),owned:x.has('owned'),target:target===''?null:Number(target),edition:x.get('edition'),notes:x.get('notes'),game:g};write();d.close();cards();toast('游戏设置已保存')};
}
backups('games',()=>personal,v=>{if(!v||Array.isArray(v)||typeof v!=='object'||Object.keys(v).length>1000||!Object.entries(v).every(([id,p])=>/^\d+$/.test(id)&&p&&(!p.game||typeof p.game.title==='string')&&(p.target==null||Number.isFinite(p.target)&&p.target>=0)))throw new Error('愿望单格式不正确');personal=v;write();render()});
try{data=await json('./data/deals.json');meta(data);render()}catch(e){$('#app').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}
