const APPS=[
 {id:'daily-nexus',name:'Daily Nexus',icon:'⌂',cat:'today',catName:'今日与看板',accent:'#7c73ff',desc:'日历、备忘、发现、音乐、专注与微工具的日常中枢。',url:'apps/daily-nexus/?v=20260827-coversdrawer1',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/daily-nexus',tags:['今日','日历','备忘','专注','音乐','工具'],update:'本机实时 · 聚合入口'},
 {id:'deskboard',name:'DeskBoard',icon:'▦',cat:'today',catName:'今日与看板',accent:'#22a6f2',desc:'iPad 行情、天气、快讯、RSS 与常用链接看板。',url:'apps/deskboard/?v=20260826-5',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/deskboard',tags:['股票','天气','RSS','新闻','iPad'],update:'实时组件 · RSS 15 分钟'},
 {id:'rss-dashboard',name:'RSS Orbit',icon:'◉',cat:'media',catName:'媒体与 ACG',accent:'#4cac78',desc:'取代 Feedly 的中文 RSS 收件箱、未读管理、稍后读与 OPML 迁移。',url:'apps/rss-dashboard/?v=20260827-6',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/rss-dashboard',tags:['RSS','Feedly','新闻','订阅','稍后读','OPML'],update:'08:00 起每 4 小时 · Cloudflare 即时刷新'},
 {id:'stock-alert',name:'Stock Alert',icon:'↗',cat:'money',catName:'资金与决策',accent:'#25c790',desc:'自选股、期权活跃度、技术模型与价格提醒。',url:'apps/stock-alert/?v=20260826-5',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/stock-alert',tags:['股票','期权','技术面','估值','提醒'],update:'交易时段每小时'},
 {id:'qf-tool',name:'QF Tool',icon:'◇',cat:'money',catName:'资金与决策',accent:'#e6a83c',desc:'投资、信用卡奖励、Deal、副业机会与决策日志。',url:'apps/qf-tool/?v=20260826-5',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/qf-tool',tags:['投资','奖励','信用卡','副业','日志'],update:'每天 08:00 PT'},
 {id:'3c-scout',name:'3C Scout',icon:'⌁',cat:'shopping',catName:'购物与发现',accent:'#f16e5b',desc:'中文优先的新品、好 Deal 与极客商品发现流。',url:'apps/3c-scout/?v=20260826-5',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/3c-scout',tags:['3C','Deal','新品','购物','数码'],update:'每天约 08:15 PT'},
 {id:'meal-orbit',name:'Food Orbit',icon:'筷',cat:'life',catName:'生活与饮食',accent:'#f08a45',desc:'吃什么转盘、附近餐厅、中文食谱和本机收藏。',url:'apps/meal-orbit/?v=20260826-5',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/meal-orbit',tags:['餐厅','食谱','转盘','收藏','小红书'],update:'实时查询 · 本机收藏'},
 {id:'tsugi-checker',name:'Tsugi',icon:'継',cat:'media',catName:'媒体与 ACG',accent:'#c768df',desc:'漫画、轻小说、音乐、游戏发行与中文 ACG 新闻追踪。',url:'apps/tsugi-checker/?v=20260827-coversdrawer1',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/tsugi-checker',tags:['漫画','小说','游戏','音乐','ACG'],update:'每天 09:17 PT'}
];
const CATS=[{id:'home',name:'今日总览',icon:'⌂'},{id:'today',name:'今日与看板',icon:'▦'},{id:'money',name:'资金与决策',icon:'↗'},{id:'shopping',name:'购物与发现',icon:'⌁'},{id:'life',name:'生活与饮食',icon:'筷'},{id:'media',name:'媒体与 ACG',icon:'継'}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const db={get(k,f){try{let v=localStorage.getItem('ptu.'+k);return v===null?f:JSON.parse(v)}catch{return f}},set(k,v){localStorage.setItem('ptu.'+k,JSON.stringify(v))}};
let favorites=db.get('favorites',['daily-nexus','stock-alert','tsugi-checker','3c-scout']);
let recents=db.get('recents',[]),active=null,results=[],selected=0;

function buildNav(){
  $('#primaryNav').innerHTML='<div class="nav-label">UNIVERSE</div>'+CATS.map(c=>`<button class="nav-item" data-cat="${c.id}"><span>${c.icon}</span><span>${c.name}</span>${c.id==='home'?'':`<em>${APPS.filter(a=>a.cat===c.id).length}</em>`}</button>`).join('');
  $('#mobileNav').innerHTML=[CATS[0],CATS[1],CATS[2],CATS[5],{id:'more',name:'更多',icon:'•••'}].map(c=>`<button data-mobile="${c.id}"><span>${c.icon}</span><span>${c.name.replace('与看板','').replace('与决策','').replace('与 ACG','')}</span></button>`).join('');
  $$('[data-cat]').forEach(b=>b.onclick=()=>showCategory(b.dataset.cat));
  $$('[data-mobile]').forEach(b=>b.onclick=()=>b.dataset.mobile==='more'?openMenu():showCategory(b.dataset.mobile));
}
function card(a){let fav=favorites.includes(a.id);return `<article class="app-card" data-app="${a.id}" style="--accent:${a.accent}"><div class="card-top"><span class="app-symbol">${a.icon}</span><button class="fav ${fav?'on':''}" data-fav="${a.id}">${fav?'★':'☆'}</button></div><h3>${a.name}</h3><p>${a.desc}</p><div class="card-foot"><span class="chip">${a.catName}</span><button class="launch" data-launch="${a.id}">打开 →</button></div></article>`}
function render(){
  let pinned=favorites.map(id=>APPS.find(a=>a.id===id)).filter(Boolean),shown=[...pinned,...APPS.filter(a=>!pinned.includes(a))].slice(0,4);
  $('#favoriteGrid').innerHTML=shown.map(card).join('');
  $('#allApps').innerHTML=CATS.slice(1).map(c=>({c,apps:APPS.filter(a=>a.cat===c.id)})).filter(x=>x.apps.length).map(({c,apps})=>`<section class="category-block" id="category-${c.id}"><h3>${c.icon} ${c.name.toUpperCase()} · ${apps.length}</h3><div class="app-grid">${apps.map(card).join('')}</div></section>`).join('');
  renderRecent();renderSources();bindCards();
}
function bindCards(){
  $$('[data-launch]').forEach(b=>b.onclick=e=>{e.stopPropagation();openApp(b.dataset.launch)});
  $$('.app-card').forEach(c=>c.onclick=e=>{if(!e.target.closest('[data-fav]'))openApp(c.dataset.app)});
  $$('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFavorite(b.dataset.fav)});
}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];db.set('favorites',favorites);render();if(active?.id===id)$('#favoriteButton').textContent=favorites.includes(id)?'★':'☆'}
function renderRecent(){let items=recents.map(id=>APPS.find(a=>a.id===id)).filter(Boolean).slice(0,4);$('#recentList').innerHTML=items.length?items.map(a=>`<button class="recent-item" data-recent="${a.id}"><span class="mini">${a.icon}</span><span><strong>${a.name}</strong><small>${a.update}</small></span><em>→</em></button>`).join(''):'<div class="empty">打开一个工具后会显示在这里</div>';$$('[data-recent]').forEach(b=>b.onclick=()=>openApp(b.dataset.recent))}
function renderSources(){$('#sourceList').innerHTML=APPS.map(a=>`<a class="source-item" href="${a.repo}" target="_blank" rel="noopener"><span>${a.icon}</span><div><strong>${a.name}</strong><small>${a.update}</small></div><em>在线</em></a>`).join('')}
function updateNav(id){$$('[data-cat]').forEach(b=>b.classList.toggle('active',b.dataset.cat===id));$$('[data-mobile]').forEach(b=>b.classList.toggle('active',b.dataset.mobile===id||(active&&b.dataset.mobile===active.cat)))}
function showHome(){active=null;$('#homeView').hidden=false;$('#frameView').hidden=true;$('#toolFrame').src='about:blank';$('#pageEyebrow').textContent='COMMAND CENTER';$('#pageTitle').textContent='今日总览';$('#collectionTitle').textContent='快速启动';render();updateNav('home');closeMenu()}
function showCategory(id){if(id==='home'){if(location.hash!=='#/home')location.hash='#/home';showHome();return}showHome();let c=CATS.find(x=>x.id===id),apps=APPS.filter(a=>a.cat===id);$('#pageEyebrow').textContent='COLLECTION';$('#pageTitle').textContent=c.name;$('#collectionTitle').textContent=c.name;$('#favoriteGrid').innerHTML=apps.map(card).join('');bindCards();updateNav(id);if(location.hash!==`#/category/${id}`)location.hash=`#/category/${id}`;setTimeout(()=>$('#favoriteGrid').scrollIntoView({behavior:'smooth',block:'start'}),20)}
function openApp(id){
  let a=APPS.find(x=>x.id===id);if(!a)return;active=a;recents=[id,...recents.filter(x=>x!==id)].slice(0,8);db.set('recents',recents);
  window.location.assign(a.url);
}
function tick(){let d=new Date();$('#todayDate').textContent=new Intl.DateTimeFormat('zh-CN',{weekday:'long',month:'long',day:'numeric'}).format(d);$('#todayTime').textContent=d.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});let h=d.getHours();$('#todayGreeting').textContent=h<6?'夜深了，保留一点安静。':h<12?'早上好，先从最重要的一件事开始。':h<18?'下午好，工具都已就位。':'晚上好，收拢今天的轨道。';renderCountdown()}
function renderCountdown(){let c=db.get('countdown',null);if(!c){$('#countdownValue').textContent='未设置';$('#countdownLabel').textContent='点击设置一个重要日期';return}let t=new Date(c.date+'T00:00:00'),n=new Date();n.setHours(0,0,0,0);let days=Math.ceil((t-n)/86400000);$('#countdownValue').textContent=days>0?days+' 天':days===0?'就是今天':'已过 '+Math.abs(days)+' 天';$('#countdownLabel').textContent=c.name}
function openMenu(){$('#sidebar').classList.add('open');$('#scrim').classList.add('show')}function closeMenu(){$('#sidebar').classList.remove('open');$('#scrim').classList.remove('show')}
function theme(t){document.documentElement.dataset.theme=t;db.set('theme',t);document.querySelector('meta[name=theme-color]').content=t==='dark'?'#070b14':'#f4f6fb';try{$('#toolFrame').contentWindow.postMessage({type:'pt-universe-theme',theme:t},'*')}catch{}}
function openCommand(){if(!$('#commandDialog').open)$('#commandDialog').showModal();$('#commandInput').value='';filterCommand('');setTimeout(()=>$('#commandInput').focus(),20)}
function filterCommand(q){let s=q.trim().toLowerCase();results=APPS.filter(a=>!s||[a.name,a.desc,a.catName,...a.tags].join(' ').toLowerCase().includes(s));selected=0;$('#commandResults').innerHTML=results.length?results.map((a,i)=>`<button class="command-result ${i?'':'selected'}" data-command="${a.id}" type="button"><span>${a.icon}</span><span><strong>${a.name}</strong><small>${a.desc}</small></span><em>${a.catName}</em></button>`).join(''):'<div class="empty">没有找到对应工具</div>';$$('[data-command]').forEach(b=>b.onclick=()=>{$('#commandDialog').close();openApp(b.dataset.command)})}
function route(){let p=location.hash.replace('#/','').split('/');if(p[0]==='app')openApp(p[1]);else if(p[0]==='category')showCategory(p[1]);else showHome()}

buildNav();theme(db.get('theme',matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));tick();setInterval(tick,30000);
$('#quickNote').value=db.get('note','');let noteTimer;$('#quickNote').oninput=e=>{clearTimeout(noteTimer);$('#noteState').textContent='保存中…';noteTimer=setTimeout(()=>{db.set('note',e.target.value);$('#noteState').textContent='已保存到本机'},350)};
$('#themeButton').onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark');$('#searchButton').onclick=openCommand;$('#menuButton').onclick=openMenu;$('#scrim').onclick=closeMenu;$('#backButton').onclick=()=>{location.hash='#/home'};$('#reloadButton').onclick=()=>{if(active){$('#frameLoading').classList.remove('hide');$('#toolFrame').src=active.url}};$('#toolFrame').onload=()=>setTimeout(()=>$('#frameLoading').classList.add('hide'),220);$('#favoriteButton').onclick=()=>active&&toggleFavorite(active.id);$('#showAllButton').onclick=()=>$('#allToolsHeading').scrollIntoView({behavior:'smooth'});
$('#settingsButton').onclick=()=>{$('#settingsDialog').showModal();closeMenu()};$('#settingsClose').onclick=()=>$('#settingsDialog').close();$('#resetLocal').onclick=()=>{if(confirm('确定重置 PT Universe 的收藏、最近使用、备忘与倒计时吗？原工具数据不会受影响。')){Object.keys(localStorage).filter(k=>k.startsWith('ptu.')).forEach(k=>localStorage.removeItem(k));location.reload()}};
$('#countdownEdit').onclick=()=>{let c=db.get('countdown',{});$('#countdownName').value=c.name||'';$('#countdownDate').value=c.date||'';$('#countdownDialog').showModal()};$('#countdownForm').addEventListener('submit',e=>{let action=e.submitter?.value;if(action==='save'){e.preventDefault();if(!$('#countdownDate').value)return;db.set('countdown',{name:$('#countdownName').value||'重要日期',date:$('#countdownDate').value});$('#countdownDialog').close();renderCountdown()}else if(action==='clear'){db.set('countdown',null);setTimeout(renderCountdown)}});
$('#commandInput').oninput=e=>filterCommand(e.target.value);$('#commandInput').onkeydown=e=>{if((e.key==='ArrowDown'||e.key==='ArrowUp')&&results.length){e.preventDefault();selected=(selected+(e.key==='ArrowDown'?1:-1)+results.length)%results.length;$$('.command-result').forEach((x,i)=>x.classList.toggle('selected',i===selected));$$('.command-result')[selected]?.scrollIntoView({block:'nearest'})}else if(e.key==='Enter'&&results[selected]){e.preventDefault();$('#commandDialog').close();openApp(results[selected].id)}};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if(e.key==='Escape')closeMenu()});window.addEventListener('hashchange',route);route();
