const APPS=[
 {"id":"investment-desk","name":"Investment Desk · 投资工作台","icon":"↗","cat":"money","catName":"资金与决策","accent":"#256d53","desc":"导入持仓 CSV，自动核对行情与财报，给出买卖候选和参考区间；内置名人公开交易核验。","tags":["股票","财报","持仓","论点"],"update":"行情与财报自动刷新","url":"apps/investment-desk/","repo":"https://github.com/XiminHu66/PT-Universe/tree/main/apps/investment-desk"},
 {"id":"life-desk","name":"Life Desk · 周末与吃饭","icon":"⌖","cat":"life","catName":"生活与饮食","accent":"#208c79","desc":"半日安排、收藏餐厅、今晚菜单和食谱在一页接着用；原 Weekend Atlas 与 Food Orbit 已整合。","tags":["周末","餐厅","食谱","活动"],"update":"每日活动快照 · 实时餐厅查询","url":"apps/life-desk/","repo":"https://github.com/XiminHu66/PT-Universe/tree/main/apps/life-desk"},
 {id:'watch-inbox',name:'Muse Inbox · 每日监视',icon:'◫',cat:'today',catName:'今日与看板',accent:'#a2763c',desc:'接收 Muse 每日监视报告，汇总变化、原始证据、监视失败和建议下一步。',url:'apps/watch-inbox/',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/watch-inbox',tags:['Muse','监视','变化','条件'],update:'Muse 每日投递 · 自动汇总'},

 {id:'media-vault',name:'Media Vault · 万能下载',icon:'↓',cat:'media',catName:'媒体与 ACG',accent:'#bfd98a',desc:'轻小说阅读与 EPUB、各国音乐榜单与 FLAC、动漫、BT 与视频下载。',url:'apps/media-vault/',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/media-vault',tags:['下载','FLAC','音乐','轻小说','动漫','BT','视频'],update:'每日 08:23 PT · 实时查询'},
 {"id":"earnings-dojo","name":"Earnings Dojo · 财报训练","icon":"学","cat":"money","catName":"资金与决策","accent":"#99705c","desc":"匿名真实财报练习、客观题评分和下一季揭晓。","tags":["财报","学习","训练","投资"],"update":"每日财报快照 · 本机练习","url":"apps/earnings-dojo/","repo":"https://github.com/XiminHu66/PT-Universe/tree/main/apps/earnings-dojo"},
 {id:'room-workout',name:'Room Workout · 房间跟练',icon:'◷',cat:'life',catName:'生活与饮食',accent:'#53c5bf',desc:'22 分钟、3㎡、无跳跃、无椅子；跟着真人动作示范练。',url:'apps/room-workout/',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/room-workout',tags:['运动','健身','跟练','计时','血脂','房间'],update:'本机计时 · 动作示范'},
 {id:'daily-nexus',name:'Daily Nexus',icon:'⌂',cat:'today',catName:'今日与看板',accent:'#7c73ff',desc:'日历、备忘、发现、音乐、专注与微工具的日常中枢。',url:'apps/daily-nexus/?v=20260827-coversdrawer1',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/daily-nexus',tags:['今日','日历','备忘','专注','音乐','工具'],update:'本机实时 · 聚合入口'},
 {id:'deskboard',name:'DeskBoard',icon:'▦',cat:'today',catName:'今日与看板',accent:'#22a6f2',desc:'iPad 行情、天气、快讯、RSS 与常用链接看板。',url:'apps/deskboard/?v=20260826-5',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/deskboard',tags:['股票','天气','RSS','新闻','iPad'],update:'实时组件 · RSS 15 分钟'},
 {id:'rss-dashboard',name:'RSS Orbit',icon:'◉',cat:'media',catName:'媒体与 ACG',accent:'#4cac78',desc:'取代 Feedly 的中文 RSS 收件箱、未读管理、稍后读与 OPML 迁移。',url:'apps/rss-dashboard/?v=20260828-11',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/rss-dashboard',tags:['RSS','Feedly','新闻','订阅','稍后读','OPML'],update:'美西 08:00–24:00 每小时 · Cloudflare KV'},
 {id:'qf-tool',name:'QF Tool',icon:'◇',cat:'money',catName:'资金与决策',accent:'#e6a83c',desc:'投资、信用卡奖励、Deal、副业机会与决策日志。',url:'apps/qf-tool/?v=20260826-5',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/qf-tool',tags:['投资','奖励','信用卡','副业','日志'],update:'每天 08:00 PT'},
 {id:'3c-scout',name:'3C Scout',icon:'⌁',cat:'shopping',catName:'购物与发现',accent:'#f16e5b',desc:'中文优先的新品、好 Deal 与极客商品发现流。',url:'apps/3c-scout/?v=20260826-5',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/3c-scout',tags:['3C','Deal','新品','购物','数码'],update:'每天约 08:15 PT'},
 {id:'tsugi-checker',name:'Tsugi',icon:'継',cat:'media',catName:'媒体与 ACG',accent:'#c768df',desc:'漫画、轻小说、音乐、游戏发行与 PC 游戏比价搜索。',url:'apps/tsugi-checker/?v=20260827-coversdrawer1',repo:'https://github.com/XiminHu66/PT-Universe/tree/main/apps/tsugi-checker',tags:['漫画','小说','游戏','音乐','ACG'],update:'每天 09:17 PT'}
];
const CATS=[{id:'home',name:'今日总览',icon:'⌂'},{id:'today',name:'今日与看板',icon:'▦'},{id:'money',name:'资金与决策',icon:'↗'},{id:'shopping',name:'购物与发现',icon:'⌁'},{id:'life',name:'生活与饮食',icon:'筷'},{id:'media',name:'媒体与 ACG',icon:'継'}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const db={get(k,f){try{let v=localStorage.getItem('ptu.'+k);return v===null?f:JSON.parse(v)}catch{return f}},set(k,v){localStorage.setItem('ptu.'+k,JSON.stringify(v))}};
const APP_ALIASES={'signal-audit':['investment-desk','audit'],'ask-gpt':['investment-desk','review'],'stock-alert':['investment-desk','market'],'thesis-lab':['investment-desk','thesis'],'eastside-weekend':['life-desk','weekend'],'meal-orbit':['life-desk','dinner']};
const migrateIds=xs=>[...new Set(xs.map(id=>APP_ALIASES[id]?.[0]||id))];
let favorites=migrateIds(db.get('favorites',['daily-nexus','investment-desk','tsugi-checker','3c-scout']));db.set('favorites',favorites);
let recents=migrateIds(db.get('recents',[])),active=null,results=[],selected=0;

function buildNav(){
  $('#primaryNav').innerHTML='<div class="nav-label">UNIVERSE</div>'+CATS.map(c=>`<button class="nav-item" data-cat="${c.id}"><span>${c.icon}</span><span>${c.name}</span>${c.id==='home'?'':`<em>${APPS.filter(a=>a.cat===c.id).length}</em>`}</button>`).join('');
  $('#mobileNav').innerHTML=[CATS[0],CATS[1],CATS[2],CATS[5],{id:'more',name:'更多',icon:'•••'}].map(c=>`<button data-mobile="${c.id}"><span>${c.icon}</span><span>${c.name.replace('与看板','').replace('与决策','').replace('与 ACG','')}</span></button>`).join('');
  $$('[data-cat]').forEach(b=>b.onclick=()=>showCategory(b.dataset.cat));
  $$('[data-mobile]').forEach(b=>b.onclick=()=>b.dataset.mobile==='more'?openMenu():showCategory(b.dataset.mobile));
}
function card(a){let fav=favorites.includes(a.id);return `<article class="app-card" data-app="${a.id}" style="--accent:${a.accent}"><div class="card-top"><span class="app-symbol">${a.icon}</span><button class="fav ${fav?'on':''}" data-fav="${a.id}">${fav?'★':'☆'}</button></div><h3>${a.name}</h3><p>${a.desc}</p><div class="card-foot"><span class="chip">${a.catName}</span><button class="launch" data-launch="${a.id}">${a.id==='room-workout'?'独立打开 ↗':'打开 →'}</button></div></article>`}
function render(){
  let pinned=favorites.map(id=>APPS.find(a=>a.id===id)).filter(Boolean);
  $('#favoriteGrid').innerHTML=pinned.length?pinned.map(card).join(''):'<button class="empty pin-empty" id="emptyPinButton">尚未 Pin 常用工具 · 点击选择</button>';
  $('#allApps').innerHTML=CATS.slice(1).map(c=>({c,apps:APPS.filter(a=>a.cat===c.id)})).filter(x=>x.apps.length).map(({c,apps})=>`<section class="category-block" id="category-${c.id}"><h3>${c.icon} ${c.name.toUpperCase()} · ${apps.length}</h3><div class="app-grid">${apps.map(card).join('')}</div></section>`).join('');
  renderRecent();renderSources();renderPinOptions();bindCards();if($('#emptyPinButton'))$('#emptyPinButton').onclick=openPins;
}
function bindCards(){
  $$('[data-launch]').forEach(b=>b.onclick=e=>{e.stopPropagation();openApp(b.dataset.launch)});
  $$('.app-card').forEach(c=>c.onclick=e=>{if(!e.target.closest('[data-fav]'))openApp(c.dataset.app)});
  $$('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFavorite(b.dataset.fav)});
}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];db.set('favorites',favorites);render();if(active?.id===id)$('#favoriteButton').textContent=favorites.includes(id)?'★':'☆'}
function renderRecent(){let items=recents.map(id=>APPS.find(a=>a.id===id)).filter(Boolean).slice(0,4);$('#recentList').innerHTML=items.length?items.map(a=>`<button class="recent-item" data-recent="${a.id}"><span class="mini">${a.icon}</span><span><strong>${a.name}</strong><small>${a.update}</small></span><em>→</em></button>`).join(''):'<div class="empty">打开一个工具后会显示在这里</div>';$$('[data-recent]').forEach(b=>b.onclick=()=>openApp(b.dataset.recent))}
function renderSources(){$('#sourceList').innerHTML=APPS.map(a=>`<a class="source-item" href="${a.repo}" target="_blank" rel="noopener"><span>${a.icon}</span><div><strong>${a.name}</strong><small>${a.update}</small></div><em>在线</em></a>`).join('')}
function updateNav(id){$$('[data-cat]').forEach(b=>b.classList.toggle('active',b.dataset.cat===id));$$('[data-mobile]').forEach(b=>b.classList.toggle('active',b.dataset.mobile===id||(active&&b.dataset.mobile===active.cat)))}
function showHome(){active=null;$('#homeView').hidden=false;$('#frameView').hidden=true;$('#toolFrame').src='about:blank';$('#pageEyebrow').textContent='COMMAND CENTER';$('#pageTitle').textContent='今日总览';$('#collectionTitle').textContent='常用工具';render();updateNav('home');closeMenu()}
function renderPinOptions(){const box=$('#pinOptions');if(!box)return;box.innerHTML=APPS.map(a=>`<label><input type="checkbox" value="${a.id}" ${favorites.includes(a.id)?'checked':''}><span class="mini">${a.icon}</span><span><strong>${a.name}</strong><small>${a.catName}</small></span></label>`).join('');box.onchange=()=>{favorites=[...box.querySelectorAll('input:checked')].map(x=>x.value);db.set('favorites',favorites);render()}}
function openPins(){renderPinOptions();$('#pinDialog').showModal()}
function showCategory(id){if(id==='home'){if(location.hash!=='#/home')location.hash='#/home';showHome();return}showHome();let c=CATS.find(x=>x.id===id),apps=APPS.filter(a=>a.cat===id);$('#pageEyebrow').textContent='COLLECTION';$('#pageTitle').textContent=c.name;$('#collectionTitle').textContent=c.name;$('#favoriteGrid').innerHTML=apps.map(card).join('');bindCards();updateNav(id);if(location.hash!==`#/category/${id}`)location.hash=`#/category/${id}`;setTimeout(()=>$('#favoriteGrid').scrollIntoView({behavior:'smooth',block:'start'}),20)}
function openApp(id){
  const alias=APP_ALIASES[id];if(alias)id=alias[0];
  let a=APPS.find(x=>x.id===id);if(!a)return;recents=[id,...recents.filter(x=>x!==id)].slice(0,8);db.set('recents',recents);
  if(id==='room-workout'){renderRecent();window.open(a.url,'_blank','noopener');return}
  active=a;
  window.location.assign(a.url+(alias?'?tab='+alias[1]:''));
}
function tick(){let d=new Date();$('#todayDate').textContent=new Intl.DateTimeFormat('zh-CN',{weekday:'long',month:'long',day:'numeric'}).format(d);$('#todayTime').textContent=d.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});let h=d.getHours();$('#todayGreeting').textContent=h<6?'夜深了，保留一点安静。':h<12?'早上好，先从最重要的一件事开始。':h<18?'下午好，工具都已就位。':'晚上好，收拢今天的轨道。';renderCountdown()}
function renderCountdown(){let c=db.get('countdown',null);if(!c){$('#countdownValue').textContent='未设置';$('#countdownLabel').textContent='点击设置一个重要日期';return}let t=new Date(c.date+'T00:00:00'),n=new Date();n.setHours(0,0,0,0);let days=Math.ceil((t-n)/86400000);$('#countdownValue').textContent=days>0?days+' 天':days===0?'就是今天':'已过 '+Math.abs(days)+' 天';$('#countdownLabel').textContent=c.name}
function openMenu(){$('#sidebar').classList.add('open');$('#scrim').classList.add('show')}function closeMenu(){$('#sidebar').classList.remove('open');$('#scrim').classList.remove('show')}
function theme(t){document.documentElement.dataset.theme=t;db.set('theme',t);document.querySelector('meta[name=theme-color]').content=t==='dark'?'#070b14':'#f4f6fb';try{$('#toolFrame').contentWindow.postMessage({type:'pt-universe-theme',theme:t},'*')}catch{}}
function openCommand(){if(!$('#commandDialog').open)$('#commandDialog').showModal();$('#commandInput').value='';filterCommand('');setTimeout(()=>$('#commandInput').focus(),20)}
function filterCommand(q){let s=q.trim().toLowerCase();results=APPS.filter(a=>!s||[a.name,a.desc,a.catName,...a.tags].join(' ').toLowerCase().includes(s));selected=0;$('#commandResults').innerHTML=results.length?results.map((a,i)=>`<button class="command-result ${i?'':'selected'}" data-command="${a.id}" type="button"><span>${a.icon}</span><span><strong>${a.name}</strong><small>${a.desc}</small></span><em>${a.catName}</em></button>`).join(''):'<div class="empty">没有找到对应工具</div>';$$('[data-command]').forEach(b=>b.onclick=()=>{$('#commandDialog').close();openApp(b.dataset.command)})}
function route(){let p=location.hash.replace('#/','').split('/');if(p[0]==='app')openApp(p[1]);else if(p[0]==='category')showCategory(p[1]);else showHome()}

buildNav();theme(db.get('theme',matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));tick();setInterval(tick,30000);
$('#quickNote').value=db.get('note','');let noteTimer;$('#quickNote').oninput=e=>{clearTimeout(noteTimer);$('#noteState').textContent='保存中…';noteTimer=setTimeout(()=>{db.set('note',e.target.value);$('#noteState').textContent='已保存到本机'},350)};
$('#themeButton').onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark');$('#searchButton').onclick=openCommand;$('#menuButton').onclick=openMenu;$('#scrim').onclick=closeMenu;$('#backButton').onclick=()=>{location.hash='#/home'};$('#reloadButton').onclick=()=>{if(active){$('#frameLoading').classList.remove('hide');$('#toolFrame').src=active.url}};$('#toolFrame').onload=()=>setTimeout(()=>$('#frameLoading').classList.add('hide'),220);$('#favoriteButton').onclick=()=>active&&toggleFavorite(active.id);$('#showAllButton').onclick=()=>$('#allToolsHeading').scrollIntoView({behavior:'smooth'});
$('#pinManageButton').onclick=openPins;$('#pinClose').onclick=()=>$('#pinDialog').close();
$('#settingsButton').onclick=()=>{$('#settingsDialog').showModal();closeMenu()};$('#settingsClose').onclick=()=>$('#settingsDialog').close();$('#resetLocal').onclick=()=>{if(confirm('确定重置 PT Universe 的收藏、最近使用、备忘与倒计时吗？原工具数据不会受影响。')){Object.keys(localStorage).filter(k=>k.startsWith('ptu.')&&!k.startsWith('ptu.sync.')).forEach(k=>localStorage.removeItem(k));location.reload()}};
const syncNote=(text,bad=false)=>{const el=$('#syncStatus');el.textContent=text;el.style.color=bad?'#e14e62':'#27a778'};
if(PTSync.config())syncNote('此设备已连接');
$('#syncCreate').onclick=async()=>{try{syncNote('正在创建…');$('#syncCode').value=await PTSync.create();syncNote('已创建，把配对码复制到另一台设备')}catch(e){syncNote(e.message,true)}};
$('#syncConnect').onclick=async()=>{try{syncNote('正在连接…');await PTSync.connect($('#syncCode').value);syncNote('已连接并拉取最新设置，请刷新页面')}catch(e){syncNote(e.message,true)}};
$('#syncNow').onclick=async()=>{try{syncNote('同步中…');await PTSync.pull();await PTSync.push();syncNote('同步完成')}catch(e){syncNote(e.message,true)}};
$('#syncDisconnect').onclick=()=>{PTSync.disconnect();$('#syncCode').value='';syncNote('已断开此设备')};addEventListener('pt-sync-status',e=>{if(e.detail.type==='error')syncNote(e.detail.error,true)});
const refreshNote=(text,bad=false)=>{const el=$('#cloudRefreshStatus');el.textContent=text;el.style.color=bad?'#e14e62':'var(--muted)'};
async function pollCloudRefresh(id){for(let i=0;i<50;i++){await new Promise(r=>setTimeout(r,6000));const response=await fetch(`${PTSync.API}/api/refresh/status/${id}`,{cache:'no-store'}),run=await response.json();if(run.status==='success'){refreshNote('刷新完成，子项目重新打开后会读取新数据');return}if(run.status==='failed')throw new Error(run.error||'刷新失败')}refreshNote('任务仍在后台运行')}
$$('[data-cloud-refresh]').forEach(button=>button.onclick=async()=>{try{$$('[data-cloud-refresh]').forEach(x=>x.disabled=true);refreshNote('正在提交…');const response=await fetch(`${PTSync.API}/api/refresh/${button.dataset.cloudRefresh}`,{method:'POST'}),result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);refreshNote(`任务已排队 · ${button.textContent}`);await pollCloudRefresh(result.requestId)}catch(e){refreshNote(e.message,true)}finally{$$('[data-cloud-refresh]').forEach(x=>x.disabled=false)}});
fetch(`${PTSync.API}/api/status`).then(r=>r.json()).then(data=>{const labels={'site-updates.json':'漫画/小说','acg-news.json':'新闻','music.json':'音乐'},due=(data.files||[]).filter(x=>x.fallbackDue).map(x=>labels[x.name]||x.name),run=data.runs?.[0];if(due.length)refreshNote(`⚠ ${due.join('、')}已过期 · GitHub 备用抓取将自动接管`,true);else refreshNote(run?`最近：${run.scope} · ${run.status} · ${run.completed_at||run.started_at||'等待中'}`:'尚无刷新记录')}).catch(()=>refreshNote('刷新状态暂不可用',true));
$('#countdownEdit').onclick=()=>{let c=db.get('countdown',{});$('#countdownName').value=c.name||'';$('#countdownDate').value=c.date||'';$('#countdownDialog').showModal()};$('#countdownForm').addEventListener('submit',e=>{let action=e.submitter?.value;if(action==='save'){e.preventDefault();if(!$('#countdownDate').value)return;db.set('countdown',{name:$('#countdownName').value||'重要日期',date:$('#countdownDate').value});$('#countdownDialog').close();renderCountdown()}else if(action==='clear'){db.set('countdown',null);setTimeout(renderCountdown)}});
$('#commandInput').oninput=e=>filterCommand(e.target.value);$('#commandInput').onkeydown=e=>{if((e.key==='ArrowDown'||e.key==='ArrowUp')&&results.length){e.preventDefault();selected=(selected+(e.key==='ArrowDown'?1:-1)+results.length)%results.length;$$('.command-result').forEach((x,i)=>x.classList.toggle('selected',i===selected));$$('.command-result')[selected]?.scrollIntoView({block:'nearest'})}else if(e.key==='Enter'&&results[selected]){e.preventDefault();$('#commandDialog').close();openApp(results[selected].id)}};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if(e.key==='Escape')closeMenu()});window.addEventListener('hashchange',route);route();
