import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {researchRoute,normalizeFinancials,summarizeOffers} from '../../workers/pt-universe-api/src/research.ts';
import {buildCases,questionPool,valueSignature} from '../../apps/earnings-dojo/questions.js';
const memory=new Map();globalThis.caches={open:async()=>({match:async r=>memory.get(r.url)?.clone(),put:async(r,v)=>memory.set(r.url,v.clone())})};
let financialRequests=0;const originalFetch=globalThis.fetch;globalThis.fetch=(url,options)=>{if(String(url).includes('fundamentals-timeseries'))financialRequests++;return originalFetch(url,options)};
const sorted=summarizeOffers([{price:40,currency:'USD',discount:60},{price:25,currency:'USD',discount:50},{price:2,currency:'EUR',discount:90},{price:null,currency:'USD'}]);
assert.equal(sorted.lowest.price,25);assert.equal(sorted.maxDiscount,60);assert.equal(sorted.offers.length,2);
await assert.rejects(()=>researchRoute(new Request('https://test/api/pc/prices?steamId=../secret')));
await assert.rejects(()=>researchRoute(new Request('https://test/api/training/financials?symbol=INVALID')));
const synthetic=normalizeFinancials({timeseries:{result:[{meta:{type:['quarterlyTotalRevenue']},quarterlyTotalRevenue:[{asOfDate:'2026-06-30',periodType:'3M',currencyCode:'USD',reportedValue:{raw:100}}]},{meta:{type:['quarterlyOperatingCashFlow']},quarterlyOperatingCashFlow:[{asOfDate:'2026-06-30',periodType:'3M',reportedValue:{raw:40}}]},{meta:{type:['quarterlyCapitalExpenditure']},quarterlyCapitalExpenditure:[{asOfDate:'2026-06-30',periodType:'3M',reportedValue:{raw:-10}}]}]}},'NVDA');
assert.equal(synthetic[0].fcf,30);assert.equal(synthetic[0].shares,null);
const live=process.env.LABS_API_URL;
async function call(path){if(!live)return researchRoute(new Request('https://test'+path));let r;for(let attempt=0;attempt<12;attempt++){r=await fetch(live+path);if(r.status!==404)break;await new Promise(resolve=>setTimeout(resolve,10000))}const v=await r.json();assert.equal(r.status,200,JSON.stringify(v));return v}
const search=await call('/api/pc/search?q=Street%20Fighter%206');
const candidate=search.items.find(x=>x.steamId==='1364780');assert.ok(candidate,'Steam official candidate missing');
const prices=await call('/api/pc/prices?steamId=1364780'+(candidate.cheapId?'&cheapId='+candidate.cheapId:''));
assert.ok(prices.offers.some(o=>o.official&&o.store==='Steam'),'Steam official quote missing');
assert.ok(prices.offers.some(o=>o.storeId!=='1'),'Third-party prices missing');
assert.equal(prices.lowest.price,Math.min(...prices.offers.map(o=>o.price)));
const financial=await call('/api/training/financials?symbol=NVDA&t=1');
const second=await call('/api/training/financials?symbol=NVDA&t=2');
assert.ok(financial.live&&second.live);assert.ok(financial.quarters.length>=3);
if(!live)assert.equal(financialRequests,2,'Every refresh must request financial upstream, not reuse a static bank');
assert.notEqual(financial.updatedAt,second.updatedAt,'Verification timestamp must advance');
assert.equal(valueSignature(financial.quarters),valueSignature(second.quarters),'Same reports should remain identical, not generate fictional data');
const cases=buildCases([financial]);assert.ok(cases.length>=2);assert.ok(questionPool(cases.at(-1)).length>=3);
const changed=structuredClone(financial);changed.quarters.at(-1).revenue+=123;
assert.notEqual(valueSignature(financial.quarters),valueSignature(changed.quarters));
assert.notEqual(buildCases([changed]).at(-1).quarters.at(-1).revenue,cases.at(-1).quarters.at(-1).revenue);
mkdirSync('test-results/research',{recursive:true});
for(const [name,v] of Object.entries({search,prices,financial}))writeFileSync('test-results/research/'+name+'.json',JSON.stringify(v));
console.log('RESEARCH LIVE PASS',JSON.stringify({candidates:search.items.length,offers:prices.offers.length,lowest:prices.lowest.price,financialQuarters:financial.quarters.length,cases:cases.length,firstVerifiedAt:financial.updatedAt,secondVerifiedAt:second.updatedAt,financialUpstreamRequests:live?'production endpoint':financialRequests}));
