import {empty,normalize,merge,safeUrl,liveRestaurants,dishesFor,navigationUrl} from './model.mjs';
import {config,register,parseCode,useConfig,fetchCloud,putCloud} from './sync.mjs?v=20261005-3';
const KEY='food-ledger.v1',$=s=>document.querySelector(s),esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dishDrafts=new Map();let dishComposing=false;
let state=empty(),selected='',query='',filter='all',editingRestaurant='',editingDish='',toastTimer,syncTimer,syncBusy=false,syncAgain=false,lastSyncMessage='',storageBlocked=false,syncTask=Promise.resolve(false);
try{const raw=localStorage.getItem(KEY);if(raw)state=normalize(JSON.parse(raw))}catch{storageBlocked=true;$('#save-state').textContent='记录无法读取，请先导出或检查浏览器存储';$('#save-state').classList.add('bad')}
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const current=()=>state.restaurants.find(r=>r.id===selected&&!r.deleted);
function stamp(){return Math.max(Date.now(),...state.restaurants.map(x=>x.updatedAt+1),...state.dishes.map(x=>x.updatedAt+1))}
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,4000)}
function saveMessage(message,bad=false){$('#save-state').textContent=message;$('#save-state').classList.toggle('bad',bad);lastSyncMessage=message;$('#sync-status').textContent=message}
function persist(next){if(storageBlocked)throw Error('本机记录无法读取，已暂停写入以保留原始数据');const normalized=normalize(next);try{localStorage.setItem(KEY,JSON.stringify(normalized))}catch{throw Error('保存失败：浏览器存储不可用或已满。请先导出备份。')}state=normalized;saveMessage(config()?'已保存在此设备 · 等待同步':'已保存在此设备 · 联网后自动同步');return true}
function change(next){try{persist(next);render();scheduleSync();return true}catch(e){toast(e.message);return false}}
function scheduleSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>synchronize(),700)}
function renderList(){
 const all=liveRestaurants(state),q=query.trim().toLocaleLowerCase();
 const visible=all.filter(r=>!q||[r.name,r.address,r.note,...dishesFor(state,r.id).flatMap(d=>[d.name,d.note])].join(' ').toLocaleLowerCase().includes(q));
 const exact=all.find(r=>r.name.toLocaleLowerCase()===q);$('#add-restaurant').textContent=exact?'打开':'添加';$('#add-restaurant').disabled=!q;
 const allDishes=all.flatMap(r=>dishesFor(state,r.id));$('#restaurant-count').textContent=all.length;
 $('#summary').innerHTML=`<span>共 <b>${allDishes.length}</b> 道菜</span><span class="red">红榜 <b>${allDishes.filter(d=>d.rank==='red').length}</b></span><span class="black">黑榜 <b>${allDishes.filter(d=>d.rank==='black').length}</b></span>`;
 $('#restaurant-list').innerHTML=visible.length?visible.map(r=>{const ds=dishesFor(state,r.id);return `<button class="restaurant-card ${selected===r.id?'selected':''}" data-select="${r.id}" aria-pressed="${selected===r.id}"><h3>${esc(r.name)}</h3>${r.address?`<p>${esc(r.address)}</p>`:''}<div class="pills"><span class="pill red">红榜 ${ds.filter(d=>d.rank==='red').length}</span><span class="pill black">黑榜 ${ds.filter(d=>d.rank==='black').length}</span></div></button>`}).join(''):`<div class="list-empty">${q?'还没有匹配的记录。<br>可以把这家菜馆先记下来。':'还没记录过菜馆。<br>从一家想再去的，或踩过雷的开始。'}</div>`;
}
function rankPanel(rank,rows){return `<section class="rank-panel ${rank==='black'?'black-panel':''}"><div class="rank-header"><h3>${rank==='red'?'红榜':'黑榜'}</h3><small>${rank==='red'?'值得再点':'下次避开'}</small><b>${rows.length}</b></div>${rows.length?rows.map(d=>`<article class="dish-card" data-dish="${d.id}"><h4>${esc(d.name)}</h4>${d.note?`<p>${esc(d.note)}</p>`:''}<div class="dish-foot"><time datetime="${esc(d.date)}">${esc(d.date)||'未记日期'}</time><button class="dish-edit" data-edit-dish="${d.id}" aria-label="编辑菜品 ${esc(d.name)}">编辑</button></div></article>`).join(''):`<div class="rank-empty">${rank==='red'?'吃到喜欢的，就记在这里。':'踩过的雷，留个提醒。'}</div>`}</section>`}
function renderBoard(){
 if(dishComposing)return;const focused=document.activeElement?.id==='quick-dish-name',cursor=focused?[document.activeElement.selectionStart,document.activeElement.selectionEnd]:null;
 const r=current();if(!r){$('#board').innerHTML=`<div class="board-empty"><div class="empty-stamp" aria-hidden="true"><span>再点</span><span>避雷</span></div><h2>下次点菜，心里有数</h2><p>${liveRestaurants(state).length?'选择一家菜馆，查看自己的红黑榜。':'记下菜馆和吃过的菜。好吃的再点，踩雷的避开。'}</p><button class="primary" data-new-place>输入菜馆名</button></div>`;return}
 const ds=dishesFor(state,r.id),rankFilter=filter==='all'?['red','black']:[filter];
 $('#board').innerHTML=`<div class="restaurant-heading"><button class="mobile-back" data-back>返回菜馆列表</button><div class="detail-top"><div><p class="eyebrow">我的点菜记录</p><h2>${esc(r.name)}</h2></div><div class="detail-tools"><button class="icon-button" data-edit-place aria-label="编辑菜馆">资料</button><button class="icon-button delete" data-delete-place aria-label="删除菜馆">删除</button></div></div><div class="place-info">${r.address?`<a class="address" href="${esc(navigationUrl(r))}" target="_blank" rel="noopener noreferrer" aria-label="Google Maps 导航至 ${esc(r.name)}"><svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>${esc(r.address)}</a>`:''}${r.url?`<a class="place-link" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">打开菜馆链接</a>`:''}${r.note?`<p class="place-note">${esc(r.note)}</p>`:''}</div></div><form id="dish-quick" class="dish-quick" data-restaurant="${r.id}"><label class="dish-quick-input"><input id="quick-dish-name" name="name" required maxlength="120" value="${esc(dishDrafts.get(r.id)||'')}" placeholder="输入菜名" aria-label="快速添加菜品" autocomplete="off"></label><div class="quick-ranks"><button type="submit" class="quick-red" data-quick-rank="red" value="red">＋ 红榜</button><button type="submit" class="quick-black" data-quick-rank="black" value="black">＋ 黑榜</button></div></form><div class="board-toolbar"><div class="filters" role="group" aria-label="筛选菜品">${[['all','全部'],['red','红榜'],['black','黑榜']].map(([v,label])=>`<button data-filter="${v}" class="${filter===v?'active':''}" aria-pressed="${filter===v}">${label}</button>`).join('')}</div></div><div class="rank-columns ${filter!=='all'?'single':''}">${rankFilter.map(rank=>rankPanel(rank,ds.filter(d=>d.rank===rank))).join('')}</div>`;
 if(focused){const input=$('#quick-dish-name');input?.focus({preventScroll:true});if(cursor)input?.setSelectionRange(...cursor)}
}
function render(){renderList();renderBoard();document.body.classList.toggle('detail-open',Boolean(current())&&Boolean(location.hash))}
function select(id){selected=id;filter='all';location.hash='restaurant/'+id;render();window.scrollTo({top:0})}
function route(){const id=location.hash.startsWith('#restaurant/')?location.hash.slice(12):'';selected=state.restaurants.some(r=>r.id===id&&!r.deleted)?id:'';render()}
function openRestaurant(r=null){editingRestaurant=r?.id||'';const f=$('#restaurant-form');f.reset();$('#restaurant-error').textContent='';$('#restaurant-form-title').textContent=r?'编辑菜馆':'记一家菜馆';for(const name of ['name','address','url','note'])f.elements[name].value=r?.[name]||(name==='name'?query.trim():'');$('#restaurant-dialog').showModal();$('#restaurant-name').focus()}
function openDish(d=null){if(!current())return;editingDish=d?.id||'';const f=$('#dish-form');f.reset();$('#dish-error').textContent='';$('#dish-form-title').textContent=d?'编辑菜品':'记一道菜';$('#dish-restaurant').textContent=current().name;for(const name of ['name','note','date'])f.elements[name].value=d?.[name]||(name==='date'?today():'');f.elements.rank.value=d?.rank||(filter==='black'?'black':'red');let remove=f.querySelector('[data-delete-dish]');if(remove)remove.remove();if(d){remove=document.createElement('button');remove.type='button';remove.className='quiet';remove.dataset.deleteDish=d.id;remove.textContent='删除菜品';f.querySelector('.dialog-actions').prepend(remove)}$('#dish-dialog').showModal();$('#dish-name').focus()}
$('#restaurant-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,name=f.elements.name.value.trim(),url=safeUrl(f.elements.url.value);if(!name){$('#restaurant-error').textContent='请填写菜馆名称';return}if(f.elements.url.value.trim()&&!url){$('#restaurant-error').textContent='链接需为有效的 http 或 https 地址';return}const address=f.elements.address.value.trim();const duplicate=state.restaurants.find(r=>!r.deleted&&r.id!==editingRestaurant&&r.name.toLocaleLowerCase()===name.toLocaleLowerCase()&&r.address.toLocaleLowerCase()===address.toLocaleLowerCase());if(duplicate){$('#restaurant-error').textContent='已记过这家菜馆，可关闭窗口后搜索并编辑。不同分店请补充地址。';return}const r={id:editingRestaurant||crypto.randomUUID(),name,address,url,note:f.elements.note.value.trim(),updatedAt:stamp(),deleted:false},next=structuredClone(state),i=next.restaurants.findIndex(x=>x.id===r.id);if(i<0)next.restaurants.push(r);else next.restaurants[i]=r;if(change(next)){$('#restaurant-dialog').close();query='';$('#search').value='';select(r.id);toast('菜馆已保存')}};
$('#dish-form').onsubmit=e=>{e.preventDefault();if(!current()){toast('菜馆已被删除，请重新选择');return}const f=e.currentTarget,name=f.elements.name.value.trim();if(!name){$('#dish-error').textContent='请填写菜品名称';return}const d={id:editingDish||crypto.randomUUID(),restaurantId:selected,name,rank:f.elements.rank.value,note:f.elements.note.value.trim(),date:f.elements.date.value,updatedAt:stamp(),deleted:false},next=structuredClone(state),i=next.dishes.findIndex(x=>x.id===d.id);if(i<0)next.dishes.push(d);else next.dishes[i]=d;if(change(next)){$('#dish-dialog').close();toast('菜品已保存')}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.matches('[data-close]'))b.closest('dialog').close();if(b.dataset.select)select(b.dataset.select);if(b.matches('[data-new-place]'))$('#search').focus();if(b.matches('[data-back]')){location.hash='';window.scrollTo({top:0})}if(b.matches('[data-edit-place]'))openRestaurant(current());if(b.dataset.editDish)openDish(state.dishes.find(d=>d.id===b.dataset.editDish));if(b.dataset.filter){filter=b.dataset.filter;renderBoard()}if(b.matches('[data-delete-place]')){const r=current();if(r&&confirm(`删除「${r.name}」和它的所有菜品记录？`)){const next=structuredClone(state),time=stamp();next.restaurants.find(x=>x.id===r.id).deleted=true;next.restaurants.find(x=>x.id===r.id).updatedAt=time;next.dishes.filter(d=>d.restaurantId===r.id).forEach(d=>{d.deleted=true;d.updatedAt=time});if(change(next)){location.hash='';toast('菜馆已删除')}}}if(b.dataset.deleteDish&&confirm('删除这道菜的记录？')){const next=structuredClone(state),d=next.dishes.find(x=>x.id===b.dataset.deleteDish);d.deleted=true;d.updatedAt=stamp();if(change(next)){$('#dish-dialog').close();toast('菜品已删除')}}});
$('#restaurant-quick').onsubmit=e=>{e.preventDefault();const name=$('#search').value.trim();if(!name)return;const existing=liveRestaurants(state).find(r=>r.name.toLocaleLowerCase()===name.toLocaleLowerCase());if(existing){select(existing.id);return}const r={id:crypto.randomUUID(),name,address:'',url:'',note:'',updatedAt:stamp(),deleted:false},next=structuredClone(state);next.restaurants.push(r);if(change(next)){query='';$('#search').value='';select(r.id);$('#quick-dish-name')?.focus({preventScroll:true});toast('菜馆已添加')}};
document.addEventListener('input',e=>{if(e.target.id==='quick-dish-name')dishDrafts.set(selected,e.target.value)});
document.addEventListener('compositionstart',e=>{if(e.target.id==='quick-dish-name')dishComposing=true});
document.addEventListener('compositionend',e=>{if(e.target.id==='quick-dish-name'){dishComposing=false;dishDrafts.set(selected,e.target.value)}});
document.addEventListener('keydown',e=>{if(['search','quick-dish-name'].includes(e.target.id)&&e.key==='Enter'&&(e.isComposing||e.keyCode===229))e.preventDefault()});
document.addEventListener('submit',e=>{if(e.target.id!=='dish-quick')return;e.preventDefault();if(dishComposing)return;const restaurant=current(),name=e.target.elements.name.value.trim();if(!restaurant||restaurant.id!==e.target.dataset.restaurant||!name)return;const rank=e.submitter?.value==='black'?'black':'red',d={id:crypto.randomUUID(),restaurantId:restaurant.id,name,rank,note:'',date:today(),updatedAt:stamp(),deleted:false},next=structuredClone(state),draft=dishDrafts.get(restaurant.id);next.dishes.push(d);dishDrafts.delete(restaurant.id);if(filter!=='all'&&filter!==rank)filter='all';if(change(next)){$('#quick-dish-name')?.focus({preventScroll:true});toast('已加入'+(rank==='red'?'红榜':'黑榜'))}else dishDrafts.set(restaurant.id,draft||name)});
$('#search').oninput=e=>{query=e.target.value;renderList()};
function updatePairCode(){const cfg=config();$('#sync-current-code').value=cfg?cfg.id+'.'+cfg.token:''}
$('#settings-open').onclick=()=>{updatePairCode();$('#sync-status').textContent=lastSyncMessage||'保存第一条记录时会自动建立加密同步。';$('#settings-dialog').showModal()};
function synchronize(override=null){
 if(syncBusy){if(override)return syncTask.then(()=>synchronize(override));syncAgain=true;return syncTask}if(storageBlocked)return Promise.resolve(false);syncBusy=true;syncTask=performSync(override);return syncTask;
}
async function performSync(override){
 saveMessage('记录已保存在此设备 · 正在同步');
 try{const cfg=override||config()||await register();for(let attempt=0;attempt<4;attempt++){
  const cloud=await fetchCloud(cfg),combined=merge(state,cloud.state||empty());persist(combined);render();
  if(cloud.state&&JSON.stringify(combined)===JSON.stringify(cloud.state)){if(override)useConfig(cfg);saveMessage('已加密同步 · 手机与电脑可连接同一配对码');break}
  try{await putCloud(combined,cloud.revision,cfg);if(override)useConfig(cfg);saveMessage('已加密同步 · 手机与电脑可连接同一配对码');break}catch(e){if(e.status!==409||attempt===3)throw e}
 }updatePairCode();return true;
 }catch(e){saveMessage('已保存在此设备 · 同步未完成：'+e.message,true);updatePairCode();return false}finally{syncBusy=false;if(syncAgain){syncAgain=false;scheduleSync()}}
}
$('#sync-now').onclick=()=>synchronize();$('#sync-connect').onclick=async()=>{const button=$('#sync-connect');try{const cfg=parseCode($('#sync-code').value);button.disabled=true;$('#pair-status').textContent=syncBusy?'等待当前同步完成，再连接另一台设备…':'正在连接另一台设备…';const ok=await synchronize(cfg);if(!ok)throw Error(lastSyncMessage);$('#pair-status').textContent='已连接，菜馆和菜品记录已合并。两台设备的「本设备配对码」现在相同。';toast('已连接另一台设备')}catch(e){$('#pair-status').textContent='连接未完成：'+e.message}finally{button.disabled=false}};
$('#sync-copy').onclick=async()=>{try{if(!await synchronize())throw Error(lastSyncMessage);const cfg=config();if(!cfg)throw Error('未能建立同步，请联网后重试');updatePairCode();try{await navigator.clipboard.writeText($('#sync-current-code').value);toast('本设备配对码已复制')}catch{$('#sync-current-code').focus();$('#sync-current-code').select();toast('请长按或按 Ctrl/Cmd+C 复制已选中的配对码')}}catch(e){toast(e.message||'请联网后重试')}};
$('#export').onclick=()=>{const raw=storageBlocked?localStorage.getItem(KEY):JSON.stringify(state,null,2);const blob=new Blob([raw||''],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='food-ledger-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('完整备份已导出')};
$('#import-open').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>8_000_000)throw Error('备份文件超过 8 MB');const imported=normalize(JSON.parse(await file.text()));if(change(merge(state,imported)))toast('备份已合并')}catch(e){toast('导入失败：'+e.message)}finally{e.target.value=''}};
const hasSyncData=()=>config()||state.restaurants.length;
addEventListener('hashchange',route);addEventListener('online',()=>{if(hasSyncData())synchronize()});addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&hasSyncData())synchronize()});addEventListener('storage',e=>{if(e.key===KEY){try{state=merge(state,normalize(JSON.parse(e.newValue||JSON.stringify(empty()))));render();scheduleSync()}catch{toast('另一窗口的记录无法读取，请先备份')}}});
setInterval(()=>{if(hasSyncData()&&document.visibilityState==='visible')synchronize()},60000);route();if(hasSyncData())synchronize();
