import {emptyRecipes,presetTags,recipeLink,sourceLabel,lines,normalizeRecipes,mergeRecipes,liveRecipes} from './recipes-model.mjs?v=20261010-3';
import {fetchDocument,putDocument,extractRecipe} from './sync.mjs?v=20261010-3';
import {initShopping} from './shopping.mjs?v=20261010-3';
const KEY='food-recipes.v1',$=s=>document.querySelector(s),esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function initRecipes({onChange,toast,ensureAccount}){
 let state=emptyRecipes(),blocked=false,selected='',query='',tag='',editing='',extractedBy='',warnings=[],author='',images=[],busy=false,pending=null,controller=null;
 const shopping=initShopping({recipes:()=>liveRecipes(state),onChange,toast});
 const prepared=new Map();
 try{const raw=localStorage.getItem(KEY);if(raw)state=normalizeRecipes(JSON.parse(raw))}catch{blocked=true;$('#recipes-storage-error').textContent='菜谱记录无法读取，已暂停写入。请先导出备份。'}
 const stamp=()=>Math.max(Date.now(),...state.recipes.map(r=>r.updatedAt+1)),current=()=>state.recipes.find(r=>r.id===selected&&!r.deleted);
 function persist(next){if(blocked)throw Error('菜谱存储无法读取，已暂停保存');const normalized=normalizeRecipes(next);try{localStorage.setItem(KEY,JSON.stringify(normalized))}catch{throw Error('菜谱保存失败，请先导出备份并检查浏览器存储')}state=normalized}
 function change(next){try{persist(next);render();onChange();return true}catch(e){toast(e.message);return false}}
 function render(){
  const active=location.hash==='#recipes'||location.hash.startsWith('#recipe/'),shoppingActive=location.hash==='#shopping';$('#recipes-shell').hidden=!active;$('#food-shell').hidden=active||shoppingActive;$('#shopping-shell').hidden=!shoppingActive;shopping.render();
  document.querySelectorAll('[data-food-tab]').forEach(b=>{const yes=b.dataset.foodTab===(shoppingActive?'shopping':active?'recipes':'restaurants');b.classList.toggle('active',yes);b.setAttribute('aria-selected',String(yes))});
  const id=location.hash.startsWith('#recipe/')?location.hash.slice(8):'';selected=state.recipes.some(r=>r.id===id&&!r.deleted)?id:'';document.body.classList.toggle('recipe-detail-open',active&&!!selected);
  const all=liveRecipes(state),tags=[...new Set([...presetTags,...all.flatMap(r=>r.tags)])];if(tag&&!tags.includes(tag))tag='';$('#recipe-count').textContent=all.length;
  $('#recipe-filters').innerHTML=['',...tags].map(t=>`<button type="button" data-recipe-filter="${esc(t)}" class="${tag===t?'active':''}" aria-pressed="${tag===t}">${esc(t)||'全部'}</button>`).join('');
  const q=query.toLocaleLowerCase(),rows=all.filter(r=>(!tag||r.tags.includes(tag))&&(!q||[r.name,r.note,...r.tags,...r.ingredients].join(' ').toLocaleLowerCase().includes(q)));
  $('#recipe-list').innerHTML=rows.length?rows.map(r=>`<button class="recipe-card ${selected===r.id?'selected':''}" data-recipe="${r.id}"><span class="recipe-source">${esc(sourceLabel(r.url))}</span><h3>${esc(r.name)}</h3><p>${r.ingredients.length} 项食材 · ${r.steps.length} 个步骤</p><div class="recipe-tags">${r.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div></button>`).join(''):`<div class="list-empty">${all.length?'没有匹配的菜谱。':'把看到的好菜谱先收下。<br>链接、做法和食材，下次一起找得到。'}</div>`;
  const r=current();if(!r){$('#recipe-detail').innerHTML=`<div class="board-empty recipe-welcome"><span class="recipe-book" aria-hidden="true">⌑</span><p class="eyebrow">自己的厨房笔记</p><h2>从想做，到拿手菜</h2><p>收藏原始菜谱，记下要买的食材和做法。<br>给值得再做的，留一个「回头菜」标签。</p><button class="primary" data-new-recipe>收藏菜谱</button></div>`;return}
  const done=prepared.get(r.id)||new Set();
  $('#recipe-detail').innerHTML=`<div class="recipe-heading"><button class="mobile-back" data-recipe-back>返回菜谱列表</button><div class="detail-top"><div><p class="eyebrow">${esc(sourceLabel(r.url))}${r.author?' · '+esc(r.author):''}</p><h2>${esc(r.name)}</h2></div><button class="icon-button" data-edit-recipe>编辑</button></div><div class="recipe-shopping-action"><button type="button" class="quiet" data-shop-recipe="${r.id}">生成购物清单</button></div>${r.url?`<a class="place-link" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">打开原始菜谱 ↗</a>`:''}<div class="recipe-tags tag-actions">${presetTags.map(t=>`<button data-toggle-recipe-tag="${t}" aria-pressed="${r.tags.includes(t)}" class="${r.tags.includes(t)?'active':''}">${t}</button>`).join('')}${r.tags.filter(t=>!presetTags.includes(t)).map(t=>`<span>${esc(t)}</span>`).join('')}</div>${r.note?`<p class="place-note">${esc(r.note)}</p>`:''}${r.extractedBy==='screenshot'?'<p class="field-help">由截图识别后保存，请对照原文核对用量与步骤。</p>':''}${r.warnings.length?`<p class="recipe-warnings">${r.warnings.map(esc).join('；')}</p>`:''}</div><div class="recipe-content"><section class="ingredient-panel"><div class="recipe-section-head"><h3>食材与要买的菜</h3>${r.ingredients.length?'<button class="quiet" data-copy-ingredients>复制待买</button>':''}</div>${r.ingredients.length?`<p class="field-help">勾选已备好的食材，复制剩余清单。</p><ul class="ingredient-list">${r.ingredients.map((v,i)=>`<li><label class="${done.has(i)?'prepared':''}"><input type="checkbox" data-ingredient="${i}" ${done.has(i)?'checked':''}><span>${esc(v)}</span></label></li>`).join('')}</ul>`:'<p class="list-empty">还未记录用料，点击编辑补充或识别截图。</p>'}</section><section class="steps-panel"><div class="recipe-section-head"><h3>做菜步骤</h3><small>${r.steps.length?'按顺序开始做':''}</small></div>${r.steps.length?`<ol class="recipe-steps">${r.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>`:'<p class="list-empty">先收好链接，有空再补做法。</p>'}</section></div>`;
 }
 function resetImages(){for(const image of images)URL.revokeObjectURL(image.url);images=[];$('#recipe-images').value='';$('#recipe-image-preview').innerHTML='';$('#recipe-recognize').disabled=true}
 function open(r=null,seed=''){
  editing=r?.id||'';extractedBy=r?.extractedBy||'';warnings=r?.warnings||[];author=r?.author||'';pending=null;resetImages();const f=$('#recipe-form');f.reset();$('#recipe-extraction-preview').hidden=true;$('#recipe-extract-status').textContent='';$('#recipe-error').textContent='';$('#recipe-form-title').textContent=r?'编辑菜谱':'收藏一道菜谱';
  const url=recipeLink(seed);for(const name of ['name','url','note'])f.elements[name].value=r?.[name]||(name==='url'?url:name==='name'&&!url?seed:'');f.elements.ingredients.value=r?.ingredients.join('\n')||'';f.elements.steps.value=r?.steps.join('\n')||'';f.elements.tags.value=r?.tags.filter(t=>!presetTags.includes(t)).join('，')||'';
  document.querySelectorAll('#recipe-preset-tags input').forEach(i=>i.checked=(r?.tags||['想做']).includes(i.value));$('#recipe-delete').hidden=!r;$('#recipe-dialog').showModal();(url?$('#recipe-name'):$('#recipe-url')).focus();updateLinkHelp();
 }
 function updateLinkHelp(){const label=sourceLabel(recipeLink($('#recipe-url').value));$('#recipe-link-help').textContent=label==='小红书'?'小红书保留原始链接，可选下方截图识别食材和步骤。':label==='下厨房'?'尝试读取公开菜谱；遇到登录或验证页面时，可改用截图。':'保存任意菜谱链接，也可以只填名字手动记录。';$('#recipe-read-link').disabled=busy||label!=='下厨房'}
 function setBusy(value){busy=value;$('#recipe-read-link').disabled=value;$('#recipe-recognize').disabled=value||!images.length;$('#recipe-images').disabled=value;$('#recipe-save').disabled=value;$('#recipe-apply').disabled=value;if(!value)updateLinkHelp()}
 async function run(kind,body){
  setBusy(true);$('#recipe-extract-status').textContent=kind==='read-recipe'?'正在读取下厨房菜谱…':'正在识别所选截图，可能需要几十秒…';$('#recipe-extraction-preview').hidden=true;pending=null;controller=new AbortController();const local=controller;
  try{const cfg=await ensureAccount();if(local.signal.aborted)return;const result=await extractRecipe(kind,body,cfg);if(local.signal.aborted)return;pending=result;$('#recipe-extraction-text').textContent=[result.name||'未识别名称','食材：'+result.ingredients.join('；'),'步骤：\n'+result.steps.map((s,i)=>`${i+1}. ${s}`).join('\n'),...(result.warnings||[])].join('\n\n');$('#recipe-extraction-preview').hidden=false;$('#recipe-extract-status').textContent='提取完成。核对后点击「填入菜谱」，仍可继续编辑。'}catch(e){if(!local.signal.aborted)$('#recipe-extract-status').textContent=e.message+'。已填写的内容仍保留，可直接保存。'}finally{if(controller===local){controller=null;setBusy(false)}}
 }
 $('#recipe-quick-form').onsubmit=e=>{e.preventDefault();open(null,$('#recipe-quick').value.trim())};$('#recipe-search').oninput=e=>{query=e.target.value;render()};
 $('#recipe-url').oninput=updateLinkHelp;
 $('#recipe-read-link').onclick=()=>{const url=recipeLink($('#recipe-url').value);if(sourceLabel(url)!=='下厨房'){toast('请先填写下厨房菜谱链接');return}$('#recipe-url').value=url;run('read-recipe',{url})};
 $('#recipe-images').onchange=async e=>{
  const files=[...e.target.files];resetImages();$('#recipe-extract-status').textContent='';if(!files.length)return;if(files.length>6){toast('一次最多选择 6 张截图');return}
  setBusy(true);const preparation=new AbortController();controller=preparation;
  try{for(const file of files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>20_000_000)throw Error('请选择不超过 20 MB 的 JPG、PNG 或 WebP 图片');const data=await compressImage(file);if(preparation.signal.aborted)return;images.push({data,mimeType:'image/jpeg',url:URL.createObjectURL(file),name:file.name})}$('#recipe-image-preview').innerHTML=images.map((i,n)=>`<figure><img src="${i.url}" alt="菜谱截图 ${n+1}"><figcaption>${n+1}</figcaption></figure>`).join('');$('#recipe-extract-status').textContent=`已选择 ${images.length} 张，按显示顺序识别。文字太小或长截图建议分成几张。`}catch(e){resetImages();$('#recipe-extract-status').textContent=e.message}finally{if(controller===preparation){controller=null;setBusy(false)}}
 };
 $('#recipe-recognize').onclick=()=>run('recognize-recipe',{images:images.map(({mimeType,data})=>({mimeType,data}))});
 $('#recipe-apply').onclick=()=>{if(!pending)return;const f=$('#recipe-form');if((f.elements.ingredients.value.trim()||f.elements.steps.value.trim())&&!confirm('用提取结果替换当前表单的食材和步骤？'))return;if(!f.elements.name.value.trim()&&pending.name)f.elements.name.value=pending.name;f.elements.ingredients.value=pending.ingredients.join('\n');f.elements.steps.value=pending.steps.join('\n');extractedBy=pending.source;warnings=pending.warnings||[];author=pending.author||'';$('#recipe-extraction-preview').hidden=true;$('#recipe-extract-status').textContent='已填入。可修改名称、食材、步骤和标签，然后保存。';pending=null};
 $('#recipe-form').onsubmit=e=>{
  e.preventDefault();const f=e.currentTarget,name=f.elements.name.value.trim(),url=recipeLink(f.elements.url.value);if(!name){$('#recipe-error').textContent='请填写菜谱名称';$('#recipe-name').focus();return}if(f.elements.url.value.trim()&&!url){$('#recipe-error').textContent='请填写有效的 http 或 https 链接';return}
  if(pending&&!confirm('提取结果尚未填入。仅保存当前表单内容？'))return;
  if(editing&&!state.recipes.some(r=>r.id===editing&&!r.deleted)){toast('这道菜谱已在另一台设备删除，请重新收藏');return}
  const tags=[...document.querySelectorAll('#recipe-preset-tags input:checked')].map(i=>i.value).concat(f.elements.tags.value.split(/[，,\n]/).map(t=>t.trim()).filter(Boolean));
  const r={id:editing||crypto.randomUUID(),name,url,ingredients:lines(f.elements.ingredients.value),steps:lines(f.elements.steps.value),tags,note:f.elements.note.value.trim(),updatedAt:stamp(),deleted:false,extractedBy,warnings,author};const next=structuredClone(state),at=next.recipes.findIndex(x=>x.id===r.id);if(at<0)next.recipes.push(r);else next.recipes[at]=r;
  if(change(next)){$('#recipe-dialog').close();$('#recipe-quick').value='';location.hash='recipe/'+r.id;toast('菜谱已收藏')}
 };
 $('#recipe-delete').onclick=()=>{const r=state.recipes.find(r=>r.id===editing);if(r&&confirm(`删除「${r.name}」？`)){const next=structuredClone(state),row=next.recipes.find(r=>r.id===editing);row.deleted=true;row.updatedAt=stamp();if(change(next)){$('#recipe-dialog').close();location.hash='recipes';toast('菜谱已删除')}}};
 $('#recipe-dialog').addEventListener('close',()=>{controller?.abort();controller=null;pending=null;resetImages();setBusy(false)});
 document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.shopRecipe)shopping.open(b.dataset.shopRecipe);if(b.matches('[data-new-recipe]'))open();if(b.dataset.recipe){location.hash='recipe/'+b.dataset.recipe;window.scrollTo({top:0})}if(b.matches('[data-recipe-back]'))location.hash='recipes';if(b.matches('[data-recipe-filter]')){tag=b.dataset.recipeFilter;render()}if(b.matches('[data-edit-recipe]'))open(current());if(b.dataset.toggleRecipeTag&&current()){const next=structuredClone(state),r=next.recipes.find(r=>r.id===selected),t=b.dataset.toggleRecipeTag;r.tags=r.tags.includes(t)?r.tags.filter(v=>v!==t):[...r.tags,t];r.updatedAt=stamp();change(next)}if(b.matches('[data-copy-ingredients]')&&current()){const r=current(),done=prepared.get(r.id)||new Set(),text=r.ingredients.filter((_,i)=>!done.has(i)).join('\n');if(!text){toast('食材已全部备好');return}try{await navigator.clipboard.writeText(text);toast('待买食材已复制')}catch{$('#shopping-copy-text').value=text;$('#shopping-copy-dialog').showModal();$('#shopping-copy-text').select()}}});
 document.addEventListener('change',e=>{if(e.target.matches('[data-ingredient]')&&current()){const r=current(),done=prepared.get(r.id)||new Set(),i=Number(e.target.dataset.ingredient);if(e.target.checked)done.add(i);else done.delete(i);prepared.set(r.id,done);e.target.closest('label').classList.toggle('prepared',e.target.checked)}});
 addEventListener('storage',e=>{if(e.key===KEY){try{state=mergeRecipes(state,normalizeRecipes(JSON.parse(e.newValue||JSON.stringify(emptyRecipes()))));render();onChange()}catch{toast('另一窗口的菜谱无法读取，请先备份')}}});
 async function synchronizeRecipes(cfg){if(blocked)throw Error('菜谱存储无法读取，已暂停同步');for(let i=0;i<4;i++){const cloud=await fetchDocument(cfg,'food-recipes'),combined=mergeRecipes(state,cloud.state||emptyRecipes());persist(combined);render();if(cloud.state&&JSON.stringify(combined)===JSON.stringify(cloud.state))return;try{await putDocument(combined,cloud.revision,cfg,'food-recipes');return}catch(e){if(e.status!==409||i===3)throw e}}}
 return {render,hasData:()=>state.recipes.length>0||shopping.hasData(),shoppingSnapshot:shopping.snapshot,validateShopping:shopping.validate,importShopping:shopping.import,snapshot:()=>{if(blocked)throw Error('菜谱备份无法读取，请检查浏览器存储');return structuredClone(state)},validate:normalizeRecipes,import:value=>change(mergeRecipes(state,value)),async synchronize(cfg){await synchronizeRecipes(cfg);await shopping.synchronize(cfg)}};
}
async function compressImage(file){
 const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();let scale=Math.min(1,1600/img.naturalWidth,4000/img.naturalHeight),blob;
  for(let i=0;i<4;i++){const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',i?0.76:0.9));if(blob&&blob.size<1_000_000)break;scale*=0.8}if(!blob||blob.size>=1_000_000)throw Error('截图仍过大，请裁剪或分成几张');return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob)})
 }finally{URL.revokeObjectURL(url)}
}
