import * as M from './model.mjs';
import * as Store from './storage.mjs';
import * as Export from './export.mjs';
import * as Sync from './sync.mjs';
const $=s=>document.querySelector(s),mac=/Mac|iPhone|iPad/.test(navigator.platform),mod=mac?'⌘':'Ctrl';
function h(tag,props={},...kids){const el=document.createElement(tag);for(const [key,v] of Object.entries(props)){if(key.startsWith('on'))el.addEventListener(key.slice(2),v);else if(key==='style')Object.assign(el.style,v);else if(key==='class')el.className=v;else if(key.startsWith('data-')||key.startsWith('aria-')||key==='role')el.setAttribute(key,v);else el[key]=v}for(const child of kids.flat(Infinity)){if(child!==null&&child!==undefined&&child!==false)el.append(child instanceof Node?child:document.createTextNode(String(child)))}return el}
const button=(label,fn,props={})=>h('button',{type:'button',onclick:guard(fn),...props},label);
function guard(fn){return async e=>{try{await fn(e)}catch(error){toast(error.message,true)}}}
let state=M.empty(),ui;try{ui=JSON.parse(localStorage.getItem('pttodo.ui'))||{}}catch{ui={}}
ui={selected:'',scope:'',include:false,open:{},drafts:{},archives:{},...ui};
let ready=false,saving=Promise.resolve(),pending=0,failed=false,undo=[],dragId='',toastTimer,cloudBusy=false,cloudBlocked=false,cloudMeta={},searchResults=[],searchIndex=0,previewRecord=false;
const channel=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('pt-todo-dashboard'):null;
const persistUI=()=>{try{localStorage.setItem('pttodo.ui',JSON.stringify(ui))}catch{}};
function toast(message,bad=false,action){clearTimeout(toastTimer);const box=$('#toast');box.classList.toggle('bad',bad);box.replaceChildren(h('span',{},message),...(action?[button(action.label,()=>{action.run();box.hidden=true})]:[]));box.hidden=false;toastTimer=setTimeout(()=>box.hidden=true,action?12000:bad?9000:4000)}
function saved(text){$('#saved').textContent=text}
function queueSave(snapshot,reason='edit'){
 pending++;saved('保存中…');
 saving=saving.catch(()=>{}).then(()=>Store.save(snapshot,reason)).then(()=>{failed=false;channel?.postMessage({type:'saved'});scheduleSync()}).catch(e=>{failed=true;toast('保存失败：'+e.message+'。保留页面并下载 JSON 备份。',true)}).finally(()=>{pending--;saved(failed?'未保存 · 请备份':pending?'保存中…':'已保存到本机')});return saving;
}
function commit(fn,{paint=true,focus='',history=true,reason='edit'}={}){if(!ready)throw Error('数据尚未加载');const next=structuredClone(state);fn(next);if(history){undo.push(structuredClone(state));undo=undo.slice(-40)}state=next;queueSave(structuredClone(state),reason);if(paint)render(focus);else $('#undo-button').disabled=!undo.length;return state}
function selected(){return state.nodes.find(n=>n.id===ui.selected)}
function color(id){return M.rootOf(state,id)?.color||M.palette[0]}
function selectNode(id,{focus=false,taskId=''}={}){const n=state.nodes.find(n=>n.id===id);if(!n)return;ui.selected=id;ui.scope=M.rootOf(state,id).id;ui.taskHighlight=taskId;for(const a of M.trail(state,id).slice(0,-1))if(a.collapsed)commit(s=>{s.nodes.find(x=>x.id===a.id).collapsed=false},{paint:false,history:false});if(taskId){ui.open['detail:'+taskId]=true;ui.include=false}persistUI();render(focus?'node:'+id:'');if(taskId){requestAnimationFrame(()=>{const el=document.querySelector(`[data-key="title:detail:${CSS.escape(taskId)}"]`);el?.closest('.task')?.classList.add('highlight');el?.scrollIntoView({block:'nearest'})})}}
function preserve(box,build){const scroll=box.scrollTop;box.replaceChildren(...build().flat(Infinity).filter(x=>x!==null&&x!==undefined&&x!==false));box.scrollTop=scroll}
function render(focus=''){
 const active=document.activeElement,key=active?.dataset.key,pos=['INPUT','TEXTAREA'].includes(active?.tagName)?[active.selectionStart,active.selectionEnd]:null;
 if(!selected()&&state.nodes.length)ui.selected=M.children(state)[0]?.id||state.nodes[0].id;
 if(ui.scope!=='all'&&!state.nodes.some(n=>n.id===ui.scope&&!n.parentId))ui.scope=M.rootOf(state,ui.selected)?.id||'all';
 paintTree();paintDetail();paintChecklist();$('#undo-button').disabled=!undo.length;persistUI();
 const target=focus||key;if(target){const input=document.querySelector(`[data-key="${CSS.escape(target)}"]`);input?.focus({preventScroll:true});if(!focus&&pos&&input?.setSelectionRange)try{input.setSelectionRange(...pos)}catch{}}
}
function branchCount(id){return state.tasks.filter(t=>[id,...M.descendants(state,id)].includes(t.nodeId)&&!t.done).length}
function addNode(parent='',after='',first=false){let id;commit(s=>{id=M.createNode(s,parent,after).id;if(first){const nodes=M.children(s,parent),n=nodes.find(n=>n.id===id);nodes.splice(nodes.indexOf(n),1);nodes.unshift(n);nodes.forEach((n,i)=>n.order=i)}ui.selected=id;ui.scope=M.rootOf(s,id).id},{focus:''});render('node:'+id)}
function fold(id,value){commit(s=>{const n=s.nodes.find(n=>n.id===id);n.collapsed=value})}
function paintTree(){
 $('#tree-count').textContent=`${M.children(state).length} 个项目 · ${state.tasks.filter(t=>!t.done).length} 待办`;
 preserve($('#tree'),()=>state.nodes.length?M.visibleNodes(state).map(({n,depth})=>{
  const has=M.children(state,n.id).length,row=h('div',{class:'tree-row'+(n.id===ui.selected?' selected':'')+(n.status==='archived'?' archived':''),style:{'--depth':depth,'--branch':color(n.id)},role:'treeitem','aria-level':depth+1,'aria-selected':n.id===ui.selected,...(has?{'aria-expanded':!n.collapsed}:{})});
  const input=h('input',{class:'node-name',value:n.name,placeholder:'新项目','data-key':'node:'+n.id,'aria-label':'项目名称',onmousedown:()=>{if(ui.selected!==n.id)selectNode(n.id,{focus:true})},onfocus:()=>{if(ui.selected!==n.id)selectNode(n.id,{focus:true})},oninput:e=>{commit(s=>{const x=s.nodes.find(x=>x.id===n.id);x.name=e.target.value;x.updatedAt=M.stamp()},{paint:false,history:false});if(ui.selected===n.id)$('#detail .detail-title h2').textContent=e.target.value||'未命名项目'},onkeydown:e=>treeKey(e,n.id)});
  row.append(button(has?(n.collapsed?'▸':'▾'):'·',()=>has&&fold(n.id,!n.collapsed),{'aria-label':has?(n.collapsed?'展开项目':'折叠项目'):'无子项目',tabIndex:has?0:-1}),h('button',{class:'dot',draggable:true,type:'button','aria-label':'拖动 '+(n.name||'项目'),title:'拖动圆点移动项目',ondragstart:e=>{dragId=n.id;e.dataTransfer.setData('text/plain',n.id);e.dataTransfer.effectAllowed='move'},ondragend:clearDrag,onclick:()=>selectNode(n.id)}),input,button(String(branchCount(n.id)),()=>{selectNode(n.id);if(n.collapsed)fold(n.id,false)},{class:'count',title:'分支中的开放待办'}));
  row.addEventListener('dragover',e=>{if(!dragId)return;e.preventDefault();clearDropHints();row.classList.add('drop-'+dropZone(e,row))});row.addEventListener('dragleave',()=>row.classList.remove('drop-before','drop-after','drop-inside'));
  row.addEventListener('drop',guard(e=>{if(!dragId)return;e.preventDefault();const id=dragId,zone=dropZone(e,row);clearDrag();if(id===n.id)return;commit(s=>{if(zone==='inside')M.moveNode(s,id,n.id);else{const sib=M.children(s,n.parentId).filter(x=>x.id!==id),index=sib.findIndex(x=>x.id===n.id);M.moveNode(s,id,n.parentId,zone==='before'?n.id:sib[index+1]?.id||'')}ui.selected=id;ui.scope=M.rootOf(s,id)?.id},{focus:'node:'+id})}));return row;
 }):[h('div',{class:'empty'},h('h2',{},'把工作组织起来'),h('p',{},'创建项目与子项，记录过程，并追踪长期待办。'),button('+ 创建第一个项目',()=>addNode()),button('导入已有 worklog.json',showExport))]);
}
function dropZone(e,row){const r=row.getBoundingClientRect(),fraction=(e.clientY-r.top)/r.height;return fraction<.3?'before':fraction>.7?'after':'inside'}
function clearDropHints(){document.querySelectorAll('.drop-before,.drop-after,.drop-inside').forEach(el=>el.classList.remove('drop-before','drop-after','drop-inside'))}
function clearDrag(){dragId='';clearDropHints();$('#root-drop').classList.remove('over')}
function treeKey(e,id){
 if(e.isComposing||e.keyCode===229)return;const n=state.nodes.find(x=>x.id===id),sib=M.children(state,n.parentId),index=sib.findIndex(x=>x.id===id),visible=M.visibleNodes(state),vi=visible.findIndex(x=>x.n.id===id);
 if(e.key==='Enter'){e.preventDefault();const has=M.children(state,id);addNode(has.length&&!n.collapsed?id:n.parentId,has.length&&!n.collapsed?'':id,!!(has.length&&!n.collapsed))}
 else if(e.key==='Tab'){e.preventDefault();if(e.shiftKey)outdent(id);else indent(id)}
 else if(e.altKey&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();reorder(id,e.key==='ArrowUp'?-1:1)}
 else if((e.metaKey||e.ctrlKey)&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft'&&(n.collapsed||!M.children(state,id).length)&&n.parentId)selectNode(n.parentId,{focus:true});else fold(id,e.key==='ArrowLeft')}
 else if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const next=visible[vi+(e.key==='ArrowUp'?-1:1)];if(next)selectNode(next.n.id,{focus:true})}
 else if(e.key==='Backspace'&&!n.name){e.preventDefault();if(n.notes||M.children(state,id).length||state.tasks.some(t=>t.nodeId===id))askDeleteNode(id);else{const target=visible[vi-1]?.n.id;commit(s=>M.deleteNode(s,id));if(target)selectNode(target,{focus:true})}}
 else if(e.key==='Escape'){e.preventDefault();e.target.blur()}
}
function indent(id){const n=state.nodes.find(n=>n.id===id),siblings=M.children(state,n.parentId),i=siblings.findIndex(n=>n.id===id);if(i>0)commit(s=>{M.moveNode(s,id,siblings[i-1].id);ui.scope=M.rootOf(s,id).id},{focus:'node:'+id});else toast('前面没有同级项目，可用“移到”选择父项目')}
function outdent(id){const n=state.nodes.find(n=>n.id===id),p=state.nodes.find(x=>x.id===n.parentId);if(!p)return;const siblings=M.children(state,p.parentId),next=siblings[siblings.findIndex(x=>x.id===p.id)+1];commit(s=>{M.moveNode(s,id,p.parentId,next?.id||'');ui.scope=M.rootOf(s,id).id},{focus:'node:'+id})}
function reorder(id,delta){const n=state.nodes.find(x=>x.id===id),siblings=M.children(state,n.parentId),i=siblings.findIndex(x=>x.id===id),j=i+delta;if(j<0||j>=siblings.length)return;commit(s=>{const rows=M.children(s,n.parentId);[rows[i],rows[j]]=[rows[j],rows[i]];rows.forEach((x,k)=>x.order=k)},{focus:'node:'+id})}
function breadcrumb(id){const ns=M.trail(state,id);return h('div',{class:'breadcrumb'},ns.map((n,i)=>[i?h('span',{},'/'):null,button(n.name||'未命名',()=>selectNode(n.id),{title:M.trail(state,n.id).map(n=>n.name).join(' / ')})]))}
function composer(place,nodeId){const draftKey=place+':'+nodeId,input=h('input',{value:ui.drafts[draftKey]||'',placeholder:'添加待办…','data-key':'composer:'+place,'aria-label':place==='detail'?'项目新待办':'清单新待办',disabled:!nodeId,oninput:e=>{ui.drafts[draftKey]=e.target.value;persistUI()},onkeydown:e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();add()}}});function add(){if(!input.value.trim())return;commit(s=>M.createTask(s,nodeId,input.value));ui.drafts[draftKey]='';persistUI();render('composer:'+place)}return h('div',{class:'composer'},h('span',{class:'plus'},'+'),input,button('添加',add,{class:'primary',disabled:!nodeId}))}
function noteEditor(n){const editor=h('textarea',{class:'record-editor',value:n.notes,placeholder:'记录决定、发现、数字或会议结论（Markdown）…','data-key':'record:'+n.id,'aria-label':'项目 Markdown 记录',oninput:e=>commit(s=>{const x=s.nodes.find(x=>x.id===n.id);x.notes=e.target.value;x.updatedAt=M.stamp()},{paint:false,history:false})});return [h('div',{class:'editor-head'},h('span',{},'项目记录 · Markdown'),h('div',{class:'tools'},button(previewRecord?'编辑':'预览',()=>{previewRecord=!previewRecord;paintDetail()}),button('+ '+M.today(),()=>{commit(s=>{const x=s.nodes.find(x=>x.id===n.id);x.notes+=(x.notes?'\n\n':'')+'### '+M.today()+' —\n';x.updatedAt=M.stamp()},{focus:'record:'+n.id});const input=$(`[data-key="record:${CSS.escape(n.id)}"]`);input?.setSelectionRange(input.value.length,input.value.length)}))),previewRecord?markdown(n.notes):editor]}
function markdown(text){const el=h('div',{class:'record-preview'});let code=false;for(const line of text.split('\n')){if(line.startsWith('```')){code=!code;continue}let tag=code?'code':/^### /.test(line)?'h4':/^## /.test(line)?'h3':/^# /.test(line)?'h2':'div';const content=line.replace(/^#{1,3} /,'').replace(/^[-*] /,'• '),row=h(tag);for(const part of content.split(/(\*\*[^*]+\*\*|`[^`]+`)/g)){row.append(part.startsWith('**')?h('strong',{},part.slice(2,-2)):part.startsWith('`')?h('code',{},part.slice(1,-1)):document.createTextNode(part))}el.append(row)}if(!text)el.append(h('span',{class:'meta'},'尚无记录'));return el}
function taskCard(t,place,showPath=false){
 const key=place+':'+t.id,open=ui.open[key],row=h('article',{class:'task'+(t.done?' done':''),'data-task':t.id});
 const title=h('input',{class:'task-title',value:t.title,'data-key':'title:'+key,'aria-label':'待办内容',oninput:e=>{commit(s=>{s.tasks.find(x=>x.id===t.id).title=e.target.value},{paint:false,history:false});document.querySelectorAll(`[data-task="${CSS.escape(t.id)}"] .task-title`).forEach(input=>{if(input!==e.target)input.value=e.target.value})}});
 const check=h('input',{type:'checkbox',checked:t.done,'aria-label':(t.done?'重新打开':'完成')+' '+t.title,onchange:e=>commit(s=>M.toggleTask(s.tasks.find(x=>x.id===t.id),e.target.checked))});
 row.append(h('div',{class:'task-head'},check,h('div',{class:'task-text'},title)));
 const lines=t.notes.split('\n').filter(x=>/^\*\*\d{4}-\d{2}-\d{2}|^###? /.test(x)).length;
 row.append(h('div',{class:'task-meta'},showPath?breadcrumb(t.nodeId):null,h('span',{},'＋ '+(t.date||t.createdAt.slice(0,10))),t.done?h('span',{},'✓ '+(t.completedDate||t.completedAt.slice(0,10))):null,button('日志'+(t.notes?' ('+(lines||1)+')':''),()=>{ui.open[key]=!open;persistUI();render(open?'':'notes:'+key)},{class:'log-chip','aria-expanded':!!open}),button('删除',()=>deleteTask(t.id),{class:'task-delete danger','aria-label':'删除待办 '+t.title})));
 if(open){const editor=h('textarea',{value:t.notes,placeholder:'此待办的进度、决定或补充说明…','data-key':'notes:'+key,'aria-label':'待办日志',oninput:e=>commit(s=>s.tasks.find(x=>x.id===t.id).notes=e.target.value,{paint:false,history:false})});
  row.append(h('div',{class:'task-notes'},h('div',{class:'editor-head'},h('span',{},'待办日志 · Markdown'),button('+ '+M.today(),()=>{commit(s=>{const x=s.tasks.find(x=>x.id===t.id);x.notes+=(x.notes?'\n\n':'')+'**'+M.today()+'** — '},{focus:'notes:'+key});const e=document.querySelector(`[data-key="notes:${CSS.escape(key)}"]`);e?.setSelectionRange(e.value.length,e.value.length)})),editor,h('div',{class:'task-actions'},h('select',{value:t.nodeId,'aria-label':'移动待办到项目',onchange:e=>commit(s=>{const x=s.tasks.find(x=>x.id===t.id);x.nodeId=e.target.value;x.order=s.tasks.filter(t=>t.nodeId===x.nodeId).length;M.renumber(s)})},state.nodes.map(n=>h('option',{value:n.id,selected:n.id===t.nodeId},M.trail(state,n.id).map(n=>n.name||'未命名').join(' / ')))),h('input',{value:t.tags.join(', '),placeholder:'标签，逗号分隔','aria-label':'待办标签',onchange:e=>commit(s=>s.tasks.find(x=>x.id===t.id).tags=e.target.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean))}))))
 }else if(t.notes)row.append(h('div',{class:'note-summary'},t.notes));return row;
}
function deleteTask(id){const t=structuredClone(state.tasks.find(t=>t.id===id));commit(s=>{s.tasks=s.tasks.filter(t=>t.id!==id);M.renumber(s)});toast('已删除待办',false,{label:'撤销',run:()=>{if(state.nodes.some(n=>n.id===t.nodeId)&&!state.tasks.some(x=>x.id===t.id))commit(s=>{s.tasks.push(t);M.renumber(s)})}})}
function tasksView(tasks,place,showPath=false){const open=tasks.filter(t=>!t.done).sort((a,b)=>a.order-b.order||a.createdAt.localeCompare(b.createdAt)),done=tasks.filter(t=>t.done).sort((a,b)=>b.completedAt.localeCompare(a.completedAt));return [open.length?open.map(t=>taskCard(t,place,showPath)):h('div',{class:'empty'},tasks.length?'这部分待办已全部完成':'还没有待办'),done.length?h('details',{class:'archive',open:!!ui.archives[place],ontoggle:e=>{ui.archives[place]=e.target.open;persistUI()}},h('summary',{},'归档 · '+done.length+' 已完成'),done.map(t=>taskCard(t,place,showPath))):null]}
function paintDetail(){preserve($('#detail'),()=>{const n=selected();if(!n)return [h('div',{class:'empty'},h('h2',{},'项目记录与待办'),h('p',{},'从左侧创建项目，或导入原来的 JSON 数据。'))];const ids=ui.include?[n.id,...M.descendants(state,n.id)]:[n.id],tasks=state.tasks.filter(t=>ids.includes(t.nodeId));
 const settings=h('div',{class:'node-settings'},h('label',{},'状态',h('select',{'aria-label':'项目状态',onchange:e=>commit(s=>s.nodes.find(x=>x.id===n.id).status=e.target.value)},[['active','进行中'],['paused','暂停'],['archived','归档']].map(([v,label])=>h('option',{value:v,selected:n.status===v},label)))),h('label',{},'移到',h('select',{'aria-label':'移动项目到父项',onchange:e=>commit(s=>{M.moveNode(s,n.id,e.target.value);ui.scope=M.rootOf(s,n.id).id})},h('option',{value:'',selected:!n.parentId},'顶层'),state.nodes.filter(x=>x.id!==n.id&&!M.descendants(state,n.id).includes(x.id)).map(x=>h('option',{value:x.id,selected:n.parentId===x.id},M.trail(state,x.id).map(n=>n.name||'未命名').join(' / '))))),!n.parentId?h('label',{},'分支颜色',h('input',{type:'color',value:n.color||M.palette[0],'aria-label':'分支颜色',oninput:e=>commit(s=>s.nodes.find(x=>x.id===n.id).color=e.target.value)})):null,h('div',{class:'node-buttons'},button('缩进',()=>indent(n.id)),button('反缩进',()=>outdent(n.id)),button('上移',()=>reorder(n.id,-1)),button('下移',()=>reorder(n.id,1)),button('删除项目',()=>askDeleteNode(n.id),{class:'danger'})));
 return [breadcrumb(n.id),h('div',{class:'detail-title'},h('div',{style:{display:'flex',alignItems:'center',gap:'8px','--branch':color(n.id)}},h('span',{class:'branch-dot'}),h('h2',{},n.name||'未命名项目')),button('+ 子项',()=>addNode(n.id))),...noteEditor(n),h('div',{class:'editor-head'},h('span',{class:'section-label',style:{margin:'20px 0 0'}},'待办 · '+tasks.filter(t=>!t.done).length+' 开放'),h('label',{class:'include-toggle'},h('input',{type:'checkbox',checked:ui.include,onchange:e=>{ui.include=e.target.checked;persistUI();paintDetail()}}),'含子项目')),composer('detail',n.id),...tasksView(tasks,'detail',ui.include),settings];})}
function paintChecklist(){
 const scope=$('#scope');scope.replaceChildren(h('option',{value:'all'},'全部项目'),...M.children(state).map(n=>h('option',{value:n.id},n.name||'未命名项目')));scope.value=ui.scope;
 const ids=ui.scope==='all'?state.nodes.map(n=>n.id):[ui.scope,...M.descendants(state,ui.scope)],tasks=state.tasks.filter(t=>ids.includes(t.nodeId));$('#checklist-count').textContent=tasks.filter(t=>!t.done).length+' 开放 · '+tasks.filter(t=>t.done).length+' 已完成';
 const nodeId=selected()?.id;preserve($('#checklist'),()=>[h('div',{class:'meta',style:{marginBottom:'10px'}},nodeId?'添加到 '+M.trail(state,nodeId).map(n=>n.name||'未命名').join(' / '):'先选择项目'),composer('checklist',nodeId),...tasksView(tasks,'checklist',true)]);
}
function confirmAction(title,copy,choices){const dialog=$('#confirm-dialog');if(dialog.open)dialog.close();$('#confirm-title').textContent=title;$('#confirm-copy').textContent=copy;$('#confirm-actions').replaceChildren(...choices.map(c=>button(c.label,async()=>{dialog.close();await c.run()},{class:c.danger?'danger':c.primary?'primary':''})),button('取消',()=>dialog.close()));dialog.showModal()}
function askDeleteNode(id){const n=state.nodes.find(n=>n.id===id),count=M.descendants(state,id).length,taskCount=state.tasks.filter(t=>[id,...M.descendants(state,id)].includes(t.nodeId)).length;confirmAction('删除 '+(n.name||'未命名项目'),`包含 ${count} 个子项、${taskCount} 条待办。仅删除此项会把子项与待办上移；顶层待办移到“未分类”。此项的记录会删除，可用撤销恢复。`,[{label:'仅删除此项',run:()=>commit(s=>M.deleteNode(s,id,false)),danger:true},{label:'删除整个分支',run:()=>commit(s=>M.deleteNode(s,id,true)),danger:true}])}
function undoChange(){if(!undo.length)return;const old=undo.pop();state=old;queueSave(structuredClone(state));render();toast('已撤销上一步结构操作')}
function showSearch(){$('#search-dialog').showModal();$('#search-input').value='';paintSearch();$('#search-input').focus()}
function paintSearch(){searchResults=M.search(state,$('#search-input').value);searchIndex=0;$('#search-results').replaceChildren(...(searchResults.length?searchResults.map((r,i)=>button('',()=>openResult(i),{class:'search-result'+(!i?' active':'')})).map((el,i)=>{const r=searchResults[i];el.append(h('strong',{},(r.kind==='task'?'☐ ':'')+r.title),h('small',{},M.trail(state,r.nodeId).map(n=>n.name).join(' / ')),h('small',{},r.excerpt.slice(0,140)));return el}):[h('div',{class:'empty'},$('#search-input').value?'没有匹配结果':'输入关键词，搜索项目、记录、待办与日志')]))}
function openResult(i){const r=searchResults[i];if(!r)return;$('#search-dialog').close();selectNode(r.nodeId,{taskId:r.kind==='task'?r.id:''});if(r.kind==='node')$(`[data-key="record:${CSS.escape(r.nodeId)}"]`)?.focus()}
async function showExport(){if(!$('#export-dialog').open)$('#export-dialog').showModal();await saving;$('#folder-name').value=state.settings.folderName||'Work Log';$('#tag-prefix').value=state.settings.tagPrefix||'worklog';$('#file-preview').replaceChildren();await paintBackups();if(!$('#export-dialog').open)$('#export-dialog').showModal()}
function exportSettings(){commit(s=>{s.settings.folderName=Export.safeName($('#folder-name').value||'Work Log');s.settings.tagPrefix=$('#tag-prefix').value||'worklog'},{paint:false,history:false});return state}
function previewFiles(){const files=Export.exportFiles(exportSettings());$('#file-preview').replaceChildren(h('div',{},files.length+' 个 Markdown 文件'),...files.map(f=>{const wrap=h('div'),b=button(f.path,()=>{let pre=wrap.querySelector('pre');if(pre)pre.remove();else wrap.append(h('pre',{},f.content))});wrap.append(b);return wrap}))}
async function paintBackups(){const xs=await Store.backups()||[],bad=await Store.corrupt();$('#backup-list').replaceChildren(...(xs.length?[...xs].reverse().map(x=>h('div',{class:'backup-row'},h('span',{},new Date(x.at).toLocaleString()+' · '+x.reason),button('下载',()=>Export.download('worklog-backup-'+x.date+'.json',JSON.stringify(x.data,null,2),'application/json')),button('恢复',()=>confirmAction('恢复备份','当前数据会先保存一份备份，再使用选择的版本。',[{label:'恢复此版本',primary:true,run:()=>{replaceState(M.normalize(x.data),'import');$('#export-dialog').close();toast('备份已恢复')}}])))):[h('p',{class:'meta'},'首次修改已有数据后，会显示备份。')]),bad?button('下载保留的异常原件',()=>Export.download('worklog-corrupt.json',JSON.stringify(bad.data,null,2),'application/json')):null)}
function replaceState(next,reason){undo.push(structuredClone(state));state=next;if(reason!=='cloud'){ui.selected='';ui.scope='all'}queueSave(structuredClone(state),reason);render()}
async function importFile(file){if(!file)return;if(file.size>15_000_000)throw Error('JSON 超过 15 MB，请拆分后导入');let next;try{next=M.normalize(JSON.parse(await file.text()))}catch(e){throw Error('导入失败：'+e.message)}confirmAction('导入 '+file.name,`将用 ${next.nodes.length} 个项目、${next.tasks.length} 条待办替换当前数据。已保存的当前数据会先生成备份。`,[{label:'导入并保留旧版备份',primary:true,run:()=>{replaceState(next,'import');$('#export-dialog').close();toast('导入完成')}}])}
let syncTimer;
function syncNote(text){$('#sync-status').textContent=text;$('#sync-button').textContent=Sync.config()?'同步 · 已连接':'同步'}
function scheduleSync(){clearTimeout(syncTimer);if(!Sync.config()||cloudBusy||cloudBlocked)return;syncTimer=setTimeout(()=>syncNow().catch(e=>syncNote('本机已保存；同步失败：'+e.message)),1800)}
async function syncNow(){
 if(cloudBusy||cloudBlocked||!Sync.config())return;cloudBusy=true;syncNote('同步中…');
 try{await saving;if(failed)throw Error('本机保存失败，请先备份');const cfg=Sync.config(),remote=await Sync.fetchCloud(cfg),current=JSON.stringify(state),changed=current!==(cloudMeta.base||JSON.stringify(M.empty())),remoteChanged=remote.revision!==(cloudMeta.account===cfg.id?cloudMeta.revision:0);
  if(remote.state&&JSON.stringify(remote.state)!==current&&changed&&remoteChanged){cloudBlocked=true;syncNote('两台设备都有修改，请选择要继续使用的版本');confirmAction('发现同步冲突','本机和云端都有独立修改。可先下载两个版本；采用云端前会备份本机，上传本机前会备份云端。',[{label:'下载双方版本',run:()=>{Export.download('worklog-local.json',JSON.stringify(state,null,2),'application/json');Export.download('worklog-cloud.json',JSON.stringify(remote.state,null,2),'application/json');cloudBlocked=false;toast('双方版本已下载；再次同步可选择')}},{label:'采用云端',primary:true,run:async()=>{replaceState(remote.state,'cloud');await saving;cloudMeta={account:cfg.id,revision:remote.revision,base:JSON.stringify(state)};await Store.meta(cloudMeta);cloudBlocked=false;syncNote('已接收云端；本机旧版已备份')}},{label:'上传本机',run:async()=>{await Store.save(remote.state,'cloud');await Store.save(state,'cloud');const result=await Sync.putCloud(state,remote.revision,cfg);cloudMeta={account:cfg.id,revision:result.revision,base:JSON.stringify(state)};await Store.meta(cloudMeta);cloudBlocked=false;syncNote('本机版本已上传；云端旧版已备份')}}]);return}
  if(remote.state&&remoteChanged&&!changed){replaceState(remote.state,'cloud');await saving;cloudMeta={account:cfg.id,revision:remote.revision,base:JSON.stringify(state)}}
  else if(changed||!remote.state){const snapshot=structuredClone(state),result=await Sync.putCloud(snapshot,remote.revision,cfg);cloudMeta={account:cfg.id,revision:result.revision,base:JSON.stringify(snapshot)}}
  else cloudMeta={account:cfg.id,revision:remote.revision,base:current};
  await Store.meta(cloudMeta);syncNote('已同步 · '+new Date().toLocaleTimeString());
 }finally{cloudBusy=false;if(cloudBlocked)$('#confirm-dialog').addEventListener('close',()=>{cloudBlocked=false},{once:true})}
}
async function connectDevice(){const cfg=Sync.parseCode($('#sync-code').value);await Sync.fetchCloud(cfg);Sync.useConfig(cfg);cloudMeta={account:cfg.id,revision:0,base:JSON.stringify(M.empty())};await Store.meta(cloudMeta);await syncNow()}
// Keep ordinary editor undo and IME composition intact.
document.addEventListener('keydown',e=>{if(e.isComposing||e.keyCode===229)return;const key=e.key.toLowerCase(),editing=e.target.matches('input,textarea,[contenteditable=true]'),dialog=document.querySelector('dialog[open]');if((e.ctrlKey||e.metaKey)&&['k','e','s'].includes(key)){e.preventDefault();if(dialog&&dialog.id!=='search-dialog'&&key==='k')return;if(key==='k'){if(!$('#search-dialog').open)showSearch();else $('#search-input').focus()}if(key==='e')showExport();if(key==='s')queueSave(structuredClone(state));return}if(dialog)return;if(!editing&&key==='n'&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();$('[data-key="composer:checklist"]')?.focus()}if(!editing&&(e.ctrlKey||e.metaKey)&&key==='z'){e.preventDefault();undoChange()}});
$('#add-project').onclick=guard(()=>addNode());$('#fold-all').onclick=guard(()=>commit(s=>s.nodes.forEach(n=>n.collapsed=true)));$('#expand-all').onclick=guard(()=>commit(s=>s.nodes.forEach(n=>n.collapsed=false)));$('#undo-button').onclick=undoChange;
$('#root-drop').ondragover=e=>{if(!dragId)return;e.preventDefault();e.currentTarget.classList.add('over')};$('#root-drop').ondragleave=e=>e.currentTarget.classList.remove('over');$('#root-drop').ondrop=guard(e=>{if(!dragId)return;e.preventDefault();const id=dragId;clearDrag();commit(s=>{M.moveNode(s,id);ui.selected=id;ui.scope=id},{focus:'node:'+id})});
$('#scope').onchange=e=>{ui.scope=e.target.value;if(ui.scope!=='all')ui.selected=ui.scope;persistUI();render()};
$('#search-button').onclick=showSearch;$('.shortcut').textContent=mod+' K';$('#search-input').oninput=paintSearch;$('#search-input').onkeydown=e=>{if(e.isComposing)return;if(['ArrowDown','ArrowUp'].includes(e.key)&&searchResults.length){e.preventDefault();searchIndex=(searchIndex+(e.key==='ArrowDown'?1:-1)+searchResults.length)%searchResults.length;document.querySelectorAll('.search-result').forEach((el,i)=>{el.classList.toggle('active',i===searchIndex);if(i===searchIndex)el.scrollIntoView({block:'nearest'})})}if(e.key==='Enter'){e.preventDefault();openResult(searchIndex)}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#help-button').onclick=()=>$('#help-dialog').showModal();$('#theme-button').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';ui.theme=document.documentElement.dataset.theme;persistUI()};
document.documentElement.dataset.theme=ui.theme||(()=>{try{return JSON.parse(localStorage.getItem('ptu.theme'))||'light'}catch{return 'light'}})();
$('#export-button').onclick=guard(showExport);$('#json-download').onclick=()=>Export.download('worklog.json',JSON.stringify(state,null,2),'application/json');$('#import-button').onclick=()=>$('#import-file').click();$('#import-file').onchange=guard(async e=>{try{await importFile(e.target.files[0])}finally{e.target.value=''}});$('#preview-export').onclick=previewFiles;$('#zip-download').onclick=()=>Export.download('Work-Log-'+M.today()+'.zip',Export.zip(Export.exportFiles(exportSettings())));$('#md-download').onclick=()=>Export.download('Work-Log-'+M.today()+'.md',Export.bundle(exportSettings()));
const directorySupported=typeof window.showDirectoryPicker==='function'&&window.top===window;$('#directory-export').disabled=!directorySupported;$('#directory-help').textContent=directorySupported?'选择 Obsidian 仓库或其他目录，文件只写入上面的导出文件夹。清理仅涉及本工具清单中记录的旧文件。':'此浏览器或嵌入环境不支持目录授权。请下载 ZIP，解压后把 Work Log 文件夹放入 Obsidian 仓库。';
$('#directory-export').onclick=guard(async()=>{let root;try{root=await showDirectoryPicker({mode:'readwrite'})}catch(e){if(e.name==='AbortError')return;throw e}const result=await Export.writeDirectory(root,Export.exportFiles(exportSettings()),$('#prune-files').checked);commit(s=>{s.settings.lastExportAt=M.stamp();s.settings.lastExportPath=root.name},{paint:false,history:false});toast(`已写入 ${result.written} 个文件${result.removed?'，清理 '+result.removed+' 个旧文件':''}`)});
$('#sync-button').onclick=()=>{$('#sync-dialog').showModal();syncNote(Sync.config()?'此设备已连接，可立即同步':'尚未连接')};$('#sync-create').onclick=guard(async()=>{await saving;if(!Sync.config())$('#sync-code').value=await Sync.register();else $('#sync-code').value=Sync.config().id+'.'+Sync.config().token;await syncNow()});$('#sync-connect').onclick=guard(connectDevice);$('#sync-now').onclick=guard(syncNow);$('#sync-disconnect').onclick=()=>{localStorage.removeItem('ptu.sync.config');clearTimeout(syncTimer);cloudBlocked=false;cloudMeta={};Store.meta({});$('#sync-code').value='';syncNote('已断开此设备；本机数据保留')};
addEventListener('beforeunload',e=>{if(pending||failed){e.preventDefault();e.returnValue=''}});addEventListener('pagehide',persistUI);addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&ready)syncNow().catch(e=>syncNote(e.message))});
// Do not silently replace edits in another tab sharing this browser's database.
channel?.addEventListener('message',async()=>{if(!ready||pending)return;try{const next=await Store.load(false);if(JSON.stringify(next)!==JSON.stringify(state)){toast('另一标签页修改了数据',false,{label:'读取新版',run:async()=>{if(failed)Export.download('worklog-unsaved.json',JSON.stringify(state,null,2),'application/json');state=await Store.load();failed=false;render();saved('已读取新版')}})}}catch(e){toast(e.message,true)}});
try{state=await Store.load();cloudMeta=await Store.meta();ready=true;render();saved('已保存到本机');syncNote(Sync.config()?'此设备已连接':'尚未连接');if(Sync.config())syncNow().catch(e=>syncNote('本机可用；'+e.message))}catch(e){ready=true;render();saved('原数据需检查');toast(e.message,true)}
setInterval(()=>{if(ready&&document.visibilityState==='visible')syncNow().catch(e=>syncNote('本机已保存；'+e.message))},60000);
if(window.parent!==window)window.parent.postMessage({channel:'pt-nexus-tool',type:'ready'},location.origin);
