export const palette=['#5965db','#138773','#bd6a29','#a450a1','#387ca8','#b14c61'];
export const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export const stamp=()=>new Date().toISOString();
export const uid=p=>p+'_'+crypto.randomUUID();
export const empty=()=>({version:1,settings:{folderName:'Work Log',tagPrefix:'worklog'},nodes:[],tasks:[],logs:[]});
export const children=(s,p='')=>s.nodes.filter(n=>n.parentId===p).sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id));
export function descendants(s,id){const out=[];for(const n of children(s,id)){out.push(n.id,...descendants(s,n.id))}return out}
export function trail(s,id){const out=[];let n=s.nodes.find(n=>n.id===id);while(n){out.unshift(n);n=s.nodes.find(x=>x.id===n.parentId)}return out}
export const rootOf=(s,id)=>trail(s,id)[0];
export function visibleNodes(s){const out=[];function walk(p,depth){for(const n of children(s,p)){out.push({n,depth});if(!n.collapsed)walk(n.id,depth+1)}}walk('',0);return out}
export function renumber(s){for(const p of new Set(['',...s.nodes.map(n=>n.parentId)]))children(s,p).forEach((n,i)=>n.order=i);for(const p of new Set(s.tasks.map(t=>t.nodeId)))s.tasks.filter(t=>t.nodeId===p).sort((a,b)=>a.order-b.order).forEach((t,i)=>t.order=i)}
export function createNode(s,parentId='',after=''){if(parentId&&!s.nodes.some(n=>n.id===parentId))throw Error('父项目不存在');const siblings=children(s,parentId),index=after?siblings.findIndex(n=>n.id===after)+1:siblings.length;for(const n of siblings.slice(index))n.order++;const n={id:uid('n'),name:'',notes:'',status:'active',parentId,order:index,collapsed:false,color:parentId?'':palette[siblings.length%palette.length],createdAt:stamp(),updatedAt:stamp()};s.nodes.push(n);if(parentId)s.nodes.find(n=>n.id===parentId).collapsed=false;renumber(s);return n}
export function moveNode(s,id,parentId='',before=''){const n=s.nodes.find(n=>n.id===id);if(!n)throw Error('项目不存在');if(parentId===id||descendants(s,id).includes(parentId))throw Error('不能移动到自己的子项目中');if(parentId&&!s.nodes.some(n=>n.id===parentId))throw Error('父项目不存在');const siblings=children(s,parentId).filter(n=>n.id!==id),index=before?siblings.findIndex(n=>n.id===before):siblings.length;n.parentId=parentId;n.order=index<0?siblings.length:index;n.updatedAt=stamp();siblings.splice(n.order,0,n);siblings.forEach((n,i)=>n.order=i);if(parentId)s.nodes.find(n=>n.id===parentId).collapsed=false;renumber(s)}
export function deleteNode(s,id,cascade=false){const n=s.nodes.find(n=>n.id===id);if(!n)return;const removed=cascade?[id,...descendants(s,id)]:[id];if(!cascade){const siblings=children(s,n.parentId),next=siblings[siblings.findIndex(x=>x.id===id)+1];for(const child of children(s,id))moveNode(s,child.id,n.parentId,next?.id||'');for(const t of s.tasks.filter(t=>t.nodeId===id))t.nodeId=n.parentId;if(!n.parentId&&s.tasks.some(t=>t.nodeId==='')){let inbox=s.nodes.find(x=>!removed.includes(x.id)&&x.name==='未分类'&&!x.parentId);if(!inbox){inbox=createNode(s);inbox.name='未分类'}s.tasks.filter(t=>!t.nodeId).forEach(t=>t.nodeId=inbox.id)}}s.nodes=s.nodes.filter(n=>!removed.includes(n.id));if(cascade)s.tasks=s.tasks.filter(t=>!removed.includes(t.nodeId));renumber(s)}
export function createTask(s,nodeId,title){if(!s.nodes.some(n=>n.id===nodeId))throw Error('先选择一个项目');if(!title.trim())throw Error('请输入待办内容');const t={id:uid('t'),title:title.trim(),nodeId,done:false,notes:'',tags:[],order:s.tasks.filter(t=>t.nodeId===nodeId).length,date:today(),createdAt:stamp(),completedAt:null};s.tasks.push(t);return t}
export function toggleTask(t,done){t.done=done;t.completedAt=done?stamp():null;t.completedDate=done?today():null}
export function normalize(raw){
 if(!raw||typeof raw!=='object'||!Array.isArray(raw.nodes)||!Array.isArray(raw.tasks))throw Error('需要包含 nodes 和 tasks 的 worklog.json 文件');
 if(raw.version!=null&&raw.version!==1)throw Error('不支持此数据版本，请导出 version: 1 的文件');
 const s=empty();s.settings={...s.settings,...(raw.settings||{})};s.logs=Array.isArray(raw.logs)?structuredClone(raw.logs):[];
 const ids=new Set(),str=x=>typeof x==='string'?x:'';
 s.nodes=raw.nodes.map((n,i)=>{if(!n||!str(n.id)||ids.has(n.id))throw Error('项目 ID 缺失或重复');ids.add(n.id);return {...n,id:n.id,name:str(n.name),notes:[str(n.summary),str(n.notes)].filter(Boolean).join('\n\n'),status:['active','paused','archived'].includes(n.status)?n.status:'active',parentId:str(n.parentId),order:Number.isFinite(n.order)?n.order:i,collapsed:!!n.collapsed,color:n.parentId?'':/^#[0-9a-f]{6}$/i.test(n.color||'')?n.color:palette[i%palette.length],createdAt:str(n.createdAt)||stamp(),updatedAt:str(n.updatedAt)||stamp()}});
 for(const n of s.nodes){if(n.parentId&&!ids.has(n.parentId))throw Error('项目引用了不存在的父项目');const seen=new Set([n.id]);let p=n.parentId;while(p){if(seen.has(p))throw Error('项目层级包含循环');seen.add(p);p=s.nodes.find(n=>n.id===p).parentId}}
 const tids=new Set();s.tasks=raw.tasks.map((t,i)=>{if(!t||!str(t.id)||tids.has(t.id))throw Error('待办 ID 缺失或重复');tids.add(t.id);if(!ids.has(t.nodeId))throw Error('待办引用了不存在的项目');return {...t,id:t.id,nodeId:t.nodeId,title:str(t.title),notes:str(t.notes),done:!!t.done,tags:Array.isArray(t.tags)?t.tags.map(String):[],order:Number.isFinite(t.order)?t.order:i,date:/^\d{4}-\d{2}-\d{2}$/.test(t.date||'')?t.date:today(),createdAt:str(t.createdAt)||stamp(),completedAt:t.done?(str(t.completedAt)||str(t.createdAt)||stamp()):null}});
 // Retain the original logs too; fold readable legacy entries into the thing they describe.
 for(const l of s.logs){const target=s.tasks.find(t=>t.id===l.taskId)||s.nodes.find(n=>n.id===(l.nodeId||l.itemId));if(target){const content=l.content||l.text||l.notes||'',heading=`### ${l.date||String(l.createdAt||'').slice(0,10)||today()}${l.title?' — '+l.title:''}`,entry=heading+'\n'+content;if(content&&!target.notes.includes(entry))target.notes+=(target.notes?'\n\n':'')+entry}}
 for(const n of s.nodes)delete n.summary;
 renumber(s);return s;
}
export function search(s,q){q=q.trim().toLocaleLowerCase();if(!q)return [];return [...s.nodes.filter(n=>[n.name,n.notes].join(' ').toLocaleLowerCase().includes(q)).map(n=>({kind:'node',id:n.id,nodeId:n.id,title:n.name||'未命名项目',excerpt:n.notes})),...s.tasks.filter(t=>[t.title,t.notes,...t.tags].join(' ').toLocaleLowerCase().includes(q)).map(t=>({kind:'task',id:t.id,nodeId:t.nodeId,title:t.title,excerpt:t.notes}))]}
