import {Editor,getSchema,StarterKit,Image} from './editor.bundle.mjs';
import * as M from './model.mjs';import * as Store from './storage.mjs';import * as Sync from './sync.mjs';
const $=s=>document.querySelector(s),uiKey='ideapad.notes.ui';let ui;try{ui=JSON.parse(localStorage.getItem(uiKey))||{}}catch{ui={}}ui={selected:'',folded:[],...ui};
let state=M.empty(),editor,ready=false,dirty=false,failed=false,saveTimer,saving=Promise.resolve(),pending=0,dragId='',cloudMeta={},cloudBusy=false,syncTimer,conflict=null,editGeneration=0;
const channel=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('pt-idea-pad-notes'):null;
const h=(tag,props={},...kids)=>{const e=document.createElement(tag);for(const [k,v]of Object.entries(props)){if(k.startsWith('on'))e.addEventListener(k.slice(2),v);else if(k==='class')e.className=v;else if(k==='style')for(const [p,value]of Object.entries(v))e.style.setProperty(p,value);else if(k.startsWith('aria-')||k.startsWith('data-')||k==='role')e.setAttribute(k,v);else e[k]=v}for(const c of kids.flat()){if(c!==null&&c!==undefined)e.append(c instanceof Node?c:document.createTextNode(String(c)))}return e};
const btn=(label,fn,props={})=>h('button',{type:'button',onclick:guard(fn),...props},label);
function guard(fn){return async e=>{try{await fn(e)}catch(err){toast(err.message)}}}function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,6500)}
function persistUI(){try{localStorage.setItem(uiKey,JSON.stringify(ui))}catch{}}function selected(){return state.pages.find(p=>p.id===ui.selected&&!M.trashed(state,p))}function saved(){ $('#saved').textContent=failed?'未保存 · 请备份':dirty||pending?'保存中…':'已保存到本机'}
function changed(fn,{tree=false,paint=false,reason='edit'}={}){if(!ready)throw Error('数据尚未载入');fn(state);editGeneration++;dirty=true;clearTimeout(saveTimer);saveTimer=setTimeout(()=>flush(reason),300);saved();if(paint)render();else if(tree)paintTree()}
function flush(reason='edit'){clearTimeout(saveTimer);if(!dirty)return saving;const snapshot=structuredClone(state);dirty=false;pending++;saved();saving=saving.catch(()=>{}).then(()=>Store.save(snapshot,reason)).then(()=>{failed=false;channel?.postMessage('saved');scheduleSync()}).catch(e=>{failed=true;toast('保存失败：'+e.message+'。请先下载完整备份。')}).finally(()=>{pending--;saved()});return saving}
function download(name,data,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type})),a=h('a',{href:url,download:name});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function newPage(parentId=''){flush();let p;changed(s=>{p=M.createPage(s,parentId)},{tree:true});if(parentId)ui.folded=ui.folded.filter(x=>x!==parentId);selectPage(p.id);$('#page-title').focus()}
function selectPage(id){const p=state.pages.find(p=>p.id===id&&!M.trashed(state,p));if(!p)return;flush();ui.selected=id;ui.folded=ui.folded.filter(x=>!M.trail(state,id).slice(0,-1).some(p=>p.id===x));persistUI();render();if(matchMedia('(max-width:650px)').matches)document.body.classList.add('sidebar-closed')}
function paintTree(){const search=$('#page-search').value.trim().toLowerCase(),tree=$('#page-tree');tree.replaceChildren();const rows=[];const live=state.pages.filter(p=>!M.trashed(state,p));
 const visit=(parent='',depth=0)=>{for(const p of M.children(state,parent)){if(M.trashed(state,p))continue;rows.push({p,depth});if(!ui.folded.includes(p.id))visit(p.id,depth+1)}};
 if(search)live.filter(p=>(p.title+'\n'+M.textOf(p.content)).toLowerCase().includes(search)).forEach(p=>rows.push({p,depth:0}));else visit();
 for(const {p,depth}of rows){const kids=M.children(state,p.id),folded=ui.folded.includes(p.id),row=h('div',{class:'tree-row'+(p.id===ui.selected?' selected':''),role:'treeitem','aria-level':depth+1,'aria-selected':p.id===ui.selected,...(kids.length?{'aria-expanded':!folded}:{}),style:{'--depth':depth},'data-page':p.id});
  if(depth)row.append(h('span',{class:'tree-guide','aria-hidden':'true'}));row.append(btn(kids.length?(folded?'▸':'▾'):'',()=>{ui.folded=folded?ui.folded.filter(x=>x!==p.id):[...ui.folded,p.id];persistUI();paintTree()},{'aria-label':(folded?'展开':'折叠')+' '+(p.title||'未命名'),disabled:!kids.length}),h('button',{type:'button',class:'page-pick',draggable:!search,'aria-label':'打开 '+(p.title||'未命名'),onclick:()=>selectPage(p.id),ondragstart:e=>{dragId=p.id;e.dataTransfer.setData('text/plain',p.id);e.dataTransfer.effectAllowed='move'},ondragend:()=>{dragId='';document.querySelectorAll('.over').forEach(x=>x.classList.remove('over'))}},h('span',{class:'page-symbol','aria-hidden':'true'},'▤'),h('span',{},p.title||'未命名')),btn('＋',()=>newPage(p.id),{class:'child-add','aria-label':'在 '+(p.title||'未命名')+' 下新建页面'}));
  row.ondragover=e=>{if(dragId&&dragId!==p.id){e.preventDefault();row.classList.add('over')}};row.ondragleave=()=>row.classList.remove('over');row.ondrop=guard(e=>{e.preventDefault();row.classList.remove('over');if(!dragId||dragId===p.id)return;const id=dragId;changed(s=>M.movePage(s,id,p.id),{tree:true});ui.folded=ui.folded.filter(x=>x!==p.id);selectPage(id);dragId=''});tree.append(row)
 }
 if(!rows.length)tree.append(h('p',{class:'empty-tree'},search?'没有匹配的页面。':'先随手写一页，再用子页面整理。'));
 $('#page-count').textContent=live.length+' 个页面';
}
function render(){paintTree();const p=selected();$('#page-empty').hidden=!!p;$('#page-content').hidden=!p;$('#export-page').disabled=!p;$('#breadcrumbs').replaceChildren(btn('随手记',()=>{const first=M.children(state).find(p=>!M.trashed(state,p));if(first)selectPage(first.id)}));
 if(!p){editor?.destroy();editor=null;return}
 for(const n of M.trail(state,p.id))$('#breadcrumbs').append(h('span',{},'/'),btn(n.title||'未命名',()=>selectPage(n.id)));
 $('#page-title').value=p.title;const excluded=new Set([p.id,...M.descendants(state,p.id)]);$('#move-page').replaceChildren(h('option',{value:''},'顶层页面'),...state.pages.filter(x=>!excluded.has(x.id)&&!M.trashed(state,x)).map(x=>h('option',{value:x.id},M.trail(state,x.id).map(p=>p.title||'未命名').join(' / '))));$('#move-page').value=p.parentId;
 editor?.destroy();editor=new Editor({element:$('#editor'),extensions:[StarterKit.configure({heading:{levels:[1,2,3]},link:{openOnClick:false,autolink:true,linkOnPaste:true,defaultProtocol:'https',isAllowedUri:url=>!!M.safeURL(url),HTMLAttributes:{target:'_blank',rel:'noopener noreferrer nofollow'}}}),Image.configure({allowBase64:true})],content:M.cleanContent(p.content),editorProps:{attributes:{'aria-label':'随手记正文','role':'textbox','aria-multiline':'true'},handlePaste:(view,event)=>{const files=[...(event.clipboardData?.files||[])].filter(f=>f.type.startsWith('image/'));if(!files.length)return false;event.preventDefault();uploadImages(files,p.id);return true},handleDrop:(view,event)=>{const files=[...(event.dataTransfer?.files||[])].filter(f=>f.type.startsWith('image/'));if(!files.length)return false;event.preventDefault();const pos=view.posAtCoords({left:event.clientX,top:event.clientY})?.pos;if(pos!=null)editor.commands.setTextSelection(pos);uploadImages(files,p.id);return true}},onUpdate:({editor})=>{try{const content=M.cleanContent(editor.getJSON());changed(s=>{const note=s.pages.find(x=>x.id===p.id);note.content=content;note.updatedAt=M.stamp()});wordCount();toolbarState()}catch(e){toast('正文格式需要检查：'+e.message)}},onSelectionUpdate:toolbarState});
 $('#editor').onclick=e=>{const link=e.target.closest('a');if(link&&(e.ctrlKey||e.metaKey)){const url=M.safeURL(link.href);if(url)window.open(url,'_blank','noopener,noreferrer')}};paintChildren();wordCount();toolbarState();persistUI();
}
function paintChildren(){const p=selected();$('#child-pages').replaceChildren();if(!p)return;const kids=M.children(state,p.id);if(kids.length)$('#child-pages').append(h('small',{},'子页面'),...kids.map(n=>btn('▤  '+(n.title||'未命名')+'  ›',()=>selectPage(n.id))))}
function wordCount(){const text=editor?.getText()||'';$('#word-count').textContent=text.replace(/\s/g,'').length+' 字'}
function toolbarState(){if(!editor)return;document.querySelectorAll('[data-command]').forEach(b=>b.classList.toggle('active',editor.isActive(b.dataset.command)));$('#block-type').value=editor.isActive('heading')?String(editor.getAttributes('heading').level):'paragraph'}
function command(name){if(!editor)return;const map={bold:'toggleBold',italic:'toggleItalic',underline:'toggleUnderline',bulletList:'toggleBulletList',orderedList:'toggleOrderedList',blockquote:'toggleBlockquote',codeBlock:'toggleCodeBlock',undo:'undo',redo:'redo'};editor.chain().focus()[map[name]]().run()}
async function imageData(file){if(file.size>12_000_000)throw Error('图片超过 12 MB，请先缩小');if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type))throw Error('请使用 PNG、JPEG、WebP 或 GIF 图片');const url=URL.createObjectURL(file);try{const image=new globalThis.Image();image.src=url;await image.decode();const ratio=Math.min(1,1600/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*ratio));canvas.height=Math.max(1,Math.round(image.naturalHeight*ratio));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);let quality=.85,src=canvas.toDataURL('image/webp',quality);while(src.length>450000&&quality>.35){quality-=.15;src=canvas.toDataURL('image/webp',quality)}if(src.length>700000)throw Error('图片压缩后仍过大，请先缩小');return src}finally{URL.revokeObjectURL(url)}}
async function uploadImages(files,pageId=ui.selected){const position=editor?.state.selection.from;try{for(const file of files){const src=await imageData(file);const p=state.pages.find(p=>p.id===pageId&&!M.trashed(state,p));if(!p)throw Error('原页面已移入回收站，图片未插入');if(ui.selected===pageId&&editor){editor.chain().focus().setTextSelection(Math.min(position??editor.state.selection.from,editor.state.doc.content.size)).setImage({src,alt:file.name||'粘贴截图'}).run()}else{changed(s=>{const note=s.pages.find(p=>p.id===pageId);note.content.content.push({type:'image',attrs:{src,alt:file.name||'截图'}},{type:'paragraph'});note.updatedAt=M.stamp()});toast('图片已保存到原页面')} }$('#image-dialog').close()}catch(e){toast('图片未插入：'+e.message)}}
function openLink(){if(!editor)return;$('#link-url').value=editor.getAttributes('link').href||'';$('#link-label').value='';$('#link-dialog').showModal();$('#link-url').focus()}
function trashPage(){const p=selected();if(!p)return;changed(s=>{s.pages.find(x=>x.id===p.id).trashedAt=M.stamp()},{tree:true});ui.selected=state.pages.find(x=>!M.trashed(state,x))?.id||'';render();toast('已移入回收站，可随时恢复')}
function showTrash(){$('#trash-list').replaceChildren(...state.pages.filter(p=>p.trashedAt).map(p=>h('div',{class:'backup-row'},h('span',{},p.title||'未命名'),btn('恢复',()=>{changed(s=>s.pages.find(x=>x.id===p.id).trashedAt=null,{tree:true});showTrash();selectPage(p.id)}),btn('永久删除',()=>{if(!confirm('永久删除此页面及全部子页面？此操作无法撤销。'))return;const ids=new Set([p.id,...M.descendants(state,p.id)]);changed(s=>s.pages=s.pages.filter(p=>!ids.has(p.id)),{paint:true});showTrash()}))));if(!$('#trash-list').childElementCount)$('#trash-list').append(h('p',{},'回收站是空的'));if(!$('#trash-dialog').open)$('#trash-dialog').showModal()}
async function showBackup(){await flush();$('#backup-list').replaceChildren();const original=await Store.corrupt();if(original)$('#backup-list').append(h('div',{class:'backup-row'},h('span',{},'需检查的原始数据'),btn('下载原件',()=>download('idea-pad-original.json',JSON.stringify(original.data)))));for(const b of [...await Store.backups()||[]].reverse())$('#backup-list').append(h('div',{class:'backup-row'},h('span',{},new Date(b.at).toLocaleString()+' · '+b.reason),btn('下载',()=>download('idea-pad-snapshot.json',JSON.stringify(b.data))),btn('恢复',()=>{if(!confirm('恢复此快照？当前版本会先保存为备份。'))return;state=M.normalize(b.data);dirty=true;editGeneration++;flush('restore');ui.selected='';render();$('#backup-dialog').close();toast('已恢复快照')})));$('#backup-dialog').showModal()}
function noteSync(text){$('#sync-status').textContent=text;$('#sync-button').textContent=/失败|超过|本机可用|本机已保存；/.test(text)?'同步 · 待重试':Sync.config()?'同步 · 已连接':'同步'}
function scheduleSync(){clearTimeout(syncTimer);if(Sync.config()&&!cloudBusy&&!conflict)syncTimer=setTimeout(()=>syncNow().catch(e=>noteSync('本机已保存；'+e.message)),1800)}
async function syncNow(){if(cloudBusy||conflict||!Sync.config())return;cloudBusy=true;let success=false;noteSync('同步中…');try{await flush();if(failed)throw Error('请先解决本机保存失败');const cfg=Sync.config(),remote=await Sync.fetchCloud(cfg);await flush();const current=JSON.stringify(state),changed=current!==(cloudMeta.account===cfg.id?cloudMeta.base||JSON.stringify(M.empty()):JSON.stringify(M.empty())),remoteChanged=remote.revision!==(cloudMeta.account===cfg.id?cloudMeta.revision:0);
 if(remote.state&&JSON.stringify(remote.state)!==current&&changed&&remoteChanged){conflict={remote,cfg};$('#sync-conflict').hidden=false;$('#sync-dialog').showModal();noteSync('两台设备都有修改，等待选择版本');return}
 if(remote.state&&remoteChanged&&!changed){state=M.normalize(remote.state);const receivedBase=JSON.stringify(state);dirty=true;ui.selected=selected()?.id||state.pages.find(p=>!M.trashed(state,p))?.id||'';render();await flush('cloud');cloudMeta={account:cfg.id,revision:remote.revision,base:receivedBase}}
 else if(changed||!remote.state){const snapshot=structuredClone(state),result=await Sync.putCloud(snapshot,remote.revision,cfg);cloudMeta={account:cfg.id,revision:result.revision,base:JSON.stringify(snapshot)}}else cloudMeta={account:cfg.id,revision:remote.revision,base:current};
 await Store.meta(cloudMeta);success=true;noteSync('已同步 · '+new Date().toLocaleTimeString());
 }finally{cloudBusy=false;if(success&&!conflict&&JSON.stringify(state)!==cloudMeta.base)scheduleSync()}}
async function resolveConflict(useCloud){if(!conflict)return;await flush();const {remote,cfg}=conflict;if(useCloud){state=M.normalize(remote.state);dirty=true;await flush('cloud');render();cloudMeta={account:cfg.id,revision:remote.revision,base:JSON.stringify(state)}}else{await Store.save(remote.state,'cloud');await Store.save(state,'cloud');const snapshot=structuredClone(state),result=await Sync.putCloud(snapshot,remote.revision,cfg);cloudMeta={account:cfg.id,revision:result.revision,base:JSON.stringify(snapshot)}}await Store.meta(cloudMeta);conflict=null;$('#sync-conflict').hidden=true;noteSync('已同步 · '+new Date().toLocaleTimeString())}
$('#new-page').onclick=guard(()=>newPage());$('#first-page').onclick=guard(()=>newPage());$('#new-child').onclick=guard(()=>newPage(ui.selected));$('#page-search').oninput=paintTree;$('#page-title').oninput=e=>{const p=selected();if(!p)return;changed(s=>{const x=s.pages.find(x=>x.id===p.id);x.title=e.target.value;x.updatedAt=M.stamp()},{tree:true});const last=$('#breadcrumbs button:last-child');if(last)last.textContent=p.title||'未命名'};$('#move-page').onchange=guard(e=>{changed(s=>M.movePage(s,ui.selected,e.target.value));render()});$('#delete-page').onclick=trashPage;$('#trash-button').onclick=showTrash;
$('#root-drop').ondragover=e=>{if(dragId){e.preventDefault();e.currentTarget.classList.add('over')}};$('#root-drop').ondragleave=e=>e.currentTarget.classList.remove('over');$('#root-drop').ondrop=guard(e=>{e.preventDefault();e.currentTarget.classList.remove('over');if(dragId){changed(s=>M.movePage(s,dragId));dragId='';render()}});$('#root-drop').onclick=()=>toast('拖动左侧页面到这里，或用正文上方“移到”选择顶层页面');
$('#toggle-sidebar').onclick=()=>document.body.classList.toggle('sidebar-closed');if(matchMedia('(max-width:650px)').matches)document.body.classList.add('sidebar-closed');
for(const b of document.querySelectorAll('[data-command]')){b.onmousedown=e=>e.preventDefault();b.onclick=()=>command(b.dataset.command)}$('#block-type').onchange=e=>{if(!editor)return;if(e.target.value==='paragraph')editor.chain().focus().setParagraph().run();else editor.chain().focus().toggleHeading({level:Number(e.target.value)}).run()};
$('#insert-link').onmousedown=e=>e.preventDefault();$('#insert-link').onclick=openLink;$('#link-form').onsubmit=guard(e=>{e.preventDefault();const url=M.safeURL($('#link-url').value);if(!url)throw Error('请输入完整 HTTP(S) 链接');const label=$('#link-label').value.trim(),selection=editor.state.selection;if(label||selection.empty)editor.chain().focus().insertContent({type:'text',text:label||url,marks:[{type:'link',attrs:{href:url,target:'_blank',rel:'noopener noreferrer nofollow'}}]}).run();else editor.chain().focus().extendMarkRange('link').setLink({href:url}).run();$('#link-dialog').close()});$('#remove-link').onclick=()=>{editor?.chain().focus().extendMarkRange('link').unsetLink().run();$('#link-dialog').close()};
$('#insert-image').onmousedown=e=>e.preventDefault();$('#insert-image').onclick=()=>$('#image-dialog').showModal();$('#choose-image').onclick=()=>$('#image-file').click();$('#image-file').onchange=e=>{const files=[...e.target.files];e.target.value='';uploadImages(files)};$('#image-url-form').onsubmit=guard(e=>{e.preventDefault();const src=M.safeURL($('#image-url').value);if(!src)throw Error('请输入完整 HTTP(S) 图片地址');editor.chain().focus().setImage({src}).run();$('#image-url').value='';$('#image-dialog').close()});
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>b.closest('dialog').close();$('#backup-button').onclick=guard(showBackup);$('#download-json').onclick=()=>download('idea-pad-'+M.today()+'.json',JSON.stringify(state,null,2));$('#import-json').onclick=()=>$('#import-file').click();$('#import-file').onchange=guard(async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>64_000_000)throw Error('备份超过 64 MB，请拆分后导入');const next=M.normalize(JSON.parse(await file.text()));const schema=getSchema([StarterKit,Image.configure({allowBase64:true})]);for(const p of next.pages)schema.nodeFromJSON(p.content).check();if(!confirm(`导入 ${next.pages.length} 个页面并替换本机随手记？当前版本会先保存为备份。`))return;await flush();state=next;dirty=true;editGeneration++;await flush('import');ui.selected=state.pages.find(p=>!M.trashed(state,p))?.id||'';render();$('#backup-dialog').close();toast('导入完成')});$('#export-page').onclick=()=>{const p=selected();if(!p||!editor)return;const title=p.title||'未命名',escaped=title.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));download(title.replace(/[\\/:*?"<>|]/g,'-').slice(0,100)+'.html','<!doctype html><meta charset="utf-8"><title>'+escaped+'</title><style>body{max-width:820px;margin:45px auto;padding:0 24px;font:16px/1.8 system-ui}img{max-width:100%;height:auto}pre{white-space:pre-wrap;background:#f5f5f3;padding:16px}blockquote{border-left:3px solid #aaa;padding-left:18px}</style><h1>'+escaped+'</h1>'+editor.getHTML(),'text/html')};
$('#sync-button').onclick=()=>{$('#sync-dialog').showModal();noteSync(Sync.config()?'此设备已连接，可立即同步':'尚未连接')};$('#sync-create').onclick=guard(async()=>{if(!Sync.config())$('#sync-code').value=await Sync.register();else $('#sync-code').value=Sync.config().id+'.'+Sync.config().token;await syncNow()});$('#sync-connect').onclick=guard(async()=>{const cfg=Sync.parseCode($('#sync-code').value);await Sync.fetchCloud(cfg);Sync.useConfig(cfg);cloudMeta={account:cfg.id,revision:0,base:JSON.stringify(M.empty())};await Store.meta(cloudMeta);conflict=null;await syncNow()});$('#sync-now').onclick=guard(syncNow);$('#conflict-download').onclick=()=>{if(!conflict)return;download('idea-pad-local.json',JSON.stringify(state));download('idea-pad-cloud.json',JSON.stringify(conflict.remote.state))};$('#conflict-cloud').onclick=guard(()=>resolveConflict(true));$('#conflict-local').onclick=guard(()=>resolveConflict(false));
document.addEventListener('keydown',e=>{if(e.isComposing||e.keyCode===229)return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();flush()}if(mod&&e.key.toLowerCase()==='k'&&editor&&!document.querySelector('dialog[open]')){e.preventDefault();openLink()}if(mod&&e.shiftKey&&e.key.toLowerCase()==='f'){e.preventDefault();document.body.classList.remove('sidebar-closed');$('#page-search').focus()}});
addEventListener('beforeunload',e=>{if(dirty||pending||failed){flush();e.preventDefault();e.returnValue=''}});addEventListener('pagehide',()=>{flush();persistUI()});addEventListener('visibilitychange',()=>{if(document.hidden)flush();else if(ready)syncNow().catch(e=>noteSync('本机可用；'+e.message))});
channel?.addEventListener('message',async()=>{if(!ready||dirty||pending||failed)return;try{const next=await Store.load(false);if(JSON.stringify(next)!==JSON.stringify(state)){toast('另一标签页更新了随手记；切换页面前请重新加载');failed=true;$('#reload-notes').hidden=false;saved()}}catch(e){toast(e.message)}});
$('#reload-notes').onclick=guard(async()=>{await saving;download('idea-pad-before-reload.json',JSON.stringify(state));ready=false;editor?.setEditable(false);$('#page-title').disabled=true;try{state=await Store.load();dirty=false;failed=false;ready=true;ui.selected=selected()?.id||state.pages.find(p=>!M.trashed(state,p))?.id||'';render();$('#reload-notes').hidden=true;saved();toast('已读取新版；旧版本已下载为备份')}finally{ready=true;$('#page-title').disabled=false;editor?.setEditable(true)}});
try{state=await Store.load();const schema=getSchema([StarterKit,Image.configure({allowBase64:true})]);for(const p of state.pages)schema.nodeFromJSON(p.content).check();cloudMeta=await Store.meta();ready=true;if(!selected())ui.selected=state.pages.find(p=>!M.trashed(state,p))?.id||'';render();saved();noteSync(Sync.config()?'此设备已连接':'尚未连接');if(Sync.config())syncNow().catch(e=>noteSync('本机可用；'+e.message))}catch(e){ready=false;$('#saved').textContent='载入失败 · 原件保留';toast(e.message)}
setInterval(()=>{if(ready&&!document.hidden)syncNow().catch(e=>noteSync('本机已保存；'+e.message))},60000);
if(window.parent!==window){document.querySelector('.standalone-link').hidden=true;window.parent.postMessage({channel:'pt-nexus-tool',type:'ready'},location.origin)}
