
import {$,esc,link,read,save,toast,json,meta,boot,backups,day,download} from '../_lab/core.js';
boot();let data,map,layer,selected=null,tab='all',saved=read('weekend',[]);const markers=new Map();
function render(){map?.remove();map=null;markers.clear();
 $('#app').innerHTML='<div class="toolbar tabs"><button data-tab="all" aria-pressed="'+(tab==='all')+'">全部活动</button><button data-tab="saved" aria-pressed="'+(tab==='saved')+'">想去 · '+saved.length+'</button><button id="calendar">导出已收藏日历</button></div><div class="toolbar"><input type="search" id="query" aria-label="搜索活动" placeholder="搜索活动、地点或关键词"><label>地区<select id="city"><option value="">全部地区</option><option>Kirkland</option><option>Bellevue</option><option>Redmond</option></select></label><label>日期<select id="range"><option value="14">未来两周</option><option value="weekend">本周末</option><option value="today">今天</option><option value="45">未来 45 天</option></select></label><label>类型<select id="category"><option value="">全部类型</option><option>市集节庆</option><option>艺术音乐</option><option>户外</option><option>社区活动</option></select></label><label class="check"><input id="free" type="checkbox">已确认免费</label></div><p id="count" class="status"></p><div class="split"><div id="events" class="stack"></div><section class="panel map-panel"><div id="map" aria-label="活动地图"></div><p class="muted" id="mapNote">地点坐标由来源提供；无坐标的活动显示在城市中心，并明确标注。导航起点为 Juanita，不估算实时车程。</p><div id="selected"></div></section></div>';
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();window.scrollTo({top:0,behavior:'smooth'})});
 for(const id of ['query','city','range','category','free'])$('#'+id).addEventListener(id==='query'?'input':'change',cards);
 $('#calendar').onclick=calendar;
 if(window.L){map=L.map('map').setView([47.66,-122.17],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:18}).addTo(map);layer=L.layerGroup().addTo(map)}else $('#map').innerHTML='<p class="notice">地图组件未加载；活动列表和 Google Maps 导航仍可使用。</p>';cards();
}
function within(e){const today=day(),d=e.start.slice(0,10),range=$('#range').value;if(d<today)return false;const n=new Date(today+'T12:00:00Z');if(range==='today')return d===today;if(range==='weekend'){const wd=n.getUTCDay(),toSat=wd===0?-1:(6-wd);n.setUTCDate(n.getUTCDate()+toSat);const sat=n.toISOString().slice(0,10);n.setUTCDate(n.getUTCDate()+1);return d>=sat&&d<=n.toISOString().slice(0,10)}n.setUTCDate(n.getUTCDate()+Number(range));return d<=n.toISOString().slice(0,10)}
function filtered(){const q=$('#query').value.trim().toLowerCase();return data.events.filter(e=>within(e)&&(!$('#city').value||e.city===$('#city').value)&&(!$('#category').value||e.category===$('#category').value)&&(!$('#free').checked||e.free)&&(tab!=='saved'||saved.includes(e.id))&&(!q||[e.title,e.description,e.venue].join(' ').toLowerCase().includes(q)))}
function time(e){return e.start.slice(0,10)+(e.start.length>10?' · '+e.start.slice(11,16)+' PT':' · 时间见原文')}
function route(e){return 'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent('Juanita, Kirkland, WA')+'&destination='+encodeURIComponent(e.venue+' '+e.city+' WA')}
function cards(){const list=filtered();$('#count').textContent=list.length+' 场活动 · 美西时间 · 地点与报名条件以原文为准';
 $('#events').innerHTML=list.length?list.map(e=>'<article class="card '+(saved.includes(e.id)?'saved':'')+'"><div class="row"><span class="tag">'+esc(e.city)+' · '+esc(e.category)+'</span><small>'+esc(e.cost)+'</small></div><h3>'+esc(e.title)+'</h3><p><strong>'+esc(time(e))+'</strong><br><span class="muted">'+esc(e.venue)+'</span></p><p>'+esc(e.description)+'</p>'+(e.stale?'<p class="bad">来源刷新失败，请打开原文确认是否有变更。</p>':'')+'<div class="toolbar"><button data-save="'+e.id+'">'+(saved.includes(e.id)?'★ 已收藏':'☆ 想去')+'</button><button data-map="'+e.id+'">地图</button>'+link(route(e),'导航')+link(e.url,'活动详情')+'</div></article>').join(''):'<div class="empty">此条件下暂无活动，试试扩大日期范围或取消免费筛选。</div>';
 document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{saved=saved.includes(b.dataset.save)?saved.filter(x=>x!==b.dataset.save):[...saved,b.dataset.save];save('weekend',saved);cards();document.querySelector('[data-tab=saved]').textContent='想去 · '+saved.length});
 document.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>show(data.events.find(e=>e.id===b.dataset.map)));
 if(map){layer.clearLayers();markers.clear();const grouped=new Map();for(const e of list){const key=e.lat+','+e.lon;if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(e)}for(const es of grouped.values()){const e=es[0];const m=L.circleMarker([e.lat,e.lon],{radius:Math.min(8+es.length,20),color:'#5368d6',fillOpacity:.7}).addTo(layer);m.bindPopup(es.slice(0,10).map(x=>'<p><b>'+esc(x.title)+'</b><br>'+esc(time(x))+'<br>'+esc(x.locationExact?x.venue:x.city+' 城市中心示意；非活动精确坐标')+'</p>').join(''));es.forEach(x=>markers.set(x.id,m));m.on('click',()=>show(e,false))}}
}
function show(e,pan=true){selected=e;$('#selected').innerHTML='<h3>'+esc(e.title)+'</h3><p>'+esc(e.locationExact?e.venue:e.city+' 城市中心示意；请使用导航查询具体地点')+'</p>'+link(route(e),'Google Maps 导航')+' · '+link(e.url,'原文');if(map&&pan){map.setView([e.lat,e.lon],e.locationExact?14:12);markers.get(e.id)?.openPopup()}if(innerWidth<900)$('#map').scrollIntoView({behavior:'smooth',block:'center'})}
function calEscape(s){return String(s).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
function calendar(){const rows=data.events.filter(e=>saved.includes(e.id)&&e.start.slice(0,10)>=day());if(!rows.length){toast('请先收藏尚未结束的活动');return}const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//PT Universe//Weekend Atlas//ZH','CALSCALE:GREGORIAN'];for(const e of rows){lines.push('BEGIN:VEVENT','UID:'+e.id+'@pt-universe','DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').split('.')[0]+'Z');if(e.start.length>10)lines.push('DTSTART;TZID=America/Los_Angeles:'+e.start.replace(/[-:]/g,''));else lines.push('DTSTART;VALUE=DATE:'+e.start.replace(/-/g,''));if(e.end)lines.push('DTEND;TZID=America/Los_Angeles:'+e.end.replace(/[-:]/g,''));lines.push('SUMMARY:'+calEscape(e.title),'LOCATION:'+calEscape(e.venue),'DESCRIPTION:'+calEscape(e.description+'\n'+e.url),'URL:'+e.url,'END:VEVENT')}lines.push('END:VCALENDAR');download('eastside-weekend.ics',lines.join('\r\n'),'text/calendar');toast('已导出 '+rows.length+' 个活动')}
backups('weekend',()=>saved,v=>{if(!Array.isArray(v)||v.length>2000||!v.every(x=>typeof x==='string'))throw new Error('收藏格式不正确');saved=[...new Set(v)];save('weekend',saved);render()});
try{data=await json('./data/events.json');meta(data);render()}catch(e){$('#app').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}
