
import {$,esc,link,pct,compact,change,read,save,toast,json,meta,boot,backups,financialTable,bars,labels,day,expired} from '../_lab/core.js?v=2';
boot();
let data,selected='',theses=read('theses',[]),editing=null;
const rules={revenueYoY:'营收同比（%）',margin:'营业利润率（%）',fcf:'自由现金流（百万 USD）',sbcRatio:'SBC / 营收（%）',sharesYoY:'稀释股数同比（%）'};
function yoyQuarter(c,q){return c.quarters.find(p=>Math.abs((Date.parse(q.end)-Date.parse(p.end))/86400000-365)<18)}
function value(c,metric){const q=c.quarters.at(-1),y=yoyQuarter(c,q);if(!q)return null;if(metric==='revenueYoY'){const x=change(q.revenue,y?.revenue);return x===null?null:x*100}if(metric==='sharesYoY'){const x=change(q.shares,y?.shares);return x===null?null:x*100}if(metric==='margin')return q.revenue&&Number.isFinite(q.operatingIncome)?q.operatingIncome/q.revenue*100:null;if(metric==='sbcRatio')return q.revenue&&Number.isFinite(q.sbc)?q.sbc/q.revenue*100:null;return Number.isFinite(q.fcf)?q.fcf/1e6:null}
function evaluate(t){const c=data.companies.find(c=>c.ticker===t.ticker),v=c?value(c,t.metric):null;if(!Number.isFinite(v)||c.stale||expired(c.updatedAt))return {text:'待确认',cls:'muted',detail:'指标缺失或数据未及时更新'};const ok=t.op==='gte'?v>=t.threshold:v<=t.threshold;return {text:ok?'条件满足':'条件未满足',cls:ok?'good':'bad',detail:'当前 '+v.toFixed(2)+' · '+c.quarters.at(-1).end}}
function render(){
 $('#app').innerHTML='<div class="toolbar"><label>观察公司<select id="company">'+data.companies.map(c=>'<option value="'+esc(c.ticker)+'" '+(c.ticker===selected?'selected':'')+'>'+esc(c.ticker+' · '+c.name)+'</option>').join('')+'</select></label><span class="tag">'+data.companies.length+' 家公司</span></div><div id="companyView"></div><section class="panel"><div class="row"><h2>投资论点</h2><button id="newThesis" class="primary">＋ 添加论点</button></div><p class="muted">写下理由，并用一个可验证的指标跟踪。条件满足不等于买入建议。</p><div id="thesisForm"></div><div id="theses" class="grid"></div></section>';
 $('#company').onchange=e=>{selected=e.target.value;renderCompany();renderTheses()};
 $('#newThesis').onclick=()=>form();
 renderCompany();renderTheses();
}
function renderCompany(){const c=data.companies.find(c=>c.ticker===selected);if(!c){$('#companyView').innerHTML='<div class="empty">暂未取得财报，运行状态中可查看原因。</div>';return}
 const qs=c.quarters,q=qs.at(-1),prev=qs.at(-2),y=yoyQuarter(c,q),qoq=change(q.revenue,prev?.revenue),yoy=change(q.revenue,y?.revenue);
 $('#companyView').innerHTML='<section class="panel"><div class="row"><div><h2>'+esc(c.ticker+' · '+c.name)+'</h2><small>截至 '+esc(q.end)+' · '+esc(c.provider)+(c.stale||expired(c.updatedAt)?' · 旧快照':'')+'</small></div>'+link(c.sourceURL,'财报来源')+'</div><div class="metrics"><div class="metric"><small>单季营收 USD</small><strong>'+compact(q.revenue)+'</strong><small>环比 '+pct(qoq)+' · 同比 '+pct(yoy)+'</small></div><div class="metric"><small>营业利润率</small><strong>'+pct(Number.isFinite(q.operatingIncome)&&q.revenue?q.operatingIncome/q.revenue:null)+'</strong></div><div class="metric"><small>自由现金流 USD</small><strong>'+compact(q.fcf)+'</strong><small>经营现金流 − 资本支出</small></div><div class="metric"><small>SBC / 营收</small><strong>'+pct(Number.isFinite(q.sbc)&&q.revenue?q.sbc/q.revenue:null)+'</strong></div></div>'+bars(qs.slice(-6))+
 '<h3>本季变化</h3><p>'+Object.entries(labels).filter(([k])=>k!=='shares'&&Number.isFinite(q[k])&&Number.isFinite(prev?.[k])).map(([k,l])=>l+' '+compact(prev[k])+' → '+compact(q[k])+'（'+pct(change(q[k],prev[k]))+'）').join('；')+'</p><h3>最近季度对比</h3>'+financialTable(qs.slice(-6))+'<details><summary>口径与可核对证据</summary><p>金额为 USD，B=十亿，M=百万；股数使用稀释加权平均股数。季度现金流若由累计数相减，会在下方标记；缺失值显示 —，不补零。同比只比较约一年前的季度。数据可能包含后续重述。</p>'+qs.slice(-6).map(p=>'<div><b>'+esc(p.end)+'</b> '+link(p.sourceURL||c.sourceURL,p.filed?'申报 '+p.filed:'来源')+'<small> '+esc(p.note||'')+'</small></div>').join('')+'</details></section>';
}
function renderTheses(){const items=theses.filter(t=>t.ticker===selected);$('#theses').innerHTML=items.length?items.map(t=>{const e=evaluate(t);return '<article class="card"><div class="row"><span class="tag">'+esc(t.ticker)+'</span><strong class="'+e.cls+'">'+e.text+'</strong></div><h3>'+esc(t.title)+'</h3><p>'+esc(t.reason)+'</p><p>'+esc(rules[t.metric])+' '+(t.op==='gte'?'≥':'≤')+' '+esc(t.threshold)+'</p><small>'+esc(e.detail)+'</small><p class="muted">复查日期：'+esc(t.reviewDate||'未设置')+'</p><div class="toolbar"><button data-edit="'+esc(t.id)+'">编辑</button><button data-review="'+esc(t.id)+'">记录本次判断</button><button data-delete="'+esc(t.id)+'">删除</button></div><details><summary>判断历史 · '+(t.history||[]).length+'</summary>'+(t.history||[]).slice().reverse().map(h=>'<p>'+esc(h.at)+' · '+esc(h.status)+'<br><small>'+esc(h.detail)+'</small></p>').join('')+'</details></article>'}).join(''):'<div class="empty">为 '+esc(selected||'观察公司')+' 写下第一个投资论点。</div>';
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>form(theses.find(t=>t.id===b.dataset.edit)));
 document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('删除这条论点及其历史？')){theses=theses.filter(t=>t.id!==b.dataset.delete);save('theses',theses);renderTheses()}});
 document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{const t=theses.find(t=>t.id===b.dataset.review),v=evaluate(t);t.history=[...(t.history||[]),{at:new Date().toISOString(),status:v.text,detail:v.detail}].slice(-100);save('theses',theses);renderTheses();toast('已保存本次判断')});
}
function form(t={}){editing=t.id||null;$('#thesisForm').innerHTML='<form id="editor" class="panel"><div class="form-grid"><label>公司<select name="ticker">'+data.companies.map(c=>'<option '+(c.ticker===(t.ticker||selected)?'selected':'')+'>'+esc(c.ticker)+'</option>').join('')+'</select></label><label>论点名称<input name="title" required maxlength="100" value="'+esc(t.title||'')+'" placeholder="例如：增长没有以利润率下降为代价"></label><label class="wide">理由与风险<textarea name="reason" maxlength="3000">'+esc(t.reason||'')+'</textarea></label><label>验证指标<select name="metric">'+Object.entries(rules).map(([k,v])=>'<option value="'+k+'" '+(k===t.metric?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label>方向<select name="op"><option value="gte">至少 ≥</option><option value="lte" '+(t.op==='lte'?'selected':'')+'>最多 ≤</option></select></label><label>阈值（百分比填 20 表示 20%）<input name="threshold" type="number" step="any" required value="'+esc(t.threshold??20)+'"></label><label>下次复查<input name="reviewDate" type="date" value="'+esc(t.reviewDate||'')+'"></label></div><div class="toolbar"><button class="primary" type="submit">保存论点</button><button id="cancel" type="button">取消</button></div></form>';
 $('#cancel').onclick=()=>$('#thesisForm').innerHTML='';
 $('#editor').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.threshold=Number(v.threshold);if(!Number.isFinite(v.threshold))return;const item={...v,id:editing||crypto.randomUUID(),history:t.history||[],updatedAt:new Date().toISOString()};theses=editing?theses.map(x=>x.id===editing?item:x):[...theses,item];save('theses',theses);selected=item.ticker;render();toast('论点已保存')};$('#editor input[name=title]').focus();
}
backups('theses',()=>theses,v=>{if(!Array.isArray(v)||v.length>1000||!v.every(x=>x&&typeof x.id==='string'&&typeof x.title==='string'&&rules[x.metric]&&['gte','lte'].includes(x.op)&&Number.isFinite(x.threshold)&&(!x.history||Array.isArray(x.history))))throw new Error('记录格式不正确');theses=v;save('theses',v);render()});
try{data=await json('./data/financials.json');selected=data.companies[0]?.ticker||'';meta(data);render()}catch(e){$('#app').innerHTML='<div class="empty">'+esc(e.message)+'，请稍后读取最新快照。</div>'}
