const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PT_PLAYWRIGHT||'playwright');
const root=path.resolve(__dirname,'../..'),mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost'),file=path.join(root,decodeURIComponent(url.pathname).replace(/^\//,''),url.pathname.endsWith('/')?'index.html':'');try{res.setHeader('content-type',mime[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end('missing')}});
let browser,cloud=null;const errors=[],accounts=new Map();let holdRead=null,failRegistrations=0;
async function mock(ctx){await ctx.route('https://pt-universe-api.summer07-nanjolno.workers.dev/**',async route=>{const req=route.request(),url=new URL(req.url()),body=req.postDataJSON(),send=(value,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)});if(url.pathname.endsWith('/register')){if(failRegistrations){failRegistrations--;return route.fulfill({status:503,contentType:'text/plain',body:'temporarily unavailable'})}accounts.set(body.id,{token:body.token,ciphertext:null,revision:0});return send({ok:true},201)}const account=accounts.get(url.pathname.split('/')[3]);if(!account||req.headers().authorization!=='Bearer '+account.token)return send({error:'bad credential'},401);if(req.method()==='GET'){if(holdRead){const gate=holdRead;holdRead=null;await gate.promise}return send({ciphertext:account.ciphertext,revision:account.revision})}if(req.method()==='PUT'){if(body.baseRevision!==account.revision)return send({error:'conflict'},409);account.ciphertext=body.ciphertext;cloud=body.ciphertext;return send({revision:++account.revision})}return send({ok:true})})}

const saved=async p=>p.waitForFunction(()=>document.querySelector('#save-state').textContent.startsWith('已加密同步'));
const dish=async(p,name,rank,note)=>{await p.locator('#quick-dish-name').fill(name);await p.locator(`[data-quick-rank=${rank}]`).click();assert.equal(await p.locator('#dish-dialog').isVisible(),false);assert.equal(await p.locator('#quick-dish-name').inputValue(),'');await saved(p);if(note){await p.locator('.dish-card').filter({has:p.locator('h4',{hasText:name})}).locator('.dish-edit').click();await p.locator('#dish-form textarea').fill(note);await p.getByRole('button',{name:'保存菜品',exact:true}).click();await saved(p)}};
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+'/';browser=await chromium.launch({headless:true,...(process.env.PT_CHROMIUM?{executablePath:process.env.PT_CHROMIUM,args:['--no-sandbox','--no-proxy-server','--disable-gpu']}: {})});
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await mock(mobile);const p=await mobile.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'apps/food-ledger/');assert.equal(await p.locator('.restaurant-card').count(),0);
 await p.locator('#search').fill('椒 & 味 · Bellevue');await p.locator('#search').press('Enter');await saved(p);assert.equal(await p.locator('#restaurant-dialog').isVisible(),false);assert.equal(await p.locator('.restaurant-card').count(),1);await p.locator('[data-edit-place]').click();await p.locator('#restaurant-form input[name=address]').fill('123 Main St, Bellevue, WA');await p.locator('#restaurant-form input[name=url]').fill('example.com/menu');await p.locator('#restaurant-form textarea').fill('周末记得提前订位');await p.getByRole('button',{name:'保存菜馆',exact:true}).click();await saved(p);assert.equal(await p.locator('.detail-top h2').textContent(),'椒 & 味 · Bellevue');
 assert.equal(new URL(await p.locator('.address').getAttribute('href')).searchParams.get('destination'),'椒 & 味 · Bellevue 123 Main St, Bellevue, WA');assert.equal(await p.locator('.place-link').getAttribute('href'),'https://example.com/menu');assert.equal(await p.locator('.address').getAttribute('target'),'_blank');
 await dish(p,'水煮鱼','red','鲜嫩，麻辣适中');await dish(p,'炒饭','black','偏干，下次避开');assert.equal(await p.locator('.dish-card').count(),2);assert.ok(!cloud.includes('水煮鱼'));assert.ok(JSON.parse(cloud).body);
 await p.locator('[data-filter=black]').click();assert.equal(await p.locator('.dish-card').count(),1);assert.equal(await p.locator('.dish-card h4').textContent(),'炒饭');await p.locator('.dish-edit').click();await p.locator('#dish-form textarea').fill('偏干，油多');await p.getByRole('button',{name:'保存菜品',exact:true}).click();await saved(p);await p.reload();await p.locator('.detail-top').waitFor();assert.equal(await p.locator('.dish-card').count(),2);
 await p.locator('[data-back]').click();await p.locator('#search').fill('水煮鱼');assert.equal(await p.locator('.restaurant-card').count(),1);await p.locator('#search').fill('not-found');assert.equal(await p.locator('.restaurant-card').count(),0);await p.locator('#search').fill('椒 & 味 · Bellevue');assert.equal(await p.locator('#add-restaurant').textContent(),'打开');await p.locator('#add-restaurant').click();assert.equal(await p.locator('.restaurant-card').count(),1);
 await p.locator('#settings-open').click();const code=await p.locator('#sync-current-code').inputValue();assert.ok(code);const download=p.waitForEvent('download');await p.locator('#export').click();const dl=await download;await dl.saveAs('/tmp/food-ledger-backup.json');const exported=JSON.parse(fs.readFileSync('/tmp/food-ledger-backup.json','utf8'));assert.equal(exported.dishes.length,2);await p.locator('#settings-dialog [data-close]').click();
 const desktop=await browser.newContext({viewport:{width:1440,height:1000}});await mock(desktop);const q=await desktop.newPage();q.on('pageerror',e=>errors.push(e.message));await q.goto(base+'apps/food-ledger/');
 // A device with an automatically created account can still connect to the phone.
 await q.locator('#search').fill('电脑已有的菜馆');await q.locator('#add-restaurant').click();await saved(q);await q.locator('#settings-open').click();const oldCode=await q.locator('#sync-current-code').inputValue();assert.notEqual(oldCode,code);
 // A background read must not replace a freshly pasted code, even while busy.
 let release;holdRead={promise:new Promise(r=>release=r)};await q.locator('#sync-now').click();await q.waitForFunction(()=>document.querySelector('#save-state').textContent.includes('正在同步'));await q.locator('#sync-code').fill(code);await q.locator('#sync-connect').click();assert.ok(await q.locator('#sync-connect').isDisabled());release();await q.waitForFunction(()=>document.querySelector('#pair-status').textContent.startsWith('已连接'));
 assert.equal(await q.locator('#sync-code').inputValue(),code);assert.equal(await q.locator('#sync-current-code').inputValue(),code);await q.locator('#settings-dialog [data-close]').click();await q.locator('.restaurant-card').filter({hasText:'椒 & 味'}).click();assert.equal(await q.locator('.dish-card').count(),2);
 // Failed authentication remains visible and cannot switch the active account.
 await q.locator('#settings-open').click();await q.locator('#sync-code').fill(code.slice(0,37)+'A'.repeat(43));await q.locator('#sync-connect').click();await q.waitForFunction(()=>document.querySelector('#pair-status').textContent.startsWith('连接未完成'));assert.equal(await q.locator('#sync-current-code').inputValue(),code);await q.locator('#sync-now').click();await saved(q);assert.ok((await q.locator('#pair-status').textContent()).startsWith('连接未完成'));await q.locator('#settings-dialog [data-close]').click();

 // Independent offline updates merge across devices, then deletions do not resurrect.
 await mobile.setOffline(true);await desktop.setOffline(true);
 await p.locator('#quick-dish-name').fill('担担面');await p.locator('[data-quick-rank=red]').click();
 await q.locator('#quick-dish-name').fill('凉拌黄瓜');await q.locator('[data-quick-rank=red]').click();
 await new Promise(r=>setTimeout(r,850));await mobile.setOffline(false);await saved(p);await desktop.setOffline(false);await q.locator('#settings-open').click();await q.locator('#sync-now').click();await saved(q);await q.locator('#settings-dialog [data-close]').click();assert.equal(await q.locator('.dish-card').count(),4);
 await p.locator('#settings-open').click();await p.locator('#sync-now').click();await saved(p);await p.locator('#settings-dialog [data-close]').click();assert.equal(await p.locator('.dish-card').count(),4);
 q.on('dialog',d=>d.accept());await q.locator('.dish-card').filter({hasText:'炒饭'}).locator('.dish-edit').click();await q.locator('[data-delete-dish]').click();await saved(q);assert.equal(await q.locator('.dish-card').count(),3);
 // Importing the old backup merges tombstones instead of reviving deleted dishes.
 await q.locator('#settings-open').click();await q.locator('#import-file').setInputFiles('/tmp/food-ledger-backup.json');await saved(q);await q.locator('#settings-dialog [data-close]').click();assert.equal(await q.locator('.dish-card').count(),3);
 // A typed dish draft survives a cloud refresh without being saved or duplicated.
 await q.locator('#quick-dish-name').fill('还未提交的草稿');await q.locator('[data-filter=red]').click();assert.equal(await q.locator('#quick-dish-name').inputValue(),'还未提交的草稿');
 await q.locator('#settings-open').click();await q.locator('#sync-now').click();await saved(q);await q.locator('#settings-dialog [data-close]').click();assert.equal(await q.locator('#quick-dish-name').inputValue(),'还未提交的草稿');assert.equal(await q.locator('.dish-card').count(),3);
 // Chinese IME Enter confirms composition without creating a dish.
 await q.locator('#quick-dish-name').dispatchEvent('compositionstart');await q.locator('#quick-dish-name').dispatchEvent('keydown',{key:'Enter',isComposing:true});assert.equal(await q.locator('.dish-card').count(),3);await q.locator('#quick-dish-name').dispatchEvent('compositionend');await q.locator('#quick-dish-name').fill('');await q.locator('[data-filter=all]').click();
 // Safe rendering and invalid-link handling.
 await q.locator('[data-edit-place]').click();await q.locator('#restaurant-form input[name=url]').fill('javascript:alert(1)');await q.getByRole('button',{name:'保存菜馆',exact:true}).click();assert.ok(await q.locator('#restaurant-error').textContent());assert.ok(await q.locator('#restaurant-dialog').isVisible());await q.locator('#restaurant-dialog [data-close]').first().click();
 for(const size of [{width:1440,height:1000},{width:820,height:1000},{width:390,height:844},{width:320,height:640}]){await q.setViewportSize(size);assert.ok(await q.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow at '+size.width);await q.screenshot({path:'/tmp/food-ledger-'+size.width+'.png',fullPage:true})}
 await q.setViewportSize({width:390,height:844});await q.locator('[data-back]').click();await q.screenshot({path:'/tmp/food-ledger-list.png',fullPage:true});
 // A failed first registration keeps local records and retries after reopening.
 const retryContext=await browser.newContext();await mock(retryContext);const retry=await retryContext.newPage();await retry.goto(base+'apps/food-ledger/');failRegistrations=1;await retry.locator('#search').fill('注册失败后仍保存的菜馆');await retry.locator('#add-restaurant').click();await retry.waitForFunction(()=>document.querySelector('#save-state').textContent.includes('同步未完成'));assert.equal(await retry.locator('.restaurant-card').count(),1);assert.equal(await retry.evaluate(()=>localStorage.getItem('ptu.sync.config')),null);await retry.reload();await saved(retry);assert.equal(await retry.locator('.restaurant-card').count(),1);assert.ok(await retry.evaluate(()=>localStorage.getItem('ptu.sync.config')));await retryContext.close();
 assert.deepEqual(errors,[]);console.log('Food ledger quick-entry browser passed: CRUD, mobile/desktop, search, filters, reload, navigation, safe links, encrypted pairing, offline merge, deletion and backups');await mobile.close();await desktop.close();
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();server.close()});
