import {read,save,esc,stamp,toast,field,data} from './core.js';
export const API='https://pt-universe-api.summer07-nanjolno.workers.dev';let registering=null;
export async function account(create=false){let a=read('collector-account',null);if(a)return a;if(!create)return null;if(registering)return registering;registering=(async()=>{a={id:crypto.randomUUID(),token:Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('')};const r=await fetch(API+'/api/sync/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(a),signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('后台账号创建失败 HTTP '+r.status);if(!save('collector-account',a))throw Error('无法保存后台连接');return a})();try{return await registering}finally{registering=null}}
async function request(path='',body){const a=await account(body!==undefined);if(!a)return {sources:[]};const r=await fetch(API+'/api/decision/'+a.id+'/sources'+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer '+a.token,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(60000)});const d=await r.json();if(!r.ok)throw Error(d.error||'后台 HTTP '+r.status);return d}
export async function connectSource(config){return (await request('',config)).id}
export async function sources(){const d=await request();save('collector-cache',d.sources);return d.sources}
export const cachedSources=()=>read('collector-cache');
export async function sourceAction(id,action){return request('/'+id,{action})}
export async function checkSource(id){return request('/'+id+'/check',{})}
export function sourceStatus(id){const s=cachedSources().find(x=>x.id===id);return !s?'后台连接尚未读取':(s.paused?'已暂停':s.error?'抓取失败：'+s.error:'后台每小时检查')+' · 最近检查 '+stamp(s.checked_at)}
export function sourceManager(kind,onChange){const section=document.createElement('section');section.className='d-panel';document.querySelector('#decision-app').before(section);
function render(){const list=cachedSources().filter(s=>s.kind===kind);section.innerHTML='<h2>自动订阅来源</h2><p class="d-muted">配置一次公开 RSS / Atom 订阅地址，后台每小时收集新原文；关闭页面后继续运行。来源及原文保存在你的 PT 后台，以连接凭据隔离。X 主页不是 RSS，尚未连接 X 账号；不能自动读取关注列表。</p><form id="collector-form" class="d-form">'+field('name','发布者名称','text','','required maxlength="100"')+field('url','RSS / Atom 地址','url','','required')+'<div class="d-actions d-wide"><button class="d-primary">连接并开始自动收集</button><button type="button" id="collector-refresh">读取后台结果</button></div></form><div aria-live="polite" id="collector-status"></div>'+list.map(s=>'<article class="d-inset"><b>'+esc(s.name)+'</b><p>'+esc(sourceStatus(s.id))+'</p><small>已保留 '+(s.data?.items?.length||0)+' 条原文</small><div class="d-actions"><button data-source="'+s.id+'" data-action="'+(s.paused?'resume':'pause')+'">'+(s.paused?'继续收集':'暂停收集')+'</button><button data-source="'+s.id+'" data-action="remove">断开来源</button></div></article>').join('');
section.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await connectSource({...data(e.target),kind});await refresh()}catch(err){section.querySelector('#collector-status').textContent=err.message}finally{b.disabled=false}};
section.querySelector('#collector-refresh').onclick=refresh;section.querySelectorAll('[data-source]').forEach(b=>b.onclick=async()=>{try{await sourceAction(b.dataset.source,b.dataset.action);await refresh()}catch(e){toast(e.message)}})}
async function refresh(){try{const all=await sources();onChange(all);if(!section.contains(document.activeElement)||document.activeElement.tagName==='BUTTON')render()}catch(e){const el=section.querySelector('#collector-status');if(el)el.textContent=e.message}}
render();refresh();setInterval(()=>{if(!document.hidden)refresh()},60000);addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});return {refresh};
}
