import {$,esc,link,fmt,stamp,read,raw,save,field,area,data,id,marketData,json,ask,appURL,backupBar,hookSync,toast,dateIn,num} from './core.js';
import {holdingReview,fresh} from './models.mjs';
const host=document.querySelector('[data-decision="holdings"]');
let market={symbols:{}},financials={companies:[]},failure='',editing=null;
const metrics={revenueYoY:'营收同比 %',margin:'营业利润率 %',fcf:'FCF 百万美元',sbcRatio:'SBC / 营收 %',sharesYoY:'稀释股数同比 %'};
function records(){return read('holdings')}
function reviews(){const hs=records(),all=hs.every(h=>num(market.symbols[h.symbol]?.price)>0&&fresh(market.symbols[h.symbol]?.lastTradeAt,96)),total=hs.reduce((a,h)=>a+(market.symbols[h.symbol]?.price||0)*h.quantity,0),theses=raw('ptu.labs.theses');return hs.map(h=>{const q=market.symbols[h.symbol],c=financials.companies?.find(c=>c.ticker===h.symbol),weight=all&&total>0?q.price*h.quantity/total*100:null;return {h,q,c,weight,...holdingReview(h,q,c,theses,weight)}})}
function render(){const rows=reviews();host.innerHTML=`<section class="d-panel"><div class="d-row"><div><div class="d-kicker">Portfolio review</div><h2>我的持仓 · 什么变化需要复查</h2></div><button id="holding-refresh">↻ 读取最新证据</button></div><p class="d-muted">将实际持仓录入一次，在 Stock Alert 与 Thesis Lab 共用。只提示你设定的复查条件；不会自动交易。股票现货、USD；占比仅针对已录入且有有效报价的股票，不包含现金或期权。</p>${failure?`<p class="d-error">${esc(failure)}</p>`:''}<div class="d-actions"><button id="holding-add" class="d-primary">＋ 录入持仓</button><button id="holding-csv">批量粘贴 CSV</button><button id="holding-ask" ${rows.length?'':'disabled'}>生成持仓提问包 ↗</button></div><div id="holding-editor"></div><div class="d-statgrid"><div class="d-stat"><b>${rows.length}</b><span>已录入标的</span></div><div class="d-stat"><b>${rows.filter(x=>x.reasons.some(r=>r.kind==='review')).length}</b><span>需要复查</span></div><div class="d-stat"><b>${rows.filter(x=>x.reasons.some(r=>r.kind==='unknown')).length}</b><span>证据待确认</span></div><div class="d-stat"><b>${rows.filter(x=>!x.reasons.length).length}</b><span>当前未触发条件</span></div></div><div class="d-grid">${rows.map(x=>card(x)).join('')||'<div class="d-empty d-wide">尚未录入实际持仓。先添加标的、数量和复查边界；不会把自选列表当作你的持仓。</div>'}</div><div id="holding-backup"></div></section>`;
 $('#holding-add',host).onclick=()=>form();$('#holding-refresh',host).onclick=load;$('#holding-csv',host).onclick=csvForm;$('#holding-ask',host).onclick=()=>ask('持仓复查',rows.map(evidence),'哪些变化需要我复查？请按实际敞口和证据质量排序，列出需要补充的数据和可选行动。');
 host.querySelectorAll('[data-h-edit]').forEach(b=>b.onclick=()=>form(records().find(x=>x.id===b.dataset.hEdit)));
 host.querySelectorAll('[data-h-remove]').forEach(b=>b.onclick=()=>{if(confirm('移除此持仓及其复查记录？')){save('holdings',records().filter(x=>x.id!==b.dataset.hRemove));render()}});
 host.querySelectorAll('[data-h-review]').forEach(b=>b.onclick=()=>reviewForm(rows.find(x=>x.h.id===b.dataset.hReview)));
 host.querySelectorAll('[data-h-ask]').forEach(b=>b.onclick=()=>{const x=rows.find(x=>x.h.id===b.dataset.hAsk);ask(x.h.symbol+' 持仓复查',evidence(x))});
 backupBar($('#holding-backup',host),['holdings'],(_,v)=>v.every(valid));
}
function valid(h){return h&&typeof h.id==='string'&&/^[A-Z0-9.^-]{1,20}$/.test(h.symbol)&&h.quantity>0&&h.cost>=0&&Number.isFinite(h.quantity)&&Number.isFinite(h.cost)&&Array.isArray(h.reviews||[])&&Number.isFinite(h.movePct)&&h.movePct>0;}
function evidence(x){return {symbol:x.h.symbol,quantity:x.h.quantity,cost:x.h.cost,note:x.h.note,quote:x.price,quoteAt:x.q?.lastTradeAt,source:x.q?.source||'Yahoo / Stock Alert snapshot',sourceURL:'https://finance.yahoo.com/quote/'+encodeURIComponent(x.h.symbol)+'/',weightInEnteredEquities:x.weight,reviewReasons:x.reasons,theses:x.thesis,financialPeriod:x.quarter,financialSource:x.c?.sourceURL,lastReview:x.h.reviews?.at(-1)||null};}
function card(x){return `<article class="d-inset"><div class="d-row"><h3>${esc(x.h.symbol)} <small>${fmt(x.h.quantity)} 股</small></h3><span class="d-pill ${x.reasons.length?'review':''}">${x.reasons.length?'需要核对':'未触发条件'}</span></div><p>报价 $${fmt(x.price)} · 成本 $${fmt(x.h.cost)} · 已录入股票占比 ${fmt(x.weight,1)}%</p><small>行情时间 ${stamp(x.q?.lastTradeAt)}${!fresh(x.q?.lastTradeAt,24)?' · 非当日新鲜报价':''}</small><ul>${x.reasons.map(r=>`<li>${esc(r.text)}</li>`).join('')||'<li>当前数据未触发你的复查条件。</li>'}</ul><p class="d-muted">${esc(x.h.note||'尚未填写持有理由')}</p><div class="d-actions">${link(appURL('stock-alert/?symbol='+encodeURIComponent(x.h.symbol)),'技术与期权')}${link(appURL('thesis-lab/?symbol='+encodeURIComponent(x.h.symbol)),'财报与论点')}</div><div class="d-actions"><button data-h-review="${x.h.id}">记录本次复查</button><button data-h-ask="${x.h.id}">问 GPT ↗</button><button data-h-edit="${x.h.id}">编辑</button><button data-h-remove="${x.h.id}">移除</button></div><details><summary>复查历史 · ${x.h.reviews?.length||0}</summary>${[...(x.h.reviews||[])].reverse().map(r=>`<p><small>${stamp(r.at)} · 当时价格 $${fmt(r.price)}</small><br>${esc(r.note)}<br><small>${esc((r.reasons||[]).map(x=>x.text).join('；'))}</small></p>`).join('')||'尚无记录'}</details></article>`}
function form(h={}){editing=h.id||null;$('#holding-editor',host).innerHTML=`<form id="holding-form" class="d-inset d-form">${field('symbol','股票代码','text',h.symbol||'','required maxlength="20" pattern="[A-Za-z0-9.^-]+"')}${field('quantity','实际数量','number',h.quantity??'','required min="0.000001" step="any"')}${field('cost','每股成本 USD','number',h.cost??'','required min="0" step="any"')}${field('lower','价格复查下界（可空）','number',h.lower??'','min="0.000001" step="any"')}${field('upper','价格复查上界（可空）','number',h.upper??'','min="0.000001" step="any"')}${field('movePct','较上次复查变动阈值 %','number',h.movePct??5,'required min="0.1" step="0.1"')}${field('maxWeight','最大股票占比 %（可空）','number',h.maxWeight??'','min="0.1" max="100" step="0.1"')}${field('reviewDate','下次复查日期','date',h.reviewDate||'')}${area('note','持有理由／失效条件',h.note||'','maxlength="3000"')}<div class="d-actions d-wide"><button class="d-primary">保存持仓</button><button type="button" id="holding-cancel">取消</button></div></form>`;$('#holding-cancel',host).onclick=()=>$('#holding-editor',host).replaceChildren();$('#holding-form',host).onsubmit=e=>{e.preventDefault();const v=data(e.target),s=v.symbol.trim().toUpperCase();if(records().some(x=>x.symbol===s&&x.id!==editing)){toast('该股票已有记录，请编辑原持仓');return}const n={...v,id:editing||id(),symbol:s,quantity:num(v.quantity),cost:num(v.cost),lower:num(v.lower),upper:num(v.upper),maxWeight:num(v.maxWeight),movePct:num(v.movePct),reviews:h.reviews||[]};if(n.lower!==null&&n.upper!==null&&n.lower>=n.upper){toast('下界必须小于上界');return}if(!valid(n)){toast('请检查数量和阈值');return}if(save('holdings',editing?records().map(x=>x.id===editing?n:x):[...records(),n]))render()};$('#holding-form input',host).focus();}
function reviewForm(x){$('#holding-editor',host).innerHTML=`<form id="holding-review-form" class="d-inset d-form"><h3 class="d-wide">${esc(x.h.symbol)} · 记录本次判断</h3>${area('note','这次结论及理由','','required maxlength="3000"')}${field('reviewDate','下次复查','date','',`required min="${dateIn()}"`)}<div class="d-actions d-wide"><button class="d-primary">保存复查</button><button type="button" id="holding-cancel">取消</button></div><p class="d-muted d-wide">保存当前证据和判断。仍然满足的价格或论点条件会保留提示，不会被标记为风险消失。</p></form>`;$('#holding-cancel',host).onclick=render;$('#holding-review-form',host).onsubmit=e=>{e.preventDefault();const d=data(e.target),hs=records(),h=hs.find(h=>h.id===x.h.id);h.reviewDate=d.reviewDate;h.reviews=[...(h.reviews||[]),{at:new Date().toISOString(),note:d.note,price:x.price,quarter:x.quarter,reasons:x.reasons,thesis:x.thesis}].slice(-100);if(save('holdings',hs))render()};$('#holding-review-form textarea',host).focus();}
function csvForm(){$('#holding-editor',host).innerHTML=`<form id="holding-csv-form" class="d-inset"><h3>批量录入</h3><p class="d-muted">每行 股票代码,数量,每股成本。可带 symbol,quantity,cost 表头。重复代码只更新数量和成本，保留已有边界与历史。</p><textarea name="csv" required placeholder="symbol,quantity,cost"></textarea><div class="d-actions"><button class="d-primary">验证并导入</button><button id="holding-cancel" type="button">取消</button></div></form>`;$('#holding-cancel',host).onclick=render;$('#holding-csv-form',host).onsubmit=e=>{e.preventDefault();try{const lines=data(e.target).csv.trim().split(/\r?\n/).filter(Boolean),hs=structuredClone(records());let count=0;lines.forEach((l,i)=>{if(i===0&&/^symbol\s*,/i.test(l))return;const parts=l.split(',').map(x=>x.trim());if(parts.length!==3)throw Error('第 '+(i+1)+' 行需要三个字段');const [s,q,c]=parts,symbol=s.toUpperCase(),prev=hs.find(x=>x.symbol===symbol),v={...(prev||{}),id:prev?.id||id(),symbol,quantity:num(q),cost:num(c),movePct:prev?.movePct||5,reviews:prev?.reviews||[]};if(!valid(v))throw Error('第 '+(i+1)+' 行格式无效');if(prev)Object.assign(prev,v);else hs.push(v);count++});if(!count)throw Error('没有可导入记录');if(save('holdings',hs)){render();toast('已导入 '+count+' 行')}}catch(err){toast(err.message)}};}
async function load(){const b=$('#holding-refresh',host);if(b)b.disabled=true;const rs=await Promise.allSettled([marketData(),json('apps/thesis-lab/data/financials.json')]);failure='';if(rs[0].status==='fulfilled')market=rs[0].value;else failure='行情读取失败，保留已有记录。';if(rs[1].status==='fulfilled')financials=rs[1].value;else failure+=' 财报读取失败，论点证据待确认。';render()}
if(host){render();load();hookSync(render);addEventListener('decision-thesis-updated',render)}
