import {$,esc,link,stamp,read,raw,save,field,select,data,id,json,ask,appURL,backupBar,toast,dateIn,copy,download} from './core.js';
import {mountMealAI} from './life-ai.js';
import {planEvents,fresh} from './models.mjs';
import {prepareRecipes,mealPreferences,planMeals} from './meal-planner.mjs';
const host=document.querySelector('[data-decision="weekend"], [data-decision="meal"]'),mode=host?.dataset.decision;
const cityChoices=[['','全部地区'],...['Kirkland','Bellevue','Redmond','Lynnwood','Everett','Kent','Seattle'].map(x=>[x,x])];
let events={events:[]},options=[],batch=0;
const saved=()=>{const value=read(mode==='meal'?'meal-plans':'weekend-plans');return Array.isArray(value)?value.filter(p=>p&&typeof p.id==='string'&&typeof p.title==='string'&&typeof p.text==='string'):[]};
function mealStatus(message){const el=$('#meal-status',host);if(el)el.textContent=message;}
const places=()=>raw('savedPlaces').filter(p=>p&&typeof p.name==='string');
function render(){if(mode==='meal')renderMeal();else renderWeekend();}
function history(){return `<details><summary>已选安排 · ${saved().length}</summary>${saved().slice().reverse().slice(0,12).map(p=>`<div class="d-inset"><b>${esc(p.title)}</b><small> · ${stamp(p.at)}</small><p>${esc(p.summary)}</p><div class="d-actions"><button data-plan-copy="${p.id}">复制安排</button><button data-plan-remove="${p.id}">移除</button></div></div>`).join('')||'<p class="d-muted">尚未选择安排。</p>'}</details>`}
function bindHistory(){host.querySelectorAll('[data-plan-copy]').forEach(b=>b.onclick=()=>copy(saved().find(p=>p.id===b.dataset.planCopy).text));host.querySelectorAll('[data-plan-remove]').forEach(b=>b.onclick=()=>{save(mode==='meal'?'meal-plans':'weekend-plans',saved().filter(p=>p.id!==b.dataset.planRemove));render()});$('#life-backup',host).replaceChildren();backupBar($('#life-backup',host),[mode==='meal'?'meal-plans':'weekend-plans'],(_,v)=>v.every(p=>typeof p.id==='string'&&typeof p.title==='string'&&typeof p.text==='string'&&typeof p.summary==='string'));}
let recipeLibrary=[],recipeSnapshot=null,recipeLoad=null;
async function loadMealLibrary(){
 if(recipeLoad)return recipeLoad;
 mealStatus('正在读取完整菜谱库…');
 recipeLoad=json('apps/meal-orbit/data/recipes.json').then(snapshot=>{recipeLibrary=prepareRecipes(snapshot);recipeSnapshot=snapshot;$('#meal-plan-form button[type=submit]',host).disabled=false;generateMeals(mealPreferences(data($('#meal-plan-form',host))));}).catch(e=>{mealStatus('菜谱库读取失败：'+e.message+'。请点击“重新读取菜谱库”。');}).finally(()=>{recipeLoad=null});
 return recipeLoad;
}
function renderMeal(){
 const pref=mealPreferences(read('meal-preferences',{}));
 host.innerHTML=`<div class="d-panel"><div class="d-kicker">Dinner, decided</div><h2>今晚菜单 · 按你的食材选</h2><p class="d-muted">使用「找食谱」同一份 HowToCook 完整数据库，优先推荐用到你所填食材的菜。可保存多道组成今晚菜单；用时与做法来自原菜谱。</p><form id="meal-plan-form" class="d-form">${select('minutes','可用时间',[['20','20 分钟'],['30','30 分钟'],['45','45 分钟'],['60','60 分钟'],['90','90 分钟'],['120','120 分钟'],['any','不限时间']],pref.minutes)}${select('people','用餐人数',[['1','1 人'],['2','2 人'],['3','3 人'],['4','4 人']],pref.people)}${select('equipment','器材',[['all','锅＋微波炉＋空气炸锅'],['pot','只有锅'],['microwave','只有微波炉'],['airfryer','只有空气炸锅'],['any','不限器材']],pref.equipment)}${select('category','想做什么',[['dinner','晚餐菜肴与主食'],['all','全部菜谱'],['meat_dish','荤菜'],['vegetable_dish','素菜'],['aquatic','水产'],['staple','主食'],['soup','汤'],['breakfast','早餐'],['dessert','甜点'],['drink','饮品'],['semi-finished','半成品'],['condiment','酱料']],pref.category)}${field('exclude','不吃的食材','text',pref.exclude,'maxlength="200" placeholder="例如：虾、鸡蛋、牛奶"')}${field('pantry','优先用掉的食材','text',pref.pantry,'maxlength="200" placeholder="例如：牛肉 土豆，支持空格或逗号"')}<div class="d-actions"><button type="submit" class="d-primary" disabled>生成今晚菜单</button><button id="meal-more" type="button" disabled>换一组</button></div></form><p id="meal-status" class="d-note" role="status" aria-live="polite"></p><p id="meal-library" class="d-muted"></p><div id="meal-options"></div><button id="meal-reload" type="button">重新读取菜谱库</button><div id="life-history">${history()}</div><div id="life-backup"></div></div>`;
 const form=$('#meal-plan-form',host);
 form.oninput=()=>{ $('#meal-options',host).hidden=true;$('#meal-more',host).disabled=true;mealStatus('条件已修改，请点击“生成今晚菜单”，按新条件重新推荐。'); };
 form.onsubmit=e=>{e.preventDefault();const p=mealPreferences(data(form)),key=JSON.stringify(p);const stored=save('meal-preferences',p);generateMeals(p,{next:key===mealKey});if(!stored)mealStatus($('#meal-status',host).textContent+' · 偏好未能保存到本机');};
 $('#meal-more',host).onclick=()=>generateMeals(mealPreferences(data(form)),{next:true});
 mountMealAI(host,()=>({recipes:recipeLibrary,preferences:mealPreferences(data(form)),recent:saved().slice(-3).map(p=>p.title)}));
 $('#meal-reload',host).onclick=loadMealLibrary;bindHistory();if(recipeLibrary.length){$('#meal-plan-form button[type=submit]',host).disabled=false;generateMeals(pref)}else loadMealLibrary();
}
let mealResult=null,mealKey='';
function generateMeals(p,{next=false}={}){
 const offset=next&&mealResult?mealResult.offset+3:0;
 if(!recipeLibrary.length)return;
 mealResult=planMeals(recipeLibrary,p,{offset,recent:saved().slice(-3).map(x=>x.title)});mealKey=JSON.stringify(p);options=mealResult.options;
 const {total,pantry,exclude,unavailable,unknownExclusions}=mealResult;
 const equipment={all:'锅＋微波炉＋空气炸锅',pot:'只有锅',microwave:'只有微波炉',airfryer:'只有空气炸锅',any:'不限器材'}[p.equipment];
 const notes=[`已按 ${p.minutes==='any'?'不限时间':p.minutes+' 分钟内'} · ${p.people} 人份 · ${equipment} 推荐`,`符合条件 ${total} 个，展示 ${options.length} 个`];
 if(pantry.length)notes.push('优先食材：'+pantry.join('、'));
 if(exclude.length)notes.push('排除：'+exclude.join('、'));
 if(unavailable.length)notes.push('当前条件下未匹配到：'+unavailable.join('、'));
 if(unknownExclusions.length)notes.push('无法识别忌口：'+unknownExclusions.join('、')+'，请换成具体食材名后重试');
 if(total>0&&total<=3)notes.push('已展示全部可选菜单；可放宽条件增加选择');
 if(next&&total>3)notes.push('已换一组');
 mealStatus(notes.join('。'));
 $('#meal-library',host).textContent=`完整菜谱库 ${recipeLibrary.length} 篇 · 上游更新 ${stamp(recipeSnapshot.updatedAt)} · 用时按原文概述筛选，器材按原文识别；未标注用时的菜谱仅在“不限时间”出现。`;
 $('#meal-more',host).disabled=total<=3;
 const target=$('#meal-options',host);target.hidden=false;
 target.innerHTML=options.length?`<div class="d-grid">${options.map((m,i)=>`<article class="d-inset" data-meal-id="${esc(m.id)}"><span class="d-pill">${m.minutes!==null?'原文约 '+m.minutes+' 分钟':'原文未标用时'} · 计划 ${m.people} 人 · ${esc(m.categoryName)}</span><h3>${esc(m.name)}</h3><p class="d-muted">器材：${esc(m.equipment.join('＋')||'原文未提到专用加热设备')}${m.advance?' · 需提前腌制／准备':''}</p>${m.matched.length?`<p class="d-note">用到你填写的：${esc(m.matched.join('、'))}</p>`:''}<details open><summary>食材与工具</summary><pre>${esc(m.ingredientsText||'请查看原菜谱')}</pre></details><details><summary>用量 · 计划 ${m.people} 人</summary><p class="d-muted">${esc(m.amounts.note)}</p><pre>${esc(m.amounts.text)}</pre></details><details><summary>完整做法与注意事项</summary><pre>${esc(m.md)}</pre></details><p>${link(m.source,'HowToCook 原菜谱')}</p><div class="d-actions"><button class="d-primary" data-meal-pick="${i}">今晚就吃这个</button><button data-meal-copy="${i}">复制清单</button></div></article>`).join('')}</div>`:`<div class="d-empty">${unknownExclusions.length?'无法识别这些忌口，请使用具体食材名。':pantry.length?'当前条件下没有能用到所填食材的菜谱。可以增加时间、更换器材或选择“全部菜谱”；不会用不相关菜单代替。':'没有满足条件的菜谱，请调整时间、器材、类别或忌口。'}</div>`;
 host.querySelectorAll('[data-meal-pick]').forEach(b=>b.onclick=()=>{
  const m=options[Number(b.dataset.mealPick)],plan={id:id(),title:m.name,summary:`计划 ${m.people} 人 · ${m.minutes!==null?'原文约 '+m.minutes+' 分钟':'用时未标注'}`,at:new Date().toISOString(),text:mealText(m)};
  if(save('meal-plans',[...saved(),plan].slice(-100))){
   $('#life-history',host).innerHTML=history();bindHistory();b.disabled=true;b.textContent='已选为今晚菜单';mealStatus('已保存：'+m.name+'。可在“已选安排”查看。');toast('已保存今晚菜单');
  }else mealStatus('保存失败：本机存储不可用，请先复制清单。');
 });
 host.querySelectorAll('[data-meal-copy]').forEach(b=>b.onclick=()=>copy(mealText(options[Number(b.dataset.mealCopy)])));
}
function mealText(m){return `${m.name}\n计划 ${m.people} 人 · ${m.minutes!==null?'原文约 '+m.minutes+' 分钟':'原文未标注用时'}\n${m.amounts.note}\n\n食材与工具：\n${m.ingredientsText}\n\n用量：\n${m.amounts.text}\n\n做法：\n${m.stepsText}\n\n来源：${m.source}\n\n完整原文：\n${m.md}`}
function renderWeekend(){const pref=read('weekend-preferences',{});host.innerHTML=`<section class="d-panel"><div class="d-kicker">A half day, ready to choose</div><h2>半日安排 · 活动＋吃饭</h2><p class="d-muted">从真实活动快照选最多三个方案，保留来源与地点。时间表是建议；交通、营业、票务需在出发前核对。</p><form id="weekend-plan-form" class="d-form">${field('date','哪天出发','date',pref.date>=dateIn()?pref.date:dateIn(),'required')}${select('city','地区',cityChoices,pref.city||'')}${select('start','活动最早开始',[['9','09:00'],['10','10:00'],['12','12:00'],['14','14:00']],pref.start||'10')}${select('hours','可用时长',[['3','3 小时'],['4','4 小时'],['6','6 小时']],pref.hours||'4')}${select('free','费用',[['any','不限'],['yes','只看已确认免费']],pref.free||'any')}${field('query','兴趣关键词（可空）','text',pref.query||'','maxlength="80"')}${select('restaurant','用餐选择',[['','在活动附近找餐厅'],...places().map(p=>[p.id,p.name+' · '+(p.address||'地区未填')])],pref.restaurant||'')}<div class="d-actions d-wide"><button class="d-primary">生成半日方案</button><button id="weekend-refresh" type="button">↻ 读取活动快照</button>${link(appURL('meal-orbit/'),'今晚在家做饭')}</div></form><p class="d-muted">活动快照 ${stamp(events.updatedAt)} · ${fresh(events.updatedAt)?'已加载':'数据未载入或过期；请核对来源'}</p><div id="weekend-options"></div>${history()}<div id="life-backup"></div></section>`;$('#weekend-plan-form',host).onsubmit=e=>{e.preventDefault();const p=data(e.target);save('weekend-preferences',p);generateWeekend(p)};$('#weekend-refresh',host).onclick=load;bindHistory();if(events.events.length)generateWeekend(data($('#weekend-plan-form',host)));}
const time=n=>`${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toString().padStart(2,'0')}`;
function generateWeekend(p){const pool=planEvents(events.events,{date:p.date,city:p.city,start:Number(p.start),hours:Number(p.hours),query:p.query,freeOnly:p.free==='yes'}).filter(e=>!e.checkedAt||fresh(e.checkedAt));const restaurant=places().find(x=>x.id===p.restaurant);options=pool.slice(batch,batch+3);if(!options.length&&pool.length){batch=0;options=pool.slice(0,3)}const plans=options.map(e=>{const start=e.start.length>=16?Number(e.start.slice(11,13))*60+Number(e.start.slice(14,16)):Number(p.start)*60;let duration=60;if(e.end?.slice(0,10)===e.start.slice(0,10)&&e.end.length>=16){duration=Math.max(60,Math.min(90,Number(e.end.slice(11,13))*60+Number(e.end.slice(14,16))-start))}const finish=start+duration;const food=restaurant?.name||e.city+' '+e.venue+' 附近餐厅';const route='https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent('Juanita, Kirkland WA')+'&destination='+encodeURIComponent(food)+'&waypoints='+encodeURIComponent(e.venue+', '+e.city);return {e,start,finish,food,route,restaurant,p};});$('#weekend-options',host).innerHTML=plans.length?`<p class="d-muted">找到 ${pool.length} 个候选 · 行程内预留 30 分钟转场，不代表实时车程。带固定时段活动可能只安排部分参观，预约项目请以原文为准。</p><div class="d-grid">${plans.map((x,i)=>`<article class="d-inset"><span class="d-pill">${esc(x.e.city)} · ${esc(x.e.cost)}</span><h3>${esc(x.e.title)}</h3><p class="d-muted">${esc(x.e.description?.slice(0,220)||'详情见活动原文')}</p><div class="d-step"><b>${time(x.start)}</b><div><strong>参加活动</strong><p>${esc(x.e.venue)}</p><small>${x.e.start.length<16?'原文未给出时间，以上为建议安排':'来源开始时间 '+esc(x.e.start.slice(11,16))} · ${link(x.e.url,'核对活动')}</small></div></div><div class="d-step"><b>${time(x.finish+30)}</b><div><strong>${esc(x.restaurant?.name||'附近吃饭')}</strong><p>${x.restaurant?'使用你收藏的餐厅；请核对是否顺路、是否营业。':'选择活动附近餐厅，避免再跨区。'}</p>${link('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(x.food),'查看餐厅')}</div></div><div class="d-actions"><button class="d-primary" data-weekend-pick="${i}">选这个方案</button>${link(x.route,'路线与实际车程')}<button data-weekend-ask="${i}">问 GPT ↗</button></div></article>`).join('')}</div>${pool.length>3?'<button id="weekend-more">换一组方案</button>':''}`:'<div class="d-empty">当前快照没有满足这些条件的活动。可更换日期、地区或关键词；不会用旧活动填充行程。</div>';host.querySelectorAll('[data-weekend-pick]').forEach(b=>b.onclick=()=>{const x=plans[Number(b.dataset.weekendPick)],text=weekendText(x),plan={id:id(),title:x.e.title,summary:p.date+' · '+x.e.city,at:new Date().toISOString(),text};save('weekend-plans',[...saved(),plan].slice(-100));toast('方案已保存，可在下方复制安排');renderWeekend()});host.querySelectorAll('[data-weekend-ask]').forEach(b=>b.onclick=()=>ask('周末半日安排',plans[Number(b.dataset.weekendAsk)],'请检查行程时间和交通是否合理，核对活动和餐厅营业信息，再给出可执行安排。'));$('#weekend-more',host)?.addEventListener('click',()=>{batch=(batch+3)%pool.length;generateWeekend(p)});}
function weekendText(x){return `${x.p.date} · ${x.e.city}\n${time(x.start)} ${x.e.title}\n${x.e.venue}\n活动原文：${x.e.url}\n${time(x.finish+30)} 用餐：${x.food}\n建议行程，出发前核对活动时段、票务、营业和实际车程。\n路线：${x.route}`}
async function load(){try{events=await json('apps/eastside-weekend/data/events.json');renderWeekend()}catch(e){toast(e.message);renderWeekend()}}
if(host){render();if(mode==='weekend')load()}

addEventListener('workspace-records',e=>{if(mode==='weekend'&&['savedPlaces','sync'].includes(e.detail.key)){const select=host.querySelector('[name=restaurant]');if(!select)return;const value=select.value;select.replaceChildren(new Option('活动附近用餐',''),...places().map(p=>new Option(p.name,p.id||p.name)));if([...select.options].some(o=>o.value===value))select.value=value;}});
