import {$,esc,link,stamp,read,raw,save,field,select,data,id,json,ask,appURL,backupBar,toast,dateIn,copy,download} from './core.js';
import {planEvents,fresh} from './models.mjs';
const host=document.querySelector('[data-decision="weekend"], [data-decision="meal"]'),mode=host?.dataset.decision;
const cityChoices=[['','全部地区'],...['Kirkland','Bellevue','Redmond','Lynnwood','Everett','Kent','Seattle'].map(x=>[x,x])];
let events={events:[]},options=[],batch=0;
const meals=[
 {name:'番茄鸡蛋饭＋清炒西兰花',minutes:25,equipment:['锅'],tags:'鸡蛋 大米 西兰花 番茄',ingredients:[['大米',150,'g'],['鸡蛋',3,'个'],['番茄',2,'个'],['西兰花',300,'g']],steps:['大米煮饭；同时清洗并切好番茄和西兰花。','炒熟鸡蛋盛出，炒软番茄后放回鸡蛋，按口味调味。','西兰花焯水后清炒，和米饭一起分装。']},
 {name:'豆腐蘑菇汤面',minutes:20,equipment:['锅'],tags:'豆腐 大豆 面条 小麦 蘑菇 青菜',ingredients:[['面条',180,'g'],['豆腐',250,'g'],['蘑菇',150,'g'],['青菜',200,'g']],steps:['切好豆腐、蘑菇和青菜，烧一锅水。','下蘑菇、豆腐煮开，再加入面条按包装时间煮熟。','最后加入青菜煮熟，按口味调味；两人分食。']},
 {name:'空气炸锅鸡腿＋土豆＋青菜',minutes:40,equipment:['空气炸锅','锅'],tags:'鸡肉 土豆 青菜',ingredients:[['去骨鸡腿肉',350,'g'],['土豆',400,'g'],['青菜',250,'g']],steps:['鸡腿和土豆分别切成合适大小，按口味调味。','按设备说明分批或分区烹饪，避免生肉汁接触已熟食物；确认鸡肉熟透。','用锅煮熟青菜，配鸡腿和土豆一起上桌。']},
 {name:'虾仁蔬菜炒饭',minutes:20,equipment:['锅'],tags:'虾 甲壳类 米饭 胡萝卜 豌豆 鸡蛋',ingredients:[['已煮熟米饭',350,'g'],['虾仁',200,'g'],['鸡蛋',2,'个'],['胡萝卜和豌豆',200,'g']],steps:['准备米饭和切好的蔬菜，炒熟鸡蛋盛出。','将虾仁和蔬菜炒熟，再加入米饭充分炒热。','放回鸡蛋，调味后两人分食。']},
 {name:'香菇青菜豆腐饭',minutes:30,equipment:['锅'],tags:'香菇 青菜 豆腐 大豆 大米',ingredients:[['大米',150,'g'],['豆腐',300,'g'],['香菇',150,'g'],['青菜',250,'g']],steps:['先煮饭，切好豆腐、香菇和青菜。','豆腐煎至表面上色，加入香菇与少量水烧熟。','青菜另行炒熟；与豆腐、米饭一起分装。']},
 {name:'金枪鱼黄瓜饭碗',minutes:15,equipment:['微波炉'],tags:'金枪鱼 鱼 黄瓜 米饭 玉米',ingredients:[['可直接加热米饭',350,'g'],['即食金枪鱼罐头',2,'罐'],['黄瓜',1,'根'],['即食玉米粒',100,'g']],steps:['按包装说明充分加热米饭。','黄瓜清洗切丁，金枪鱼与玉米沥水。','将食材分成两碗，按口味少量调味。']}
];
const saved=()=>read(mode==='meal'?'meal-plans':'weekend-plans');
const places=()=>raw('savedPlaces').filter(p=>p&&typeof p.name==='string');
function render(){if(mode==='meal')renderMeal();else renderWeekend();}
function history(){return `<details><summary>已选安排 · ${saved().length}</summary>${saved().slice().reverse().slice(0,12).map(p=>`<div class="d-inset"><b>${esc(p.title)}</b><small> · ${stamp(p.at)}</small><p>${esc(p.summary)}</p><div class="d-actions"><button data-plan-copy="${p.id}">复制安排</button><button data-plan-remove="${p.id}">移除</button></div></div>`).join('')||'<p class="d-muted">尚未选择安排。</p>'}</details>`}
function bindHistory(){host.querySelectorAll('[data-plan-copy]').forEach(b=>b.onclick=()=>copy(saved().find(p=>p.id===b.dataset.planCopy).text));host.querySelectorAll('[data-plan-remove]').forEach(b=>b.onclick=()=>{save(mode==='meal'?'meal-plans':'weekend-plans',saved().filter(p=>p.id!==b.dataset.planRemove));render()});backupBar($('#life-backup',host),[mode==='meal'?'meal-plans':'weekend-plans'],(_,v)=>v.every(p=>typeof p.id==='string'&&typeof p.title==='string'&&typeof p.text==='string'&&typeof p.summary==='string'));}
function renderMeal(){const pref=read('meal-preferences',{});host.innerHTML=`<div class="d-panel"><div class="d-kicker">Dinner, decided</div><h2>今晚菜单 · 选一个就开始做</h2><p class="d-muted">按可用时间、器材和不吃的食材，给出最多三个完整组合。份量和时间是家庭烹饪估计，可自行调整。</p><form id="meal-plan-form" class="d-form">${select('minutes','可用时间',[['20','20 分钟'],['30','30 分钟'],['45','45 分钟']],pref.minutes||'30')}${select('people','用餐人数',[['1','1 人'],['2','2 人'],['3','3 人'],['4','4 人']],pref.people||'2')}${select('equipment','器材',[['all','锅＋微波炉＋空气炸锅'],['pot','只有锅'],['microwave','只有微波炉']],pref.equipment||'all')}${field('exclude','不吃的食材（逗号分隔）','text',pref.exclude||'','maxlength="200"')}${field('pantry','优先用掉（食材关键词，逗号分隔）','text',pref.pantry||'','maxlength="200"')}<div class="d-actions"><button class="d-primary">生成今晚菜单</button></div></form><div id="meal-options"></div>${history()}<div id="life-backup"></div></div>`;$('#meal-plan-form',host).onsubmit=e=>{e.preventDefault();const p=data(e.target);save('meal-preferences',p);generateMeals(p)};bindHistory();generateMeals(pref.minutes?pref:{minutes:'30',people:'2',equipment:'all',exclude:'',pantry:''})}
function generateMeals(p){const ex=p.exclude.split(/[,，、]/).map(x=>x.trim()).filter(Boolean),pan=p.pantry.split(/[,，、]/).map(x=>x.trim()).filter(Boolean),equipment=p.equipment==='pot'?['锅']:p.equipment==='microwave'?['微波炉']:['锅','微波炉','空气炸锅'];const matches=meals.filter(m=>m.minutes<=Number(p.minutes)&&m.equipment.every(x=>equipment.includes(x))&&!ex.some(x=>m.tags.includes(x)||m.name.includes(x))).sort((a,b)=>pan.filter(x=>b.tags.includes(x)).length-pan.filter(x=>a.tags.includes(x)).length);const last=saved().at(-1)?.title;options=matches.sort((a,b)=>Number(a.name===last)-Number(b.name===last)).slice(0,3).map(m=>({...m,people:Number(p.people),ingredients:m.ingredients.map(([n,q,u])=>[n,q*Number(p.people)/2,u])}));$('#meal-options',host).innerHTML=options.length?`<div class="d-grid">${options.map((m,i)=>`<article class="d-inset"><span class="d-pill">约 ${m.minutes} 分钟 · ${m.people} 人</span><h3>${esc(m.name)}</h3><p class="d-muted">${m.equipment.join('＋')}${pan.some(x=>m.tags.includes(x))?' · 用到优先食材':''}</p><details open><summary>采购／备料清单</summary>${m.ingredients.map(([n,q,u])=>`<label class="d-check"><input type="checkbox">${n} ${q}${u}</label>`).join('')}</details><ol>${m.steps.map(s=>`<li>${esc(s.replace('两人',m.people+' 人'))}</li>`).join('')}</ol><div class="d-actions"><button class="d-primary" data-meal-pick="${i}">今晚就吃这个</button><button data-meal-copy="${i}">复制清单</button></div></article>`).join('')}</div>`:'<div class="d-empty">现有菜单没有满足所有条件的组合。请放宽时间或器材条件；不会忽略你排除的食材。</div>';host.querySelectorAll('[data-meal-pick]').forEach(b=>b.onclick=()=>{const m=options[Number(b.dataset.mealPick)],plan={id:id(),title:m.name,summary:`${m.people} 人 · ${m.minutes} 分钟`,at:new Date().toISOString(),text:mealText(m)};save('meal-plans',[...saved(),plan].slice(-100));toast('已保存今晚菜单');renderMeal()});host.querySelectorAll('[data-meal-copy]').forEach(b=>b.onclick=()=>copy(mealText(options[Number(b.dataset.mealCopy)])));}
function mealText(m){return `${m.name}\n${m.people} 人 · 预计 ${m.minutes} 分钟\n备料：\n${m.ingredients.map(([n,q,u])=>`${n} ${q}${u}`).join('\n')}\n步骤：\n${m.steps.map((s,i)=>`${i+1}. ${s.replace('两人',m.people+' 人')}`).join('\n')}`}
function renderWeekend(){const pref=read('weekend-preferences',{});host.innerHTML=`<section class="d-panel"><div class="d-kicker">A half day, ready to choose</div><h2>半日安排 · 活动＋吃饭</h2><p class="d-muted">从真实活动快照选最多三个方案，保留来源与地点。时间表是建议；交通、营业、票务需在出发前核对。</p><form id="weekend-plan-form" class="d-form">${field('date','哪天出发','date',pref.date>=dateIn()?pref.date:dateIn(),'required')}${select('city','地区',cityChoices,pref.city||'')}${select('start','活动最早开始',[['9','09:00'],['10','10:00'],['12','12:00'],['14','14:00']],pref.start||'10')}${select('hours','可用时长',[['3','3 小时'],['4','4 小时'],['6','6 小时']],pref.hours||'4')}${select('free','费用',[['any','不限'],['yes','只看已确认免费']],pref.free||'any')}${field('query','兴趣关键词（可空）','text',pref.query||'','maxlength="80"')}${select('restaurant','用餐选择',[['','在活动附近找餐厅'],...places().map(p=>[p.id,p.name+' · '+(p.address||'地区未填')])],pref.restaurant||'')}<div class="d-actions d-wide"><button class="d-primary">生成半日方案</button><button id="weekend-refresh" type="button">↻ 读取活动快照</button>${link(appURL('meal-orbit/'),'今晚在家做饭')}</div></form><p class="d-muted">活动快照 ${stamp(events.updatedAt)} · ${fresh(events.updatedAt)?'已加载':'数据未载入或过期；请核对来源'}</p><div id="weekend-options"></div>${history()}<div id="life-backup"></div></section>`;$('#weekend-plan-form',host).onsubmit=e=>{e.preventDefault();const p=data(e.target);save('weekend-preferences',p);generateWeekend(p)};$('#weekend-refresh',host).onclick=load;bindHistory();if(events.events.length)generateWeekend(data($('#weekend-plan-form',host)));}
const time=n=>`${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toString().padStart(2,'0')}`;
function generateWeekend(p){const pool=planEvents(events.events,{date:p.date,city:p.city,start:Number(p.start),hours:Number(p.hours),query:p.query,freeOnly:p.free==='yes'}).filter(e=>!e.checkedAt||fresh(e.checkedAt));const restaurant=places().find(x=>x.id===p.restaurant);options=pool.slice(batch,batch+3);if(!options.length&&pool.length){batch=0;options=pool.slice(0,3)}const plans=options.map(e=>{const start=e.start.length>=16?Number(e.start.slice(11,13))*60+Number(e.start.slice(14,16)):Number(p.start)*60;let duration=60;if(e.end?.slice(0,10)===e.start.slice(0,10)&&e.end.length>=16){duration=Math.max(60,Math.min(90,Number(e.end.slice(11,13))*60+Number(e.end.slice(14,16))-start))}const finish=start+duration;const food=restaurant?.name||e.city+' '+e.venue+' 附近餐厅';const route='https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent('Juanita, Kirkland WA')+'&destination='+encodeURIComponent(food)+'&waypoints='+encodeURIComponent(e.venue+', '+e.city);return {e,start,finish,food,route,restaurant,p};});$('#weekend-options',host).innerHTML=plans.length?`<p class="d-muted">找到 ${pool.length} 个候选 · 行程内预留 30 分钟转场，不代表实时车程。带固定时段活动可能只安排部分参观，预约项目请以原文为准。</p><div class="d-grid">${plans.map((x,i)=>`<article class="d-inset"><span class="d-pill">${esc(x.e.city)} · ${esc(x.e.cost)}</span><h3>${esc(x.e.title)}</h3><p class="d-muted">${esc(x.e.description?.slice(0,220)||'详情见活动原文')}</p><div class="d-step"><b>${time(x.start)}</b><div><strong>参加活动</strong><p>${esc(x.e.venue)}</p><small>${x.e.start.length<16?'原文未给出时间，以上为建议安排':'来源开始时间 '+esc(x.e.start.slice(11,16))} · ${link(x.e.url,'核对活动')}</small></div></div><div class="d-step"><b>${time(x.finish+30)}</b><div><strong>${esc(x.restaurant?.name||'附近吃饭')}</strong><p>${x.restaurant?'使用你收藏的餐厅；请核对是否顺路、是否营业。':'选择活动附近餐厅，避免再跨区。'}</p>${link('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(x.food),'查看餐厅')}</div></div><div class="d-actions"><button class="d-primary" data-weekend-pick="${i}">选这个方案</button>${link(x.route,'路线与实际车程')}<button data-weekend-ask="${i}">问 GPT ↗</button></div></article>`).join('')}</div>${pool.length>3?'<button id="weekend-more">换一组方案</button>':''}`:'<div class="d-empty">当前快照没有满足这些条件的活动。可更换日期、地区或关键词；不会用旧活动填充行程。</div>';host.querySelectorAll('[data-weekend-pick]').forEach(b=>b.onclick=()=>{const x=plans[Number(b.dataset.weekendPick)],text=weekendText(x),plan={id:id(),title:x.e.title,summary:p.date+' · '+x.e.city,at:new Date().toISOString(),text};save('weekend-plans',[...saved(),plan].slice(-100));toast('方案已保存，可在下方复制安排');renderWeekend()});host.querySelectorAll('[data-weekend-ask]').forEach(b=>b.onclick=()=>ask('周末半日安排',plans[Number(b.dataset.weekendAsk)],'请检查行程时间和交通是否合理，核对活动和餐厅营业信息，再给出可执行安排。'));$('#weekend-more',host)?.addEventListener('click',()=>{batch=(batch+3)%pool.length;generateWeekend(p)});}
function weekendText(x){return `${x.p.date} · ${x.e.city}\n${time(x.start)} ${x.e.title}\n${x.e.venue}\n活动原文：${x.e.url}\n${time(x.finish+30)} 用餐：${x.food}\n建议行程，出发前核对活动时段、票务、营业和实际车程。\n路线：${x.route}`}
async function load(){try{events=await json('apps/eastside-weekend/data/events.json');renderWeekend()}catch(e){toast(e.message);renderWeekend()}}
if(host){render();if(mode==='weekend')load()}
