import {$,esc,link,fmt,stamp,read,save,field,area,select,data,id,json,ask,backupBar,hookSync,toast,dateIn,num} from './core.js';
import {purchaseState,fresh} from './models.mjs';
const host=document.querySelector('[data-decision="shopping"]');let feed={items:[]},error='';const items=()=>read('purchases');
function matches(c){const words=c.keyword.toLowerCase().split(/\s+/).filter(Boolean);return feed.items.filter(p=>words.every(w=>(p.title+' '+(p.summary||'')).toLowerCase().includes(w))).sort((a,b)=>(b.published_at||'').localeCompare(a.published_at||'')).slice(0,5)}
function render(){host.innerHTML=`<section class="d-panel"><div class="d-row"><div><div class="d-kicker">Shortlist / buy with context</div><h2>我的候选购买清单</h2></div><button id="purchase-refresh">↻ 检查信息流</button></div><p class="d-muted">记住你想买的具体版本、目标价与兼容条件。现有信息流按关键词匹配；文章中的价格只是线索，确认实际商品后才成为价格记录。打开此页时检查，不承诺后台商家实时监价。</p>${error?`<p class="d-error">${esc(error)}</p>`:''}<div class="d-actions"><button id="purchase-add" class="d-primary">＋ 添加候选</button><small>信息流快照 ${stamp(feed.generated_at)}</small></div><div id="purchase-editor"></div><div class="d-grid">${items().map(card).join('')||'<div class="d-empty d-wide">把真正考虑购买的物品放在这里，之后每次看到优惠都能与原条件对照。</div>'}</div><div id="purchase-backup"></div></section>`;$('#purchase-add',host).onclick=()=>form();$('#purchase-refresh',host).onclick=load;
 host.querySelectorAll('[data-p-edit]').forEach(b=>b.onclick=()=>form(items().find(c=>c.id===b.dataset.pEdit)));
 host.querySelectorAll('[data-p-price]').forEach(b=>b.onclick=()=>observation(items().find(c=>c.id===b.dataset.pPrice)));
 host.querySelectorAll('[data-p-ask]').forEach(b=>b.onclick=()=>{const c=items().find(c=>c.id===b.dataset.pAsk);ask(c.name+' 购买判断',{candidate:c,state:purchaseState(c),matchingArticles:matches(c).map(p=>({title:p.title,url:p.source_url,publishedAt:p.published_at}))},'请核对型号、版本和兼容性，比较买入、等待、放弃的理由。价格记录不等于当前结账价，请指出还需核对什么。')});
 host.querySelectorAll('[data-p-done]').forEach(b=>b.onclick=()=>{const all=items(),c=all.find(c=>c.id===b.dataset.pDone);c.status=c.status==='purchased'?'watching':'purchased';save('purchases',all);render()});
 host.querySelectorAll('[data-p-remove]').forEach(b=>b.onclick=()=>{if(confirm('删除候选及其价格记录？')){save('purchases',items().filter(c=>c.id!==b.dataset.pRemove));render()}});
 backupBar($('#purchase-backup',host),['purchases'],(_,v)=>v.every(c=>c&&typeof c.id==='string'&&typeof c.name==='string'&&typeof c.keyword==='string'&&typeof c.variant==='string'&&['USD','CNY','JPY'].includes(c.currency)&&c.target>0&&Array.isArray(c.observations)&&c.observations.every(o=>o.price>0&&typeof o.variant==='string'&&typeof o.currency==='string'&&Number.isFinite(Date.parse(o.at)))));
}
function card(c){const s=purchaseState(c),o=c.observations.at(-1),found=matches(c);return `<article class="d-inset"><div class="d-row"><h3>${esc(c.name)}</h3><span class="d-pill ${s.state}">${esc(s.text)}</span></div><p>目标 ≤ ${fmt(c.target)} ${c.currency} · ${esc(c.variant||'尚未指定版本')}</p><p class="d-muted">使用需求：${esc(c.need||'未填写')}<br>兼容条件：${esc(c.requirement||'未填写')}<br>确认依据：${esc(c.evidence||'未提供')}</p>${o?`<p>最近确认 ${fmt(o.price)} ${esc(o.currency)} · ${esc(o.variant)}<br><small>${stamp(o.at)} · ${link(o.url,'价格来源')}</small></p>`:'<p class="d-muted">还没有确认过价格。</p>'}<div class="d-actions"><button data-p-price="${c.id}">记录已核对价格</button><button data-p-edit="${c.id}">编辑条件</button><button data-p-ask="${c.id}">问 GPT ↗</button><button data-p-done="${c.id}">${c.status==='purchased'?'重新关注':'已购买'}</button><button data-p-remove="${c.id}">移除</button></div><details ${found.length?'open':''}><summary>匹配的资讯线索 · ${found.length}</summary>${found.map(p=>`<p>${link(p.source_url,p.title)}<br><small>${stamp(p.published_at)} · ${esc(p.price||'文章没有明确报价')} · ${fresh(p.published_at,72)?'近期报道':'较早报道'}；请核对商品本身</small></p>`).join('')||'<p class="d-muted">当前信息流无匹配，调整关键词或直接记录商家页面上的价格。</p>'}</details><details><summary>价格记录 · ${c.observations.length}</summary>${[...c.observations].reverse().map(p=>`<p>${fmt(p.price)} ${esc(p.currency)} · ${esc(p.variant)}<br><small>${stamp(p.at)} · ${link(p.url,'来源')}</small></p>`).join('')}</details></article>`}
function form(c={}){$('#purchase-editor',host).innerHTML=`<form id="purchase-form" class="d-inset d-form">${field('name','候选名称','text',c.name||'','required maxlength="120"')}${field('keyword','信息流关键词（空格分隔，全部匹配）','text',c.keyword||c.name||'','required maxlength="120"')}${field('variant','具体版本／配置','text',c.variant||'','required maxlength="160"')}${field('target','目标价格','number',c.target||'','required min="0.01" step="any"')}${select('currency','币种',[['USD','USD'],['CNY','CNY'],['JPY','JPY']],c.currency||'USD')}${select('compatibility','兼容性',[['unknown','待确认'],['yes','已确认兼容'],['no','不兼容']],c.compatibility||'unknown')}${area('need','为什么需要它',c.need||'','maxlength="1500"')}${area('requirement','必须满足的设备／接口／场景',c.requirement||'','maxlength="1500"')}${area('evidence','兼容性依据（已确认时必填）',c.evidence||'','maxlength="1500"')}${field('snoozeUntil','暂缓至（可空）','date',c.snoozeUntil||'')}<div class="d-actions d-wide"><button class="d-primary">保存候选</button><button id="purchase-cancel" type="button">取消</button></div></form>`;$('#purchase-cancel',host).onclick=render;$('#purchase-form',host).onsubmit=e=>{e.preventDefault();const v=data(e.target);if(v.compatibility==='yes'&&!v.evidence.trim()){toast('请填写确认兼容的依据');return}const x={...c,...v,target:num(v.target),id:c.id||id(),status:c.status||'watching',observations:c.observations||[]};if(save('purchases',c.id?items().map(i=>i.id===c.id?x:i):[...items(),x]))render()};$('#purchase-form input',host).focus();}
function observation(c){const now=new Date().toISOString().slice(0,16);$('#purchase-editor',host).innerHTML=`<form id="purchase-price-form" class="d-inset d-form"><h3 class="d-wide">${esc(c.name)} · 记录核对后的报价</h3>${field('price','价格（含哪些费用请写在备注）','number','','required min="0.01" step="any"')}${select('currency','币种',[['USD','USD'],['CNY','CNY'],['JPY','JPY']],c.currency)}${field('variant','实际商品版本','text',c.variant,'required maxlength="160"')}${field('url','商家或证据链接','url','','required')}${field('at','核对时间 UTC','datetime-local',now,'required')}${area('note','税费、运费、库存或限制','','maxlength="1000"')}<div class="d-actions d-wide"><button class="d-primary">保存价格证据</button><button id="purchase-cancel" type="button">取消</button></div></form>`;$('#purchase-cancel',host).onclick=render;$('#purchase-price-form',host).onsubmit=e=>{e.preventDefault();const v=data(e.target),at=new Date(v.at+'Z').toISOString();if(Date.parse(at)>Date.now()+300000){toast('核对时间不能在未来');return}const all=items(),item=all.find(i=>i.id===c.id);item.observations=[...item.observations,{...v,id:id(),price:num(v.price),at,recordedAt:new Date().toISOString()}].sort((a,b)=>a.at.localeCompare(b.at)).slice(-100);if(save('purchases',all))render()};$('#purchase-price-form input',host).focus();}
async function load(){const b=$('#purchase-refresh',host);if(b)b.disabled=true;try{feed=await json('apps/3c-scout/data/products.json');error=''}catch(e){error=e.message}render()}
if(host){render();load();hookSync(render)}
