import {esc,read,raw,stamp,copy,setupPage} from './core.js';
setupPage();
const investment=document.body.dataset.workspace==='investment',params=new URLSearchParams(location.search);
const routes=investment?{market:'stock-alert',thesis:'thesis-lab'}:{weekend:'eastside-weekend',dinner:'meal-orbit',restaurants:'meal-orbit',recipes:'meal-orbit',favorites:'meal-orbit',wheel:'meal-orbit'};
const buttons=[...document.querySelectorAll('[data-tab]')],frames=new Map();let tab='',symbol=params.get('symbol')||raw('ptu.workspace.symbol','NVDA');
if(!/^[A-Z0-9.^-]{1,20}$/.test(symbol))symbol='NVDA';
function send(frame,type,data={}){frame.contentWindow?.postMessage({channel:'pt-workspace',type,...data},location.origin)}
function setSymbol(value){value=String(value).trim().toUpperCase();if(!/^[A-Z0-9.^-]{1,20}$/.test(value))return;const changed=value!==symbol;symbol=value;localStorage.setItem('ptu.workspace.symbol',JSON.stringify(symbol));if(investment)document.querySelector('#ws-symbol').value=symbol;if(changed)for(const x of frames.values())send(x.frame,'symbol',{symbol});address();summary();}
function address(){const u=new URL(location.href);u.searchParams.set('tab',tab);if(investment)u.searchParams.set('symbol',symbol);history.replaceState(null,'',u)}
function activate(next){if(!buttons.some(b=>b.dataset.tab===next))next=investment?'review':'weekend';tab=next;
 buttons.forEach(b=>{const on=b.dataset.tab===tab;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1});
 document.querySelectorAll('.ws-panel').forEach(p=>p.hidden=true);
 if(routes[tab]){const slug=routes[tab];let x=frames.get(slug);if(!x){const panel=document.createElement('section');panel.className='ws-panel';panel.setAttribute('role','tabpanel');const status=document.createElement('div');status.className='ws-frame-status';status.textContent='正在读取…';const frame=document.createElement('iframe');frame.title=slug;frame.loading='eager';frame.src='../'+slug+'/?embedded=workspace'+(investment?'&symbol='+encodeURIComponent(symbol):'');panel.append(status,frame);document.querySelector('#ws-frames').append(panel);x={panel,frame,status};frames.set(slug,x);frame.addEventListener('load',()=>{status.hidden=true;send(frame,'activate',{tab});if(investment)send(frame,'symbol',{symbol})});}
 x.panel.id='panel-'+tab;x.panel.setAttribute('aria-labelledby','tab-'+tab);x.panel.hidden=false;send(x.frame,'activate',{tab});if(investment)send(x.frame,'symbol',{symbol});
 }else document.querySelector('#panel-'+tab).hidden=false;
 if(tab==='plans')renderPlans();address();summary();
}
function summary(){document.querySelector('#ws-summary').textContent=investment?'当前标的 '+symbol+' · 行情与财报共用选择':'已选 '+read('weekend-plans').length+' 个出行安排 · '+read('meal-plans').length+' 份菜单 · '+raw('savedPlaces').length+' 家收藏餐厅';}
function renderPlans(){const el=document.querySelector('#ws-plans');if(!el)return;const plans=[...read('weekend-plans').map(p=>({...p,kind:'出行'})),...read('meal-plans').map(p=>({...p,kind:'菜单'}))].sort((a,b)=>String(b.at).localeCompare(a.at));el.innerHTML=plans.map((p,i)=>'<article class="d-panel"><small>'+p.kind+' · '+stamp(p.at)+'</small><h2>'+esc(p.title)+'</h2><p>'+esc(p.summary)+'</p><pre>'+esc(p.text)+'</pre><button data-copy="'+i+'">复制安排</button></article>').join('')||'<div class="ws-empty">在半日安排或今晚菜单中选一个方案，会集中出现在这里。</div>';el.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copy(plans[Number(b.dataset.copy)].text))}
buttons.forEach((b,i)=>{b.onclick=()=>activate(b.dataset.tab);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;activate(buttons[j].dataset.tab);buttons[j].focus()}}});
if(investment){document.querySelector('#ws-symbol').value=symbol;document.querySelector('#ws-symbols').innerHTML=[...new Set(['NVDA','AAPL','MSFT','QQQ','SPY',...read('holdings').map(h=>h.symbol)])].map(s=>'<option value="'+esc(s)+'">').join('');document.querySelector('#ws-symbol-form').onsubmit=e=>{e.preventDefault();setSymbol(document.querySelector('#ws-symbol').value);if(tab==='review')activate('market')};}
addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.channel!=='pt-workspace')return;const x=[...frames.values()].find(x=>x.frame.contentWindow===e.source);if(!x)return;const d=e.data;if(d.type==='height'&&Number.isFinite(d.height))x.frame.style.height=Math.min(30000,Math.max(500,d.height))+'px';if(d.type==='ready'){send(x.frame,'activate',{tab});if(investment)send(x.frame,'symbol',{symbol})}if(d.type==='symbol'&&investment&&x.panel.hidden===false)setSymbol(d.symbol);if(d.type==='navigate'&&buttons.some(b=>b.dataset.tab===d.tab)){if(d.symbol)setSymbol(d.symbol);activate(d.tab)}if(d.type==='records'){dispatchEvent(new Event('decision-thesis-updated'));summary();}});
document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a)return;const u=new URL(a.href);if(u.origin!==location.origin)return;const slug=u.pathname.match(/\/apps\/([^/]+)/)?.[1],next=Object.keys(routes).find(k=>routes[k]===slug);if(next){e.preventDefault();e.stopImmediatePropagation();if(u.searchParams.get('symbol'))setSymbol(u.searchParams.get('symbol'));activate(next)}},true);
addEventListener('storage',e=>{summary();if(tab==='plans')renderPlans();for(const x of frames.values())send(x.frame,'records',{key:e.key})});addEventListener('decision-change',summary);addEventListener('pt-sync-applied',()=>{summary();renderPlans();for(const x of frames.values())send(x.frame,'records',{key:'sync'})});
activate(params.get('tab')|| (investment?'review':'weekend'));

addEventListener('investment-select',e=>{if(!investment)return;setSymbol(e.detail.symbol);activate(e.detail.tab||'review')});
addEventListener('decision-change',e=>{if(!investment)return;document.querySelector('#ws-symbols').innerHTML=[...new Set([...read('holdings').map(h=>h.symbol),...raw('stock_alert_watchlist_v1').map(h=>h.symbol)])].map(s=>'<option value="'+esc(s)+'">').join('');for(const x of frames.values())send(x.frame,'records',{key:e.detail.key})});
