import {connectSource,sources,cachedSources,sourceStatus,sourceAction} from '../_decision/collector.js';
import {$,esc,link,stamp,read,save,field,area,select,data,id,ask,backupBar,setupPage,hookSync,toast,dateIn,url} from '../_decision/core.js';
import {watchCheck,diffLines,num} from '../_decision/models.mjs';
setupPage();const host=$('#decision-app');const monitors=()=>read('monitors');let filter='all';
function latest(w){return w.observations.at(-1)}
function status(w){const last=latest(w);if(w.paused)return {state:'paused',text:'监视项已暂停'};if(w.snoozeUntil&&w.snoozeUntil>dateIn())return {state:'snooze',text:'稍后处理 · '+w.snoozeUntil};if(last&&w.resolvedId===last.id)return {state:'done',text:'这次变化已处理'};const pending=w.observations.find(o=>o.id===w.pendingId);if(pending&&w.resolvedId!==pending.id)return {...pending.check,text:pending.check.text+' · 尚未处理'};return last?.check||{state:'empty',text:'等待首次基线'};}
function render(){const list=monitors(),need=list.filter(w=>['matched','review','unknown'].includes(status(w).state));const shown=list.filter(w=>filter==='all'||filter==='action'&&need.includes(w)||filter==='paused'&&w.paused);host.innerHTML=`<div class="d-statgrid"><div class="d-stat"><b>${list.length}</b><span>等待中的事情</span></div><div class="d-stat"><b>${need.length}</b><span>需要你处理</span></div><div class="d-stat"><b>${list.filter(w=>status(w).state==='done').length}</b><span>本次已处理</span></div><div class="d-stat"><b>${list.reduce((n,w)=>n+w.observations.length,0)}</b><span>保留的观察记录</span></div></div><div class="d-note">接收结果后即时比较。启用自动检查后，关闭页面也会每小时抓取公开网页并保留变化；打开时自动对照等待条件。Muse 账号尚未连接。首次抓取建立基线；失败保留旧证据，不当作没有变化。</div><section class="d-panel"><div class="d-row"><h2>我在等什么</h2><div class="d-actions"><button id="watch-add" class="d-primary">＋ 新建等待条件</button><button id="watch-import-results">导入监视结果</button></div></div><div id="watch-editor"></div><div class="d-actions"><select id="watch-filter" aria-label="监视筛选"><option value="all">全部监视项</option><option value="action">需要处理</option><option value="paused">已暂停</option></select></div>${shown.map(card).join('')||'<div class="d-empty">还没有对应的监视项。添加网址和等待条件，即可开始后台检查。</div>'}<div id="watch-backup"></div></section>`;
 host.querySelectorAll('[data-w-auto]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const all=monitors(),w=all.find(x=>x.id===b.dataset.wAuto);w.autoSourceId=await connectSource({kind:'page',url:w.url,name:w.name,selector:w.selector||''});save('monitors',all);await pull();render()}catch(e){toast(e.message);b.disabled=false}});
 $('#watch-filter').value=filter;$('#watch-filter').onchange=e=>{filter=e.target.value;render()};$('#watch-add').onclick=()=>form();$('#watch-import-results').onclick=importForm;
 host.querySelectorAll('[data-w-capture]').forEach(b=>b.onclick=()=>capture(monitors().find(w=>w.id===b.dataset.wCapture)));
 host.querySelectorAll('[data-w-edit]').forEach(b=>b.onclick=()=>form(monitors().find(w=>w.id===b.dataset.wEdit)));
 host.querySelectorAll('[data-w-done]').forEach(b=>b.onclick=()=>{const all=monitors(),w=all.find(w=>w.id===b.dataset.wDone);w.resolvedId=latest(w)?.id||null;w.pendingId=null;w.resolvedAt=new Date().toISOString();w.snoozeUntil='';save('monitors',all);render()});
 host.querySelectorAll('[data-w-pause]').forEach(b=>b.onclick=()=>{const all=monitors(),w=all.find(w=>w.id===b.dataset.wPause);w.paused=!w.paused;save('monitors',all);if(w.autoSourceId)sourceAction(w.autoSourceId,w.paused?'pause':'resume').catch(e=>toast(e.message));render()});
 host.querySelectorAll('[data-w-snooze]').forEach(b=>b.onclick=()=>{const all=monitors(),w=all.find(w=>w.id===b.dataset.wSnooze),date=$('input[type=date]',b.closest('.d-actions')).value;if(!date||date<=dateIn()){toast('请选择今天之后的日期');return}w.snoozeUntil=date;save('monitors',all);render()});
 host.querySelectorAll('[data-w-ask]').forEach(b=>b.onclick=()=>{const w=monitors().find(w=>w.id===b.dataset.wAsk);ask(w.name+' 监视变化',{intent:w.intent,source:w.url,rule:{type:w.rule,value:w.value},previous:w.observations.at(-2),current:latest(w)},'这次变化是否真的满足我的等待条件？请区分页面变化、证据和推断，给出下一步与需要核实的内容。')});
 backupBar($('#watch-backup'),['monitors'],(_,v)=>v.every(w=>w&&typeof w.id==='string'&&typeof w.name==='string'&&typeof w.intent==='string'&&typeof w.value==='string'&&url(w.url)!=='#'&&['change','contains','absent','lte','gte'].includes(w.rule)&&Array.isArray(w.observations)&&w.observations.every(o=>typeof o.id==='string'&&typeof o.text==='string'&&o.check&&typeof o.check.state==='string')));
}
function card(w){const s=status(w),last=latest(w),alert=w.observations.find(o=>o.id===w.pendingId)||last,alertIndex=w.observations.findIndex(o=>o.id===alert?.id),before=w.observations[alertIndex-1],diff=diffLines(before?.text,alert?.text);return `<article class="d-inset"><div class="d-row"><h3>${esc(w.name)}</h3><span class="d-pill ${s.state}">${esc(s.text)}</span></div><p><strong>等待条件：</strong>${esc(w.intent)}</p><p class="d-muted">规则：${esc({change:'任何正文变化',contains:'新出现关键词',absent:'关键词消失',lte:'数值 ≤',gte:'数值 ≥'}[w.rule])} ${esc(w.value||'')} · ${link(w.url,'查看网站')}</p><small>最近观察 ${stamp(last?.observedAt)} · 接收 ${stamp(last?.receivedAt)}</small>${last?`<details ${['matched','review'].includes(s.state)?'open':''}><summary>待处理变化／最近变化对比</summary>${before?`<div class="d-grid"><div><b>移除／旧内容</b><pre>${esc(diff.removed.slice(0,50).join('\n')||'没有移除的行')}</pre></div><div><b>新增／新内容</b><pre>${esc(diff.added.slice(0,50).join('\n')||'没有新增的行')}</pre></div></div><small>按行比较，最多各显示 50 行；完整文本在历史中。</small>`:'首次基线，无变化对比。'}</details>`:''}<div class="d-actions">${w.autoSourceId?`<p class="d-muted">${esc(sourceStatus(w.autoSourceId))}</p>`:`<button data-w-auto="${w.id}">启用后台自动检查</button>`}<button data-w-capture="${w.id}" ${w.paused?'disabled':''}>粘贴新结果</button><button data-w-done="${w.id}" ${last?'':'disabled'}>本次已处理</button><button data-w-ask="${w.id}" ${last?'':'disabled'}>问 GPT ↗</button><button data-w-edit="${w.id}">编辑条件</button><button data-w-pause="${w.id}">${w.paused?'恢复接收':'暂停'}</button></div><div class="d-actions"><label>稍后处理日期<input type="date" value="${esc(w.snoozeUntil||'')}" aria-label="稍后处理日期"></label><button data-w-snooze="${w.id}">稍后提醒</button></div><details><summary>完整观察历史 · ${w.observations.length}</summary>${w.observations.slice().reverse().map(o=>`<div><small>${stamp(o.observedAt)} · ${esc(o.check.text)} · ${esc(o.provider||'手动粘贴')}</small><pre>${esc(o.text)}</pre></div>`).join('')}</details></article>`}
function form(w={}){$('#watch-editor').innerHTML=`<form id="watch-form" class="d-inset d-form">${field('name','监视项名称','text',w.name||'','required maxlength="120"')}${field('url','来源网址','url',w.url||'','required maxlength="2000"')}${select('rule','触发规则',[['change','正文有变化 → 待人工确认'],['contains','新出现指定关键词'],['absent','原有关键词消失'],['lte','数值新近 ≤ 阈值'],['gte','数值新近 ≥ 阈值']],w.rule||'change')}${field('selector','只监视此区域（CSS 选择器，可空）','text',w.selector||'','maxlength="200"')}<label class="d-check d-wide"><input type="checkbox" name="background" ${w.autoSourceId||!w.id?'checked':''}>后台自动检查公开网页（网址及正文存入 PT 后台）</label>${area('intent','我到底在等什么',w.intent||'','required maxlength="2000"')}${field('value','关键词／阈值（正文变化规则可空）','text',w.value||'','maxlength="200"')}<div class="d-actions d-wide"><button class="d-primary">保存等待条件</button><button id="watch-cancel" type="button">取消</button></div><p class="d-muted d-wide">数值规则只接收目标字段的纯数字，避免把网页中的日期或其他价格误识别。修改触发规则会用最近正文重新建立基线，旧记录保留。</p></form>`;$('#watch-cancel').onclick=render;$('#watch-form').onsubmit=async e=>{e.preventDefault();const v=data(e.target);if(v.rule!=='change'&&!v.value.trim()){toast('请填写关键词或阈值');return}if(['lte','gte'].includes(v.rule)&&num(v.value)===null){toast('阈值必须是数字');return}if(url(v.url)==='#'){toast('仅支持 http/https 网页');return}const all=monitors();if(all.some(x=>x.id!==w.id&&x.url===v.url&&x.intent===v.intent)){toast('相同监视条件已存在');return}const updated={...w,...v,id:w.id||id(),paused:w.paused||false,observations:w.observations||[]};if(w.id&&(w.rule!==v.rule||w.value!==v.value||w.url!==v.url)){updated.resolvedId=null;updated.pendingId=null;updated.snoozeUntil='';const base=latest(w);if(base)updated.observations=[...updated.observations,{...base,id:id(),receivedAt:new Date().toISOString(),provider:'规则修改后重建基线',check:{state:'baseline',text:'规则已修改，以此记录重新建立基线'}}].slice(-40)}try{if(v.background==='on'){if(!w.autoSourceId||w.url!==v.url||w.selector!==v.selector){updated.autoSourceId=await connectSource({kind:'page',url:v.url,name:v.name,selector:v.selector||''});if(w.autoSourceId)await sourceAction(w.autoSourceId,'pause');}}else if(w.autoSourceId){await sourceAction(w.autoSourceId,'pause');updated.autoSourceId=null;}}catch(err){toast('后台未启用：'+err.message);return}if(save('monitors',w.id?all.map(x=>x.id===w.id?updated:x):[...all,updated])){render();pull()}};$('#watch-form input').focus();}
function append(w,text,observedAt,provider){if(w.paused)throw Error('监视项已暂停');if(typeof text!=='string'||!text.trim()||text.length>60000)throw Error('正文应为 1–60000 个字符');if(!Number.isFinite(Date.parse(observedAt))||Date.parse(observedAt)>Date.now()+300000)throw Error('观察时间无效或在未来');const prior=latest(w);if(prior&&Date.parse(observedAt)<Date.parse(prior.observedAt))throw Error('观察时间早于最近记录，请按时间顺序导入');if(prior?.text===text&&prior.observedAt===observedAt)return false;const o={id:id(),text,observedAt,receivedAt:new Date().toISOString(),provider};o.check=watchCheck(w,prior,o);w.observations=[...w.observations,o].slice(-40);if(o.check.state==='matched'||o.check.state==='review'||o.check.state==='unknown'){w.snoozeUntil='';w.resolvedId=null;w.pendingId=o.id}return true;}
function capture(w){$('#watch-editor').innerHTML=`<form id="watch-capture" class="d-inset d-form"><h3 class="d-wide">${esc(w.name)} · 接收结果</h3>${field('provider','结果来源','text','Muse / 手动','required maxlength="100"')}${field('observedAt','观察时间 UTC','datetime-local',new Date().toISOString().slice(0,16),'required')}${area('text',latest(w)?'新正文／新数值':'首次基线正文／数值','','required maxlength="60000"')}<div class="d-actions d-wide"><button class="d-primary">保存并比较</button><button id="watch-cancel" type="button">取消</button></div></form>`;$('#watch-cancel').onclick=render;$('#watch-capture').onsubmit=e=>{e.preventDefault();try{const d=data(e.target),all=monitors(),item=all.find(x=>x.id===w.id);if(append(item,d.text,new Date(d.observedAt+'Z').toISOString(),d.provider)){if(save('monitors',all))render()}else toast('相同结果已存在')}catch(err){toast(err.message)}};$('#watch-capture textarea').focus();}
function importForm(){$('#watch-editor').innerHTML=`<form id="watch-results" class="d-inset"><h3>批量接收监视结果</h3><p class="d-muted">粘贴 JSON 数组，或 {"observations":[…]}。每项包含 url、text、observedAt（带 Z 或时区）、provider（可选）。按网址匹配所有对应规则；未知网址与暂停项跳过，导入前显示数量。</p><pre>[{"url":"https://example.com/product","text":"新正文","observedAt":"2026-09-30T17:00:00Z","provider":"Muse"}]</pre><textarea name="payload" required maxlength="1500000" aria-label="监视结果 JSON"></textarea><div class="d-actions"><label class="d-button">选择 JSON 文件<input id="watch-results-file" type="file" accept=".json" hidden></label><button class="d-primary">验证并导入</button><button id="watch-cancel" type="button">取消</button></div></form>`;$('#watch-cancel').onclick=render;$('#watch-results-file').onchange=async e=>{const f=e.target.files[0];if(f?.size>1500000){toast('文件超过 1.5 MB');return}if(f)$('#watch-results textarea').value=await f.text()};$('#watch-results').onsubmit=e=>{e.preventDefault();try{const payload=JSON.parse(data(e.target).payload),incoming=Array.isArray(payload)?payload:payload.observations;if(!Array.isArray(incoming)||incoming.length>300)throw Error('最多导入 300 条结果');const all=structuredClone(monitors());let count=0,skip=0;incoming.sort((a,b)=>String(a.observedAt).localeCompare(String(b.observedAt))).forEach(o=>{if(typeof o.url!=='string'||typeof o.text!=='string'||typeof o.observedAt!=='string'||!/(Z|[+-]\d\d:\d\d)$/.test(o.observedAt))throw Error('每项需要 url、text 和带时区的 observedAt');const targets=all.filter(w=>url(w.url)===url(o.url)&&!w.paused);if(!targets.length){skip++;return}for(const w of targets)if(append(w,o.text,new Date(o.observedAt).toISOString(),String(o.provider||'JSON 导入').slice(0,100)))count++});if(!count){toast('没有新记录可导入，未知网址／暂停／重复共 '+skip+' 条');return}if(confirm(`将接收 ${count} 条观察记录，跳过 ${skip} 条未知网址或暂停项。继续？`)&&save('monitors',all)){render();toast('已接收 '+count+' 条结果')}}catch(err){toast(err.message)}};}
let pulling=false;
async function pull(){if(pulling||!monitors().some(w=>w.autoSourceId))return;pulling=true;try{const remote=await sources(),all=monitors();let changed=false;for(const w of all){if(!w.autoSourceId||w.paused)continue;const s=remote.find(s=>s.id===w.autoSourceId);for(const o of s?.data?.snapshots||[]){if(!o.text||w.observations.some(x=>x.observedAt===o.at)||Date.parse(o.at)<=Date.parse(latest(w)?.observedAt||'1970-01-01'))continue;append(w,o.text,o.at,'后台自动抓取');changed=true}}if(changed)save('monitors',all);if(!document.querySelector('#watch-form,#watch-capture,#watch-results'))render()}catch(e){toast('后台结果未读取：'+e.message)}finally{pulling=false}}
render();hookSync(render);pull();setInterval(()=>{if(!document.hidden)pull()},60000);addEventListener('visibilitychange',()=>{if(!document.hidden)pull()});

