(() => {
'use strict';
const KEY='pt-learning.v1', THEME='pt-learning.theme';
const $=s=>document.querySelector(s), escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let manifest, sources=[], cache=new Map(), generation=0, timer, readingCleanup=()=>{};
const empty=()=>({version:1,lessons:{},last:null});
let state=empty();
try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.version===1&&x.lessons&&typeof x.lessons==='object'&&!Array.isArray(x.lessons)){state=x;}}catch{}
function toast(msg){$('#status').textContent=msg;clearTimeout(timer);timer=setTimeout(()=>$('#status').textContent='',4500);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{toast('未能保存到本机，请导出学习记录，避免关闭页面后丢失。');return false;}}
function theme(t){document.documentElement.dataset.theme=t;try{localStorage.setItem(THEME,t);}catch{}}
let t;try{t=localStorage.getItem(THEME)}catch{}theme(t|| (matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));
$('#theme').onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark');
addEventListener('message',e=>{if(e.origin===location.origin&&e.data?.type==='pt-universe-theme'&&['light','dark'].includes(e.data.theme))theme(e.data.theme)});
// Respond to resizing as well as initial page load; keep the current chapter visible.
matchMedia('(min-width:761px)').addEventListener('change',e=>document.querySelectorAll('.course-menu').forEach(d=>d.open=e.matches));

function revealChapter(){const aside=$('.outline'),active=$('.chapter-link.active');if(!aside||!active||!aside.querySelector('.course-menu')?.open)return;const list=matchMedia('(max-width:760px)').matches?aside.querySelector('.chapters'):aside,a=active.getBoundingClientRect(),r=list.getBoundingClientRect();if(a.top<r.top||a.bottom>r.bottom)list.scrollTop+=a.top-r.top-(list.clientHeight-a.height)/2;}
document.addEventListener('toggle',e=>{if(e.target.matches?.('.course-menu')&&e.target.open)revealChapter();},true);
async function getJSON(file){const res=await fetch('data/'+file+'?v=20261005-textbook2');if(!res.ok)throw new Error('课程载入失败（HTTP '+res.status+'）');return res.json()}
async function getCourse(id){if(!cache.has(id)){const c=manifest.courses.find(c=>c.id===id);if(!c)throw new Error('未找到课程');cache.set(id,await getJSON(c.file));}return cache.get(id)}
const totalDone=c=>Object.keys(state.lessons).filter(id=>id.startsWith(c.id+'-')&&state.lessons[id]?.done===true).length;
const resume=c=>{const last=state.last;if(last?.courseId===c.id&&last.lessonId.startsWith(c.id+'-')){const n=Number(last.lessonId.split('-').pop());if(n>=1&&n<=c.chapterCount)return n;}const n=Array.from({length:c.chapterCount},(_,i)=>i+1).find(n=>!state.lessons[c.id+'-'+String(n).padStart(2,'0')]?.done);return c.history?.resume&&totalDone(c)===0?c.history.resume:n||1;};
const path=(id,n)=>`#/course/${id}/${String(n).padStart(2,'0')}`;
const textOf=l=>[l.orientation?.intro,"本章问题："+l.guide.question,...l.guide.terms.map(t=>t.term+"："+t.definition),"案例起点："+l.walkthrough.setup,"最后交付："+l.caseStudy.artifact,"起点预测："+l.caseStudy.predict,"概念导读",...l.body,...(l.sections||[]).flatMap(s=>[s.title,...s.paragraphs,...(s.figures||[]).flatMap(f=>["图示："+f.title,f.caption,...(f.series?f.series.map(t=>t.name+"："+t.values.join(", ")):[])]),"关键结论："+s.keyPoint,...(s.formula?[s.formula.expression,s.formula.note]:[]),...(s.table?[s.table.caption,s.table.headers.join(' / '),...s.table.rows.map(r=>r.join(' / '))]:[])]),"逐步推演："+l.walkthrough?.title,l.walkthrough?.setup,...(l.walkthrough?.steps||[]),l.walkthrough?.result,"换条件："+l.caseStudy.transfer.question,"逐步答案："+l.caseStudy.transfer.answer,"补充例子："+l.example,"误区："+l.pitfall,"实操练习",...l.steps,"检查标准："+l.criteria,"参考思路："+l.answer,...(l.code?["可运行起点",l.labGuide.before,l.code,"预期输出："+l.labGuide.expect,"控制变量："+l.labGuide.change]:[]),"理解自检："+l.check?.question,"自检解释："+l.check?.answer].filter(Boolean).join('\n\n');
const meta=c=>`${c.chapterCount} 章 · 约 ${Math.round(c.minutes/60)} 小时（含参考阅读与练习）`;
function home(){
 document.title='Self Learning · PT Universe';const done=manifest.courses.reduce((a,c)=>a+totalDone(c),0),total=manifest.courses.reduce((a,c)=>a+c.chapterCount,0), last=state.last, c=last&&manifest.courses.find(c=>c.id===last.courseId);
 $('#content').innerHTML=`<div class="intro"><div><div class="kicker">教材阅读版 · 2026.10.05 / ${manifest.courses.length} 条学习路线</div><h1>把问题弄懂，再亲手做出来。</h1><p>从一个具体问题开始，先看带条件和结果的例子，再解释原理，最后自己验证。整章连续阅读，答案按需展开；九门课都能独立开始。</p></div><div class="summary"><div><strong>${String(manifest.courses.length).padStart(2,'0')}</strong><span>课程</span></div><div><strong>${total}</strong><span>章节</span></div><div><strong>${done}</strong><span>已完成</span></div></div></div>
 ${c?`<div class="resume"><div><strong>继续：${escape(c.title)} · 第 ${resume(c)} 章</strong><p>学习位置已保存；完成状态由你手动标记。</p></div><a class="button primary" href="${path(c.id,resume(c))}">继续学习</a></div>`:''}
 <div class="courses">${manifest.courses.map(c=>`<article class="course-card" style="--course:${c.color}"><div class="meta"><span class="tag">${escape(c.english)}</span></div><h2>${escape(c.title)}</h2><p class="desc">${escape(c.description)}</p><div class="course-delivery"><small>沿途完成的项目</small><strong>${escape(c.projectTitle)}</strong></div><div class="meta">${meta(c)}</div><div class="track"><i style="width:${totalDone(c)/c.chapterCount*100}%"></i></div><small>${totalDone(c)} / ${c.chapterCount} 章已完成${c.history?' · 历史教学至第 4 章':''}</small><div class="bottom"><a class="button primary" href="${path(c.id,resume(c))}">${totalDone(c)||state.last?.courseId===c.id?'继续学习':c.history?'接续第 4 章':'开始第 1 章'}</a><a href="#/course/${c.id}">完整目录</a></div></article>`).join('')}</div>
 <div class="method"><section class="panel"><h2>每章怎么学</h2><ol><li>先看本章的问题、案例条件和要完成的成果。预测可以稍后再写。</li><li>往下连续阅读：每节先看具体例子，再读原理、图示和小结；需要专注一节时切换分节学习。</li><li>换一个条件，独立推导并展开答案对照；再完成实践与自检，留下可以检查的成果。</li><li>按具体阅读指引核对来源；写下笔记，确认能解释后手动标记完成。</li></ol><p class="reading-plan">普通章建议 60–75 分钟：分节讲义与案例约 20–30 分钟，参考阅读约 15–20 分钟，自检、练习与复盘约 20–30 分钟。金融复杂章可分两次，毕业项目分多次完成；所示时间是规划值。</p></section><section class="panel"><h2>资料与历史</h2><p>基础可以来自经典教材；软件、安全和交互细节结合维护中的文档。前沿论文是进阶阅读，不替代基本概念和实践验证。</p><p>金融课沿用此前 16 章顺序，库存与 SBC 保留在第 3 章。前四章依据历史摘要重整，历史教学位置与本页完成记录分开。</p><a class="button" href="#/references">浏览 ${sources.length} 份参考资料</a><p><small>进度、练习回答和笔记自动保存在当前浏览器；用顶部导出／导入，在 Win、Mac 或其他设备间迁移。本站不自动同步这些记录。</small></p></section></div>`;
}
function outline(c,selected){let group='';return `<aside class="outline" aria-label="课程章节"><details class="course-menu" ${matchMedia('(min-width:761px)').matches?'open':''}><summary><span>${escape(c.title)}</span><small>课程目录</small></summary><div class="outline-info"><a href="#/">全部课程</a><span>${totalDone(c)} / ${c.lessons.length} 章已完成</span></div><div class="chapters">${c.lessons.map(l=>{const head=group!==l.module?`<div class="module">${escape(l.module)}</div>`:'';group=l.module;return head+`<a class="chapter-link ${selected===l.id?'active':''}" ${selected===l.id?'aria-current="page"':''} href="${path(c.id,l.number)}"><span class="num">${String(l.number).padStart(2,'0')}</span><span>${escape(l.title)}</span>${state.lessons[l.id]?.done?'<span class="check" aria-label="已完成">✓</span>':''}</a>`}).join('')}</div><p><a href="#/course/${c.id}">课程总览与毕业标准</a></p><a href="#/references">资料目录</a></details></aside>`;}

function overview(c){document.title=c.title+' · Self Learning';$('#content').innerHTML=`<div class="workspace">${outline(c)}<article class="reader"><div class="kicker">${escape(c.english)}</div><h1>${escape(c.title)}</h1><p>${escape(c.description)}</p><div class="callout"><strong>前置知识</strong><p>${escape(c.prerequisites)}</p></div>${c.history?`<div class="callout"><strong>金融课迁移说明</strong><p>${escape(c.history.note)}</p></div>`:''}<a class="button primary" href="${path(c.id,resume({...c,chapterCount:c.lessons.length}))}">从第 ${resume({...c,chapterCount:c.lessons.length})} 章继续</a><section class="course-plan"><h2>这门课会做出什么</h2><p><strong>${escape(c.learningProject.title)}</strong></p><ol>${c.learningProject.phases.map(p=>`<li>${escape(p)}</li>`).join('')}</ol><details><summary>开始前准备</summary><p>${escape(c.learningProject.prepare)}</p></details></section><h2>路线与目标</h2>${manifest.courses.find(m=>m.id===c.id).modules.map(m=>`<section class="course-overview"><h3>${escape(m)}</h3>${c.lessons.filter(l=>l.module===m).map(l=>`<p><a href="${path(c.id,l.number)}">${String(l.number).padStart(2,'0')} · ${escape(l.title)}</a><br><small>${escape(l.goal)}</small></p>`).join('')}</section>`).join('')}<section class="project"><h2>毕业项目</h2><p>${escape(c.capstone)}</p><h3>验收标准</h3><p>${escape(c.acceptance)}</p></section></article></div>`;}
function refCard(ref,section){return `<div class="ref"><a href="${escape(ref.url)}" target="_blank" rel="noopener noreferrer">${escape(ref.title)}</a><p>${escape(ref.author)}</p><div class="meta"><span class="tag">${escape(ref.type)}</span><span>${escape(ref.version)}</span><span>核对 ${ref.checkedAt}</span></div>${section?`<p class="reading"><strong>本章阅读：</strong>${escape(section)}</p>`:`<p>${escape(ref.read)}</p>`}<p>${escape(ref.caveat)}</p></div>`;}
function lesson(c,l){
 document.title=l.title+' · '+c.title+' · Self Learning';
 state.last={courseId:c.id,lessonId:l.id};save();const data=state.lessons[l.id]||{};
 const n=l.sections.length, review=n+3, refsUnit=n+4, total=n+5;
 let current=Number.isInteger(data.unit)?Math.max(0,Math.min(refsUnit,data.unit)):0;
 let mode='full';try{mode=localStorage.getItem('pt-learning.reading.v2')==='guided'?'guided':'full';}catch{}
 const units=[{title:'导读：从一个问题开始',target:'guide'},...l.sections.map((s,i)=>({title:s.title,target:'teaching-'+i})),{title:'验证：换条件与案例对照',target:'worked-case'},{title:'练习：自己做一次',target:'practice'},{title:'复盘：解释与记录',target:'understanding'},{title:'阅读：资料与深入',target:'references'}];
 const terms=l.guide.terms;
 function prose(value){
  const pattern=terms.map(t=>t.term).sort((a,b)=>b.length-a.length).map(t=>t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|');
  if(!pattern)return escape(value);const regex=new RegExp(pattern,'g');let out='',last=0;
  for(const match of String(value).matchAll(regex)){
   const i=terms.findIndex(t=>t.term===match[0]);out+=escape(value.slice(last,match.index))+`<button type="button" class="term-link" data-term="${i}" aria-label="解释术语：${escape(match[0])}">${escape(match[0])}</button>`;last=match.index+match[0].length;
  }return out+escape(value.slice(last));
 }
 const paras=arr=>arr.map(p=>`<p>${prose(p)}</p>`).join('');
 const cs=l.caseStudy;
 const caseStart=`<div class="case-start"><div class="unit-eyebrow">本章跟随案例</div><h3>${escape(l.walkthrough.title)}</h3><p>${prose(l.walkthrough.setup)}</p><div class="case-deliverable"><strong>最后留下什么</strong><span>${escape(cs.artifact)}</span></div><details class="prediction"><summary>先写一句预测（可选）</summary><label for="guess">${prose(cs.predict)}</label><textarea id="guess" class="short-answer" placeholder="写一句预测和理由，读完案例后回来比较。">${escape(data.guess||'')}</textarea></details><nav class="case-path" aria-label="本章案例步骤">${l.walkthrough.steps.map((step,j)=>`<button type="button" data-case-jump="${cs.placements[j]}" data-case-step="${j+1}"><span>步骤 ${j+1} · ${escape(l.sections[cs.placements[j]-1].title)}</span><small>${escape(step)}</small></button>`).join('')}</nav></div><details class="preparation"><summary>准备与跟学方法</summary><p>${prose(c.learningProject.prepare)}</p><p>往下读每节的例子与解释，案例步骤就在对应讲解处。最后换条件检验理解，再自己完成实践，留下“${escape(cs.artifact)}”。</p>${l.code?`<button type="button" data-case-jump="${n+2}" data-case-target="practice">先看本章运行起点与预期输出</button>`:''}</details>`;
 const caseRecall=()=>`<details class="case-recall"><summary>回看本章案例：${escape(l.walkthrough.title)}</summary><p>${prose(l.walkthrough.setup)}</p><p>起点预测：${prose(cs.predict)}</p><button type="button" data-case-jump="0">回到起点与我的预测</button></details>`;
 const checkpoints=i=>cs.placements.flatMap((unit,j)=>unit===i+1?[`<div class="case-checkpoint"><div class="checkpoint-number" aria-hidden="true">${j+1}</div><div><div class="unit-eyebrow">沿用本章案例 · 步骤 ${j+1} / 3</div><h3 id="case-step-${j+1}" tabindex="-1">${escape(l.walkthrough.title)}</h3><p>${prose(l.walkthrough.steps[j])}</p><p class="checkpoint-link">${j<2?`接着在讲解 ${cs.placements[j+1]} 看步骤 ${j+2}：${escape(l.sections[cs.placements[j+1]-1].title)}`:'三个步骤完成后，到“案例完整对照”核对结果与边界。'}</p></div></div>`]:[]).join('');
 const table=s=>s.table?`<div class="table-wrap"><table><caption>${escape(s.table.caption)}</caption><thead><tr>${s.table.headers.map(h=>`<th scope="col">${escape(h)}</th>`).join('')}</tr></thead><tbody>${s.table.rows.map(r=>`<tr>${r.map(v=>`<td>${escape(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'';
 const deepTypes=new Set(['论文','经典论文','研究议程','研究数据','实验','版本说明']);
 const linked=l.refs.map(r=>({ref:sources.find(s=>s.id===r.id),section:r.section})).filter(r=>r.ref);
 let core=linked.filter(r=>!deepTypes.has(r.ref.type)),deep=linked.filter(r=>deepTypes.has(r.ref.type));if(!core.length){core=deep.slice(0,1);deep=deep.slice(1);}
 $('#content').innerHTML=`<div class="workspace lesson-workspace">${outline(c,l.id)}
 <article class="reader tutorial-reader">
 <header id="reader-top"><div class="breadcrumb"><a href="#/">课程</a><span>／</span><a href="#/course/${c.id}">${escape(c.title)}</a><span>／ 第${l.number}章</span></div><div class="edition">教材阅读版 · 2026.10.05</div><h1>${escape(l.title)}</h1><p class="lesson-goal">${escape(l.goal)}</p><div class="meta"><span>${escape(l.module)}</span><span>${l.minutes} 分钟，含阅读与实践</span><span>资料核对 ${c.checkedAt}</span></div></header>
 <div class="reader-controls"><div class="control-row"><div class="mode-switch" role="group" aria-label="阅读方式"><button data-mode="guided">分节学习</button><button data-mode="full">连续阅读</button></div><div class="reader-utilities"><button id="show-terms">术语</button><button id="open-notes">笔记</button></div></div><nav class="stage-nav" aria-label="本章学习阶段"><button data-stage-jump="0">01 情境</button><button data-stage-jump="1">02 例子与讲解</button><button data-stage-jump="${n+1}">03 验证理解</button><button data-stage-jump="${refsUnit}">04 资料</button></nav></div>
 <div class="unit-status"><span id="unit-location"></span><button id="resume-reading" class="text-button" ${data.unit>0?'':'hidden'}>回到上次阅读</button></div><details class="chapter-toc"><summary>展开本章目录 · ${n} 节讲解与实践</summary><nav aria-label="本章学习路径">${units.map((u,i)=>`<button data-jump="${u.target}" data-unit-jump="${i}"><span>${i===0?'○':i<=n?String(i).padStart(2,'0'):'·'}</span>${escape(u.title)}</button>`).join('')}</nav></details><div class="unit-track" aria-hidden="true"><i></i></div>
 <div class="unit-panels">
 <section class="learning-unit lesson-copy" data-unit="0"><div class="unit-eyebrow">01 / 从情境开始</div><h2 id="guide" tabindex="-1">${escape(l.guide.question)}</h2>${caseStart}<details class="concept-intro"><summary>本章和前后知识怎样衔接</summary>${l.orientation?`<p class="chapter-orientation">${prose(l.orientation.intro)}</p>`:''}${paras(l.body)}</details><div class="outcome"><h3>学完后，你应该能做到</h3><p>${escape(l.criteria)}</p></div><details class="term-preview"><summary>本章术语 · ${terms.length} 个</summary><dl>${terms.map(t=>`<dt>${escape(t.term)}</dt><dd>${escape(t.definition)}</dd>`).join('')}</dl></details><p class="reading-plan">正文中带点状下划线的术语可点击查看解释。例子中的条件先保持不变，再看后面的解释；读完后用换条件的小题检验理解。</p>${l.number>1?`<p class="reading-plan">需要回顾？<a href="${path(c.id,l.number-1)}">上一章：${escape(c.lessons[l.number-2].title)}</a></p>`:`<p class="reading-plan">前置知识：${escape(c.prerequisites)}</p>`}${c.history&&l.number<=4?'<details class="history-note"><summary>此前金融学习的位置</summary><p>本课程沿用此前大纲与学习摘要。旧教学位置为第4章；本页练习和完成状态由你记录。</p></details>':''}</section>
 <div class="full-lecture">${l.sections.map((s,i)=>`<section class="learning-unit teaching-section lesson-copy" data-unit="${i+1}"><div class="unit-eyebrow">02 / 讲解 ${i+1} / ${n}</div><h2 id="teaching-${i}" tabindex="-1">${escape(s.title)}</h2><div class="section-example"><h3>先用例子理解</h3>${paras(s.paragraphs.slice(0,1))}</div><h3 class="explanation-heading">把原理讲清楚</h3>${paras(s.paragraphs.slice(1))}${s.formula?`<div class="formula"><strong>${escape(s.formula.expression)}</strong><p>${escape(s.formula.note)}</p></div>`:''}${(s.figures||[]).map(f=>window.LearningFigures.render(f)).join('')}${table(s)}${s.explorer?window.LearningExplorers.render(s.explorer):''}${checkpoints(i)}<div class="key-point"><span>记住这一点</span><p>${prose(s.keyPoint)}</p></div></section>`).join('')}</div>
 <section class="learning-unit lesson-copy" data-unit="${n+1}"><div class="unit-eyebrow">03 / 验证理解</div><h2 id="worked-case" tabindex="-1">换个条件，你还会判断吗？</h2><details class="case-consolidation"><summary>需要时，回看本章案例的完整推导</summary><div class="worked-case"><h3>${escape(l.walkthrough.title)}</h3><p class="reading-plan">把前面分节中的三个步骤连起来，检查结果怎样从起点得到，再比较你最初的预测。</p><p>${prose(l.walkthrough.setup)}</p><ol>${l.walkthrough.steps.map((p,j)=>`<li>${prose(p)}<br><button type="button" class="text-button" data-case-jump="${cs.placements[j]}" data-case-step="${j+1}">回看讲解 ${cs.placements[j]} 的这一步</button></li>`).join('')}</ol><div class="key-point"><span>观察结果</span><p>${prose(l.walkthrough.result)}</p></div></div></details><div class="transfer-example"><div class="unit-eyebrow">换个条件，再用一次</div><h3>${prose(cs.transfer.question)}</h3><label for="transfer-response">先写出推导或判断依据</label><textarea id="transfer-response" class="short-answer" placeholder="列条件、算中间结果，或说明怎样验证…">${escape(data.transferResponse||'')}</textarea><details><summary>查看逐步答案与适用边界</summary><p>${prose(cs.transfer.answer)}</p></details></div><details class="extra-example"><summary>再看一个例子</summary><p>${prose(l.example)}</p></details><div class="pitfall"><h3>注意这个边界</h3><p>${prose(l.pitfall)}</p></div></section>
 <section class="learning-unit lesson-section lab lesson-copy" data-unit="${n+2}"><div class="unit-eyebrow">03 / 动手验证</div><h2 id="practice" tabindex="-1">现在，自己做一次</h2><ol>${l.steps.map(s=>`<li>${prose(s)}</li>`).join('')}</ol>${l.code?`<h3>可运行的起点</h3><p class="reading-plan">保存为 lab.py，需要 Python 3；在该文件所在目录打开终端。Windows可用 py lab.py，macOS可用 python3 lab.py，命令按安装环境调整。</p><p class="lab-before">${prose(l.labGuide.before)}</p><pre><code>${escape(l.code)}</code></pre><div class="lab-observation"><h3>运行后，核对这些输出</h3><p>${prose(l.labGuide.expect)}</p><h3>再只改一个条件</h3><p>${prose(l.labGuide.change)}</p></div>`:''}<div class="outcome"><h3>你应该得到什么</h3><p>${escape(l.criteria)}</p></div><label for="response">写下过程与观察</label><textarea id="response" placeholder="记录结果、推导、验证方式和还不确定的地方…">${escape(data.response||'')}</textarea><details><summary>做过以后，查看参考思路</summary><p>${prose(l.answer)}</p></details></section>
 <section class="learning-unit lesson-copy understanding" data-unit="${review}"><div class="unit-eyebrow">03 / 解释与复盘</div><h2 id="understanding" tabindex="-1">用自己的话解释</h2><p class="check-question">${prose(l.check.question)}</p><label for="self-check">先写下你的回答</label><textarea id="self-check" placeholder="先独立回答，再展开解释对照。这里保存的是你的判断，不会自动评分。">${escape(data.selfCheck||'')}</textarea><details><summary>查看解释，再对照自己的回答</summary><p>${prose(l.check.answer)}</p></details><h3>本章关键结论</h3><ul class="recap">${l.sections.map(s=>`<li>${prose(s.keyPoint)}</li>`).join('')}</ul>${l.orientation?`<div class="chapter-connection"><h3>接下来，把什么问题接着讲清楚？</h3><p>${prose(l.orientation.nextQuestion)}</p><p class="reading-plan">下一步：${escape(l.orientation.nextTitle)}</p></div>`:''}<section class="notes"><label for="note">笔记与下一次想追问的问题</label><textarea id="note" placeholder="哪里还不懂？下次要查哪份资料或做哪个实验？">${escape(data.note||'')}</textarea><small id="save-state">本机自动保存；导出记录可迁移设备。</small></section><div class="completion"><label><input type="checkbox" id="done" ${data.done?'checked':''}>我能解释核心概念，并完成了本章练习</label></div><p class="reading-plan">阅读位置与完成标记分别记录；翻页不会自动标记学会。</p></section>
 <section class="learning-unit lesson-copy" data-unit="${refsUnit}"><div class="unit-eyebrow">04 / 核对资料</div><h2 id="references" tabindex="-1">Reference 与阅读路径</h2><p>先读下列核心材料的指定部分，核对本章概念和做法。讲义为本站独立编写，原资料保留作者、版本与适用范围。</p><h3>核心阅读</h3><div class="refs">${core.map(r=>refCard(r.ref,r.section)).join('')}</div>${deep.length?`<details class="deep-reading"><summary>进阶与研究阅读 · ${deep.length} 份</summary><p class="reading-plan">在完成核心练习后，再阅读论文、大型实验、版本说明或数据集。研究结论的适用条件需要单独检查。</p><div class="refs">${deep.map(r=>refCard(r.ref,r.section)).join('')}</div></details>`:''}<div class="lesson-nav">${l.number>1?`<a class="button" href="${path(c.id,l.number-1)}">上一章</a>`:'<a class="button" href="#/">课程首页</a>'}${l.number<c.lessons.length?`<a class="button primary" href="${path(c.id,l.number+1)}">下一章节</a>`:`<a class="button primary" href="#/course/${c.id}">课程总览</a>`}</div></section>
 </div>
 <nav class="unit-nav" aria-label="本章分节翻页"><button id="unit-prev">上一步</button><span id="unit-next-label"></span><button id="unit-next" class="primary">继续</button></nav>
 <div class="reader-bottom"><button id="copy-context">复制本章提问上下文</button><button id="print">打印本章</button><span>进度与笔记保存在当前浏览器 · <button id="export-inline" class="text-button">导出备份</button></span></div>
 </article>

 </div><dialog id="term-dialog" aria-labelledby="term-title"><div class="dialog-top"><h2 id="term-title">本章术语</h2><button id="close-terms" aria-label="关闭术语解释">关闭</button></div><p class="reading-plan">这些定义用于本章入门理解；具体软件和财务口径仍以对应资料为准。</p><dl>${terms.map((t,i)=>`<div id="term-${i}" tabindex="-1"><dt>${escape(t.term)}</dt><dd>${escape(t.definition)}</dd></div>`).join('')}</dl></dialog>`;
 const panels=[...document.querySelectorAll('.learning-unit')];
 function write(patch={}){const previous=state.lessons[l.id]||{};state.lessons[l.id]={...previous,note:$('#note').value,guess:$('#guess').value,transferResponse:$('#transfer-response').value,response:$('#response').value,selfCheck:$('#self-check').value,done:$('#done').checked,unit:current,...patch,updatedAt:Date.now()};if(save())$('#save-state').textContent='已保存到本机 · '+new Date().toLocaleTimeString();}
 function display(){
  document.querySelector('.tutorial-reader').dataset.mode=mode;panels.forEach((el,i)=>el.hidden=mode==='guided'&&i!==current);
  document.querySelectorAll('button[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));
  document.querySelectorAll('[data-unit-jump]').forEach(b=>{const active=Number(b.dataset.unitJump)===current;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});
  document.querySelectorAll('[data-stage-jump]').forEach(b=>{const stage=current===0?0:current<=n?1:current<refsUnit?n+1:refsUnit;b.setAttribute('aria-current',Number(b.dataset.stageJump)===stage?'step':'false');});
  $('#unit-location').textContent=`${mode==='guided'?'当前':'上次阅读'} ${current+1} / ${total} · ${current===0?'导读':current<=n?'讲解 '+current+'/'+n:units[current].title.split('：')[0]}`;
  $('.unit-track i').style.width=((current+1)/total*100)+'%';
  $('#unit-prev').disabled=current===0;$('#unit-next').disabled=current===refsUnit;$('#unit-next').textContent=current===refsUnit?'本章阅读结束':'继续';$('#unit-next-label').textContent=current<refsUnit?'接下来：'+units[current+1].title:'可以复习本章，或进入下一章';
 }
 function go(unit,focus=true){window.LearningExplorers.stopAll();current=Math.max(0,Math.min(refsUnit,unit));display();write();if(focus){const target=document.getElementById(units[current].target);target?.scrollIntoView({block:'start',behavior:'instant'});target?.focus({preventScroll:true});}}
 document.querySelectorAll('[data-unit-jump]').forEach(b=>b.onclick=()=>{go(Number(b.dataset.unitJump));$('.chapter-toc').open=false;});
 document.querySelectorAll('[data-case-jump]').forEach(b=>b.onclick=()=>{go(Number(b.dataset.caseJump),false);const target=b.dataset.caseStep?document.getElementById('case-step-'+b.dataset.caseStep):document.getElementById(b.dataset.caseTarget||'guide');target?.scrollIntoView({block:'start',behavior:'instant'});target?.focus({preventScroll:true});});
 document.querySelectorAll('[data-stage-jump]').forEach(b=>b.onclick=()=>go(Number(b.dataset.stageJump)));
 const resumeUnit=current;$('#resume-reading').onclick=()=>go(resumeUnit);
 $('#unit-prev').onclick=()=>go(current-1);$('#unit-next').onclick=()=>go(current+1);
 document.querySelectorAll('button[data-mode]').forEach(b=>b.onclick=()=>{window.LearningExplorers.stopAll();mode=b.dataset.mode;try{localStorage.setItem('pt-learning.reading.v2',mode)}catch{}display();document.getElementById(units[current].target)?.scrollIntoView({block:'start',behavior:'instant'});});
 $('#open-notes').onclick=()=>{go(review,false);$('#note').scrollIntoView({block:'center',behavior:'instant'});$('#note').focus({preventScroll:true});};
 const dialog=$('#term-dialog');function showTerms(index){dialog.showModal();if(Number.isInteger(index)){const target=document.getElementById('term-'+index);target?.scrollIntoView({block:'center'});target?.focus({preventScroll:true});}}
 $('#show-terms').onclick=()=>showTerms();$('#close-terms').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}};
 document.querySelectorAll('[data-term]').forEach(b=>b.onclick=()=>showTerms(Number(b.dataset.term)));
 $('#guess').oninput=()=>write();$('#transfer-response').oninput=()=>write();$('#note').oninput=()=>write();$('#response').oninput=()=>write();$('#self-check').oninput=()=>write();
 $('#done').onchange=()=>{write();const old=$('.outline');old.outerHTML=outline(c,l.id);toast($('#done').checked?'本章已完成。':'已取消完成标记。');};
 $('#export-inline').onclick=()=>$('#export').click();
 $('#print').onclick=()=>{const details=[...document.querySelectorAll('details')],opens=details.map(d=>d.open),hidden=panels.map(p=>p.hidden);details.forEach(d=>d.open=true);panels.forEach(p=>p.hidden=false);window.LearningFigures.redraw();window.print();details.forEach((d,i)=>d.open=opens[i]);panels.forEach((p,i)=>p.hidden=hidden[i]);};
 $('#copy-context').onclick=async()=>{const value=`我在 Self Learning 学习《${c.title}》第 ${l.number} 章：${l.title}。\n目标：${l.goal}\n${textOf(l)}\n我的起点预测：${$('#guess').value}\n我的换条件回答：${$('#transfer-response').value}\n我的练习记录：${$('#response').value}\n互动实验当前参数与结果：${[...document.querySelectorAll('[data-explorer]')].map(el=>el.querySelector('h3').textContent+'；'+[...el.querySelectorAll('[data-field]')].map(input=>input.getAttribute('aria-label')+'='+ (input.type==='checkbox'?input.checked:input.value)).join('，')+'；'+el.querySelector('.explorer-output').innerText).join('\n')}\n我的自检回答：${$('#self-check').value}\n我的问题：${$('#note').value}\nReference：\n${l.refs.map(r=>{const s=sources.find(s=>s.id===r.id);return s?.title+'：'+s?.url+'；本章阅读：'+r.section}).join('\n')}\n请针对本章解释我的问题，先直观讲解，再用例子检验理解；不要提前进入下一章。`;try{await navigator.clipboard.writeText(value);toast('已复制，可以贴到 ChatGPT 继续追问。')}catch{const area=document.createElement('textarea');area.value=value;document.body.append(area);area.select();let ok=false;try{ok=document.execCommand('copy')}catch{}area.remove();toast(ok?'已复制本章上下文。':'无法自动复制，请手动复制正文与笔记。');}};
 // Track actual continuous reading only after a user scroll, so opening at the
 // chapter start never erases a previous reading position.
 let userScrolled=false,readingFrame=0;
 const markScroll=()=>{userScrolled=true;};
 const scrollKey=e=>{if(['PageDown','PageUp','ArrowDown','ArrowUp',' '].includes(e.key)&&!e.target.matches('input,textarea,select,button'))markScroll();};
 const trackScroll=()=>{if(mode!=='full'||!userScrolled||readingFrame)return;readingFrame=requestAnimationFrame(()=>{readingFrame=0;const visible=panels.filter(p=>p.getBoundingClientRect().top<=150);const unit=visible.length?panels.indexOf(visible.at(-1)):0;if(unit!==current){current=unit;display();write();}});};
 addEventListener('wheel',markScroll,{passive:true});addEventListener('touchmove',markScroll,{passive:true});addEventListener('keydown',scrollKey);addEventListener('scroll',trackScroll,{passive:true});
 readingCleanup=()=>{removeEventListener('wheel',markScroll);removeEventListener('touchmove',markScroll);removeEventListener('keydown',scrollKey);removeEventListener('scroll',trackScroll);cancelAnimationFrame(readingFrame);};
 window.LearningExplorers.bind($('.reader'));window.LearningFigures.bind($('.reader'));display();revealChapter();
}

function references(){document.title='参考资料 · Self Learning';$('#content').innerHTML=`<a href="#/">全部课程</a><div class="intro"><div><div class="kicker">REFERENCE DESK / ${sources.length} 份资料</div><h1>知道来源，也知道适用范围。</h1><p>${escape(manifest.policy)}</p></div></div><div class="toolbar"><input class="search" id="ref-search" aria-label="搜索参考资料" placeholder="搜索作者、资料名、主题…"><select id="ref-course" aria-label="按课程筛选"><option value="">全部课程</option>${manifest.courses.map(c=>`<option value="${c.id}">${escape(c.title)}</option>`).join('')}</select><select id="ref-type" aria-label="按类型筛选"><option value="">全部类型</option>${[...new Set(sources.map(s=>s.type))].map(t=>`<option>${escape(t)}</option>`).join('')}</select></div><p class="reading-plan">核对日期表示实际查阅日期，不是文章发布日期。旧材料明确标为经典基础；活文档会变化，本页不会自动伪造更新日期。</p><div id="ref-results" class="reference-grid"></div>`;
 let draw=0;async function renderRefs(){const id=++draw,q=$('#ref-search').value.trim().toLowerCase(),cid=$('#ref-course').value,kind=$('#ref-type').value;let allowed=null;if(cid){const c=await getCourse(cid);allowed=new Set(c.lessons.flatMap(l=>l.refs.map(r=>r.id)));}if(id!==draw||!$('#ref-results'))return;const list=sources.filter(s=>(!allowed||allowed.has(s.id))&&(!kind||s.type===kind)&&(!q||[s.title,s.author,s.read,s.version,s.type].join(' ').toLowerCase().includes(q)));$('#ref-results').innerHTML=list.length?list.map(s=>refCard(s)).join(''):'<p class="no-result">没有匹配资料，试试其他主题。</p>';}
 for(const id of ['#ref-search','#ref-course','#ref-type'])$(id).addEventListener('input',()=>renderRefs().catch(e=>toast(e.message)));renderRefs();
}
async function route(){readingCleanup();window.LearningExplorers.stopAll();window.LearningFigures.clear();if(!manifest)return;const token=++generation;try{const parts=location.hash.replace(/^#\/?/,'').split('/');if(parts[0]==='references')references();else if(parts[0]==='course'){const c=await getCourse(parts[1]);if(token!==generation)return;if(parts[2]){const l=c.lessons.find(l=>String(l.number).padStart(2,'0')===parts[2]);if(!l)throw new Error('未找到这个章节');lesson(c,l)}else overview(c);}else home();if(token===generation){scrollTo(0,0);$('#content').focus({preventScroll:true});}}catch(e){if(token!==generation)return;$('#content').innerHTML=`<section class="panel"><h1>暂时无法打开课程</h1><p>${escape(e.message)}</p><button id="retry">重试</button> <a href="#/">返回课程首页</a></section>`;$('#retry').onclick=route;}}
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='self-learning-records-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('学习记录已导出，包含进度、练习记录和笔记。');};
$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2_000_000)throw new Error('文件超过 2 MB 限制。');const data=JSON.parse(await file.text());if(data.version!==1||!data.lessons||typeof data.lessons!=='object'||Array.isArray(data.lessons))throw new Error('不是有效的 Self Learning 记录。');const all=await Promise.all(manifest.courses.map(c=>getCourse(c.id))),ids=new Set(all.flatMap(c=>c.lessons.map(l=>l.id))),incoming={};let count=0;for(const [id,v] of Object.entries(data.lessons)){if(!ids.has(id))throw new Error('含未知章节：'+id);if(!v||typeof v!=='object'||Array.isArray(v)||typeof v.done!=='boolean'||typeof v.note!=='string'||typeof v.response!=='string'||!Number.isFinite(v.updatedAt)||v.updatedAt<0||v.note.length>50000||v.response.length>50000)throw new Error('章节记录格式不正确。');const lesson=all.flatMap(c=>c.lessons).find(l=>l.id===id);for(const field of ['guess','transferResponse'])if(v[field]!==undefined&&(typeof v[field]!=='string'||v[field].length>50000))throw new Error('案例回答格式不正确。');if(v.selfCheck!==undefined&&(typeof v.selfCheck!=='string'||v.selfCheck.length>50000))throw new Error('自检记录格式不正确。');if(v.unit!==undefined&&(!Number.isInteger(v.unit)||v.unit<0||v.unit>lesson.sections.length+4))throw new Error('分节位置不正确。');incoming[id]={done:v.done,note:v.note,response:v.response,updatedAt:v.updatedAt,...(v.selfCheck!==undefined?{selfCheck:v.selfCheck}:{}),...(v.guess!==undefined?{guess:v.guess}:{}),...(v.transferResponse!==undefined?{transferResponse:v.transferResponse}:{}),...(v.unit!==undefined?{unit:v.unit}:{})};}let last=null;if(data.last){const c=all.find(c=>c.id===data.last.courseId);if(!c?.lessons.some(l=>l.id===data.last.lessonId))throw new Error('学习位置无效。');last={courseId:c.id,lessonId:data.last.lessonId};}const merged={...state.lessons};for(const [id,v] of Object.entries(incoming))if(!merged[id]||v.updatedAt>=(merged[id].updatedAt||0)){merged[id]=v;count++;}const old=state;state={version:1,lessons:merged,last:last||state.last};if(!save()){state=old;throw new Error('没有足够空间保存导入记录。');}const destination=last?path(last.courseId,Number(last.lessonId.split('-').pop())):location.hash;if(destination!==location.hash)location.hash=destination;else await route();toast(`已合并 ${count} 章记录；同章保留较新的记录。`);}catch(err){toast('导入失败：'+err.message);}finally{e.target.value='';}};
addEventListener('pagehide',()=>window.LearningExplorers.stopAll());document.addEventListener('visibilitychange',()=>{if(document.hidden)window.LearningExplorers.stopAll();});addEventListener('hashchange',route);addEventListener('storage',e=>{if(e.key===KEY){try{const next=JSON.parse(e.newValue);if(next?.version===1){state=next;route();}}catch{}}});
Promise.all([getJSON('manifest.json'),getJSON('sources.json')]).then(([m,r])=>{manifest=m;sources=r;route();}).catch(e=>{$('#content').innerHTML=`<section class="panel"><h1>课程资料未载入</h1><p>${escape(e.message)}</p><button onclick="location.reload()">重新载入</button></section>`;});
})();
