(() => {
'use strict';
const KEY='pt-learning.v1', THEME='pt-learning.theme';
const $=s=>document.querySelector(s), escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let manifest, sources=[], cache=new Map(), generation=0, timer;
const empty=()=>({version:1,lessons:{},last:null});
let state=empty();
try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.version===1&&x.lessons&&typeof x.lessons==='object'&&!Array.isArray(x.lessons)){state=x;}}catch{}
function toast(msg){$('#status').textContent=msg;clearTimeout(timer);timer=setTimeout(()=>$('#status').textContent='',4500);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{toast('未能保存到本机，请导出学习记录，避免关闭页面后丢失。');return false;}}
function theme(t){document.documentElement.dataset.theme=t;try{localStorage.setItem(THEME,t);}catch{}}
let t;try{t=localStorage.getItem(THEME)}catch{}theme(t|| (matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));
$('#theme').onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark');
addEventListener('message',e=>{if(e.origin===location.origin&&e.data?.type==='pt-universe-theme'&&['light','dark'].includes(e.data.theme))theme(e.data.theme)});
async function getJSON(file){const res=await fetch('data/'+file+'?v=20261002-expanded2');if(!res.ok)throw new Error('课程载入失败（HTTP '+res.status+'）');return res.json()}
async function getCourse(id){if(!cache.has(id)){const c=manifest.courses.find(c=>c.id===id);if(!c)throw new Error('未找到课程');cache.set(id,await getJSON(c.file));}return cache.get(id)}
const totalDone=c=>Object.keys(state.lessons).filter(id=>id.startsWith(c.id+'-')&&state.lessons[id]?.done===true).length;
const resume=c=>{const last=state.last;if(last?.courseId===c.id&&last.lessonId.startsWith(c.id+'-')){const n=Number(last.lessonId.split('-').pop());if(n>=1&&n<=c.chapterCount)return n;}const n=Array.from({length:c.chapterCount},(_,i)=>i+1).find(n=>!state.lessons[c.id+'-'+String(n).padStart(2,'0')]?.done);return c.history?.resume&&totalDone(c)===0?c.history.resume:n||1;};
const path=(id,n)=>`#/course/${id}/${String(n).padStart(2,'0')}`;
const textOf=l=>["概念导读",...l.body,...(l.sections||[]).flatMap(s=>[s.title,...s.paragraphs,...(s.table?[s.table.caption,s.table.headers.join(' / '),...s.table.rows.map(r=>r.join(' / '))]:[])]),"逐步推演："+l.walkthrough?.title,l.walkthrough?.setup,...(l.walkthrough?.steps||[]),l.walkthrough?.result,"补充例子："+l.example,"误区："+l.pitfall,"实操练习",...l.steps,"检查标准："+l.criteria,"参考思路："+l.answer,...(l.code?["可运行起点",l.code]:[]),"理解自检："+l.check?.question,"自检解释："+l.check?.answer].filter(Boolean).join('\n\n');
const meta=c=>`${c.chapterCount} 章 · 约 ${Math.round(c.minutes/60)} 小时（含参考阅读与练习）`;
function home(){
 document.title='Self Learning · PT Universe';const done=manifest.courses.reduce((a,c)=>a+totalDone(c),0),total=manifest.courses.reduce((a,c)=>a+c.chapterCount,0), last=state.last, c=last&&manifest.courses.find(c=>c.id===last.courseId);
 $('#content').innerHTML=`<div class="intro"><div><div class="kicker">SELF LEARNING / 五条学习路线</div><h1>把知识补全，再用项目验证。</h1><p>每章提供分节讲解、机制与条件、逐步案例、理解自检和实操练习；先跟着正文推演，再阅读对应资料。每门课都可独立学习，也可以按你的项目需要交叉阅读。</p></div><div class="summary"><div><strong>05</strong><span>课程</span></div><div><strong>${total}</strong><span>章节</span></div><div><strong>${done}</strong><span>已完成</span></div></div></div>
 ${c?`<div class="resume"><div><strong>继续：${escape(c.title)} · 第 ${resume(c)} 章</strong><p>学习位置已保存；完成状态由你手动标记。</p></div><a class="button primary" href="${path(c.id,resume(c))}">继续学习</a></div>`:''}
 <div class="courses">${manifest.courses.map(c=>`<article class="course-card" style="--course:${c.color}"><div class="meta"><span class="tag">${escape(c.english)}</span></div><h2>${escape(c.title)}</h2><p class="desc">${escape(c.description)}</p><div class="meta">${meta(c)}</div><div class="track"><i style="width:${totalDone(c)/c.chapterCount*100}%"></i></div><small>${totalDone(c)} / ${c.chapterCount} 章已完成${c.history?' · 历史教学至第 4 章':''}</small><div class="bottom"><a class="button primary" href="${path(c.id,resume(c))}">${totalDone(c)||state.last?.courseId===c.id?'继续学习':c.history?'接续第 4 章':'开始第 1 章'}</a><a href="#/course/${c.id}">完整目录</a></div></article>`).join('')}</div>
 <div class="method"><section class="panel"><h2>每章怎么学</h2><ol><li>先读分节讲义，跟着推导与案例写出每一步，再用自己的话解释。</li><li>阅读本章 reference 的指定部分；基础必读在前，研究与深入实验在后。</li><li>按步骤做练习，核对检查标准，再看参考思路。</li><li>写下问题与答案，完成后标记本章，进入下一章。</li></ol><p class="reading-plan">普通章建议 60–75 分钟：分节讲义与案例约 20–30 分钟，参考阅读约 15–20 分钟，自检、练习与复盘约 20–30 分钟。金融复杂章可分两次，毕业项目分多次完成；所示时间是规划值。</p></section><section class="panel"><h2>资料与历史</h2><p>基础可以来自经典教材；软件、安全和交互细节结合维护中的文档。前沿论文是进阶阅读，不替代基本概念和实践验证。</p><p>金融课沿用此前 16 章顺序，库存与 SBC 保留在第 3 章。前四章依据历史摘要重整，历史教学位置与本页完成记录分开。</p><a class="button" href="#/references">浏览 ${sources.length} 份参考资料</a><p><small>进度、练习回答和笔记自动保存在当前浏览器；用顶部导出／导入，在 Win、Mac 或其他设备间迁移。本站不自动同步这些记录。</small></p></section></div>`;
}
function outline(c,selected){let group='';return `<aside class="outline" aria-label="课程章节"><a href="#/">五门课程</a><h2>${escape(c.title)}</h2><small>${totalDone(c)} / ${c.lessons.length} 章已完成</small><div class="chapters">${c.lessons.map(l=>{const head=group!==l.module?`<div class="module">${escape(l.module)}</div>`:'';group=l.module;return head+`<a class="chapter-link ${selected===l.id?'active':''}" ${selected===l.id?'aria-current="page"':''} href="${path(c.id,l.number)}"><span class="num">${String(l.number).padStart(2,'0')}</span><span>${escape(l.title)}</span>${state.lessons[l.id]?.done?'<span class="check" aria-label="已完成">✓</span>':''}</a>`}).join('')}</div><p><a href="#/course/${c.id}">课程总览与毕业标准</a></p><a href="#/references">资料目录</a></aside>`;}
function overview(c){document.title=c.title+' · Self Learning';$('#content').innerHTML=`<div class="workspace">${outline(c)}<article class="reader"><div class="kicker">${escape(c.english)}</div><h1>${escape(c.title)}</h1><p>${escape(c.description)}</p><div class="callout"><strong>前置知识</strong><p>${escape(c.prerequisites)}</p></div>${c.history?`<div class="callout"><strong>金融课迁移说明</strong><p>${escape(c.history.note)}</p></div>`:''}<a class="button primary" href="${path(c.id,resume({...c,chapterCount:c.lessons.length}))}">从第 ${resume({...c,chapterCount:c.lessons.length})} 章继续</a><h2>路线与目标</h2>${manifest.courses.find(m=>m.id===c.id).modules.map(m=>`<section class="course-overview"><h3>${escape(m)}</h3>${c.lessons.filter(l=>l.module===m).map(l=>`<p><a href="${path(c.id,l.number)}">${String(l.number).padStart(2,'0')} · ${escape(l.title)}</a><br><small>${escape(l.goal)}</small></p>`).join('')}</section>`).join('')}<section class="project"><h2>毕业项目</h2><p>${escape(c.capstone)}</p><h3>验收标准</h3><p>${escape(c.acceptance)}</p></section></article></div>`;}
function refCard(ref,section){return `<div class="ref"><a href="${escape(ref.url)}" target="_blank" rel="noopener noreferrer">${escape(ref.title)}</a><p>${escape(ref.author)}</p><div class="meta"><span class="tag">${escape(ref.type)}</span><span>${escape(ref.version)}</span><span>核对 ${ref.checkedAt}</span></div>${section?`<p class="reading"><strong>本章阅读：</strong>${escape(section)}</p>`:`<p>${escape(ref.read)}</p>`}<p>${escape(ref.caveat)}</p></div>`;}
function lesson(c,l){document.title=l.title+' · '+c.title+' · Self Learning';state.last={courseId:c.id,lessonId:l.id};save();const data=state.lessons[l.id]||{};
 $('#content').innerHTML=`<div class="workspace">${outline(c,l.id)}<article class="reader"><header><div class="kicker">${escape(c.english)} / ${escape(l.module)}</div><h1>${String(l.number).padStart(2,'0')} · ${escape(l.title)}</h1><p>${escape(l.goal)}</p><div class="meta"><span>第 ${l.number} / ${c.lessons.length} 章</span><span>建议 ${l.minutes} 分钟（含参考与练习）</span><span>资料核对 ${c.checkedAt}</span><span>讲解 ${l.textCharacters?.toLocaleString()||textOf(l).length.toLocaleString()} 字符（含案例与解析）</span></div>${l.prerequisite?`<p class="reading-plan">建议先学：<a href="${path(c.id,l.number-1)}">第 ${l.number-1} 章</a></p>`:`<p class="reading-plan">开始前：${escape(c.prerequisites)}</p>`}${c.history&&l.number<=4?'<small>迁移讲义：依据此前金融课程大纲与摘要重整。</small>':''}</header>
 <details class="chapter-toc" ${matchMedia('(min-width:761px)').matches?'open':''}><summary>本章阅读目录</summary><nav aria-label="本章阅读目录">${(l.sections||[]).map((s,i)=>`<button data-jump="teaching-${i}">${i+1}. ${escape(s.title)}</button>`).join('')}<button data-jump="worked-case">逐步推演案例</button><button data-jump="practice">练习与解析</button><button data-jump="understanding">理解自检</button><button data-jump="references">Reference</button></nav></details>
 <section class="lesson-copy" aria-label="概念导读"><h2>先建立直觉</h2>${l.body.map(p=>`<p>${escape(p)}</p>`).join('')}</section>
 <div class="full-lecture">${(l.sections||[]).map((s,i)=>`<section class="teaching-section lesson-copy"><h2 id="teaching-${i}" tabindex="-1">${i+1}. ${escape(s.title)}</h2>${s.paragraphs.map(p=>`<p>${escape(p)}</p>`).join('')}${s.table?`<div class="table-wrap"><table><caption>${escape(s.table.caption)}</caption><thead><tr>${s.table.headers.map(h=>`<th scope="col">${escape(h)}</th>`).join('')}</tr></thead><tbody>${s.table.rows.map(r=>`<tr>${r.map(v=>`<td>${escape(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:''}</section>`).join('')}</div>
 <section class="lesson-section worked-case"><h2 id="worked-case" tabindex="-1">逐步推演：${escape(l.walkthrough?.title||l.title)}</h2><p>${escape(l.walkthrough?.setup)}</p><ol>${(l.walkthrough?.steps||[]).map(p=>`<li>${escape(p)}</li>`).join('')}</ol><div class="callout"><strong>从这个例子得到什么</strong><p>${escape(l.walkthrough?.result)}</p></div></section>
 <section class="lesson-section"><h2>一步步看例子</h2><div class="example">${escape(l.example)}</div><div class="callout"><strong>容易踩的坑</strong><p>${escape(l.pitfall)}</p></div></section>
 <section class="lesson-section lab"><h2 id="practice" tabindex="-1">本章练习</h2><ol>${l.steps.map(s=>`<li>${escape(s)}</li>`).join('')}</ol>${l.code?`<h3>可运行的起点</h3><small>保存为 lab.py，Python 3 运行：Windows 可用 py lab.py；macOS 可用 python3 lab.py。需要安装 Python 3；终端命令按自己的安装环境调整。</small><pre><code>${escape(l.code)}</code></pre>`:''}<p class="criteria"><strong>检查标准：</strong>${escape(l.criteria)}</p><label for="response">练习记录／自己的解释</label><textarea id="response" placeholder="写下结果、计算过程、观察和仍未解决的问题…">${escape(data.response||'')}</textarea><details><summary>做完后查看参考思路</summary><p>${escape(l.answer)}</p></details></section>
 <section class="lesson-section understanding"><h2 id="understanding" tabindex="-1">理解自检</h2><p>${escape(l.check?.question)}</p><details><summary>先回答，再看解释</summary><p>${escape(l.check?.answer)}</p></details></section>
 <section class="lesson-section"><h2 id="references" tabindex="-1">Reference 与阅读路径</h2><p class="reading-plan">按下列顺序读指定部分。讲义是本站独立编写；原材料用于核对与深入学习。论文和大型实验按需深读，先完成本章核心练习。</p><div class="refs">${l.refs.map(r=>{const ref=sources.find(s=>s.id===r.id);return ref?refCard(ref,r.section):''}).join('')}</div></section>
 <section class="lesson-section notes"><label for="note">本章笔记与提问</label><textarea id="note" placeholder="记下你想追问的概念或下一次实验…">${escape(data.note||'')}</textarea><small id="save-state">本机自动保存；导出记录可迁移到其他设备。</small></section>
 <div class="lesson-nav"><button id="copy-context">复制本章提问上下文</button><button id="print">打印本章</button></div>
 <div class="completion"><label><input type="checkbox" id="done" ${data.done?'checked':''}>我能解释核心概念，并完成了本章练习</label></div>
 <nav class="lesson-nav" aria-label="章节翻页">${l.number>1?`<a class="button" href="${path(c.id,l.number-1)}">上一章</a>`:'<a class="button" href="#/">课程首页</a>'}${l.number<c.lessons.length?`<a class="button primary" href="${path(c.id,l.number+1)}">下一章节</a>`:`<a class="button primary" href="#/course/${c.id}">回到课程总览</a>`}</nav></article></div>`;
 if(matchMedia('(max-width:760px)').matches){const list=$('.chapters'),active=$('.chapter-link.active');if(list&&active)list.scrollTop=Math.max(0,active.offsetTop-list.offsetTop-list.clientHeight/2);}
 document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{const target=document.getElementById(b.dataset.jump);target?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'});target?.focus({preventScroll:true});});
 function update(){state.lessons[l.id]={note:$('#note').value,response:$('#response').value,done:$('#done').checked,updatedAt:Date.now()};if(save())$('#save-state').textContent='已保存到本机 · '+new Date().toLocaleTimeString();}
 $('#note').oninput=update;$('#response').oninput=update;$('#done').onchange=()=>{update();const aside=$('.outline');aside.outerHTML=outline(c,l.id);toast($('#done').checked?'本章已完成，可以进入下一章。':'已取消本章完成标记。');};
 $('#print').onclick=()=>{const details=[...document.querySelectorAll('details')];const opens=details.map(d=>d.open);details.forEach(d=>d.open=true);window.print();details.forEach((d,i)=>d.open=opens[i]);};
 $('#copy-context').onclick=async()=>{const value=`我在 Self Learning 学习《${c.title}》第 ${l.number} 章：${l.title}。\n目标：${l.goal}\n${textOf(l)}\n我的练习记录：${$('#response').value}\n我的问题：${$('#note').value}\nReference：\n${l.refs.map(r=>{const s=sources.find(s=>s.id===r.id);return s?.title+'：'+s?.url+'；本章阅读：'+r.section}).join('\n')}\n请针对本章解释我的问题，先直观讲解，再用例子检验理解；不要提前进入下一章。`;try{await navigator.clipboard.writeText(value);toast('已复制，可以贴到 ChatGPT 继续追问。')}catch{const area=document.createElement('textarea');area.value=value;document.body.append(area);area.select();let ok=false;try{ok=document.execCommand('copy')}catch{}area.remove();toast(ok?'已复制本章上下文。':'无法自动复制，请在笔记中写下问题后手动复制正文。');}};
}
function references(){document.title='参考资料 · Self Learning';$('#content').innerHTML=`<a href="#/">五门课程</a><div class="intro"><div><div class="kicker">REFERENCE DESK / ${sources.length} 份资料</div><h1>知道来源，也知道适用范围。</h1><p>${escape(manifest.policy)}</p></div></div><div class="toolbar"><input class="search" id="ref-search" aria-label="搜索参考资料" placeholder="搜索作者、资料名、主题…"><select id="ref-course" aria-label="按课程筛选"><option value="">全部课程</option>${manifest.courses.map(c=>`<option value="${c.id}">${escape(c.title)}</option>`).join('')}</select><select id="ref-type" aria-label="按类型筛选"><option value="">全部类型</option>${[...new Set(sources.map(s=>s.type))].map(t=>`<option>${escape(t)}</option>`).join('')}</select></div><p class="reading-plan">核对日期表示实际查阅日期，不是文章发布日期。旧材料明确标为经典基础；活文档会变化，本页不会自动伪造更新日期。</p><div id="ref-results" class="reference-grid"></div>`;
 let draw=0;async function renderRefs(){const id=++draw,q=$('#ref-search').value.trim().toLowerCase(),cid=$('#ref-course').value,kind=$('#ref-type').value;let allowed=null;if(cid){const c=await getCourse(cid);allowed=new Set(c.lessons.flatMap(l=>l.refs.map(r=>r.id)));}if(id!==draw||!$('#ref-results'))return;const list=sources.filter(s=>(!allowed||allowed.has(s.id))&&(!kind||s.type===kind)&&(!q||[s.title,s.author,s.read,s.version,s.type].join(' ').toLowerCase().includes(q)));$('#ref-results').innerHTML=list.length?list.map(s=>refCard(s)).join(''):'<p class="no-result">没有匹配资料，试试其他主题。</p>';}
 for(const id of ['#ref-search','#ref-course','#ref-type'])$(id).addEventListener('input',()=>renderRefs().catch(e=>toast(e.message)));renderRefs();
}
async function route(){if(!manifest)return;const token=++generation;try{const parts=location.hash.replace(/^#\/?/,'').split('/');if(parts[0]==='references')references();else if(parts[0]==='course'){const c=await getCourse(parts[1]);if(token!==generation)return;if(parts[2]){const l=c.lessons.find(l=>String(l.number).padStart(2,'0')===parts[2]);if(!l)throw new Error('未找到这个章节');lesson(c,l)}else overview(c);}else home();if(token===generation){scrollTo(0,0);$('#content').focus({preventScroll:true});}}catch(e){if(token!==generation)return;$('#content').innerHTML=`<section class="panel"><h1>暂时无法打开课程</h1><p>${escape(e.message)}</p><button id="retry">重试</button> <a href="#/">返回课程首页</a></section>`;$('#retry').onclick=route;}}
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='self-learning-records-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('学习记录已导出，包含进度、练习记录和笔记。');};
$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2_000_000)throw new Error('文件超过 2 MB 限制。');const data=JSON.parse(await file.text());if(data.version!==1||!data.lessons||typeof data.lessons!=='object'||Array.isArray(data.lessons))throw new Error('不是有效的 Self Learning 记录。');const all=await Promise.all(manifest.courses.map(c=>getCourse(c.id))),ids=new Set(all.flatMap(c=>c.lessons.map(l=>l.id))),incoming={};let count=0;for(const [id,v] of Object.entries(data.lessons)){if(!ids.has(id))throw new Error('含未知章节：'+id);if(!v||typeof v!=='object'||Array.isArray(v)||typeof v.done!=='boolean'||typeof v.note!=='string'||typeof v.response!=='string'||!Number.isFinite(v.updatedAt)||v.updatedAt<0||v.note.length>50000||v.response.length>50000)throw new Error('章节记录格式不正确。');incoming[id]={done:v.done,note:v.note,response:v.response,updatedAt:v.updatedAt};}let last=null;if(data.last){const c=all.find(c=>c.id===data.last.courseId);if(!c?.lessons.some(l=>l.id===data.last.lessonId))throw new Error('学习位置无效。');last={courseId:c.id,lessonId:data.last.lessonId};}const merged={...state.lessons};for(const [id,v] of Object.entries(incoming))if(!merged[id]||v.updatedAt>=(merged[id].updatedAt||0)){merged[id]=v;count++;}const old=state;state={version:1,lessons:merged,last:last||state.last};if(!save()){state=old;throw new Error('没有足够空间保存导入记录。');}await route();toast(`已合并 ${count} 章记录；同章保留较新的记录。`);}catch(err){toast('导入失败：'+err.message);}finally{e.target.value='';}};
addEventListener('hashchange',route);addEventListener('storage',e=>{if(e.key===KEY){try{const next=JSON.parse(e.newValue);if(next?.version===1){state=next;route();}}catch{}}});
Promise.all([getJSON('manifest.json'),getJSON('sources.json')]).then(([m,r])=>{manifest=m;sources=r;route();}).catch(e=>{$('#content').innerHTML=`<section class="panel"><h1>课程资料未载入</h1><p>${escape(e.message)}</p><button onclick="location.reload()">重新载入</button></section>`;});
})();
