import assert from 'node:assert/strict';import fs from 'node:fs';import {build} from 'esbuild';
const built=await build({entryPoints:['src/content-hub.ts'],bundle:true,format:'esm',platform:'node',write:false});const H=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
const fixture=name=>fs.readFileSync('tests/fixtures/hub-'+name+'.html','utf8');
assert.equal(H.parseTopics(fixture('topics')).length,2);assert.equal(H.parseTopics(fixture('topics'))[0].subject_id,495291);assert.equal(H.parseTopics(fixture('topics'))[0].published_at,null);
const anime=H.parseAnime1(JSON.parse(fs.readFileSync('tests/fixtures/hub-anime1.json','utf8')));assert.equal(anime[0].latest_episode,2);assert.equal(anime[0].status,'ongoing');assert.equal(anime[0].url,'https://anime1.me/?cat=1971');assert.ok(anime[0].search_title.includes('圣女'));assert.equal(H.parseAnime1([[5,'剧场版','劇場版','2025','春','']])[0].latest_episode,null);const novels=H.parseCompletedNovels(fixture('novels'));assert.equal(novels.length,2);assert.ok(novels.every(x=>x.status==='completed'&&x.type==='novel'));assert.ok(novels[0].author);assert.equal(H.normalizeQuery('hd 490   pro'),'hd490 pro');
const assets=H.parseAssets(fixture('assets'));assert.equal(assets.length,2);assert.equal(assets[0].title,'Skyboxes Space');assert.match(assets[0].cover,/^https:\/\/kenney.nl\/media/);assert.equal(assets[0].license,'CC0');
const web=H.parseWebSearch(fixture('search'));assert.equal(web.length,2);assert.ok(web[0].url.includes('sonarworks.com'));assert.ok(web[1].url.includes('unheardlab.com'));assert.ok(!H.relevant({title:'Google Images',url:'https://images.google.com',excerpt:''},'HD490 Pro'));assert.ok(H.relevant(web[1],'HD490 Pro'));assert.equal(H.parseWebSearch(fixture('search').replace(/class="snippet /g,'data-type="web" class="extra snippet ').replace(/title search-snippet-title/g,'extra search-snippet-title title')).length,2,'search parser tolerates class and attribute order changes');
assert.equal(H.resultURL('http://www.bing.com/news/apiclick.aspx?url=https%3A%2F%2Fnews.qq.com%2Fa%3Fx%3D1%26y%3D2'),'https://news.qq.com/a?x=1&y=2');
const duck=H.parseDuckSearch(`<a class='result-link' href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fwww.sennheiser.com%2Fhd-490-pro">HD 490 Pro</a><td class='result-snippet'>Official studio headphones</td>`);assert.equal(duck[0].url,'https://www.sennheiser.com/hd-490-pro');assert.equal(duck[0].excerpt,'Official studio headphones');assert.ok(H.relevant(duck[0],'hd490 pro'));assert.ok(H.relevant({title:'华为刹车踏板断裂',url:'https://news.qq.com/a',excerpt:'测试踩断踏板'},'华为刹车会被踩断'));assert.equal(H.searchTerms('华为刹车会被踩断','claim'),'华为 刹车 踩断');assert.ok(H.searchTerms('社会保险','claim').replace(/ /g,'').includes('社会'));assert.ok(H.searchTerms('会计规则','claim').replace(/ /g,'').includes('会计'));assert.ok(!H.relevant({title:'机场停车',excerpt:'每日优惠',url:'https://www.apple.com/a'},'hd490 pro'));
for(const bad of ['https://127.0.0.1/','https://169.254.169.254/','https://www.apple.com:9000/','https://www.apple.com.evil.com/','http://www.apple.com/','https://user:pass@www.apple.com/','file:///etc/passwd'])assert.throws(()=>H.publicURL(bad));
const para='This is a real source paragraph with enough context for evidence extraction and a source reference.';
const evidence=H.parseEvidence(`<title>Product A</title><script>var x='<p>${para} SCRIPT</p>'</script><nav><p>${para} NAV</p></nav><p>${para}</p><script type="application/ld+json">{"@type":"Product","name":"A","additionalProperty":[{"name":"Weight","value":"250","unitText":"g"}]}</script><table><tr><td>Impedance</td><td>130 Ω</td></tr></table>`,'https://www.sennheiser.com/p');assert.equal(evidence.paragraphs.length,1);assert.equal(evidence.paragraphs[0].text,para);assert.equal(evidence.paragraphs[0].id,'p1');assert.equal(evidence.specs.find(x=>x.name==='Weight').value,'250 g');assert.equal(evidence.status,'unverified');assert.ok(evidence.specs.every(x=>x.source===evidence.url));
const old=[{id:'one',first_seen:'2020-01-01',title:'Old'}];const history=H.mergeHistory([{id:'one',title:'Changed'},{id:'two',title:'New'}],old);assert.equal(history.length,2);assert.equal(history[0].first_seen,'2020-01-01');assert.equal(history[0].title,'Changed');
const map=new Map(),writes=[];let grants=1;const env={PT_UNIVERSE_DATA:{get:async k=>map.get(k)||null,put:async(k,v)=>{writes.push(k);map.set(k,JSON.parse(v));}},DB:{prepare:()=>({bind:()=>({run:async()=>({meta:{changes:grants}})})})}};
const original=globalThis.fetch;let fetches=0;
const route=path=>H.contentHubRoute(new Request('https://test/api/hub/'+path),env);
try{
 globalThis.fetch=async()=>{fetches++;return new Response(JSON.stringify([{weekday:{id:1,cn:'星期一'},items:[{id:1,name:'A',type:2}]}]));};
 let r=await route('calendar');assert.equal(r.body.days[0].items[0].title,'A');assert.equal(fetches,1);await route('calendar');assert.equal(fetches,1,'fresh cache must suppress upstream requests');
 const previous=map.get('hub/calendar');previous.checked_at='2020-01-01T00:00:00Z';globalThis.fetch=async()=>{throw Error('upstream failed')};r=await route('calendar');assert.equal(r.body.stale,true);assert.equal(r.body.checked_at,previous.checked_at,'failed refresh must not claim a new success time');assert.equal(map.get('hub/calendar').stale,false);
 globalThis.fetch=async()=>new Response(null,{status:302,headers:{location:'http://169.254.169.254/'}});r=await route('check/read?url='+encodeURIComponent('https://www.apple.com/p'));assert.equal(r.status,400);assert.match(r.body.error,/不支持/);
 globalThis.fetch=async()=>new Response('large',{headers:{'content-length':'2000001'}});r=await route('check/read?url='+encodeURIComponent('https://www.apple.com/large'));assert.equal(r.status,400);assert.match(r.body.error,/过大/);
 grants=0;r=await route('check/search?q=Product+A');assert.equal(r.status,429);grants=1;
 // A provider outage must neither erase good results nor pin an empty result for an hour.
 globalThis.fetch=async u=>String(u).includes('search.brave.com')?new Response(fixture('search')):new Response('<rss/>');r=await route('check/search?q=hd+490+pro&mode=product');assert.equal(r.body.items.length,2);assert.equal(r.body.search_state,'ready');const searchKey=writes.find(k=>k.startsWith('hub/check-v3/'));const positive=map.get(searchKey);const positiveTime=positive.checked_at;
 globalThis.fetch=async()=>new Response('rate limited',{status:429});r=await route('check/search?q=hd+490+pro&mode=product&refresh=1');assert.equal(r.body.stale,true);assert.equal(r.body.items.length,2);assert.equal(r.body.checked_at,positiveTime);assert.ok(r.body.errors.some(x=>x.includes('429')));assert.equal(map.get(searchKey).items.length,2);
 grants=0;r=await route('check/search?q=hd+490+pro&mode=product&refresh=1');assert.equal(r.status,429,'manual refresh still enforces cooldown');grants=1;
 r=await route('check/search?q=Cold+failure');assert.equal(r.body.search_state,'unavailable');assert.equal(r.body.items.length,0);const emptyKey=writes.at(-1);map.get(emptyKey).checked_at=new Date(Date.now()-31000).toISOString();let retryFetches=0;globalThis.fetch=async()=>{retryFetches++;return new Response('<rss/>');};await route('check/search?q=Cold+failure');assert.ok(retryFetches>=3,'empty failure must retry after 30 seconds instead of an hour');
 // Independent engines can recover while Brave is rate limited.
 globalThis.fetch=async u=>String(u).includes('lite.duckduckgo.com')?new Response(`<a href="https://www.sennheiser.com/hd-490-pro" class="result-link">HD 490 Pro</a><td class="result-snippet">Official reference headphones</td>`):new Response('rate limited',{status:429});r=await route('check/search?q=hd490+pro&mode=product&refresh=1');assert.equal(r.body.items.length,1);assert.equal(r.body.items[0].readable,true);
 map.set('hub/topics',{checked_at:'2020-01-01',items:[{id:'v2ex-1',source:'v2ex',title:'Keep me',first_seen:'2020-01-01'}],sources:{v2ex:{checked_at:'2020-01-01'}}});globalThis.fetch=async u=>{if(String(u).includes('v2ex'))throw Error('source failed');return new Response(fixture('topics'));};r=await route('topics');assert.ok(r.body.items.some(x=>x.id==='v2ex-1'));assert.equal(r.body.sources.v2ex.ok,false);assert.equal(r.body.sources.v2ex.checked_at,'2020-01-01');
 map.set('data/site-updates.json',{generated_at:'2026-10-08',items:[{id:'stable-id',title:'Known manga',url:'https://m.manhuagui.com/comic/61789/',source:'manhuagui',type:'manga',latest:'第1话'}]});map.set('hub/discover-v2',{checked_at:'2020-01-01',items:[{id:'stable-id',url:'https://m.manhuagui.com/comic/61789/',first_seen:'2020-01-01'}]});globalThis.fetch=async()=>new Response(fixture('completed'));r=await route('discover');assert.ok(!r.body.items.some(x=>H.canonicalWorkURL(x.url)==='https://manhuagui.com/comic/61789'),'update-stream works are excluded from discovery');assert.equal(r.body.catalog_only,true);assert.ok(r.body.excluded_updates>0);assert.equal(r.body.items.length,1);
 // A cold failed completed source seeds only previously observed explicit completion rows.
 map.set('hub/discover-v2',{checked_at:new Date().toISOString(),items:[],sources:{completed:{ok:false}}});
 globalThis.fetch=async u=>{if(String(u).includes('raw.githubusercontent'))return new Response(JSON.stringify({snapshot:true,checked_at:'2026-10-08T19:24:00Z',items:[{id:'completed-9',source:'manhuagui-completed',status:'completed',title:'Historical completed work',type:'manga',url:'https://m.manhuagui.com/comic/9/',first_seen:'2026-10-08T19:24:00Z'}]}));throw Error('completion source timeout');};r=await route('discover');const cachedCompleted=r.body.items.find(x=>x.id==='completed-9');assert.ok(cachedCompleted);assert.equal(cachedCompleted.cached_source_at,'2026-10-08T19:24:00Z');assert.equal(cachedCompleted.first_seen,'2026-10-08T19:24:00Z');assert.equal(r.body.sources.completed.ok,false);assert.equal(r.body.sources.completed.fallback,'verified_snapshot');assert.equal(r.body.sources.completed.checked_at,'2026-10-08T19:24:00Z');
 globalThis.fetch=async u=>String(u).includes('brave')?new Response(fixture('search')):new Response('<rss/>');r=await route('check/search?q=HD490+Pro&mode=product');assert.ok(r.body.items.length);assert.ok(r.body.items.every(x=>x.status==='unverified'));assert.ok(r.body.items.some(x=>x.readable));assert.ok(!r.body.items.some(x=>x.title==='Google Images'));
 r=await H.contentHubRoute(new Request('https://test/api/hub/assets',{method:'POST'}),env);assert.equal(r.status,405);r=await route('does-not-exist');assert.equal(r.status,404);assert.equal(await H.contentHubRoute(new Request('https://test/api/other'),env),null);
}finally{globalThis.fetch=original;}
console.log('Content hub passed: real source fixtures, SSRF/redirect/size limits, rate limit, cache failure timestamps, partial history, completion provenance, unverified evidence');
