import assert from 'node:assert/strict';import fs from 'node:fs';import {build} from 'esbuild';
const built=await build({entryPoints:['src/content-hub.ts'],bundle:true,format:'esm',platform:'node',write:false});const H=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
const fixture=name=>fs.readFileSync('tests/fixtures/hub-'+name+'.html','utf8');
assert.equal(H.parseTopics(fixture('topics')).length,2);assert.equal(H.parseTopics(fixture('topics'))[0].subject_id,495291);assert.equal(H.parseTopics(fixture('topics'))[0].published_at,null);
const assets=H.parseAssets(fixture('assets'));assert.equal(assets.length,2);assert.equal(assets[0].title,'Skyboxes Space');assert.match(assets[0].cover,/^https:\/\/kenney.nl\/media/);assert.equal(assets[0].license,'CC0');
const web=H.parseWebSearch(fixture('search'));assert.equal(web.length,2);assert.ok(web[0].url.includes('sonarworks.com'));assert.ok(web[1].url.includes('unheardlab.com'));assert.ok(!H.relevant({title:'Google Images',url:'https://images.google.com',excerpt:''},'HD490 Pro'));assert.ok(H.relevant(web[1],'HD490 Pro'));
for(const bad of ['https://127.0.0.1/','https://169.254.169.254/','https://www.apple.com:9000/','https://www.apple.com.evil.com/','http://www.apple.com/','https://user:pass@www.apple.com/','file:///etc/passwd'])assert.throws(()=>H.publicURL(bad));
const para='This is a real source paragraph with enough context for evidence extraction and a source reference.';
const evidence=H.parseEvidence(`<title>Product A</title><script>var x='<p>${para} SCRIPT</p>'</script><nav><p>${para} NAV</p></nav><p>${para}</p><script type="application/ld+json">{"@type":"Product","name":"A","additionalProperty":[{"name":"Weight","value":"250","unitText":"g"}]}</script><table><tr><td>Impedance</td><td>130 Ω</td></tr></table>`,'https://www.sennheiser.com/p');assert.equal(evidence.paragraphs.length,1);assert.equal(evidence.paragraphs[0].text,para);assert.equal(evidence.paragraphs[0].id,'p1');assert.equal(evidence.specs.find(x=>x.name==='Weight').value,'250 g');assert.equal(evidence.status,'unverified');assert.ok(evidence.specs.every(x=>x.source===evidence.url));
const old=[{id:'one',first_seen:'2020-01-01',title:'Old'}];const history=H.mergeHistory([{id:'one',title:'Changed'},{id:'two',title:'New'}],old);assert.equal(history.length,2);assert.equal(history[0].first_seen,'2020-01-01');assert.equal(history[0].title,'Changed');
const map=new Map(),writes=[];let grants=1;const env={PT_UNIVERSE_DATA:{get:async k=>map.get(k)||null,put:async(k,v)=>{writes.push(k);map.set(k,JSON.parse(v));}},DB:{prepare:()=>({bind:()=>({run:async()=>({meta:{changes:grants}})})})}};
const original=globalThis.fetch;let fetches=0;
const route=path=>H.contentHubRoute(new Request('https://test/api/hub/'+path),env);
try{
 globalThis.fetch=async()=>{fetches++;return new Response(JSON.stringify([{weekday:{id:1,cn:'星期一'},items:[{id:1,name:'A',type:2}]}]));};
 let r=await route('calendar');assert.equal(r.body.days[0].items[0].title,'A');assert.equal(fetches,1);await route('calendar');assert.equal(fetches,1,'fresh cache must suppress upstream requests');
 const previous=map.get('hub/calendar');previous.checked_at='2020-01-01T00:00:00Z';globalThis.fetch=async()=>{throw Error('upstream failed')};r=await route('calendar');assert.equal(r.body.stale,true);assert.equal(r.body.checked_at,previous.checked_at,'failed refresh must not claim a new success time');assert.equal(map.get('hub/calendar').stale,false);
 globalThis.fetch=async()=>new Response(null,{status:302,headers:{location:'http://169.254.169.254/'}});r=await route('check/read?url='+encodeURIComponent('https://www.apple.com/p'));assert.equal(r.status,400);assert.match(r.body.error,/不支持/);
 globalThis.fetch=async()=>new Response('large',{headers:{'content-length':'2000001'}});r=await route('check/read?url='+encodeURIComponent('https://www.apple.com/large'));assert.equal(r.status,400);assert.match(r.body.error,/过大/);
 grants=0;r=await route('check/search?q=Product+A');assert.equal(r.status,429);grants=1;
 map.set('hub/topics',{checked_at:'2020-01-01',items:[{id:'v2ex-1',source:'v2ex',title:'Keep me',first_seen:'2020-01-01'}],sources:{v2ex:{checked_at:'2020-01-01'}}});globalThis.fetch=async u=>{if(String(u).includes('v2ex'))throw Error('source failed');return new Response(fixture('topics'));};r=await route('topics');assert.ok(r.body.items.some(x=>x.id==='v2ex-1'));assert.equal(r.body.sources.v2ex.ok,false);assert.equal(r.body.sources.v2ex.checked_at,'2020-01-01');
 map.set('data/site-updates.json',{generated_at:'2026-10-08',items:[{id:'stable-id',title:'Known manga',url:'https://m.manhuagui.com/comic/61789/',source:'manhuagui',type:'manga',latest:'第1话'}]});map.set('hub/discover',{checked_at:'2020-01-01',items:[{id:'stable-id',url:'https://m.manhuagui.com/comic/61789/',first_seen:'2020-01-01'}]});globalThis.fetch=async()=>new Response(fixture('completed'));r=await route('discover');const item=r.body.items.find(x=>x.id==='stable-id');assert.equal(item.status,'completed');assert.equal(item.first_seen,'2020-01-01');assert.ok(item.author);assert.equal(r.body.items.length,2);
 globalThis.fetch=async u=>String(u).includes('brave')?new Response(fixture('search')):new Response('<rss/>');r=await route('check/search?q=HD490+Pro&mode=product');assert.ok(r.body.items.length);assert.ok(r.body.items.every(x=>x.status==='unverified'));assert.ok(r.body.items.some(x=>x.readable));assert.ok(!r.body.items.some(x=>x.title==='Google Images'));
 r=await H.contentHubRoute(new Request('https://test/api/hub/assets',{method:'POST'}),env);assert.equal(r.status,405);r=await route('does-not-exist');assert.equal(r.status,404);assert.equal(await H.contentHubRoute(new Request('https://test/api/other'),env),null);
}finally{globalThis.fetch=original;}
console.log('Content hub passed: real source fixtures, SSRF/redirect/size limits, rate limit, cache failure timestamps, partial history, completion provenance, unverified evidence');
