import assert from 'node:assert/strict';import {build} from 'esbuild';import {Miniflare} from 'miniflare';
const result=await build({entryPoints:['src/decision.ts'],bundle:true,platform:'node',format:'esm',write:false});const m=await import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));const {inferSignal}=await import('../../../apps/_decision/signal-ingest.mjs');
for(const u of ['http://example.com','https://127.0.0.1','https://[::1]/','https://metadata.internal','https://user:pass@example.com','https://example.com:8080','https://foo.workers.dev'])assert.throws(()=>m.publicURL(u));assert.equal(m.publicURL('https://example.com/a').hostname,'example.com');
const at='2026-09-30T18:00:00Z',feed='<rss><channel><item><guid>one</guid><title>$NVDA bullish</title><link>https://example.com/one</link><pubDate>Wed, 30 Sep 2026 17:00:00 GMT</pubDate><description>original text</description></item></channel></rss>';
const items=m.feedItems(feed,'https://example.com/feed',at);assert.equal(items.length,1);assert.equal(items[0].firstSeenAt,at);assert.equal(inferSignal(items[0],{id:'s',name:'bot'}).direction,'long');for(const title of ['$NVDA bullish if price breaks 200','$NVDA bullish $AAPL bearish','$NVDA not bullish','$NVDA call buy'])assert.equal(inferSignal({...items[0],title},{name:'bot'}),null);assert.throws(()=>m.feedItems('<html>login</html>','https://example.com',at));
const runtimeScript=result.outputFiles[0].text+'\nexport default {async fetch(req){const body=await req.text();try{return Response.json(new URL(req.url).pathname==="/product"?await products(body):await pageText(body,"main"))}catch(e){return Response.json({error:e.message},{status:400})}}';
const mf=new Miniflare({workers:[{config:{type:'worker',name:'test',compatibilityDate:'2026-08-28',manifest:{mainModule:'index.mjs',modulesRoot:process.cwd(),modules:{'index.mjs':{type:'esm',contents:runtimeScript}}},env:{DB:{type:'d1',id:'decision-test'},PT_UNIVERSE_DATA:{type:'kv',id:'decision-test'}}}}]});const env=await mf.getBindings('test'),realFetch=globalThis.fetch,owner='11111111-1111-4111-8111-111111111111',owner2='22222222-2222-4222-8222-222222222222';
try{
let extracted=await mf.dispatchFetch('https://test/page',{method:'POST',body:'<html><body><header>ignore</header><main><p>Registration closed</p><script>fake OPEN</script><div hidden>hidden OPEN</div></main></body></html>'});assert.equal(await extracted.json(),'Registration closed');
extracted=await mf.dispatchFetch('https://test/product',{method:'POST',body:'<html><script type="application/ld+json">{"@type":"Product","name":"QA item","sku":"v2","offers":{"@type":"Offer","price":"80","priceCurrency":"USD"}}</script></html>'});assert.equal((await extracted.json())[0].price,80);
extracted=await mf.dispatchFetch('https://test/product',{method:'POST',body:'<p>Example price 100, date 2026</p>'});assert.equal(extracted.status,400);
globalThis.fetch=async()=>new Response(feed,{headers:{'content-type':'application/rss+xml'}});const request=(path,body)=>new Request('https://worker.example/api/decision/'+path+'/sources',{method:body?'POST':'GET',headers:{'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
assert.equal((await m.decisionRoute(request(owner),env,async()=>false)).status,401);
const created=await m.decisionRoute(request(owner,{kind:'feed',name:'QA',url:'https://example.com/feed'}),env,async()=>true);assert.equal(created.status,201);const id=created.body.id;let list=(await m.decisionRoute(request(owner),env,async()=>true)).body.sources;assert.equal(list.length,1);assert.equal(list[0].data.items.length,1);assert.equal((await m.decisionRoute(request(owner2),env,async()=>true)).body.sources.length,0);
await env.DB.prepare('UPDATE decision_sources SET next_at=0').run();globalThis.fetch=async()=>new Response(feed.replace('original text','edited text'),{headers:{'content-type':'application/rss+xml'}});await m.decisionTick(env);list=(await m.decisionRoute(request(owner),env,async()=>true)).body.sources;assert.equal(list[0].data.items[0].text,'original text');assert.equal(list[0].data.items[0].latestText,'edited text');assert.equal(list[0].data.items.length,1);
await env.DB.prepare('UPDATE decision_sources SET next_at=0').run();globalThis.fetch=async()=>new Response('down',{status:503});await m.decisionTick(env);list=(await m.decisionRoute(request(owner),env,async()=>true)).body.sources;assert.match(list[0].error,/503/);assert.equal(list[0].data.items.length,1);
await env.DB.prepare('UPDATE decision_sources SET next_at=0,paused=1').run();let calls=0;globalThis.fetch=async()=>{calls++;return new Response(feed)};await m.decisionTick(env);assert.equal(calls,0);console.log('Decision collector tests passed: authorization, isolation, collection, edits, failure retention, pause, SSRF URL validation and cautious signal parsing');
}finally{globalThis.fetch=realFetch;await mf.dispose()}
