import assert from 'node:assert/strict';import {build} from 'esbuild';import {Miniflare} from 'miniflare';
const built=await build({entryPoints:['src/muse.ts'],bundle:true,platform:'node',format:'esm',write:false}),m=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
const mf=new Miniflare({workers:[{config:{type:'worker',name:'test',compatibilityDate:'2026-08-28',manifest:{mainModule:'index.mjs',modulesRoot:process.cwd(),modules:{'index.mjs':{type:'esm',contents:'export default {fetch(){return new Response("ok")}}'}}},env:{DB:{type:'d1',id:'muse-test'},PT_UNIVERSE_DATA:{type:'kv',id:'muse-test'}}}}]});
const env=await mf.getBindings('test'),owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',auth=async req=>req.headers.get('authorization')==='Bearer reader';
const call=(id,action,token,body)=>m.museRoute(new Request('https://test/api/muse/'+id+'/'+action,{method:action==='reports'?'GET':'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})}),env,auth);
try{assert.equal((await call(owner,'reports','invalid')).status,401);const c=await call(owner,'channel','reader',{});assert.equal(c.status,201);const token=c.body.token;assert.equal(token.length,64);assert.equal((await call(owner,'reports',token)).status,401);assert.equal((await call(owner,'deliver','reader',{})).status,401);
const report={reportId:'muse-2026-09-30',date:'2026-09-30',summary:'Evidence changed',items:[{id:'site',title:'Site',summary:'Opened',status:'action',priority:'high',observedAt:new Date().toISOString(),urls:['https://example.com/original'],action:'Review'}]};assert.equal((await call(owner,'deliver',token,report)).status,201);assert.equal((await call(owner,'deliver',token,report)).body.duplicate,true);assert.equal((await call(owner,'deliver',token,{...report,summary:'edited'})).status,409);assert.equal((await call(owner,'reports','reader')).body.reports.length,1);assert.equal((await call(other,'reports','reader')).body.reports.length,0);assert.equal((await call(other,'deliver',token,report)).status,401);
assert.equal((await call(owner,'deliver',token,{...report,reportId:'bad',items:[{...report.items[0],urls:['javascript:alert(1)']}]})).status,400);assert.equal((await call(owner,'deliver',token,{...report,reportId:'bad',items:[{...report.items[0],urls:[]}]})).status,400);assert.equal((await call(owner,'deliver',token,{...report,reportId:'bad',summary:'a'.repeat(160000)})).status,400);assert.throws(()=>m.validateReport({...report,date:'2026-02-31'}));assert.throws(()=>m.validateReport({...report,items:[{...report.items[0],observedAt:'2099-01-01'}]}));
const rotated=await call(owner,'channel','reader',{});assert.equal((await call(owner,'deliver',token,{...report,reportId:'later'})).status,401);assert.equal((await call(owner,'deliver',rotated.body.token,{...report,reportId:'later'})).status,201);assert.equal((await call(owner,'reports','reader')).body.reports.length,2);console.log('Muse tests passed: write/read separation, isolation, validation, bounded body, idempotence, conflicts and token rotation');
}finally{await mf.dispose()}
