(()=>{
 'use strict';
 const H=PTContent,{esc,url,img,date}=H,$=s=>document.querySelector(s);
 const KEY='tsugi-hub-state',saved=H.read(KEY,{works:[],anime:[],progress:{},hidden:[],read:[],discovery:[],blocked:''});
 for(const k of ['works','anime','hidden','read','discovery'])if(!Array.isArray(saved[k]))saved[k]=[];saved.progress||={};
 const data={},pending=new Set(),fresh={},seen=H.read('tsugi-hub-seen',{});let activeSubject=null;
 const persist=()=>H.save(KEY,saved),empty=t=>`<div class="hub-empty">${esc(t)}</div>`;
 function sourceStatus(value){return `${value.stale?'缓存 · ':''}最后成功刷新 ${date(value.checked_at)}${Object.values(value.sources||{}).some(s=>!s.ok)?' · 部分来源失败，保留历史':''}`;}
 function notice(tab,text,bad=false){const node=$('#'+tab+'Status');if(node){node.textContent=text;node.classList.toggle('error',bad);}}
 function track(name,rows){const old=new Set(seen[name]||[]);fresh[name]=new Set(old.size?rows.filter(x=>!old.has(String(x.id))).map(x=>String(x.id)):[]);seen[name]=rows.map(x=>String(x.id));H.save('tsugi-hub-seen',seen);}
 const badge=(name,id)=>fresh[name]?.has(String(id))?'<span class="hub-new">本轮新增</span>':'';
 const typeLabel=t=>({1:'书籍',2:'动画',4:'游戏',manga:'漫画',novel:'小说'}[t]||'作品');
 const workCard=(s,action='map')=>`<article class="hub-card">${img(s.cover,s.title)}<div class="hub-card-body"><span class="hub-chip">${esc(s.relation||typeLabel(s.type))}</span><h3>${esc(s.title)}</h3><p class="hub-meta">${esc(s.date||'日期未提供')}</p><p class="hub-summary">${esc(s.summary||'打开条目查看作品资料与关系')}</p><div class="hub-actions"><button class="hub-btn" data-${action}="${esc(s.id)}">${action==='map'?'查看关系':'分集 / 进度'}</button><a class="hub-btn" href="${esc(url(s.url))}" target="_blank" rel="noopener">来源 ↗</a></div></div></article>`;
 async function searchWorks(e){e.preventDefault();const button=$('#worksSearchBtn');button.disabled=true;notice('works','正在查询作品…');try{const r=await H.get('search?q='+encodeURIComponent($('#worksQuery').value.trim()));data.search=r.items;$('#worksResults').innerHTML=r.items.length?r.items.map(s=>workCard(s)).join(''):empty('未找到作品，试试中文名或原名');notice('works',sourceStatus(r));}catch(e){notice('works',e.message,true);}finally{button.disabled=false;}}
 function renderArchive(){const host=$('#worksArchive');host.innerHTML=saved.works.length?saved.works.map(w=>`<button class="hub-btn" data-map="${esc(w.subject.id)}">${esc(w.subject.title)} <span class="hub-meta">${w.relations.length} 个关联</span></button>`).join(''): '<span class="hub-meta">搜索作品后，关系图可以保存到这里。</span>';}
 async function showWork(id){
  notice('works','正在读取作品关系…');try{const r=await H.get('subject/'+Number(id));activeSubject=r;renderWork(r);notice('works',sourceStatus(r)+(r.relation_error?' · 关联来源暂不可用':''));}catch(e){const old=saved.works.find(w=>String(w.subject.id)===String(id));if(old){activeSubject=old;renderWork(old);notice('works','显示已保存关系 · '+e.message,true);}else notice('works',e.message,true);}
 }
 function renderWork(r){const s=r.subject;$('#worksDetail').innerHTML=`<article class="hub-detail"><div class="hub-row">${img(s.cover,s.title)}<div><span class="hub-kicker">作品关系</span><h2>${esc(s.title)}</h2><span class="hub-meta">${esc(typeLabel(s.type))} · ${esc(s.date||'日期未提供')}</span></div><button class="hub-btn primary" id="saveWork">${saved.works.some(x=>x.subject.id===s.id)?'更新已存关系':'保存关系图'}</button><button class="hub-btn" id="removeWork">取消收藏</button></div><details><summary>作品简介 · 可能包含剧情信息</summary><p>${esc(s.summary||'来源未提供简介')}</p></details><div class="hub-note">关联名称来自 Bangumi；前传、续集、改编关系保留原标记。公开日期顺序不等于故事时间线。</div><div class="hub-relations">${r.relations.length?r.relations.map(x=>workCard(x)).join(''):empty('来源没有关联条目')}</div><div class="hub-actions"><button class="hub-btn" id="workOrder">整理公开发行日期</button><a class="hub-btn" href="${esc(url(s.url))}" target="_blank" rel="noopener">原始条目 ↗</a></div><div id="workOrderList"></div></article>`;
  $('#saveWork').onclick=()=>{saved.works=saved.works.filter(x=>x.subject.id!==s.id);saved.works.unshift({...activeSubject,saved_at:new Date().toISOString()});saved.works=saved.works.slice(0,40);persist();renderArchive();$('#saveWork').textContent='已保存';};
  $('#removeWork').onclick=()=>{saved.works=saved.works.filter(x=>x.subject.id!==s.id);persist();renderArchive();$('#saveWork').textContent='保存关系图';};
  $('#workOrder').onclick=async()=>{const b=$('#workOrder');b.disabled=true;b.textContent='读取关联日期…';try{const ids=r.relations.slice(0,12);const fetched=await Promise.allSettled(ids.map(x=>H.get('subject/'+x.id)));const rows=[s,...fetched.filter(x=>x.status==='fulfilled').map(x=>x.value.subject)].sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));$('#workOrderList').innerHTML=`<div class="hub-note">按已公开日期排列；${fetched.filter(x=>x.status==='rejected').length} 个条目读取失败。日期缺失条目排在后面。</div>`+rows.map(x=>`<div class="hub-row"><span class="hub-chip">${esc(x.date||'未知日期')}</span><div>${esc(x.title)}</div></div>`).join('');}catch(e){notice('works',e.message,true);}finally{b.disabled=false;b.textContent='整理公开发行日期';}};
 }
 async function loadAnime(){if(pending.has('anime'))return;pending.add('anime');notice('anime','读取放送日历…');try{data.anime=await H.get('calendar',{fallback:'data/hub-calendar.json'});track('anime',data.anime.days.flatMap(x=>x.items));renderAnime();notice('anime',sourceStatus(data.anime));}catch(e){notice('anime',e.message,true);$('#animeGrid').innerHTML=empty('放送来源暂不可用，点击刷新重试');}finally{pending.delete('anime');}}
 function renderAnime(){if(!data.anime)return;const filter=$('#animeDay').value,q=$('#animeQuery').value.trim().toLowerCase(),only=$('#animeFollowOnly').checked;let days=data.anime.days;if(filter!=='all')days=days.filter(x=>String(x.weekday.id)===filter);const map=new Map();for(const d of days)for(const s of d.items)if(!map.has(s.id))map.set(s.id,{...s,weekday:d.weekday.cn});let rows=[...map.values()];if(only)rows=saved.anime.filter(s=>filter==='all'||rows.some(x=>x.id===s.id));rows=rows.filter(s=>!q||`${s.title} ${s.original_title}`.toLowerCase().includes(q));$('#animeGrid').innerHTML=rows.length?rows.map(s=>`<article class="hub-card">${img(s.cover,s.title)}<div class="hub-card-body"><span class="hub-chip">${esc(s.weekday||'我的关注')}</span>${badge('anime',s.id)}<h3>${esc(s.title)}</h3><p>进度 ${saved.progress[s.id]||0}${s.episodes?' / '+s.episodes:''} 集</p><div class="hub-actions"><button class="hub-btn" data-anime="${s.id}">分集 / 进度</button><button class="hub-btn" data-follow="${s.id}">${saved.anime.some(a=>a.id===s.id)?'✓ 已关注':'＋ 关注'}</button></div></div></article>`).join(''):empty(only?'还没有符合条件的关注作品':'这个条件下没有番剧');}
 async function episodes(id){const s=data.anime?.days.flatMap(x=>x.items).find(x=>x.id===id)||saved.anime.find(x=>x.id===id);if(!s)return;const modal=$('#hubEpisodes');$('#episodeTitle').textContent=s.title;$('#episodeList').innerHTML=empty('读取分集记录…');modal.showModal();try{const r=await H.get('episodes/'+id);$('#episodeList').innerHTML=`<div class="hub-note">记录日期不代表你所在地区的平台已上线；未提供日期时显示未知。${r.total>100?'本次显示前 100 集。':''}</div>`+(r.items.length?r.items.map(ep=>`<div class="hub-row"><label><input type="checkbox" data-progress="${id}" data-sort="${ep.sort}" ${Number(saved.progress[id]||0)>=ep.sort?'checked':''}> 第 ${ep.sort} 集</label><div><a href="${esc(url(ep.url))}" target="_blank" rel="noopener">${esc(ep.title||'分集标题未提供')}</a><p>${esc(ep.airdate||'日期未知')} · <span data-episode-status="${ep.sort}">${Number(saved.progress[id]||0)>=ep.sort?'已看':'待看'}</span></p></div></div>`).join(''):empty('尚无分集记录'));}catch(e){$('#episodeList').innerHTML=empty(e.message);}}
 async function loadTopics(){if(pending.has('topics'))return;pending.add('topics');notice('topics','读取中文话题…');try{data.topics=await H.get('topics',{fallback:'data/hub-topics.json'});track('topics',data.topics.items);renderTopics();notice('topics',sourceStatus(data.topics));}catch(e){notice('topics',e.message,true);$('#topicsList').innerHTML=empty('话题来源暂不可用，点击刷新重试');}finally{pending.delete('topics');}}
 function renderTopics(){if(!data.topics)return;const source=$('#topicsSource').value,q=$('#topicsQuery').value.trim().toLowerCase(),blocks=String(saved.blocked||'').split(/[,，\n]/).map(x=>x.trim().toLowerCase()).filter(Boolean);let rows=data.topics.items.filter(x=>!saved.hidden.includes(x.id)&&(source==='all'||source===x.source)&&(!q||`${x.title} ${x.subject_title||''} ${x.excerpt||''}`.toLowerCase().includes(q))&&!blocks.some(w=>x.title.toLowerCase().includes(w)));if($('#topicsUnread').checked)rows=rows.filter(x=>!saved.read.includes(x.id));if($('#topicsOrder').value==='replies')rows.sort((a,b)=>b.replies-a.replies);$('#topicsList').innerHTML=rows.length?rows.slice(0,100).map(x=>`<article class="hub-row"><div><span class="hub-chip">${esc(x.source_label)}</span>${x.subject_title?`<span class="hub-chip">${esc(x.subject_title)}</span>`:''}${badge('topics',x.id)}${x.spoiler?'<details><summary>可能剧透 · 点击展开标题</summary>':''}<h3><a href="${esc(url(x.url))}" data-topic-read="${esc(x.id)}" target="_blank" rel="noopener">${esc(x.title)}</a></h3>${x.excerpt?`<p class="hub-summary">${esc(x.excerpt)}</p>`:''}${x.spoiler?'</details>':''}<span class="hub-meta">${x.replies} 回复 · ${esc(x.activity_text||date(x.published_at))}${saved.read.includes(x.id)?' · 已读':''}</span></div><div class="hub-actions"><button class="hub-btn" data-hide-topic="${esc(x.id)}">隐藏</button>${x.subject_id?`<button class="hub-btn" data-topic-map="${x.subject_id}">作品关系</button>`:''}</div></article>`).join(''):empty('没有符合条件的话题');}
 async function loadDiscovery(){if(pending.has('discover'))return;pending.add('discover');notice('discovery','整理新发现与完结目录…');try{data.discover=await H.get('discover',{fallback:'data/hub-discover.json'});track('discover',data.discover.items);renderDiscovery();notice('discovery',sourceStatus(data.discover));}catch(e){notice('discovery',e.message,true);$('#discoveryGrid').innerHTML=empty('来源暂不可用，点击刷新重试');}finally{pending.delete('discover');}}
 function renderDiscovery(){if(!data.discover)return;const q=$('#discoveryQuery').value.trim().toLowerCase(),type=$('#discoveryType').value,mode=$('#discoveryMode').value;let rows=data.discover.items.filter(x=>(type==='all'||x.type===type)&&(!q||`${x.title} ${x.author||''} ${(x.tags||[]).join(' ')}`.toLowerCase().includes(q)));if(mode==='completed')rows=rows.filter(x=>x.status==='completed');if(mode==='saved')rows=rows.filter(x=>saved.discovery.includes(x.id));if(mode==='new')rows.sort((a,b)=>String(b.first_seen).localeCompare(String(a.first_seen)));$('#discoveryGrid').innerHTML=rows.length?rows.slice(0,160).map(x=>`<article class="hub-card">${img(x.cover,x.title)}<div class="hub-card-body"><span class="hub-chip">${esc(typeLabel(x.type))}</span>${x.status==='completed'?'<span class="hub-chip">来源标记完结</span>':''}${badge('discover',x.id)}<h3>${esc(x.title)}</h3><p>${esc(x.author||x.source_label||x.source)}</p><p class="hub-summary">${esc(x.summary||x.latest||'来源未提供简介')}</p><p class="hub-meta">本站发现 ${date(x.first_seen)} · ${esc(x.status_basis||'状态未确认')}</p><div class="hub-actions"><button class="hub-btn" data-save-discovery="${esc(x.id)}">${saved.discovery.includes(x.id)?'✓ 已加入书架':'加入书架'}</button><a class="hub-btn" href="${esc(url(x.url))}" target="_blank" rel="noopener">原始作品 ↗</a></div></div></article>`).join(''):empty(mode==='completed'?'当前来源没有明确完结条目；不会根据更新间隔猜测完结':'没有符合条件的作品');}
 document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.map)showWork(b.dataset.map);if(b.dataset.anime)episodes(Number(b.dataset.anime));if(b.dataset.follow){const id=Number(b.dataset.follow),s=data.anime.days.flatMap(d=>d.items).find(x=>x.id===id);if(saved.anime.some(x=>x.id===id))saved.anime=saved.anime.filter(x=>x.id!==id);else if(s)saved.anime.push(s);persist();renderAnime();}if(b.dataset.hideTopic){saved.hidden.push(b.dataset.hideTopic);persist();renderTopics();}if(b.dataset.topicRead){saved.read=[...new Set([...saved.read,b.dataset.topicRead])];persist();setTimeout(renderTopics,0);}if(b.dataset.topicMap){$('#nav [data-tab=works]').click();showWork(b.dataset.topicMap);}if(b.dataset.saveDiscovery){const id=b.dataset.saveDiscovery,x=data.discover.items.find(x=>x.id===id);if(saved.discovery.includes(id)){return;}else{saved.discovery.push(id);const library=H.read('tsugi-local-library-v1',[]);const key=x.url.replace(/\/$/,'');if(!library.some(v=>String(v.url).replace(/\/$/,'')===key)){library.unshift({...x,enabled:true,added_at:new Date().toISOString()});H.save('tsugi-local-library-v1',library);if(typeof state!=='undefined'){state.localLibrary=library;if(typeof renderLibrary==='function')renderLibrary();}}}persist();renderDiscovery();}});
 document.addEventListener('change',e=>{if(e.target.dataset.progress){const id=Number(e.target.dataset.progress),sort=Number(e.target.dataset.sort);saved.progress[id]=e.target.checked?sort:Math.max(0,sort-1);persist();renderAnime();document.querySelectorAll('[data-progress]').forEach(n=>n.checked=Number(saved.progress[id]||0)>=Number(n.dataset.sort));document.querySelectorAll('[data-episode-status]').forEach(n=>n.textContent=Number(saved.progress[id]||0)>=Number(n.dataset.episodeStatus)?'已看':'待看');}});
 $('#worksSearch').onsubmit=searchWorks;renderArchive();
 $('#worksExport').onclick=()=>H.download('tsugi-works.json',saved.works);
 $('#animeRefresh').onclick=loadAnime;$('#topicsRefresh').onclick=loadTopics;$('#discoveryRefresh').onclick=loadDiscovery;
 for(const id of ['animeDay','animeQuery','animeFollowOnly'])$('#'+id).addEventListener('input',renderAnime);
 for(const id of ['topicsSource','topicsQuery','topicsOrder','topicsUnread'])$('#'+id).addEventListener('input',renderTopics);
 for(const id of ['discoveryQuery','discoveryType','discoveryMode'])$('#'+id).addEventListener('input',renderDiscovery);
 $('#topicsBlocked').value=saved.blocked||'';$('#topicsBlocked').onchange=e=>{saved.blocked=e.target.value;persist();renderTopics();};$('#topicsRestore').onclick=()=>{saved.hidden=[];persist();renderTopics();};$('#closeEpisodes').onclick=()=>$('#hubEpisodes').close();
 for(const b of document.querySelectorAll('#nav [data-tab]'))b.addEventListener('click',()=>{const tab=b.dataset.tab;if(tab==='anime'&&!data.anime)loadAnime();if(tab==='topics'&&!data.topics)loadTopics();if(tab==='discovery'&&!data.discover)loadDiscovery();});
 const tab=new URLSearchParams(location.search).get('tab');if(['works','topics','anime','discovery'].includes(tab))$('#nav [data-tab='+tab+']').click();
})();
