(()=>{
 'use strict';
 const H=PTContent,{esc,url,img,date}=H,$=s=>document.querySelector(s);
 const KEY='tsugi-hub-state',saved=H.read(KEY,{works:[],anime:[],progress:{},hidden:[],read:[],discovery:[],blocked:''});
 for(const k of ['works','anime','hidden','read','discovery'])if(!Array.isArray(saved[k]))saved[k]=[];saved.progress||={};saved.anime1||=[];if(!Array.isArray(saved.anime1))saved.anime1=[];
 const data={},pending=new Set(),fresh={},seen=H.read('tsugi-hub-seen',{});let activeSubject=null,workRequest=0,episodeRequest=0,topicLimit=60,animeLimit=48;
 const persist=()=>H.save(KEY,saved),empty=t=>`<div class="hub-empty">${esc(t)}</div>`;
 function sourceStatus(value){return `${value.stale?'缓存 · ':''}最后成功刷新 ${date(value.checked_at)}${Object.values(value.sources||{}).some(s=>!s.ok)?' · 部分来源失败，保留历史':''}`;}
 function notice(tab,text,bad=false){const node=$('#'+tab+'Status');if(node){node.textContent=text;node.classList.toggle('error',bad);}}
 function track(name,rows){const old=new Set(seen[name]||[]);fresh[name]=new Set(old.size?rows.filter(x=>!old.has(String(x.id))).map(x=>String(x.id)):[]);seen[name]=rows.map(x=>String(x.id));H.save('tsugi-hub-seen',seen);}
 const badge=(name,id)=>fresh[name]?.has(String(id))?'<span class="hub-new">本轮新增</span>':'';
 const typeLabel=t=>({1:'书籍',2:'动画',4:'游戏',manga:'漫画',novel:'小说'}[t]||'作品');
 const workCard=(s,action='map')=>`<article class="hub-card">${img(s.cover,s.title)}<div class="hub-card-body"><span class="hub-chip">${esc(s.relation||typeLabel(s.type))}</span><h3>${esc(s.title)}</h3><p class="hub-meta">${esc(s.date||'日期未提供')}</p><p class="hub-summary">${esc(s.summary||'打开条目查看作品资料与关系')}</p><div class="hub-actions"><button class="hub-btn" data-${action}="${esc(s.id)}">${action==='map'?'查看关系':'分集 / 进度'}</button><a class="hub-btn" href="${esc(url(s.url))}" target="_blank" rel="noopener">来源 ↗</a></div></div></article>`;
 async function searchWorks(e){e.preventDefault();const button=$('#worksSearchBtn');button.disabled=true;notice('works','正在查询作品…');try{const r=await H.get('search?q='+encodeURIComponent($('#worksQuery').value.trim()));data.search=r.items;$('#worksResults').innerHTML=r.items.length?r.items.map(s=>workCard(s)).join(''):empty('未找到作品，试试中文名或原名');notice('works',sourceStatus(r));}catch(e){notice('works',e.message,true);}finally{button.disabled=false;}}
 function renderArchive(){const host=$('#worksArchive');host.innerHTML=saved.works.length?saved.works.map(w=>`<button class="hub-btn" data-map="${esc(w.subject.id)}">${esc(w.subject.title)} <span class="hub-meta">${w.relations.length} 个关联</span></button>`).join(''): '<span class="hub-meta">搜索作品后，关系图可以保存到这里。</span>';}
 async function showWork(id){
  const request=++workRequest;notice('works','正在读取作品关系…');try{const r=await H.get('subject/'+Number(id));if(request!==workRequest)return;activeSubject=r;renderWork(r);notice('works',sourceStatus(r)+(r.relation_error?' · 关联来源暂不可用':''));}catch(e){if(request!==workRequest)return;const old=saved.works.find(w=>String(w.subject.id)===String(id));if(old){activeSubject=old;renderWork(old);notice('works','显示已保存关系 · '+e.message,true);}else notice('works',e.message,true);}
 }
 function renderWork(r){const s=r.subject;$('#worksDetail').innerHTML=`<article class="hub-detail"><div class="hub-row">${img(s.cover,s.title)}<div><span class="hub-kicker">作品关系</span><h2>${esc(s.title)}</h2><span class="hub-meta">${esc(typeLabel(s.type))} · ${esc(s.date||'日期未提供')}</span></div><button class="hub-btn primary" id="saveWork">${saved.works.some(x=>x.subject.id===s.id)?'更新已存关系':'保存关系图'}</button><button class="hub-btn" id="removeWork">取消收藏</button></div><details><summary>作品简介 · 可能包含剧情信息</summary><p>${esc(s.summary||'来源未提供简介')}</p></details><div class="hub-note">关联名称来自 Bangumi；前传、续集、改编关系保留原标记。公开日期顺序不等于故事时间线。</div><div class="hub-relations">${r.relations.length?r.relations.map(x=>workCard(x)).join(''):empty('来源没有关联条目')}</div><div class="hub-actions"><button class="hub-btn" id="workOrder">整理公开发行日期</button><a class="hub-btn" href="${esc(url(s.url))}" target="_blank" rel="noopener">原始条目 ↗</a></div><div id="workOrderList"></div></article>`;
  $('#saveWork').onclick=()=>{saved.works=saved.works.filter(x=>x.subject.id!==s.id);saved.works.unshift({...activeSubject,saved_at:new Date().toISOString()});saved.works=saved.works.slice(0,40);persist();renderArchive();$('#saveWork').textContent='已保存';};
  $('#removeWork').onclick=()=>{saved.works=saved.works.filter(x=>x.subject.id!==s.id);persist();renderArchive();$('#saveWork').textContent='保存关系图';};
  $('#workOrder').onclick=async()=>{const request=workRequest,b=$('#workOrder');b.disabled=true;b.textContent='读取关联日期…';try{const ids=r.relations.slice(0,12);const fetched=await Promise.allSettled(ids.map(x=>H.get('subject/'+x.id)));if(request!==workRequest)return;const rows=[s,...fetched.filter(x=>x.status==='fulfilled').map(x=>x.value.subject)].sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));$('#workOrderList').innerHTML=`<div class="hub-note">按已公开日期排列；${fetched.filter(x=>x.status==='rejected').length} 个条目读取失败。日期缺失条目排在后面。</div>`+rows.map(x=>`<div class="hub-row"><span class="hub-chip">${esc(x.date||'未知日期')}</span><div>${esc(x.title)}</div></div>`).join('');}catch(e){if(request===workRequest)notice('works',e.message,true);}finally{b.disabled=false;b.textContent='整理公开发行日期';}};
 }
 async function loadAnime(){if(pending.has('anime'))return;pending.add('anime');notice('anime','读取 Anime1 动画目录…');try{data.anime=await H.get('anime1',{fallback:'data/hub-anime1.json'});track('anime1',data.anime.items);const year=$('#animeYear').value;$('#animeYear').innerHTML='<option value="all">全部年份</option>'+[...new Set(data.anime.items.map(x=>x.year))].sort().reverse().map(y=>`<option value="${esc(y)}">${esc(y)} 年</option>`).join('');$('#animeYear').value=[...$('#animeYear').options].some(o=>o.value===year)?year:'all';renderAnime();notice('anime',sourceStatus(data.anime)+' · Anime1 原始更新顺序');}catch(e){notice('anime',e.message,true);$('#animeGrid').innerHTML=empty('Anime1 目录暂不可用，点击刷新重试');}finally{pending.delete('anime');}}
 function renderAnime(){if(!data.anime)return;const filter=$('#animeDay').value,q=$('#animeQuery').value.trim().toLowerCase(),year=$('#animeYear').value,only=$('#animeFollowOnly').checked,live=new Map(data.anime.items.map(x=>[x.id,x]));let rows=only?saved.anime1.map(x=>live.get(x.id)||x):data.anime.items;rows=rows.filter(s=>(filter==='all'||s.status===filter)&&(year==='all'||s.year===year)&&(!q||`${s.title} ${s.search_title||''}`.toLowerCase().includes(q)));$('#animeMore').hidden=rows.length<=animeLimit;$('#animeGrid').innerHTML=rows.length?rows.slice(0,animeLimit).map(s=>{const followed=saved.anime1.some(a=>a.id===s.id),progress=saved.progress[s.id];return `<article class="anime-entry"><div class="anime-season"><b>${esc(s.season)}</b><span>${esc(s.year)}</span></div><div class="anime-copy"><span class="anime-label ${s.status}">${s.status==='ongoing'?'连载中':s.status==='completed'?'已完结':'特别篇'}</span>${badge('anime1',s.id)}<h3><a href="${esc(url(s.url))}" target="_blank" rel="noopener">${esc(s.title)}</a></h3><p>Anime1 已上架 <b>${esc(s.available_label||'集数未提供')}</b>${s.subtitles?' · '+esc(s.subtitles):''}${followed?' · 已看 '+(progress===undefined?'尚未记录':progress+' 集'):''}</p></div><div class="anime-actions"><a class="hub-btn primary" href="${esc(url(s.url))}" target="_blank" rel="noopener">观看 / 选集 ↗</a><button class="hub-btn" data-follow="${esc(s.id)}">${followed?'✓ 已关注':'＋ 关注'}</button>${followed?`<button class="hub-btn subtle" data-anime="${esc(s.id)}">记录进度</button>`:''}</div></article>`;}).join(''):empty(only?'没有符合筛选条件的关注作品':'没有符合条件的 Anime1 作品');}
 function episodes(id){const s=data.anime?.items.find(x=>x.id===id)||saved.anime1.find(x=>x.id===id);if(!s)return;$('#episodeTitle').textContent=s.title;const count=s.latest_episode;$('#episodeList').innerHTML=`<div class="episode-current"><span>来源已上架</span><strong>${esc(s.available_label||'未提供')}</strong><a class="hub-btn primary" href="${esc(url(s.url))}" target="_blank" rel="noopener">前往 Anime1 选集 ↗</a></div><p class="hub-note">下面只记录你已看至第几集，不表示来源更新进度。勾选一集会把之前各集一并标为已看。</p>`+(count&&count<=120?Array.from({length:Math.floor(count)},(_,i)=>{const n=i+1;return `<div class="hub-row"><label><input type="checkbox" data-progress="${esc(id)}" data-sort="${n}" ${Number(saved.progress[id]||0)>=n?'checked':''}> 第 ${n} 集</label><span data-episode-status="${n}">${Number(saved.progress[id]||0)>=n?'已看':'待看'}</span></div>`;}).join(''):`<label>已看至 <input type="number" id="animeProgressInput" min="0" max="${count||9999}" value="${saved.progress[id]||0}"> 集</label><button class="hub-btn" id="animeProgressSave">保存进度</button>`);if($('#animeProgressSave'))$('#animeProgressSave').onclick=()=>{const n=Number($('#animeProgressInput').value);if(!Number.isInteger(n)||n<0||n>(count||9999))return;saved.progress[id]=n;persist();renderAnime();$('#hubEpisodes').close();};$('#hubEpisodes').showModal();}
 async function loadTopics(){if(pending.has('topics'))return;pending.add('topics');notice('topics','读取中文话题…');try{data.topics=await H.get('topics',{fallback:'data/hub-topics.json'});track('topics',data.topics.items);renderTopics();notice('topics',sourceStatus(data.topics));}catch(e){notice('topics',e.message,true);$('#topicsList').innerHTML=empty('话题来源暂不可用，点击刷新重试');}finally{pending.delete('topics');}}
 function renderTopics(){if(!data.topics)return;const source=$('#topicsSource').value,q=$('#topicsQuery').value.trim().toLowerCase(),blocks=String(saved.blocked||'').split(/[,，\n]/).map(x=>x.trim().toLowerCase()).filter(Boolean);let rows=data.topics.items.filter(x=>!saved.hidden.includes(x.id)&&(source==='all'||source===x.source)&&(!q||`${x.title} ${x.subject_title||''} ${x.excerpt||''}`.toLowerCase().includes(q))&&!blocks.some(w=>x.title.toLowerCase().includes(w)));if($('#topicsUnread').checked)rows=rows.filter(x=>!saved.read.includes(x.id));if($('#topicsOrder').value==='replies')rows.sort((a,b)=>b.replies-a.replies);$('#topicsCount').textContent=rows.length+' 条';$('#topicsMore').hidden=rows.length<=topicLimit;$('#topicsList').innerHTML=rows.length?rows.slice(0,topicLimit).map(x=>{const read=saved.read.includes(x.id);return `<article class="topic-entry ${read?'is-read':'is-unread'}"><div class="topic-avatar ${x.source}" aria-hidden="true">${x.source==='bangumi'?'B':'V'}</div><div class="topic-copy"><div class="topic-meta"><span class="topic-community">${esc(x.source_label)}</span>${x.subject_title?`<button class="topic-work" data-topic-map="${x.subject_id}">${esc(x.subject_title)}</button>`:''}${badge('topics',x.id)}</div>${x.spoiler?'<details class="topic-spoiler"><summary>可能剧透 · 展开标题</summary>':''}<h3><a href="${esc(url(x.url))}" data-topic-read="${esc(x.id)}" target="_blank" rel="noopener">${esc(x.title)}</a></h3>${x.excerpt?`<p class="topic-excerpt">${esc(x.excerpt)}</p>`:''}${x.spoiler?'</details>':''}<span class="topic-time">${esc(x.activity_text||date(x.published_at))}${read?' · 已读':''}</span></div><div class="topic-replies"><b>${Number(x.replies)||0}</b><span>回复</span></div><button class="topic-hide" data-hide-topic="${esc(x.id)}" title="隐藏此话题" aria-label="隐藏 ${esc(x.title)}">×</button></article>`;}).join(''):empty('没有符合条件的话题，试试调整关键词或来源');}
 async function loadDiscovery(){if(pending.has('discover'))return;pending.add('discover');notice('discovery','整理新发现与完结目录…');try{data.discover=await H.get('discover',{fallback:'data/hub-discover.json'});track('discover',data.discover.items);renderDiscovery();notice('discovery',sourceStatus(data.discover));}catch(e){notice('discovery',e.message,true);$('#discoveryGrid').innerHTML=empty('来源暂不可用，点击刷新重试');}finally{pending.delete('discover');}}
 function renderDiscovery(){if(!data.discover)return;const q=$('#discoveryQuery').value.trim().toLowerCase(),type=$('#discoveryType').value,mode=$('#discoveryMode').value;let rows=data.discover.items.filter(x=>['manhuagui-completed','linovelib-completed'].includes(x.source)&&(type==='all'||x.type===type)&&(!q||`${x.title} ${x.author||''} ${(x.tags||[]).join(' ')}`.toLowerCase().includes(q)));if(mode==='completed')rows=rows.filter(x=>x.status==='completed');if(mode==='saved')rows=rows.filter(x=>saved.discovery.includes(x.id));if(mode==='new')rows.sort((a,b)=>String(b.first_seen).localeCompare(String(a.first_seen)));$('#discoveryGrid').innerHTML=rows.length?rows.slice(0,160).map(x=>`<article class="hub-card">${img(x.cover,x.title)}<div class="hub-card-body"><span class="hub-chip">${esc(typeLabel(x.type))}</span>${x.status==='completed'?'<span class="hub-chip">来源标记完结</span>':''}${x.cached_source_at?'<span class="hub-chip warn">历史快照</span>':''}${badge('discover',x.id)}<h3>${esc(x.title)}</h3><p>${esc(x.author||x.source_label||x.source)}</p><p class="hub-summary">${esc(x.summary||x.latest||'来源未提供简介')}</p><p class="hub-meta">目录收录 ${date(x.first_seen)} · ${esc(x.status_basis||'状态未确认')}${x.cached_source_at?' · 来源快照 '+date(x.cached_source_at):''}</p><div class="hub-actions"><button class="hub-btn" data-save-discovery="${esc(x.id)}">${saved.discovery.includes(x.id)?'✓ 已加入书架':'加入书架'}</button><a class="hub-btn" href="${esc(url(x.url))}" target="_blank" rel="noopener">原始作品 ↗</a></div></div></article>`).join(''):empty(mode==='completed'?'当前来源没有明确完结条目；不会根据更新间隔猜测完结':'没有符合条件的作品');}
 document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.map)showWork(b.dataset.map);if(b.dataset.anime)episodes(b.dataset.anime);if(b.dataset.follow){const id=b.dataset.follow,s=data.anime.items.find(x=>x.id===id);if(saved.anime1.some(x=>x.id===id))saved.anime1=saved.anime1.filter(x=>x.id!==id);else if(s)saved.anime1.push(s);persist();renderAnime();}if(b.dataset.hideTopic){saved.hidden.push(b.dataset.hideTopic);persist();renderTopics();}if(b.dataset.topicRead){saved.read=[...new Set([...saved.read,b.dataset.topicRead])];persist();setTimeout(renderTopics,0);}if(b.dataset.topicMap){$('#nav [data-tab=works]').click();showWork(b.dataset.topicMap);}if(b.dataset.saveDiscovery){const id=b.dataset.saveDiscovery,x=data.discover.items.find(x=>x.id===id);if(saved.discovery.includes(id)){return;}else{saved.discovery.push(id);const library=H.read('tsugi-local-library-v1',[]);const key=x.url.replace(/\/$/,'');if(!library.some(v=>String(v.url).replace(/\/$/,'')===key)){library.unshift({...x,enabled:true,added_at:new Date().toISOString()});H.save('tsugi-local-library-v1',library);if(typeof state!=='undefined'){state.localLibrary=library;if(typeof renderLibrary==='function')renderLibrary();}}}persist();renderDiscovery();}});
 document.addEventListener('change',e=>{if(e.target.dataset.progress){const id=e.target.dataset.progress,sort=Number(e.target.dataset.sort);saved.progress[id]=e.target.checked?sort:Math.max(0,sort-1);persist();renderAnime();document.querySelectorAll('[data-progress]').forEach(n=>n.checked=Number(saved.progress[id]||0)>=Number(n.dataset.sort));document.querySelectorAll('[data-episode-status]').forEach(n=>n.textContent=Number(saved.progress[id]||0)>=Number(n.dataset.episodeStatus)?'已看':'待看');}});
 $('#topicsMore').onclick=()=>{topicLimit+=60;renderTopics();};$('#animeMore').onclick=()=>{animeLimit+=48;renderAnime();};
 $('#worksSearch').onsubmit=searchWorks;renderArchive();
 $('#worksExport').onclick=()=>H.download('tsugi-works.json',saved.works);
 $('#animeRefresh').onclick=loadAnime;$('#topicsRefresh').onclick=loadTopics;$('#discoveryRefresh').onclick=loadDiscovery;
 for(const id of ['animeDay','animeYear','animeQuery','animeFollowOnly'])$('#'+id).addEventListener('input',()=>{animeLimit=48;renderAnime();});
 for(const id of ['topicsSource','topicsQuery','topicsOrder','topicsUnread'])$('#'+id).addEventListener('input',()=>{topicLimit=60;renderTopics();});
 for(const id of ['discoveryQuery','discoveryType','discoveryMode'])$('#'+id).addEventListener('input',renderDiscovery);
 $('#topicsBlocked').value=saved.blocked||'';$('#topicsBlocked').onchange=e=>{saved.blocked=e.target.value;persist();renderTopics();};$('#topicsRestore').onclick=()=>{saved.hidden=[];persist();renderTopics();};$('#closeEpisodes').onclick=()=>$('#hubEpisodes').close();$('#hubEpisodes').addEventListener('close',()=>episodeRequest++);
 for(const b of document.querySelectorAll('#nav [data-tab]'))b.addEventListener('click',()=>{const tab=b.dataset.tab;if(tab==='anime'&&!data.anime)loadAnime();if(tab==='topics'&&!data.topics)loadTopics();if(tab==='discovery'&&!data.discover)loadDiscovery();});
 const tab=new URLSearchParams(location.search).get('tab');if(['works','topics','anime','discovery'].includes(tab))$('#nav [data-tab='+tab+']').click();
})();
