
import {$,esc,link,change,pct,compact,read,save,toast,json,meta,boot,backups,financialTable,bars} from '../_lab/core.js?v=2';
boot();let data,cases=[],index=0,revealed=false,history=read('dojo',[]);
function sign(a,b){return a>b?'up':a<b?'down':'same'}
const direction={up:'上升',down:'下降',same:'持平'};
function render(){const c=cases[index];if(!c){$('#app').innerHTML='<div class="empty">暂无足够连续季度的真实案例，请查看数据更新状态。</div>';return}
 const qs=c.quarters,q=qs.at(-1),p=qs.at(-2);
 $('#app').innerHTML='<div class="toolbar"><label>练习案例<select id="case">'+cases.map((_,i)=>'<option value="'+i+'" '+(i===index?'selected':'')+'>案例 '+String(i+1).padStart(2,'0')+'</option>').join('')+'</select></label><span class="tag">真实财报 · '+cases.length+' 个案例</span><span class="tag">已练习 '+history.length+' 次</span></div><section class="panel"><h2>匿名公司 · 截至 '+esc(q.end)+'</h2><p class="muted">先完成三个客观判断，再写下投资观点。公司名称和下一季数据在提交后显示。</p>'+bars(qs)+financialTable(qs)+'<p class="notice">这是财报阅读练习。金额可能包含后续重述，不是严格的历史时点回测；揭晓结果为下一季经营表现，不代表股票涨跌。</p></section><section class="panel"><form id="answer"><div class="form-grid"><label>最近一季营收环比<select name="revenue" required><option value="">请选择</option>'+Object.entries(direction).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join('')+'</select></label><label>最近一季营业利润率环比<select name="margin" required><option value="">请选择</option>'+Object.entries(direction).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join('')+'</select></label><label>最近一季经营现金流是否高于净利润？<select name="cash" required><option value="">请选择</option><option value="yes">是</option><option value="no">否</option></select></label><label>下一季营收方向预测（不计入客观题得分）<select name="forecast"><option value="up">上升</option><option value="down">下降</option><option value="same">持平</option></select></label><label class="wide">你的判断与需要进一步核实的风险<textarea name="reason" maxlength="4000" placeholder="例如：增长来自需求还是一次性因素？利润是否转换为现金？"></textarea></label></div><button class="primary" type="submit">提交并揭晓</button></form><div id="reveal"></div></section><section class="panel"><h2>练习记录</h2><div class="history">'+(history.length?history.slice().reverse().map(h=>'<p><strong>'+esc(h.company)+' · '+h.score+'/3</strong> <small>'+esc(h.date)+'</small><br>'+esc(h.reason||'未填写判断')+'</p>').join(''):'<p class="muted">完成第一次练习后会保存在这里。</p>')+'</div></section>';
 $('#case').onchange=e=>{index=Number(e.target.value);revealed=false;render();window.scrollTo({top:0,behavior:'smooth'})};
 $('#answer').onsubmit=e=>{e.preventDefault();if(revealed)return;revealed=true;const a=Object.fromEntries(new FormData(e.target));const correct={revenue:sign(q.revenue,p.revenue),margin:sign(q.operatingIncome/q.revenue,p.operatingIncome/p.revenue),cash:q.ocf>q.netIncome?'yes':'no'};const score=Object.keys(correct).filter(k=>a[k]===correct[k]).length;
 history.push({id:crypto.randomUUID(),case:c.id,company:c.name,ticker:c.ticker,date:new Date().toISOString(),score,reason:a.reason,answers:a});history=history.slice(-500);save('dojo',history);e.target.hidden=true;
 const next=c.next,forecast=sign(next.revenue,q.revenue);
 $('#reveal').innerHTML='<span class="eyebrow">REVEALED</span><h2>'+esc(c.ticker+' · '+c.name)+'</h2><div class="rating">'+score+' / 3</div><p>营收环比：'+direction[correct.revenue]+'（'+pct(change(q.revenue,p.revenue))+'）<br>营业利润率：'+direction[correct.margin]+'（'+pct(p.operatingIncome/p.revenue)+' → '+pct(q.operatingIncome/q.revenue)+'）<br>经营现金流 '+compact(q.ocf)+'，净利润 '+compact(q.netIncome)+'。</p><h3>下一季 '+esc(next.end)+' 的实际结果</h3><p>营收 '+compact(next.revenue)+'，环比 '+pct(change(next.revenue,q.revenue))+'；你的方向预测'+(a.forecast===forecast?'正确':'未命中')+'。</p><p>'+link(c.sourceURL,'核对财报来源')+'</p><p class="notice">继续追问：现金流变化是否受营运资本影响？单季增长是否存在季节性？股数增加是否抵消了利润增长？</p><button id="next" class="primary">下一案例 →</button>';
 $('#next').onclick=()=>{index=(index+1)%cases.length;revealed=false;render();window.scrollTo({top:0,behavior:'smooth'})};toast('练习结果已保存');
 };
}
backups('dojo',()=>history,v=>{if(!Array.isArray(v)||v.length>500||!v.every(x=>x&&typeof x.company==='string'&&Number.isInteger(x.score)&&x.score>=0&&x.score<=3))throw new Error('记录格式不正确');history=v;save('dojo',v);render()});
try{data=await json('../thesis-lab/data/financials.json');meta(data);for(const c of data.companies){const qs=c.quarters;for(let end=3;end<qs.length-1;end++){const group=qs.slice(end-3,end+1),next=qs[end+1];const valid=group.every(q=>['revenue','operatingIncome','ocf','netIncome'].every(k=>Number.isFinite(q[k]))&&q.revenue>0)&&Number.isFinite(next.revenue)&&[...group,next].every((q,i,all)=>!i||Math.abs((Date.parse(q.end)-Date.parse(all[i-1].end))/86400000-91)<22);if(valid)cases.push({id:c.ticker+'-'+qs[end].end,ticker:c.ticker,name:c.name,quarters:group,next,sourceURL:c.sourceURL})}}render()}catch(e){$('#app').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}
