const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PT_PLAYWRIGHT||'playwright');
const root=path.resolve(__dirname,'../..'),types={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{let file=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',types[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end('missing')}});
let browser;
const cloud=new Map();
async function mock(ctx){await ctx.route('https://pt-universe-api.*/**',async route=>{const req=route.request(),url=new URL(req.url()),key=url.pathname;let data={},status=200;if(key.includes('/api/sync/')&&!key.endsWith('/register')){const prior=cloud.get(key)||{ciphertext:null,revision:0};if(req.method()==='PUT'){const body=req.postDataJSON();assert.ok(!body.ciphertext.includes('跨设备'));if(body.baseRevision!==prior.revision){data={error:'同步冲突'};status=409}else {data={ciphertext:body.ciphertext,revision:prior.revision+1};cloud.set(key,data)}}else data=prior}await route.fulfill({status,json:data,headers:{'access-control-allow-origin':'*'}})})}
async function idle(p){await p.waitForFunction(()=>['已保存到本机','已读取新版'].includes(document.querySelector('#saved').textContent))}
async function imported(p,state){await p.locator('#export-button').click();await p.locator('#import-file').setInputFiles({name:'worklog.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(state))});await p.getByRole('button',{name:'导入并保留旧版备份'}).click();await idle(p)}
const fixture={version:1,settings:{folderName:'Work Log',tagPrefix:'worklog'},nodes:[{id:'n_root',name:'PT Universe',notes:'## 本周\n核心记录',status:'active',parentId:'',order:0,collapsed:false,color:'#5965db',createdAt:'2026-10-01T18:00:00.000Z',updatedAt:'2026-10-01T18:00:00.000Z'},{id:'n_child',name:'Dashboard',notes:'',status:'active',parentId:'n_root',order:0,collapsed:false,color:'',createdAt:'2026-10-01T18:00:00.000Z',updatedAt:'2026-10-01T18:00:00.000Z'},{id:'n_second',name:'Export',notes:'',status:'active',parentId:'n_root',order:1,collapsed:false,color:'',createdAt:'2026-10-01T18:00:00.000Z',updatedAt:'2026-10-01T18:00:00.000Z'}],tasks:[{id:'t_first',nodeId:'n_child',title:'完成网页版迁移',notes:'**2026-10-01** — 开始实现',tags:[],done:false,order:0,date:'2026-10-01',createdAt:'2026-10-01T18:00:00.000Z',completedAt:null}],logs:[]};
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}/`;browser=await chromium.launch({headless:true,...(process.env.PT_CHROMIUM?{executablePath:process.env.PT_CHROMIUM,args:['--no-sandbox','--no-proxy-server']}: {})});const errors=[];
for(const platform of ['Win32','MacIntel']){const ctx=await browser.newContext({viewport:{width:1500,height:940},timezoneId:'America/Los_Angeles',acceptDownloads:true});await ctx.addInitScript(platform=>Object.defineProperty(navigator,'platform',{get:()=>platform}),platform);await mock(ctx);const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'apps/pt-todo-dashboard/');await p.locator('#add-project').click();await p.locator('.node-name').fill('新项目');await p.locator('.record-editor').fill('快速输入后立即切换');await p.locator('[data-key="composer:detail"]').fill('新待办');await p.locator('[data-key="composer:detail"]').press('Enter');await idle(p);await p.reload();await p.locator('.record-editor').waitFor();assert.equal(await p.locator('.record-editor').inputValue(),'快速输入后立即切换');assert.equal(await p.locator('.task-title').first().inputValue(),'新待办');
await imported(p,fixture);assert.equal(await p.locator('#scope option').count(),2);const second=p.locator('[data-key="node:n_second"]');await second.click();assert.equal(await p.locator('#scope option:checked').textContent(),'PT Universe');await second.press('Tab');assert.equal(await p.locator('[data-key="node:n_second"]').inputValue(),'Export');assert.equal(await p.locator('.tree-row').filter({has:p.locator('[data-key="node:n_second"]')}).getAttribute('aria-level'),'3');await p.locator('[data-key="node:n_second"]').press('Shift+Tab');assert.equal(await p.locator('.tree-row').filter({has:p.locator('[data-key="node:n_second"]')}).getAttribute('aria-level'),'2');await p.locator('[data-key="node:n_second"]').press('Alt+ArrowUp');assert.equal(await p.locator('.node-name').nth(1).inputValue(),'Export');
const modifier=platform==='MacIntel'?'Meta':'Control';await p.locator('[data-key="node:n_root"]').click();await p.locator('[data-key="node:n_root"]').press(modifier+'+ArrowLeft');assert.equal(await p.locator('.node-name').count(),1);await p.locator('[data-key="node:n_root"]').press(modifier+'+ArrowRight');assert.equal(await p.locator('.node-name').count(),3);
// Enter on an expanded parent inserts a first child, and IME Enter does nothing.
await p.locator('[data-key="node:n_root"]').dispatchEvent('keydown',{key:'Enter',isComposing:true});assert.equal(await p.locator('.node-name').count(),3);await p.locator('[data-key="node:n_root"]').press('Enter');assert.equal(await p.locator('.node-name').count(),4);assert.equal(await p.locator('.node-name').nth(1).inputValue(),'');await p.locator('.node-name').nth(1).fill('首个子项');
await p.locator('[data-key="node:n_child"]').click();await p.locator('#detail .log-chip').click();await p.locator('[data-key="notes:detail:t_first"]').fill('**2026-10-02** — 详细日志');await p.locator('.record-editor').fill('项目记录独立');await p.locator('[data-key="composer:detail"]').fill('第二个待办');await p.locator('[data-key="composer:detail"]').press('Enter');await idle(p);assert.equal(await p.locator('.record-editor').inputValue(),'项目记录独立');await p.locator('#detail [data-task=t_first] input[type=checkbox]').check();assert.equal(await p.locator('#detail .archive [data-task=t_first]').count(),1);await p.locator('#detail .archive summary').click();await p.locator('#detail [data-task=t_first] input[type=checkbox]').uncheck();
// Search logs with each platform modifier.
await p.keyboard.press(modifier+'+k');await p.locator('#search-input').fill('详细日志');assert.equal(await p.locator('.search-result').count(),1);await p.locator('#search-input').press('Enter');assert.equal(await p.locator('[data-key="notes:detail:t_first"]').inputValue(),'**2026-10-02** — 详细日志');await p.locator('#detail [data-task=t_first] .task-delete').click();await p.locator('#toast').getByRole('button',{name:'撤销'}).click();assert.equal(await p.locator('#detail [data-task=t_first]').count(),1);
await idle(p);await p.reload();await p.locator('.record-editor').waitFor();assert.equal(await p.locator('.record-editor').inputValue(),'项目记录独立');await p.keyboard.press(modifier+'+e');await p.locator('#preview-export').click();assert.ok(await p.locator('#file-preview').innerText());const dl=p.waitForEvent('download');await p.locator('#zip-download').click();const zip=await dl;await zip.saveAs('/tmp/pt-todo-browser.zip');await p.locator('#export-dialog [data-close]').click();
// Selection and dragging use only the colored handle, preserving text selection.
const drag=p.locator('.tree-row').filter({has:p.locator('[data-key="node:n_second"]')}).locator('.dot');const target=p.locator('.tree-row').filter({has:p.locator('[data-key="node:n_child"]')});await drag.dragTo(target);await idle(p);assert.equal(await p.locator('.tree-row').filter({has:p.locator('[data-key="node:n_second"]')}).getAttribute('aria-level'),'3');
await p.locator('[data-key="node:n_child"]').click();for(const size of [{width:1500,height:940},{width:1024,height:768},{width:390,height:844}]){await p.setViewportSize(size);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await p.screenshot({path:`/tmp/pt-todo-${platform}-${size.width}.png`})}await p.setViewportSize({width:1500,height:940});await p.locator('#theme-button').click();await p.waitForFunction(()=>getComputedStyle(document.getElementById('help-button')).backgroundColor==='rgb(24, 31, 48)');await p.screenshot({path:`/tmp/pt-todo-${platform}-dark.png`});
// Encryption, download-free device pairing, round-trip and offline recovery.
await p.locator('#sync-button').click();await p.locator('#sync-create').click();await p.waitForFunction(()=>document.querySelector('#sync-status').textContent.startsWith('已同步'));const code=await p.locator('#sync-code').inputValue();assert.ok(code);await p.locator('#sync-dialog [data-close]').click();const other=await browser.newContext({viewport:{width:1440,height:900}});await mock(other);const q=await other.newPage();q.on('pageerror',e=>errors.push(e.message));await q.goto(base+'apps/pt-todo-dashboard/');await q.locator('#sync-button').click();await q.locator('#sync-code').fill(code);await q.locator('#sync-connect').click();await q.waitForFunction(()=>document.querySelector('#sync-status').textContent.startsWith('已同步'));await q.locator('#sync-dialog [data-close]').click();assert.equal(await q.locator('.node-name').first().inputValue(),'PT Universe');await q.locator('[data-key="node:n_child"]').click();assert.equal(await q.locator('.record-editor').inputValue(),'项目记录独立');
// Force two offline edits from the same base and ensure a choice appears.
await ctx.setOffline(true);await other.setOffline(true);await p.locator('.record-editor').fill('Win/Mac 本机变化');await q.locator('.record-editor').fill('另一设备变化');await idle(p);await idle(q);await ctx.setOffline(false);await p.locator('#sync-button').click();await p.locator('#sync-now').click();await p.waitForFunction(()=>document.querySelector('#sync-status').textContent.startsWith('已同步'));await p.locator('#sync-dialog [data-close]').click();await other.setOffline(false);await q.locator('#sync-button').click();await q.locator('#sync-now').click();await q.locator('#confirm-dialog').waitFor({state:'visible'});await q.getByRole('button',{name:'采用云端',exact:true}).click();await q.locator('#sync-dialog [data-close]').click();assert.equal(await q.locator('.record-editor').inputValue(),'Win/Mac 本机变化');await other.close();await ctx.close();console.log(platform+' core and encrypted sync flows passed');}
// Daily Nexus embedding reuses state and stays mounted when switching views.
const ctx=await browser.newContext({viewport:{width:1500,height:1000}});await mock(ctx);const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'apps/daily-nexus/?tab=todo');const f=p.frameLocator('#todoFrame');await f.locator('#add-project').waitFor();await f.locator('#add-project').click();await f.locator('.node-name').fill('嵌入测试');await p.locator('[data-view=home]').click();await p.locator('[data-view=todo]').click();assert.equal(await f.locator('.node-name').inputValue(),'嵌入测试');await p.locator('#quickTheme').click();assert.equal(await f.locator('html').getAttribute('data-theme'),await p.locator('html').getAttribute('data-theme'));await ctx.close();assert.deepEqual(errors,[]);console.log('Todo browser passed: persistence, keyboard/IME, drag, logs, archives, undo, search, ZIP, mobile, sync/conflicts and Nexus integration');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();server.close()});
