import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import * as M from '../../apps/pt-todo-dashboard/model.mjs';
import * as E from '../../apps/pt-todo-dashboard/export.mjs';
const s=M.empty(),a=M.createNode(s),b=M.createNode(s),c=M.createNode(s,a.id);a.name='项目';b.name='项目';c.name='CON';c.notes='## 记录\n**内容**';const task=M.createTask(s,c.id,'写报告');task.notes='**2026-10-02** — 已讨论';M.toggleTask(task,true);assert.equal(task.completedDate,M.today());
assert.throws(()=>M.moveNode(s,a.id,c.id),/子项目/);M.moveNode(s,c.id,b.id);assert.equal(c.parentId,b.id);M.deleteNode(s,b.id,false);assert.equal(c.parentId,'');assert.equal(s.tasks[0].nodeId,c.id);
const imported=M.normalize({...s,nodes:s.nodes.map(n=>({...n,summary:'legacy summary'})),logs:[{nodeId:c.id,date:'2026-10-01',text:'old log'}]});assert.ok(imported.nodes.find(n=>n.id===c.id).notes.includes('old log'));assert.deepEqual(M.normalize(imported),imported);assert.throws(()=>M.normalize({...s,tasks:[{...task,nodeId:'missing'}]}),/不存在/);assert.throws(()=>M.normalize({...s,nodes:[{...a,parentId:c.id},{...c,parentId:a.id}]}),/循环/);assert.throws(()=>M.normalize({...s,nodes:[a,a]}),/重复/);
const files=E.exportFiles(imported);assert.equal(new Set(files.map(f=>f.path.toLocaleLowerCase())).size,files.length);assert.ok(files.every(f=>!/[<>:"\\|?*]/.test(f.path)));assert.ok(files.some(f=>f.path.includes('/_CON-')));assert.ok(files.some(f=>f.content.includes('- [x] 写报告')));assert.ok(files.some(f=>f.path.endsWith(M.today()+'.md')));assert.ok(E.bundle(imported).includes('legacy summary'));await writeFile('/tmp/pt-todo-test.zip',Buffer.from(await E.zip(files).arrayBuffer()));
const deleted=structuredClone(imported);M.deleteNode(deleted,c.id,true);assert.equal(deleted.tasks.length,0);
// Deleting only a root with direct tasks preserves them under a real Inbox node.
const promote=M.empty(),root=M.createNode(promote);root.name='根';M.createTask(promote,root.id,'保留');M.deleteNode(promote,root.id,false);assert.equal(promote.tasks.length,1);assert.ok(promote.nodes.some(n=>n.id===promote.tasks[0].nodeId));
// Sibling folders remain distinct even when unsafe names and ID suffixes collide.
const collision=M.empty();collision.nodes=['n_x1abcdefgh','n_x2abcdefgh'].map((id,i)=>({...a,id,parentId:'',name:'A/B',notes:'note',order:i}));assert.equal(new Set(E.exportFiles(collision).map(f=>f.path)).size,3);
console.log('Todo model/export passed: cycles, promotion/cascade, lossless legacy migration, dates, unique cross-platform paths and ZIP');
class Directory{constructor(){this.dirs=new Map();this.files=new Map()}async getDirectoryHandle(name,{create=false}={}){if(!this.dirs.has(name)){if(!create)throw new DOMException('missing','NotFoundError');this.dirs.set(name,new Directory())}return this.dirs.get(name)}async getFileHandle(name,{create=false}={}){if(!this.files.has(name)){if(!create)throw new DOMException('missing','NotFoundError');this.files.set(name,'')}return {getFile:async()=>({text:async()=>this.files.get(name)}),createWritable:async()=>({write:async text=>this.files.set(name,text),close:async()=>{}})}}async removeEntry(name){if(!this.files.delete(name))throw new DOMException('missing','NotFoundError')}}
const directory=new Directory(),out=[{path:'Work Log/Work Log.md',content:'index'},{path:'Work Log/Projects/Old.md',content:'old'}];await E.writeDirectory(directory,out);const managed=await directory.getDirectoryHandle('Work Log'),projects=await managed.getDirectoryHandle('Projects');projects.files.set('Personal.md','untouched');await E.writeDirectory(directory,[out[0]],true);assert.equal(projects.files.has('Old.md'),false);assert.equal(projects.files.get('Personal.md'),'untouched');
const collisionDir=new Directory(),existing=await collisionDir.getDirectoryHandle('Work Log',{create:true});existing.files.set('Work Log.md','mine');await assert.rejects(()=>E.writeDirectory(collisionDir,[out[0]]),/非本工具管理/);assert.equal(existing.files.get('Work Log.md'),'mine');console.log('Directory export passed: preflight collisions, manifest ownership and safe pruning');
