'use strict';
const API='https://pt-universe-api.summer07-nanjolno.workers.dev/api/media/';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=s=>{try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}};
const href=s=>esc(safeURL(s));
const db={get(k,d){try{return JSON.parse(localStorage.getItem('ptu.mv.'+k))??d;}catch{return d;}},set(k,v){try{localStorage.setItem('ptu.mv.'+k,JSON.stringify(v));}catch{notice('浏览器无法保存本地记录，本次仍可使用。',true);}}};
const meta={music:['♫','音乐','LISTEN. DISCOVER. KEEP.','给喜欢的声音，<br>留一个位置。','从每日榜单发现音乐，寻找 FLAC 音源，收藏你的下一首循环。'],novels:['▤','轻小说','ONE MORE CHAPTER.','下一章，<br>随时随地继续。','输入小说链接、查看目录、保存进度，把喜欢的故事装进阅读器。'],anime:['▷','动漫','YOUR NEXT EPISODE.','好故事，<br>不止一种打开方式。','查找中文字幕动漫，解析单集链接，管理你的观看与下载。'],torrent:['↓','BT 下载','LET IT FLOW.','链接放进来，<br>文件慢慢到。','输入名称，同时搜索多个来源，直接获取磁力链接与种子。'],video:['◫','视频','A LINK. YOUR OPTIONS.','留下想看的，<br>按你的方式播放。','输入网页或媒体链接，查看格式、播放视频、保存字幕与文件。']};
let country=db.get('country','jp'),genre=db.get('genre','0'),chartItems=[],chartRequest=0,book=null,chapterIndex=0,readerContent='',readerName='',fontSize=19,engine=null,engineJobs=[],history=db.get('history',[]),shelf=db.get('shelf',[]),snapshot=null;
try{engine=JSON.parse(sessionStorage.getItem('mv.engine'));}catch{}
const loaded=new Set();
function notice(text,bad=false){$('#notice').hidden=!text;$('#notice').textContent=text;$('#notice').className=bad?'error':'';}
function empty(text){return `<div class="empty"><p>${esc(text)}</p></div>`;}
function date(s){return s?new Date(s).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'尚无成功更新';}
function bytes(n){return n>=1e9?(n/1e9).toFixed(2)+' GB':n>=1e6?(n/1e6).toFixed(1)+' MB':n>=1e3?(n/1e3).toFixed(1)+' KB':(n||0)+' B';}
async function busy(button,fn){if(button)button.disabled=true;try{return await fn();}catch(e){notice(e.message,true);}finally{if(button)button.disabled=false;}}
async function api(path,params={}){let r;try{r=await fetch(API+path+'?'+new URLSearchParams(params),{signal:AbortSignal.timeout(path==='health'?10000:45000),cache:'no-store'});}catch(e){throw new Error(e.name==='TimeoutError'?'来源响应超时，请重试；已缓存的章节仍可阅读。':'无法连接媒体服务，请点击右上角“检测连接”查看状态。');}const raw=await r.text();let d;try{d=JSON.parse(raw);}catch{throw new Error('接口返回 HTTP '+r.status+'，请稍后重试');}if(!r.ok||d.error)throw new Error(d.error||'接口暂不可用');return d;}
async function callEngine(path,body,config=engine){if(!config)throw new Error('此功能需要下载引擎。点击左下角 ⚙ 连接自己的电脑或 NAS。');const r=await fetch(config.url+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+config.token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(path.includes('novel')?90000:65000)});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||'引擎请求失败');return d;}
function addHistory(title,status){history=[{title,status,time:new Date().toISOString()},...history].slice(0,80);db.set('history',history);$('#queueCount').textContent=engineJobs.filter(x=>['running','queued','active','waiting'].includes(x.status)).length||history.length;}
function downloadURL(url,title){
 const valid=safeURL(url);if(!valid)throw new Error('下载链接无效');
 const a=document.createElement('a');a.href=valid;a.rel='noopener';
 // Attachment responses navigate a named frame, never a popup created after an
 // async fetch (which browsers can silently block).
 const attachment=new URL(valid).origin===new URL(API).origin&&new URL(valid).searchParams.has('download');
 if(attachment){let frame=$('#downloadFrame');if(!frame){frame=document.createElement('iframe');frame.id='downloadFrame';frame.name='media-vault-download';frame.hidden=true;document.body.append(frame);}a.target=frame.name;}
 else a.target='_blank';
 a.download=title||'';document.body.append(a);a.click();a.remove();addHistory(title,'已交给浏览器下载');
}
function blobDownload(data,name,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);addHistory(name,'已生成本地文件');}
function player(track,url,type){if(!safeURL(url))throw new Error('没有可用音频链接');$('#player').hidden=false;$('#playerTitle').textContent=track.title;$('#playerArtist').textContent=track.artist||'';$('#playerArt').src=safeURL(track.artwork)||'../../icon.svg';$('#playerType').textContent=type;$('#audio').src=url;$('#audio').play().catch(e=>notice('播放失败：'+e.message,true));}
$('#audio').addEventListener('error',()=>notice('音频加载失败：来源可能不支持跨站播放，或该浏览器不支持此编码。',true));
$('#playerClose').onclick=()=>{$('#audio').pause();$('#audio').removeAttribute('src');$('#audio').load();$('#player').hidden=true;};
$('#tabs').innerHTML=Object.entries(meta).map(([id,m])=>`<a href="#${id}" data-tab="${id}"><b>${m[0]}</b>${m[1]}</a>`).join('');
function route(){let id=location.hash.slice(1)||'music';if(!meta[id])id='music';if(id!=='video')$('#videoPlayer').pause();$$('.view').forEach(x=>x.hidden=x.id!==id);$$('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$('#breadcrumb').textContent='发现 / '+meta[id][1];$('#eyebrow').textContent=meta[id][2];$('#title').innerHTML=meta[id][3];$('#subtitle').textContent=meta[id][4];notice('');window.scrollTo(0,0);if(!loaded.has(id)){loaded.add(id);if(id==='music')loadCharts();if(id==='novels'){renderShelf();loadNovelUpdates();checkShelf();}if(id==='anime')loadAnime();if(id==='torrent')loadTasks();}}
addEventListener('hashchange',route);
const countries=[['jp','日本'],['us','美国'],['cn','中国'],['tw','台湾'],['hk','香港'],['kr','韩国'],['gb','英国']];
$('#countries').innerHTML=countries.map(([id,name])=>`<button data-country="${id}">${name}</button>`).join('');
$$('[data-country]').forEach(b=>b.onclick=()=>{country=b.dataset.country;db.set('country',country);loadCharts();});$('#genre').value=genre;$('#genre').onchange=()=>{genre=$('#genre').value;db.set('genre',genre);loadCharts();};$('#chartRefresh').onclick=e=>busy(e.currentTarget,()=>loadCharts(true));
async function loadCharts(fresh=false){const request=++chartRequest,cc=country,gg=genre;$$('[data-country]').forEach(x=>x.classList.toggle('active',x.dataset.country===cc));$('#chartMeta').textContent='正在读取 '+countries.find(x=>x[0]===cc)?.[1]+' 榜单…';$('#chartList').innerHTML=empty('正在载入真实榜单…');let d,fallback=false;
 try{await snapshotReady;d=fresh?null:snapshot?.charts?.[cc+'-'+gg];fallback=!!d;if(!d)d=await api('charts',{country:cc,genre:gg,...(fresh?{refresh:'1'}:{})});}catch(e){d=snapshot?.charts?.[cc+'-'+gg];if(!d){if(request===chartRequest){$('#chartList').innerHTML=empty(e.message);$('#chartMeta').textContent='该地区 / 曲风暂无可用数据，可换一个分类重试。';}return;}fallback=true;if(fresh)notice('实时榜单暂不可用，保留最近成功快照：'+e.message,true);}
 if(request!==chartRequest)return;chartItems=d.items||[];$('#chartMeta').textContent=`${d.source} · ${date(d.updatedAt)}${fallback?' · 每日备份快照':' · 本次获取 '+date(d.fetchedAt)} · ${chartItems.length} 首 · 播放按钮为试听`;
 $('#chartList').innerHTML=chartItems.length?chartItems.map((x,i)=>`<article class="track"><span class="rank">${String(x.rank).padStart(2,'0')}</span><img loading="lazy" src="${href(x.artwork)}" alt=""><div class="track-info"><strong title="${esc(x.title)}">${esc(x.title)}</strong><small>${esc(x.artist)}</small></div><button data-preview="${i}" aria-label="试听 ${esc(x.title)}" ${x.preview?'':'disabled'}>▶</button>${x.preview?'':`<a href="${href(x.url)}" target="_blank" rel="noopener" title="在 Apple Music 打开">↗</a>`}<button class="find-track" data-find="${i}" title="搜索 FLAC">FLAC ↗</button></article>`).join(''):empty('该榜单内暂无此曲风；可以切换全部曲风。');
 $$('[data-preview]').forEach(b=>b.onclick=()=>{const t=chartItems[+b.dataset.preview];player(t,t.preview,'试听片段');});$$('[data-find]').forEach(b=>b.onclick=()=>{$('#musicQuery').value=chartItems[+b.dataset.find].artist+' '+chartItems[+b.dataset.find].title;searchMusic(b);});}
async function searchMusic(button){return busy(button,async()=>{
 const q=$('#musicQuery').value.trim();if(!q)return;const source=$('#musicSource').value;
 notice('正在搜索 '+(source==='archive'?'档案音源':'无损专辑')+'…');$('#musicResults').hidden=false;$('#albums').innerHTML=empty('查询中…');
 try{
  if(source==='qobuz'&&!engine)throw new Error('Qobuz 需要连接已配置你本人订阅凭据的私有下载引擎。请点击左下角 ⚙；免费档案与 Ektoplazm 可直接使用。');
  const d=source==='qobuz'?await callEngine('/music/qobuz/search',{q}):await api(source==='archive'?'music/search':'music/ektoplazm',{q});
  $('#musicSourceStatus').textContent=d.source||'';
  $('#albums').innerHTML=d.items.length?d.items.map((x,i)=>`<article class="card">${x.artwork?`<img loading="lazy" src="${href(x.artwork)}" alt="">`:''}<span class="badge">${source==='archive'?'档案 FLAC':x.format||'FLAC'}</span><h3>${esc(x.title)}</h3><p>${esc(x.artist)}</p><p class="caption">${esc(x.album||'')}${x.size?' · '+bytes(x.size):''}</p><div class="actions">${source==='qobuz'?`<select data-qobuz-quality="${i}" aria-label="音质"><option value="6">FLAC 16-bit / 44.1 kHz</option><option value="7">FLAC 24-bit ≤96 kHz</option><option value="27">FLAC 24-bit ≤192 kHz</option></select><button data-qobuz-download="${i}" ${x.available?'':'disabled'}>${x.available?'↓ 订阅音轨下载':'此账户不可用'}</button>`:source==='archive'?`<button data-track-download="${i}">↓ 下载 FLAC</button><button data-track-play="${i}">▶ 播放</button>`:`<a class="button" href="${href(x.downloadURL)}" target="_blank" rel="noopener">↓ 下载 FLAC 专辑</a>`}</div></article>`).join(''):empty('该来源没有匹配结果，请更换关键词或音源。');
  $$('[data-qobuz-download]').forEach(b=>b.onclick=()=>busy(b,()=>submitJob('qobuz',d.items[+b.dataset.qobuzDownload].id,$('[data-qobuz-quality="'+b.dataset.qobuzDownload+'"]').value)));
  $$('[data-album]').forEach(b=>b.onclick=()=>busy(b,()=>showArchive(d.items[+b.dataset.album])));
  const resolve=async (b,play)=>{const t=d.items[Number(play?b.dataset.trackPlay:b.dataset.trackDownload)];return busy(b,async()=>{notice('正在获取 FLAC 文件…');const f=await api('archive/file',{id:t.id,name:t.name});if(play){player(t,f.url,'FLAC');notice('正在播放档案中的 FLAC 文件');}else await saveRemote(f.downloadURL||f.url,t.artist+' - '+t.title+'.flac',true,f.size);});};
  $$('[data-track-download]').forEach(b=>b.onclick=()=>resolve(b,false));$$('[data-track-play]').forEach(b=>b.onclick=()=>resolve(b,true));
  notice(`找到 ${d.items.length} 个结果。`);
 }catch(e){$('#albums').innerHTML=empty(e.message);throw e;}
});}
async function saveRemote(url,name,verifyFLAC=false,size=0){
 if(size>128e6){const r=await fetch(url,{headers:{Range:'bytes=0-3'},signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error('文件不可访问：HTTP '+r.status);const reader=r.body.getReader(),first=await reader.read();await reader.cancel();if(verifyFLAC&&new TextDecoder().decode(first.value?.slice(0,4))!=='fLaC')throw new Error('文件签名不是 FLAC');downloadURL(url,name);notice('FLAC 文件已验证，已交给浏览器下载（'+bytes(size)+'）；完成情况请查看浏览器下载列表。');return;}

 notice('正在下载 '+name+'…');const r=await fetch(url,{signal:AbortSignal.timeout(240000)});if(!r.ok)throw new Error('文件下载失败：HTTP '+r.status);
 const blob=await r.blob();if(verifyFLAC&&await blob.slice(0,4).text()!=='fLaC')throw new Error('收到的文件不是 FLAC，已停止保存');
 if(!blob.size)throw new Error('下载文件为空');blobDownload(blob,name);notice('已生成下载文件：'+name+' · '+bytes(blob.size));
}
$('#musicSearch').onsubmit=e=>{e.preventDefault();searchMusic(e.submitter);};
async function showArchive(item){$('#files').showModal();$('#filesTitle').textContent=item.title;$('#filesList').innerHTML=empty('正在核验文件格式…');let d;try{d=await api('archive/files',{id:item.id});}catch(e){$('#filesList').innerHTML=empty(e.message);throw e;}const files=d.files.filter(x=>/\.flac$/i.test(x.name));$('#filesList').innerHTML=(files.length?files.map((f,i)=>`<div class="file-row"><strong>${esc(f.name)}</strong><p>${esc(f.format)} · ${bytes(f.size)}</p><div class="actions"><button data-file-play="${i}">▶ 播放</button><button data-file-save="${i}">↓ FLAC</button></div></div>`).join(''):empty('该资源目前没有可公开访问的 FLAC 文件。'))+`<p>来源许可证：${esc(d.license||'来源未提供许可证字段；请查看原始资源说明')}</p>`;$$('[data-file-play]').forEach(b=>b.onclick=()=>player({...item,title:files[+b.dataset.filePlay].name},files[+b.dataset.filePlay].url,'FLAC'));$$('[data-file-save]').forEach(b=>b.onclick=()=>downloadURL(files[+b.dataset.fileSave].url,files[+b.dataset.fileSave].name));}
function renderShelf(){$('#bookshelf').innerHTML=shelf.length?shelf.map((x,i)=>`<article class="card"><span class="badge">${esc(x.source||'书架')}</span><h3>${esc(x.title)}</h3><p>${x.chapters||0} 章${x.watch?' · 追更中':''}${x.newChapters?' · 新增 '+x.newChapters+' 章':''} · 上次 ${date(x.time)}</p><div class="actions"><button data-book="${i}">继续阅读</button><button data-remove-book="${i}" aria-label="移除 ${esc(x.title)}">移除</button></div></article>`).join(''):empty('书架还很安静。粘贴第一本小说的链接，或导入本地 TXT 开始阅读。');$$('[data-book]').forEach(b=>b.onclick=()=>openNovel(shelf[+b.dataset.book].url,b));$$('[data-remove-book]').forEach(b=>b.onclick=()=>{shelf.splice(+b.dataset.removeBook,1);db.set('shelf',shelf);renderShelf();});}
async function openNovel(url,button){if(exportRunning){notice('请先完成或停止当前小说打包。',true);return;}return busy(button,async()=>{$('#novelURL').value=url;notice('正在读取小说目录…');const d=await api('novel',{url});readerRequest++;book=d;shelf=[{...shelf.find(x=>x.url===d.url),title:d.title,url:d.url,chapters:d.chapters.length,source:d.source,time:new Date().toISOString()},...shelf.filter(x=>x.url!==d.url)].slice(0,60);db.set('shelf',shelf);renderShelf();$('#novelDetail').hidden=false;$('#novelDetail').innerHTML=`<span class="badge">${esc(d.source)}</span><h2>${esc(d.title)}</h2><p class="caption">${d.chapters.length} 章 · ${date(d.fetchedAt)} · 网页直接阅读 / 文字版 EPUB</p><div class="actions"><button id="bookContinue" class="primary">继续阅读</button><label>从 <input id="exportFrom" type="number" min="1" max="${d.chapters.length}" value="1" style="width:5em"> 到 <input id="exportTo" type="number" min="1" max="${d.chapters.length}" value="${d.chapters.length}" style="width:5em"> 章</label><button id="bookEPUB">下载 EPUB</button><button id="bookAlternative">查找其他版本</button><button id="exportCancel" hidden>停止打包</button><button id="bookWatch">${shelf.find(x=>x.url===d.url)?.watch?'停止本机追更':'加入本机追更'}</button><p id="exportStatus" role="status"></p><a href="${href(d.url)}" target="_blank" rel="noopener">原站 ↗</a></div><div class="chapters">${d.chapters.map((c,i)=>`<button class="chapter-row" data-chapter="${i}">${i+1}. ${esc(c.title)}</button>`).join('')}</div>`;$$('[data-chapter]').forEach(b=>b.onclick=()=>busy(b,()=>readChapter(+b.dataset.chapter)));$('#bookContinue').onclick=e=>busy(e.currentTarget,()=>readChapter(Math.min(db.get('progress',{})[d.url]||0,d.chapters.length-1)));$('#bookEPUB').onclick=e=>busy(e.currentTarget,exportBook);$('#bookAlternative').onclick=findBookAlternatives;$('#exportCancel').onclick=()=>{exportStopped=true;};$('#bookWatch').onclick=e=>{const item=shelf.find(x=>x.url===d.url);item.watch=!item.watch;db.set('shelf',shelf);e.currentTarget.textContent=item.watch?'停止本机追更':'加入本机追更';renderShelf();notice(item.watch?'已追更：打开小说页时每天检查一次，也可点击“检查书架更新”。无需运行下载引擎。':'已停止追更');};notice('目录已载入。');$('#novelDetail').scrollIntoView({behavior:'smooth'});});}
$('#novelSearch').onsubmit=e=>{e.preventDefault();const q=$('#novelURL').value.trim();if(/^https?:\/\//i.test(q))openNovel(q,e.submitter);else busy(e.submitter,()=>searchNovelTitles(q));};
let exportStopped=false,exportRunning=false,readerRequest=0;

const chapterDB=new Promise(resolve=>{try{const r=indexedDB.open('media-vault-reading',1);const timer=setTimeout(()=>resolve(null),2000);r.onupgradeneeded=()=>r.result.createObjectStore('chapters');r.onsuccess=()=>{clearTimeout(timer);resolve(r.result);};r.onerror=r.onblocked=()=>{clearTimeout(timer);resolve(null);};}catch{resolve(null);}});
async function chapterCache(key,value){const storage=await chapterDB;if(!storage)return null;try{return await new Promise(resolve=>{const tx=storage.transaction('chapters',value?'readwrite':'readonly'),table=tx.objectStore('chapters'),r=value?table.put(value,key):table.get(key);let result=null;r.onsuccess=()=>{result=r.result;};tx.oncomplete=()=>resolve(result);tx.onerror=tx.onabort=()=>resolve(null);});}catch{return null;}}
async function cachedChapter(url){const key='v4:'+url,old=await chapterCache(key);if(old)return old;const d=await api('chapter',{url});if(!d.text?.trim()&&!d.blocks?.some(b=>b.type==='image'))throw new Error('来源没有返回完整正文，已停止导出');await chapterCache(key,d);return d;}
async function readChapter(index){
 if(!book||index<0||index>=book.chapters.length)return;const request=++readerRequest,target=book;chapterIndex=index;const c=target.chapters[index];$('#readerPrev').disabled=true;$('#readerNext').disabled=true;
 readerContent='';$('#readerRetry').hidden=true;$('#readerAlternative').hidden=true;$('#readerDownload').disabled=true;$('#readerEPUB').disabled=true;$('#readerTitle').textContent=book.title+' · '+c.title;$('#readerText').textContent='正在读取完整章节与分页…';if(!$('#reader').open)$('#reader').showModal();
 try{const d=await cachedChapter(c.url);if(request!==readerRequest)return;readerContent=d.text;readerName=d.title||c.title;$('#readerDownload').disabled=!readerContent;$('#readerEPUB').disabled=!readerContent;
 $('#readerTitle').textContent=book.title+' · '+readerName;
 $('#readerText').innerHTML=d.blocks?.length?d.blocks.map(b=>b.type==='image'?`<img loading="lazy" referrerpolicy="no-referrer" src="${href(b.url)}" alt="章节插图" style="max-width:100%;height:auto">`:`<p>${esc(b.text)}</p>`).join(''):esc(d.text).replace(/\n/g,'<br>');
 $('#readerPrev').disabled=index===0;$('#readerNext').disabled=index===book.chapters.length-1;$('#reader').scrollTop=0;
 const progress=db.get('progress',{});progress[book.url]=index;db.set('progress',progress);
 }catch(e){if(request!==readerRequest)return;$('#readerText').textContent=e.message;$('#readerRetry').hidden=false;$('#readerAlternative').hidden=false;throw e;}finally{if(request===readerRequest){$('#readerPrev').disabled=index===0;$('#readerNext').disabled=index===target.chapters.length-1;}}
}
async function exportBook(){
 if(exportRunning)throw new Error('已有小说正在打包');
 const from=Number($('#exportFrom').value),to=Number($('#exportTo').value),target=book;
 if(!Number.isInteger(from)||!Number.isInteger(to)||from<1||to<from||to>target.chapters.length)throw new Error('请选择有效章节范围');
 exportRunning=true;exportStopped=false;$('#exportCancel').hidden=false;const chapters=[];
 try{for(let i=from-1;i<to;i++){if(exportStopped)throw new Error('已停止，已抓取章节保留在本机，下次继续会复用');$('#exportStatus').textContent=`正在读取 ${i-from+2} / ${to-from+1}：${target.chapters[i].title}。请保持页面打开。`;const d=await cachedChapter(target.chapters[i].url);if(exportStopped)throw new Error('已停止打包，已读取章节保留在本机缓存');chapters.push({title:d.title||target.chapters[i].title,text:d.text||'本章为插图，文字版 EPUB 不包含图片。'});}
 const filename=target.title+(from===1&&to===target.chapters.length?'':`（${from}—${to}章）`);await createBookEPUB(filename,chapters);$('#exportStatus').textContent=`完成：${chapters.length} 章文字版 EPUB。`;
 }catch(e){$('#exportStatus').textContent='未完成：'+e.message;throw e;}finally{exportRunning=false;$('#exportCancel').hidden=true;}
}
async function createBookEPUB(title,chapters){
 const zip=new JSZip(),uid=crypto.randomUUID();zip.file('mimetype','application/epub+zip',{compression:'STORE'});
 zip.file('META-INF/container.xml','<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles></container>');
 chapters.forEach((c,i)=>zip.file(`OEBPS/c${i}.xhtml`,`<?xml version="1.0" encoding="UTF-8"?><html xmlns="http://www.w3.org/1999/xhtml" lang="zh"><head><title>${esc(c.title)}</title></head><body><h1>${esc(c.title)}</h1>${c.text.split(/\n+/).map(t=>'<p>'+esc(t)+'</p>').join('')}</body></html>`));
 zip.file('OEBPS/nav.xhtml',`<?xml version="1.0" encoding="UTF-8"?><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops"><head><title>目录</title></head><body><nav epub:type="toc"><ol>${chapters.map((c,i)=>`<li><a href="c${i}.xhtml">${esc(c.title)}</a></li>`).join('')}</ol></nav></body></html>`);
 zip.file('OEBPS/content.opf',`<?xml version="1.0" encoding="UTF-8"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="uid"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="uid">urn:uuid:${uid}</dc:identifier><dc:title>${esc(title)}</dc:title><dc:language>zh</dc:language><meta property="dcterms:modified">${new Date().toISOString().replace(/\.\d+Z/,'Z')}</meta></metadata><manifest><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>${chapters.map((_,i)=>`<item id="c${i}" href="c${i}.xhtml" media-type="application/xhtml+xml"/>`).join('')}</manifest><spine>${chapters.map((_,i)=>`<itemref idref="c${i}"/>`).join('')}</spine></package>`);
 blobDownload(await zip.generateAsync({type:'blob',mimeType:'application/epub+zip'}),title+'.epub');
}
$('#readerPrev').onclick=e=>busy(e.currentTarget,()=>readChapter(chapterIndex-1));$('#readerNext').onclick=e=>busy(e.currentTarget,()=>readChapter(chapterIndex+1));$('#readerDownload').onclick=()=>blobDownload(readerContent,readerName+'.txt');$('#fontMinus').onclick=()=>{$('#readerText').style.fontSize=(fontSize=Math.max(14,fontSize-1))+'px';};$('#fontPlus').onclick=()=>{$('#readerText').style.fontSize=(fontSize=Math.min(32,fontSize+1))+'px';};
$('#txtImport').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>8e6){notice('TXT 最大支持 8 MB',true);return;}readerRequest++;readerContent=await f.text();$('#readerDownload').disabled=false;$('#readerEPUB').disabled=false;readerName=f.name.replace(/\.txt$/i,'');$('#readerTitle').textContent=readerName;$('#readerText').textContent=readerContent;$('#readerPrev').disabled=true;$('#readerNext').disabled=true;if(!$('#reader').open)$('#reader').showModal();e.target.value='';};
async function loadNovelUpdates(){try{const d=await api('novel/updates');renderNovelUpdates(d);}catch(e){if(snapshot?.novels)renderNovelUpdates(snapshot.novels);else $('#novelUpdates').innerHTML=empty(e.message);}}
function renderNovelUpdates(d){$('#novelUpdates').innerHTML=d.sources.map(s=>`<article class="card"><span class="badge">${s.ok?'已更新':'来源暂不可用'}</span><h3>${esc(new URL(s.url).hostname)}</h3><p>${date(s.fetchedAt)} · ${esc(s.error||'公开更新列表')}</p>${s.items.slice(0,12).map(x=>`<button class="chapter-row" data-update-url="${esc(x.url)}">${esc(x.title)}</button>`).join('')}<a href="${href(s.url)}" target="_blank" rel="noopener">原站查看 ↗</a></article>`).join('');$$('[data-update-url]').forEach(b=>b.onclick=()=>openNovel(b.dataset.updateUrl,b));}
$('#novelRefresh').onclick=e=>busy(e.currentTarget,loadNovelUpdates);
const toSimplified=OpenCC.Converter({from:'tw',to:'cn'}),toTraditional=OpenCC.Converter({from:'cn',to:'tw'});
const normalizeTitle=s=>toSimplified(String(s)).normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
const matchesTitle=(title,q)=>q.trim().split(/\s+/).every(term=>normalizeTitle(title).includes(normalizeTitle(term)));
let animeRequest=0,animeCatalogItems=null,animeFiltered=[],animePage=1,animeCategory=null;
async function loadAnime(q='',fresh=false){
 const request=++animeRequest;animeCategory=null;$('#animeBack').hidden=true;$('#animeList').innerHTML=empty('正在读取完整番剧目录…');
 try{if(!animeCatalogItems||fresh){const d=await api('anime',fresh?{refresh:'1'}:{});if(request!==animeRequest)return;animeCatalogItems=d.items.map(x=>({...x,normalized:normalizeTitle(x.title)}));const year=$('#animeYear'),value=year.value;year.innerHTML='<option value="">全部年份</option>'+[...new Set(d.items.map(x=>x.year).filter(Boolean))].sort().reverse().map(y=>`<option>${esc(y)}</option>`).join('');year.value=value;}
 if(request!==animeRequest)return;$('#animeQuery').value=q;filterAnime();
 }catch(e){if(request===animeRequest){$('#animeList').innerHTML=empty(e.message);$('#animeMeta').textContent='目录读取失败';$('#animePager').hidden=true;}}
}
function filterAnime(){
 if(!animeCatalogItems)return;animeRequest++;animeCategory=null;$('#animeBack').hidden=true;
 const q=$('#animeQuery').value,year=$('#animeYear').value,season=$('#animeSeason').value,terms=q.trim().split(/\s+/).map(normalizeTitle).filter(Boolean);
 animeFiltered=animeCatalogItems.filter(x=>(!year||x.year===year)&&(!season||x.season===season)&&terms.every(t=>x.normalized.includes(t)));animePage=1;renderAnime();
}
function renderAnime(){
 const totalPages=Math.max(1,Math.ceil(animeFiltered.length/36));animePage=Math.min(animePage,totalPages);const rows=animeFiltered.slice((animePage-1)*36,animePage*36);
 $('#animeMeta').textContent=`完整目录 ${animeCatalogItems.length} 部 · 匹配 ${animeFiltered.length} 部 · 简繁体通用`;
 $('#animeList').innerHTML=rows.length?rows.map(x=>`<article class="card"><span class="badge">${esc(x.year)} ${esc(x.season)}</span><h3>${esc(x.title)}</h3><p>${esc(x.episodes)}${x.group?' · '+esc(x.group):''}</p><div class="actions"><button data-series="${x.id}">查看剧集</button><a href="${href(x.url)}" target="_blank" rel="noopener">原站 ↗</a></div></article>`).join(''):empty('目录中没有匹配番剧，请减少关键词或清除年份筛选。');
 $('#animePager').hidden=false;$('#animePageLabel').textContent=`第 ${animePage} / ${totalPages} 页`;$('#animePrev').disabled=animePage<=1;$('#animeNext').disabled=animePage>=totalPages;
 $$('[data-series]').forEach(b=>b.onclick=()=>busy(b,()=>loadEpisodes(b.dataset.series,1)));
}
async function loadEpisodes(id,page=1){
 const request=++animeRequest;animeCategory=id;$('#animePrev').disabled=true;$('#animeNext').disabled=true;$('#animeList').innerHTML=empty('正在读取剧集…');$('#animeBack').hidden=false;
 try{const d=await api('anime/episodes',{id,page});if(request!==animeRequest)return;animePage=page;
 $('#animeMeta').textContent=(animeCatalogItems?.find(x=>String(x.id)===String(id))?.title||'番剧')+' · 剧集按最近发布排列';
 $('#animeList').innerHTML=d.items.length?d.items.map((x,i)=>`<article class="card"><h3>${esc(x.title)}</h3><div class="actions"><button data-episode="${i}">解析 / 播放</button><a href="${href(x.url)}" target="_blank" rel="noopener">原站 ↗</a></div></article>`).join(''):empty('本页没有可用剧集');
 $('#animePager').hidden=false;$('#animePageLabel').textContent='剧集第 '+page+' 页';$('#animePrev').disabled=page<=1;$('#animeNext').disabled=!d.hasNext;
 $$('[data-episode]').forEach(b=>b.onclick=()=>parseVideo(d.items[+b.dataset.episode].url,b));
 }catch(e){if(request===animeRequest){$('#animeList').innerHTML=empty(e.message);$('#animePager').hidden=true;}}
}
$('#animeSearch').onsubmit=e=>{e.preventDefault();const q=$('#animeQuery').value.trim();if(/^https:\/\//i.test(q)){try{const u=new URL(q);if(u.hostname==='anime1.me'&&u.searchParams.has('cat'))busy(e.submitter,()=>loadEpisodes(u.searchParams.get('cat')));else parseVideo(q,e.submitter);}catch{notice('链接无效',true);}}else busy(e.submitter,()=>loadAnime(q));};
$('#animeRefresh').onclick=e=>busy(e.currentTarget,()=>loadAnime($('#animeQuery').value,true));
$('#animeYear').onchange=$('#animeSeason').onchange=filterAnime;
$('#animeBack').onclick=()=>{animeRequest++;filterAnime();};
for(const [id,delta] of [['animePrev',-1],['animeNext',1]])$('#'+id).onclick=e=>{if(animeCategory)loadEpisodes(animeCategory,animePage+delta);else{animePage+=delta;renderAnime();$('#animeMeta').scrollIntoView({block:'start'});}};
let novelCatalogItems=null,novelSearchRequest=0;
async function searchNovelTitles(q){
 const request=++novelSearchRequest;$('#novelMatches').hidden=false;$('#novelMatches').innerHTML=empty('正在查找书名与其他版本…');
 try{if(!novelCatalogItems){const d=await api('novel/catalog');novelCatalogItems=d.items;}if(request!==novelSearchRequest)return;
 const items=novelCatalogItems.filter(x=>matchesTitle(x.title+' '+x.alias+' '+x.author,q));let count=40;
 const render=()=>{$('#novelMatches').innerHTML=`<p class="caption">找到 ${items.length} 本 · 选择后使用该版本的独立目录、阅读进度与导出</p>`+(items.length?items.slice(0,count).map((x,i)=>`<article class="card"><span class="badge">${esc(x.source)}</span><h3>${esc(x.title)}</h3><p>${esc(x.author)} ${esc(x.alias)}</p><button data-novel-match="${i}">打开此版本</button></article>`).join(''):empty('没有匹配书名。请减少关键词，或直接粘贴来源链接。'))+(items.length>count?'<button id="novelMore">显示更多</button>':'');$$('[data-novel-match]').forEach(b=>b.onclick=()=>openNovel(items[+b.dataset.novelMatch].url,b));if($('#novelMore'))$('#novelMore').onclick=()=>{count+=40;render();};};render();
 }catch(e){if(request===novelSearchRequest)$('#novelMatches').innerHTML=empty(e.message);}
}
function findBookAlternatives(){if(!book)return;readerRequest++;if($('#reader').open)$('#reader').close();const q=book.title.split(/[（(]/)[0].replace(/[。.!！]+$/,'');$('#novelURL').value=q;searchNovelTitles(q);$('#novelMatches').scrollIntoView({behavior:'smooth'});}
$('#readerRetry').onclick=e=>busy(e.currentTarget,()=>readChapter(chapterIndex));
$('#readerAlternative').onclick=findBookAlternatives;
async function parseVideo(url,button){return busy(button,async()=>{location.hash='video';$('#videoURL').value=url;$('#videoResult').innerHTML=empty('解析中…');notice('');try{const native=new URL(url).hostname==='anime1.me';const d=native||!engine?await api('video',{url}):await callEngine('/resolve',{url});const formats=d.formats||[];$('#videoResult').innerHTML=`<div class="section-head"><h2>${esc(d.title)}</h2><span class="badge">${formats.length} 个选项</span></div>${engine&&!native?'<button id="videoBest" class="primary">↓ 下载并合并最佳画质</button>':''}<div>${formats.map((f,i)=>`<div class="file-row"><strong>${esc(f.label||f.format||f.ext||'媒体')}</strong><p>${esc(f.note||'')} ${f.size?bytes(f.size):''}${f.audioOnly?' · 仅音频':f.videoOnly?' · 仅视频，需合并':''}</p><div class="actions">${f.url&&!f.videoOnly?`<button data-video-play="${i}">▶ 尝试播放</button>`:''}<button data-video-save="${i}">↓ ${engine&&!native?'下载此格式':native?'下载 MP4':'打开媒体链接'}</button></div></div>`).join('')}</div><p class="caption">HLS / DASH 是分片清单，浏览器是否能播放取决于系统；保存合并文件请使用引擎。纯视频轨道不包含声音。</p>`;$$('[data-video-play]').forEach(b=>b.onclick=()=>{const f=formats[+b.dataset.videoPlay];$('#audio').pause();$('#videoPlayer').hidden=false;$('#subtitleLabel').hidden=false;$('#videoPlayer').src=safeURL(f.url);$('#videoPlayer').scrollIntoView({behavior:'smooth',block:'center'});$('#videoPlayer').play().catch(e=>notice('浏览器无法直接播放此格式：'+e.message,true));});$$('[data-video-save]').forEach(b=>b.onclick=()=>busy(b,()=>engine&&!native?submitJob('video',url,formats[+b.dataset.videoSave].id):downloadURL(formats[+b.dataset.videoSave].downloadURL||formats[+b.dataset.videoSave].url,d.title)));if(native&&$('[data-video-play]'))$('[data-video-play]').click();if($('#videoBest'))$('#videoBest').onclick=e=>busy(e.currentTarget,()=>submitJob('video',url));}catch(e){$('#videoResult').innerHTML=empty(e.message);throw e;}});}
$('#videoForm').onsubmit=e=>{e.preventDefault();parseVideo($('#videoURL').value.trim(),e.submitter);};$('#videoPlayer').onerror=()=>notice('视频无法直接播放，可尝试下载引擎或返回原站。',true);
let subtitleBlob;$('#subtitleImport').onchange=e=>{const f=e.target.files[0];if(!f)return;if(subtitleBlob)URL.revokeObjectURL(subtitleBlob);subtitleBlob=URL.createObjectURL(f);$('#videoPlayer').querySelectorAll('track').forEach(t=>t.remove());const t=document.createElement('track');t.kind='subtitles';t.label='中文字幕';t.srclang='zh';t.src=subtitleBlob;t.default=true;$('#videoPlayer').append(t);};
async function submitJob(kind,url,format){const d=await callEngine('/jobs',{kind,url,format});notice('任务已提交到你的引擎：'+d.id+'。在下载任务中查看进度与结果。');addHistory(url,'引擎任务已提交');await loadTasks();return d;}
$('#torrentForm').onsubmit=e=>{e.preventDefault();const url=$('#torrentURL').value.trim();if(engine){busy(e.submitter,()=>submitJob('torrent',url));return;}busy(e.submitter,()=>{if(/^magnet:\?xt=urn:btih:[a-z0-9]+/i.test(url)){const a=document.createElement('a');a.href=url;document.body.append(a);a.click();a.remove();notice('已请求本机 BT 客户端接手。需先安装支持磁力链接的客户端；无需常驻服务器。');}else if(safeURL(url)){downloadURL(url,'种子或直链文件');notice('已打开文件下载。种子文件请用本机 BT 客户端打开。');}else throw new Error('请输入磁力链接或有效 HTTP(S) 下载链接');});};
function openSettings(){$('#engineURL').value=engine?.url||localStorage.getItem('mv.engine.url')||'http://localhost:8789';$('#engineToken').value=engine?.token||'';$('#settings').showModal();}
$('#settingsOpen').onclick=openSettings;$('#torrentConnect').onclick=openSettings;
$('#engineSave').onclick=e=>busy(e.currentTarget,async()=>{const u=new URL($('#engineURL').value.trim());if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.search||u.hash)throw new Error('引擎地址无效');if(u.protocol==='http:'&&!['localhost','127.0.0.1','[::1]'].includes(u.hostname))throw new Error('远程引擎请使用 HTTPS 地址');const config={url:u.href.replace(/\/$/,''),token:$('#engineToken').value.trim()};if(config.token.length<24)throw new Error('请输入完整访问密钥');$('#settingsStatus').textContent='正在连接…';try{await callEngine('/health',null,config);engine=config;sessionStorage.setItem('mv.engine',JSON.stringify(config));localStorage.setItem('mv.engine.url',config.url);$('#settingsStatus').textContent='连接成功。现在可以提交 BT、视频和小说任务。';$('#engineStatus').textContent='● 引擎已连接';loadTasks();}catch(e){$('#settingsStatus').textContent='连接失败：'+e.message;throw e;}});
$('#engineDisconnect').onclick=()=>{engine=null;sessionStorage.removeItem('mv.engine');$('#engineToken').value='';$('#engineStatus').textContent='网页直连模式';$('#settingsStatus').textContent='已断开';engineJobs=[];loadTasks();};$$('[data-close]').forEach(b=>b.onclick=()=>{if(b.dataset.close==='reader')readerRequest++;$('#'+b.dataset.close).close();});
const statuses={queued:'排队中',running:'处理中',active:'下载中',waiting:'等待中',paused:'已暂停',complete:'已完成',error:'失败',interrupted:'引擎重启，需重新提交',cancelled:'已取消'};
function taskHTML(j){const progress=j.total?Math.min(100,100*j.completed/j.total):null;return `<div class="task-row"><strong>${esc(j.title||j.url||j.id)}</strong><p class="caption">${esc(statuses[j.status]||j.status)} ${progress===null?'':progress.toFixed(1)+'%'} · ${bytes(j.completed||0)} ${j.total?'/ '+bytes(j.total):''}${j.speed?' · '+bytes(j.speed)+'/s':''}</p>${progress===null?'':`<div class="progress"><i style="width:${progress}%"></i></div>`}${j.error?`<p>${esc(j.error)}</p>`:''}<div class="actions">${j.status==='complete'?`<button data-job-files="${esc(j.id)}">查看 / 取回文件</button>`:''}${['running','active','waiting','queued','paused'].includes(j.status)?`<button data-job-cancel="${esc(j.id)}">取消任务</button>`:''}</div></div>`;}
async function loadTasks(){if(!engine){$('#torrentTasks').innerHTML=empty('尚未连接引擎。连接后显示实际进度、速度和文件列表。');renderQueue();return;}try{const d=await callEngine('/jobs');engineJobs=d.jobs;$('#engineStatus').textContent='● 引擎已连接';$('#torrentTasks').innerHTML=engineJobs.length?engineJobs.map(taskHTML).join(''):empty('下载队列为空');renderQueue();bindTasks();}catch(e){$('#engineStatus').textContent='引擎连接失败';$('#torrentTasks').innerHTML=empty(e.message);}}
function renderQueue(){$('#queueList').innerHTML=engineJobs.map(taskHTML).join('')+history.slice(0,30).map(x=>`<div class="task-row"><strong>${esc(x.title)}</strong><p class="caption">${esc(x.status)} · ${date(x.time)}</p></div>`).join('')||empty('暂无任务。');$('#queueCount').textContent=engineJobs.filter(x=>['running','queued','active','waiting'].includes(x.status)).length||history.length;bindTasks();}
function bindTasks(){$$('[data-job-files]').forEach(b=>b.onclick=()=>busy(b,()=>showJobFiles(b.dataset.jobFiles)));$$('[data-job-cancel]').forEach(b=>b.onclick=()=>busy(b,async()=>{await callEngine('/jobs/cancel',{id:b.dataset.jobCancel});loadTasks();}));}
async function showJobFiles(id){const d=await callEngine('/jobs/files?id='+encodeURIComponent(id));$('#filesTitle').textContent='已完成文件';$('#filesList').innerHTML=d.files.map((f,i)=>`<div class="file-row"><strong>${esc(f.name)}</strong><p>${bytes(f.size)}</p><button data-engine-file="${i}">↓ 保存到本机</button></div>`).join('')||empty('没有可下载文件');if(!$('#files').open)$('#files').showModal();$$('[data-engine-file]').forEach(b=>b.onclick=()=>busy(b,async()=>{const f=d.files[+b.dataset.engineFile];const ticket=await callEngine('/download-ticket',{id,path:f.path});downloadURL(engine.url+'/download?ticket='+encodeURIComponent(ticket.ticket),f.name);}));}
$('#queueOpen').onclick=()=>{renderQueue();$('#queue').showModal();loadTasks();};$('#queueRefresh').onclick=e=>busy(e.currentTarget,loadTasks);$('#torrentRefresh').onclick=e=>busy(e.currentTarget,loadTasks);setInterval(()=>{if(engine&&!document.hidden&&(location.hash==='#torrent'||$('#queue').open))loadTasks();},6000);
const snapshotReady=fetch('data/snapshot.json',{cache:'no-cache',signal:AbortSignal.timeout(8000)}).then(r=>r.ok?r.json():null).then(d=>{snapshot=d;}).catch(()=>{});
if(engine)callEngine('/health').then(()=>{$('#engineStatus').textContent='● 引擎已连接';}).catch(()=>{$('#engineStatus').textContent='引擎连接失败';});
renderQueue();queueMicrotask(route);

$('#readerEPUB').onclick=e=>busy(e.currentTarget,async()=>{
 const zip=new JSZip(),id=crypto.randomUUID(),xml=s=>esc(s);
 zip.file('mimetype','application/epub+zip',{compression:'STORE'});
 zip.file('META-INF/container.xml','<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles></container>');
 zip.file('OEBPS/content.opf',`<?xml version="1.0" encoding="UTF-8"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="uid"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="uid">urn:uuid:${id}</dc:identifier><dc:title>${xml(readerName)}</dc:title><dc:language>zh</dc:language><meta property="dcterms:modified">${new Date().toISOString().replace(/\.\d+Z/,'Z')}</meta></metadata><manifest><item id="chapter" href="chapter.xhtml" media-type="application/xhtml+xml"/><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/></manifest><spine><itemref idref="chapter"/></spine></package>`);
 zip.file('OEBPS/chapter.xhtml',`<?xml version="1.0" encoding="UTF-8"?><html xmlns="http://www.w3.org/1999/xhtml" lang="zh"><head><title>${xml(readerName)}</title></head><body><h1>${xml(readerName)}</h1>${readerContent.split(/\n+/).map(p=>'<p>'+xml(p)+'</p>').join('')}</body></html>`);
 zip.file('OEBPS/nav.xhtml',`<?xml version="1.0" encoding="UTF-8"?><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops"><head><title>目录</title></head><body><nav epub:type="toc"><ol><li><a href="chapter.xhtml">${xml(readerName)}</a></li></ol></nav></body></html>`);
 blobDownload(await zip.generateAsync({type:'blob',mimeType:'application/epub+zip'}),readerName+'.epub');
});
let checkingShelf=false;
async function checkShelf(force=false){
 if(checkingShelf)return;const day=new Date().toLocaleDateString('en-CA'),items=shelf.filter(x=>x.watch&&(force||x.checkedDay!==day));if(!items.length){if(force)notice('暂无待检查的追更小说。打开小说后点击“加入本机追更”。');return;}
 checkingShelf=true;let changed=0,failed=0;
 try{for(const item of items){try{const d=await api('novel',{url:item.url,...(force?{refresh:'1'}:{})});const current=shelf.find(x=>x.url===item.url);if(!current)continue;current.newChapters=Math.max(0,d.chapters.length-(item.chapters||0));changed+=current.newChapters;current.chapters=d.chapters.length;current.checkedDay=day;current.time=new Date().toISOString();}catch{failed++;}}db.set('shelf',shelf);renderShelf();notice(`书架检查完成：新增 ${changed} 章${failed?'，'+failed+' 本来源暂不可用':''}。`);}finally{checkingShelf=false;}
}
$('#watchManage').onclick=e=>busy(e.currentTarget,()=>checkShelf(true));
$('#serviceCheck').onclick=e=>busy(e.currentTarget,async()=>{const label=$('#serviceStatus');label.textContent='正在检测连接…';try{const d=await api('health');label.textContent='媒体服务已连接 · v'+d.version;notice('媒体服务可连接。各来源的可用情况请查看搜索结果；服务连接成功不代表所有来源可用。');}catch(e){label.textContent='媒体服务暂不可达';throw e;}});
// Keep failed remote artwork from leaving broken-image icons in the UI.
document.addEventListener('error',e=>{const img=e.target;if(img.tagName==='IMG'&&!img.classList.contains('cover-fallback')){img.classList.add('cover-fallback');img.src='../../icon.svg';}},true);

$('#torrentSearch').onsubmit=e=>{e.preventDefault();busy(e.submitter,async()=>{
 const q=$('#torrentQuery').value.trim();if(!q)return;$('#torrentResults').innerHTML=empty('正在同时查询多个来源…');$('#torrentSourceStatus').textContent='';
 try{const simple=toSimplified(q),traditional=toTraditional(q);const d=await api('torrent/search',{q:simple,variant:traditional,source:$('#torrentSource').value});$('#torrentSourceStatus').textContent=d.sources.map(s=>s.source+'：'+(s.ok?s.count+' 条':s.error)).join(' · ');
 $('#torrentResults').innerHTML=d.items.length?d.items.map((x,i)=>`<article class="card"><span class="badge">${esc((x.sources||[x.source]).join(' / '))}</span><h3>${esc(x.title)}</h3><p>${x.sizeBytes?bytes(x.sizeBytes):esc(x.size||'')} · 做种 ${x.seeders===null||x.seeders===undefined?'未知':x.seeders}${x.tracker?' · '+esc(x.tracker):''}</p><p class="caption">${x.publishedAt?'发布 '+esc(x.publishedAt):''}${x.lastSeen?' · 最近收录 '+esc(x.lastSeen):''}</p><div class="actions">${/^magnet:\?xt=urn:btih:/i.test(x.magnet)?`<a class="button" href="${esc(x.magnet)}">打开磁力</a><button data-magnet-copy="${i}">复制磁力</button>`:''}${/^https?:/.test(x.torrent)?`<a class="button" href="${href(x.torrent)}" target="_blank" rel="noopener">下载种子</a>`:''}${x.url?`<a href="${href(x.url)}" target="_blank" rel="noopener">资源详情 ↗</a>`:''}${engine?`<button data-torrent-send="${i}">加入引擎下载</button>`:''}</div></article>`).join(''):empty('没有可用结果。请检查上方来源状态或换一个关键词。');
 $$('[data-magnet-copy]').forEach(b=>b.onclick=()=>busy(b,async()=>{await navigator.clipboard.writeText(d.items[+b.dataset.magnetCopy].magnet);b.textContent='已复制';}));
 $$('[data-torrent-send]').forEach(b=>b.onclick=()=>busy(b,()=>{const x=d.items[+b.dataset.torrentSend];return submitJob('torrent',x.magnet||x.torrent);}));
 }catch(err){$('#torrentResults').innerHTML=empty(err.message);throw err;}
});};
