import {DEFAULT,validate,createGame,play,endTurn,simulate} from './engine.mjs';
const H=PTContent,{esc,url,img}=H,$=s=>document.querySelector(s),KEY='ptu.cardlab.config',types={attack:'攻击',guard:'护盾',heal:'治疗',bleed:'裂伤'},signs={attack:'⚔',guard:'◈',heal:'✚',bleed:'❖'};
let config;try{config=validate(H.read(KEY,DEFAULT));}catch{config=structuredClone(DEFAULT);}let draft=structuredClone(config),game=createGame(config,42),assets=null;const favorites=H.read('ptu.cardlab.assets',[]);H.theme();
function note(id,t,bad=false){$('#'+id).textContent=t;$('#'+id).classList.toggle('error',bad);}
function render(){const actor=(a,name,extra)=>`<span class="hub-kicker">${extra}</span><h2>${name}</h2><strong>${a.hp} / ${a.maxHp} 生命</strong><div class="life"><span style="width:${100*a.hp/a.maxHp}%"></span></div><span class="hub-meta">攻击 ${a.attack} · 防御 ${a.defense} · 护盾 ${a.block}${a.bleed?' · 裂伤 '+a.bleed:''}</span>`;$('#hero').innerHTML=actor(game.hero,'旅人','YOUR CHARACTER');$('#enemy').innerHTML=actor(game.enemy,'守门者','NEXT: '+({heavy:'重击 +5',guard:'架势 +8 护盾',attack:'攻击'}[game.intent]));$('#turnState').textContent=game.result?({won:'胜利！调整牌组再试一局',lost:'战败 · 可以调整牌组或种子',draw:'100 回合未决'}[game.result]):`第 ${game.turn} 回合 · 能量 ${game.energy}/3 · 牌库 ${game.draw.length} · 弃牌 ${game.discard.length}`;$('#die').textContent=game.lastRoll||'⚄';$('#endTurn').disabled=!!game.result;$('#hand').innerHTML=game.hand.map(c=>`<button class="play-card ${c.type}" data-play="${esc(c.instance)}" ${game.result||c.cost>game.energy?'disabled':''}><span><span class="hub-chip">${c.cost} 能量</span><strong>${esc(c.name)}</strong></span><span class="card-sign">${signs[c.type]}</span><small>${types[c.type]} ${c.value}${c.type==='attack'?' + 攻击属性':''}</small></button>`).join('');$('#battleLog').innerHTML=game.log.map(x=>'<div>'+esc(x)+'</div>').join('');}
function edit(){ $('#actors').innerHTML=['hero','enemy'].map(key=>`<label>${key==='hero'?'角色':'敌人'}参数<div class="actor-fields">${['hp','attack','defense'].map((f,i)=>`<label>${['生命','攻击','防御'][i]}<input type="number" data-actor="${key}" data-stat="${f}" value="${draft[key][f]}" min="${f==='hp'?1:0}" max="${f==='hp'?500:f==='attack'?60:30}"></label>`).join('')}</div></label>`).join('');$('#cardEditor').innerHTML=draft.cards.map((c,i)=>`<tr data-index="${i}"><td><input data-field="name" aria-label="卡牌名称" maxlength="60" value="${esc(c.name)}"></td><td><select data-field="type" aria-label="卡牌类型">${Object.entries(types).map(([v,t])=>`<option value="${v}" ${v===c.type?'selected':''}>${t}</option>`).join('')}</select></td>${['cost','value','copies'].map(f=>`<td><input type="number" data-field="${f}" aria-label="${{cost:'能量',value:'效果',copies:'张数'}[f]}" min="${f==='cost'?0:1}" max="${f==='cost'?3:f==='copies'?10:60}" value="${c[f]}"></td>`).join('')}<td><button data-remove="${i}" aria-label="删除 ${esc(c.name)}">×</button></td></tr>`).join('');}
async function loadAssets(){note('assetStatus','读取官方素材目录…');try{assets=await H.get('assets',{fallback:'data/assets.json'});const cats=[...new Set(assets.items.map(x=>x.category).filter(Boolean))];$('#assetCategory').innerHTML='<option value="all">全部类别</option>'+cats.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');renderAssets();note('assetStatus',`${assets.items.length} 个素材包 · 最后成功刷新 ${H.date(assets.checked_at)}${assets.stale?' · 最近成功快照':''}${Object.values(assets.sources||{}).some(x=>!x.ok)?' · 部分目录暂不可用':''}`);}catch(e){note('assetStatus',e.message,true);}}
function renderAssets(){if(!assets)return;const q=$('#assetQuery').value.toLowerCase(),cat=$('#assetCategory').value;const rows=assets.items.filter(x=>(cat==='all'||cat===x.category)&&(!$('#assetSaved').checked||favorites.some(f=>f.id===x.id))&&`${x.title} ${x.category}`.toLowerCase().includes(q));$('#assetGrid').innerHTML=rows.length?rows.map(x=>`<article class="hub-card">${img(x.cover,x.title,'asset-cover')}<div class="hub-card-body"><span class="hub-chip">${esc(x.category)}</span><span class="hub-chip">${esc(x.license)}</span><h3>${esc(x.title)}</h3><div class="hub-actions"><a class="hub-btn" href="${esc(url(x.url))}" target="_blank" rel="noopener">预览 / 下载 ↗</a><button data-asset="${esc(x.id)}">${favorites.some(f=>f.id===x.id)?'✓ 已收藏':'收藏'}</button></div><details class="hub-meta"><summary>许可来源</summary><p>${esc(x.license_basis)}</p><a href="${esc(url(x.license_url))}" target="_blank" rel="noopener">官方许可声明 ↗</a></details></div></article>`).join(''):'<div class="hub-empty">没有符合条件的素材包</div>';}
$('#newGame').onclick=()=>{game=createGame(config,Number($('#seed').value));render();};$('#endTurn').onclick=()=>{endTurn(game);render();};
$('#saveDeck').onclick=()=>{try{config=validate(draft);H.save(KEY,config);game=createGame(config,Number($('#seed').value));render();note('deckStatus','已保存并开始新一局');}catch(e){note('deckStatus',e.message,true);}};
$('#defaultDeck').onclick=()=>{draft=structuredClone(DEFAULT);edit();note('deckStatus','已载入初始牌组，点击保存并应用');};$('#addCard').onclick=()=>{draft.cards.push({id:crypto.randomUUID(),name:'新卡牌',type:'attack',cost:1,value:5,copies:1});edit();};$('#exportDeck').onclick=()=>{try{H.download('card-lab-config.json',validate(draft));}catch(e){note('deckStatus',e.message,true);}};
$('#importDeck').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>200000)throw Error('配置文件不能超过 200 KB');draft=validate(JSON.parse(await f.text()));edit();note('deckStatus','导入完成，点击保存并应用');}catch(e){note('deckStatus',e.message,true);}finally{e.target.value='';}};
$('#simulate').onclick=()=>{try{const r=simulate(draft,Number($('#simRuns').value),Number($('#simSeed').value));$('#simResult').textContent=`${r.runs} 局 · 胜率 ${(100*r.winRate).toFixed(1)}% · 平均 ${r.turns.toFixed(1)} 回合 · 平均伤害 ${r.damage.toFixed(1)} · 未决 ${r.draws} 局`;note('deckStatus',r.strategy);}catch(e){note('deckStatus',e.message,true);}};
document.addEventListener('input',e=>{const n=e.target;if(n.dataset.actor)draft[n.dataset.actor][n.dataset.stat]=Number(n.value);if(n.dataset.field){const c=draft.cards[Number(n.closest('tr').dataset.index)];c[n.dataset.field]=['name','type'].includes(n.dataset.field)?n.value:Number(n.value);}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.play){play(game,b.dataset.play);render();}if(b.dataset.remove!==undefined){draft.cards.splice(Number(b.dataset.remove),1);edit();}if(b.dataset.pane){document.querySelectorAll('[data-pane]').forEach(x=>x.classList.toggle('active',x===b));for(const name of ['play','deck','assets'])$('#pane-'+name).hidden=name!==b.dataset.pane;if(b.dataset.pane==='assets'&&!assets)loadAssets();}if(b.dataset.asset){const i=favorites.findIndex(x=>x.id===b.dataset.asset);if(i<0)favorites.push(assets.items.find(x=>x.id===b.dataset.asset));else favorites.splice(i,1);H.save('ptu.cardlab.assets',favorites);renderAssets();}}catch(e){note('deckStatus',e.message,true);}});
for(const id of ['assetQuery','assetCategory','assetSaved'])$('#'+id).oninput=renderAssets;$('#refreshAssets').onclick=loadAssets;$('#exportAssets').onclick=()=>H.download('card-lab-assets.json',favorites);render();edit();
