const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');const {chromium}=require(process.env.PT_PLAYWRIGHT||'playwright');const root=path.resolve(__dirname,'../..');
const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'};const server=http.createServer((req,res)=>{try{let file=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('Not found');}});let browser;const errors=[];
const subj={id:1,title:'测试作品',original_title:'Test',type:2,date:'2026-10-08',cover:'',summary:'作品简介',url:'https://bgm.tv/subject/1',episodes:3};const stamp='2026-10-08T20:00:00Z',paragraph='This published source paragraph contains a concrete product statement and enough context to verify where the quotation came from.';let topicBatch=1,aiCalls=0;const gates=new Map();function hold(key){let release,entered;const wait=new Promise(r=>release=r),started=new Promise((resolve,reject)=>{const timer=setTimeout(()=>{release();reject(Error('Request did not start: '+key));},10000);entered=()=>{clearTimeout(timer);resolve();};});gates.set(key,{wait,entered});return {started,release};}
async function observe(page){await page.evaluate(()=>{const get=PTContent.get;window.settled={};PTContent.get=async(...args)=>{try{return await get(...args);}finally{window.settled[args[0]]=(window.settled[args[0]]||0)+1;}};});}
async function settled(page,key){await page.waitForFunction(key=>window.settled[key]>0,key);}
const animeSubject={id:'anime1-1',category_id:1,title:'测试番剧',year:'2026',season:'秋',status:'ongoing',available_label:'連載中(03)',latest_episode:3,url:'https://anime1.me/?cat=1'};
const datasets={anime1:{checked_at:stamp,items:[animeSubject]},calendar:{checked_at:stamp,days:[{weekday:{id:1,cn:'星期一'},items:[subj]}]},assets:{checked_at:stamp,items:[{id:'cards',title:'Card pack',category:'2D',cover:'',url:'https://kenney.nl/assets/cards',license:'CC0',license_url:'https://kenney.nl/support',license_basis:'Official declaration'}]},discover:{checked_at:stamp,items:[{id:'manga-a',title:'完结漫画',url:'https://m.manhuagui.com/comic/1/',type:'manga',source:'manhuagui-completed',status:'completed',status_basis:'来源完结目录',source_label:'漫画柜',first_seen:stamp,author:'作者'},{id:'novel-b',title:'未知状态小说',type:'novel',url:'https://tw.linovelib.com/novel/1.html',status:'unknown',first_seen:stamp}]}};
async function mock(r){const u=new URL(r.request().url()),p=u.pathname.split('/api/hub/')[1];const key=(p||(u.pathname.startsWith('/api/check/')?'check/analyze':u.pathname))+(u.search?'?'+u.searchParams.toString():'');const gate=gates.get(key);if(gate){gates.delete(key);gate.entered();await gate.wait;}let d={};if(p){d=datasets[p]||{};if(p.startsWith('search?')||p==='search')d={checked_at:stamp,items:[subj]};if(p==='subject/1')d={checked_at:stamp,subject:subj,relations:[{...subj,id:2,title:'续作',relation:'续集',url:'https://bgm.tv/subject/2'}]};if(p==='subject/2')d={checked_at:stamp,subject:{...subj,id:2,title:'续作',date:'2027-01-01'},relations:[]};if(p==='episodes/1')d={checked_at:stamp,total:3,items:[1,2,3].map(x=>({id:x,sort:x,title:(gate?'旧分集 ':'分集 ')+x,airdate:'2026-10-0'+x,url:'https://bgm.tv/ep/'+x}))};if(p==='topics')d={checked_at:stamp,items:[{id:'topic-1',title:'普通话题',source:'bangumi',source_label:'Bangumi',url:'https://bgm.tv/rakuen/topic/subject/1',replies:2,subject_id:1},{id:'topic-2',title:'剧透：最后的结局',source:'bangumi',source_label:'Bangumi',url:'https://bgm.tv/rakuen/topic/subject/2',replies:1,spoiler:true},...(topicBatch>1?[{id:'topic-3',title:'新增话题',source:'v2ex',source_label:'V2EX',url:'https://www.v2ex.com/t/3',replies:0}]:[])]};if(p==='check/search')d={checked_at:stamp,items:[{id:'e1',title:'Product source',url:'https://www.sennheiser.com/a',host:'www.sennheiser.com',excerpt:'Evidence candidate',kind:'product_candidate',readable:true,status:'unverified',source:'Public search'}]};if(p==='check/read')d={checked_at:stamp,title:u.searchParams.get('url').endsWith('/b')?'Product B':'Product A',url:u.searchParams.get('url'),retrieved_at:stamp,method:'Original paragraphs',paragraphs:[{id:'p1',text:paragraph}],specs:[{name:'Weight',value:u.searchParams.get('url').endsWith('/b')?'300 g':'250 g',source:u.searchParams.get('url')}],status:'unverified'};}else if(u.pathname.startsWith('/api/check/')){aiCalls++;const body=JSON.parse(r.request().postData());d={model:'gemini-test',generated_at:stamp,cached:aiCalls>1,output:{summary:'基于来源的商品总结',verdict:'supported',reasoning:[{text:'原文支持这项结论',sourceIds:['s1']}],evidence:[{text:'来源原文',sourceId:'s1',paragraphId:'p1',quote:paragraph,url:body.urls[0]}],pros:[{text:'来源描述的优点',sourceIds:['s1']}],cons:[],fit:'按具体场景选择',unknowns:['缺少其他版本测试'],scope:'已读取来源原文',humanVerified:false},sources:[{id:'s1',title:'Original source',url:body.urls[0],retrieved_at:stamp,paragraphs:[{id:'p1',text:paragraph}]}]};}else if(u.pathname.endsWith('site-updates.json'))d={generated_at:stamp,items:[],sources:{}};else if(u.pathname.endsWith('feed.json'))d={updates:[],items:{},sources:{}};else if(u.pathname.endsWith('music.json'))d={recent_chart:[],weekly_chart:[],new_releases:[],sources:{}};else if(u.pathname.endsWith('game-releases.json'))d={items:{pc:[],mobile:[],console:[]},sources:{}};else if(u.pathname.endsWith('content.json'))d={site_updates:[],music:{}};await r.fulfill({headers:{'Access-Control-Allow-Origin':'*'},json:d});}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/`;browser=await chromium.launch({headless:true,...(process.env.PT_CHROMIUM?{executablePath:process.env.PT_CHROMIUM,args:['--no-sandbox','--no-proxy-server','--disable-gpu','--no-zygote','--use-gl=disabled','--disable-software-rasterizer']}: {})});const ctx=await browser.newContext({timezoneId:'UTC',viewport:{width:1440,height:1000}});await ctx.route(/^https:\/\//,mock);const p=await ctx.newPage();p.on('console',m=>{if(m.type()==='error')console.error('Browser:',m.text())});p.on('requestfailed',r=>console.error('Request failed:',r.url(),r.failure()));p.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR:',e.message)});
await p.goto(base+'apps/tsugi-checker/?tab=works');await p.locator('#worksQuery').fill('测试作品');await p.locator('#worksSearchBtn').click();await p.locator('#worksResults [data-map]').click();await p.locator('#saveWork').click();assert.equal(await p.locator('#worksArchive [data-map]').count(),1);await p.locator('#workOrder').click();await p.locator('#workOrderList').getByText('2027-01-01',{exact:true}).waitFor();
await p.locator('[data-tab=anime]').click();await p.locator('[data-follow]').click();await p.locator('[data-anime]').click();await p.locator('[data-sort="2"]').check();assert.equal(await p.locator('[data-sort="1"]').isChecked(),true);assert.equal(await p.locator('[data-sort="3"]').isChecked(),false);assert.equal(await p.locator('[data-episode-status="1"]').innerText(),'已看');await p.locator('#closeEpisodes').click();await p.locator('#animeFollowOnly').check();assert.equal(await p.locator('#animeGrid .anime-entry').count(),1);
await p.locator('[data-tab=topics]').click();await p.locator('#topicsList .topic-entry').first().waitFor();assert.equal(await p.locator('#topicsList details a').isVisible(),false,'spoiler title should be collapsed');await p.locator('[data-hide-topic="topic-1"]').click();assert.equal(await p.locator('#topicsList .topic-entry').count(),1);topicBatch=2;await p.locator('#topicsRefresh').click();await p.locator('#topicsList .hub-new').waitFor();await p.locator('#topics details.hub-note summary').click();await p.locator('#topicsRestore').click();assert.equal(await p.locator('#topicsList .topic-entry').count(),3);
await p.locator('[data-tab=discovery]').click();await p.locator('#discoveryMode').selectOption('completed');await p.locator('[data-save-discovery="manga-a"]').click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('tsugi-local-library-v1'))[0].title),'完结漫画');assert.equal(await p.locator('#discoveryGrid .hub-card').count(),1);await p.reload();await p.locator('[data-tab=works]').click();assert.equal(await p.locator('#worksArchive [data-map]').count(),1);
console.log('Core Tsugi flows passed');
// Return an older relationship request after the user has already selected another work.
await p.locator('[data-tab=works]').click();await observe(p);const oldWork=hold('subject/1');await p.locator('#worksArchive [data-map="1"]').click();await oldWork.started;await p.evaluate(()=>{const b=document.createElement('button');b.dataset.map='2';document.body.append(b);b.click();b.remove();});await p.locator('#worksDetail h2').filter({hasText:'续作'}).waitFor();oldWork.release();await settled(p,'subject/1');assert.equal(await p.locator('#worksDetail h2').innerText(),'续作','late work response must not overwrite the latest selection');
// Anime1 availability is separate from personal progress and jumps to the real source.
await p.locator('[data-tab=anime]').click();await p.locator('#animeGrid .anime-entry').first().waitFor();assert.ok((await p.locator('#animeGrid').innerText()).includes('連載中(03)'));assert.equal(await p.locator('#animeGrid a').first().getAttribute('href'),'https://anime1.me/?cat=1');await p.locator('[data-anime]').click();assert.equal(await p.locator('[data-sort="2"]').isChecked(),true);await p.locator('#closeEpisodes').click();
for(const width of [1440,390]){await p.setViewportSize({width,height:844});for(const name of ['works','topics','anime','discovery']){await p.locator('[data-tab='+name+']').click();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Tsugi '+name+' should not overflow at '+width);}await p.screenshot({path:'/tmp/pt-hub-tsugi-'+width+'.png'});}await p.setViewportSize({width:1440,height:1000});
await p.goto(base+'apps/check-desk/');await p.locator('[data-mode=product]').click();await p.locator('#query').fill('HD490 Pro');await p.locator('#searchButton').click();await p.locator('[data-read]').click();await p.locator('[data-quote]').click();assert.ok((await p.locator('#evidenceList').innerText()).includes(paragraph));await p.locator('#verdict').selectOption('supported');await p.locator('#caseNote').fill('Verified user note');p.on('dialog',d=>d.accept('Version '+Date.now()));await p.locator('#addProduct').click();await p.locator('#sourceImport summary').click();await p.locator('#sourceURL').fill('https://www.sennheiser.com/b');await p.locator('#readForm button').click();await p.locator('#reader h2').filter({hasText:'Product B'}).waitFor();await p.locator('#addProduct').click();await p.locator('#compareProducts').click();assert.ok((await p.locator('#comparisonTable').innerText()).includes('250 g'));assert.ok((await p.locator('#comparisonTable').innerText()).includes('300 g'));await p.locator('#closeComparison').click();await p.locator('#saveCase').click();await p.reload();await p.locator('#openArchive').click();await p.locator('[data-load-case]').click();assert.equal(await p.locator('#caseNote').inputValue(),'Verified user note');assert.equal(await p.locator('#verdict').inputValue(),'supported');assert.ok((await p.locator('#evidenceList').innerText()).includes('读取'));assert.equal(await p.locator('#productList .hub-note').count(),2);
console.log('Core Check Desk flows passed');
// AI runs only on a click, keeps the human verdict, and survives archiving.
assert.equal(aiCalls,0,'search and source reading must never generate AI output');await p.evaluate(()=>localStorage.setItem('ptu.sync.config',JSON.stringify({id:'11111111-1111-4111-8111-111111111111',token:'test-token'})));await p.locator('#verdict').selectOption('mixed');await p.locator('#runAI').click();await p.locator('#aiResult .ai-summary').waitFor();assert.equal(aiCalls,1);assert.equal(await p.locator('#verdict').inputValue(),'mixed');assert.ok((await p.locator('#aiResult').innerText()).includes('缺少其他版本测试'));assert.equal(await p.locator('#aiResult .ai-citation').first().getAttribute('href'),'https://www.sennheiser.com/a');await p.locator('#saveCase').click();await p.reload();await p.locator('#openArchive').click();await p.locator('#archiveList .hub-row').filter({hasText:'HD490 Pro'}).locator('[data-load-case]').click();await p.locator('#aiResult .ai-summary').waitFor();assert.equal(aiCalls,1,'restoring an archive must not invoke AI');await p.locator('#caseNote').fill('');await p.locator('#verdict').selectOption('unverified');await p.locator('#newCase').click();assert.ok(await p.evaluate(()=>JSON.parse(localStorage.getItem('ptu.checkdesk.cases')).some(c=>c.ai?.output.summary==='基于来源的商品总结')),'AI-only result must be saved before starting a new case');
// Notes and manual conclusions are meaningful records even without extracted evidence.
await p.locator('#newCase').click();await p.locator('#query').fill('Only notes');await p.locator('#caseNote').fill('Keep my preliminary reasoning');await p.locator('#verdict').selectOption('insufficient');await p.locator('#newCase').click();let records=await p.evaluate(()=>JSON.parse(localStorage.getItem('ptu.checkdesk.cases')));assert.equal(records.find(c=>c.query==='Only notes').note,'Keep my preliminary reasoning');assert.equal(records.find(c=>c.query==='Only notes').verdict,'insufficient');
await p.locator('#query').fill('Before switching mode');await p.locator('#caseNote').fill('Mode switch note');await p.locator('[data-mode=claim]').click();assert.equal(await p.locator('#caseNote').inputValue(),'');assert.ok(await p.evaluate(()=>JSON.parse(localStorage.getItem('ptu.checkdesk.cases')).some(c=>c.note==='Mode switch note')));
await p.locator('#caseNote').fill('Before archive load');await p.locator('#openArchive').click();await p.locator('#archiveList .hub-row').filter({hasText:'Only notes'}).locator('[data-load-case]').click();assert.equal(await p.locator('#caseNote').inputValue(),'Keep my preliminary reasoning');assert.ok(await p.evaluate(()=>JSON.parse(localStorage.getItem('ptu.checkdesk.cases')).some(c=>c.note==='Before archive load')));
await p.locator('#query').fill('Changed question');await p.locator('#searchButton').click();await p.locator('[data-read]').waitFor();assert.equal(await p.locator('#caseNote').inputValue(),'');
console.log('Notes-only transitions passed');
// A delayed source and search may finish after a new case or mode switch.
await observe(p);await p.locator('#sourceImport summary').click();const delayedReader=hold('check/read?url=https%3A%2F%2Fwww.sennheiser.com%2Fa');await p.locator('#sourceURL').fill('https://www.sennheiser.com/a');await p.locator('#readForm button').click();await delayedReader.started;await p.locator('#newCase').click();delayedReader.release();await settled(p,'check/read?url=https%3A%2F%2Fwww.sennheiser.com%2Fa');assert.equal(await p.locator('#reader').isVisible(),false,'late reader must not reopen in a new case');
await p.locator('[data-mode=claim]').click();const delayedSearch=hold('check/search?q=Delayed+question&mode=claim');await p.locator('#query').fill('Delayed question');await p.locator('#searchButton').click();await delayedSearch.started;await p.locator('[data-mode=product]').click();delayedSearch.release();await settled(p,'check/search?q=Delayed+question&mode=claim');assert.equal(await p.locator('[data-read]').count(),0,'late search must not populate a different mode');assert.equal(await p.locator('#searchButton').isEnabled(),true);
// Of two overlapping source reads, only the latest one can supply evidence.
const oldReader=hold('check/read?url=https%3A%2F%2Fwww.sennheiser.com%2Fa');await p.locator('#sourceURL').fill('https://www.sennheiser.com/a');await p.locator('#readForm button').click();await oldReader.started;await p.locator('#sourceURL').fill('https://www.sennheiser.com/b');await p.locator('#readForm button').click();await p.locator('#reader h2').filter({hasText:'Product B'}).waitFor();oldReader.release();await p.waitForFunction(()=>window.settled['check/read?url=https%3A%2F%2Fwww.sennheiser.com%2Fa']===2);assert.equal(await p.locator('#reader h2').innerText(),'Product B');await p.locator('[data-quote]').click();assert.equal(await p.locator('#evidenceList a').getAttribute('href'),'https://www.sennheiser.com/b');
const delayedAI=hold('check/analyze');await p.locator('#runAI').click();await delayedAI.started;await p.locator('#newCase').click();const aiResponse=p.waitForResponse(r=>r.url().includes('/api/check/')&&r.status()===200);delayedAI.release();await aiResponse;await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await p.locator('#aiResult').isVisible(),false,'late AI output cannot populate a different case');
for(const width of [1440,390]){await p.setViewportSize({width,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Check Desk overflow');await p.screenshot({path:'/tmp/pt-hub-check-'+width+'.png',fullPage:true});}
await p.goto(base+'apps/card-lab/');await p.locator('.play-card').first().waitFor();assert.equal(await p.locator('.play-card').count(),5);await p.locator('.play-card:not(:disabled)').first().click();assert.equal(await p.locator('.play-card').count(),4);await p.locator('#endTurn').click();assert.ok((await p.locator('#turnState').innerText()).includes('第 2 回合'));await p.locator('[data-pane=deck]').click();await p.locator('#cardEditor [data-field=value]').first().fill('20');await p.locator('#saveDeck').click();await p.locator('#simulate').click();assert.ok((await p.locator('#simResult').innerText()).includes('100 局'));await p.reload();await p.locator('[data-pane=deck]').click();assert.equal(await p.locator('#cardEditor [data-field=value]').first().inputValue(),'20');await p.locator('#cardEditor [data-field=cost]').first().fill('4');await p.locator('#saveDeck').click();assert.ok((await p.locator('#deckStatus').innerText()).includes('必须'));assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('ptu.cardlab.config')).cards[0].cost),1);await p.locator('[data-pane=assets]').click();await p.locator('[data-asset]').click();await p.locator('#assetSaved').check();assert.equal(await p.locator('#assetGrid .hub-card').count(),1);
for(const width of [1440,390]){await p.setViewportSize({width,height:844});for(const name of ['play','deck','assets']){await p.locator('[data-pane='+name+']').click();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Card Lab '+name+' overflow');}await p.screenshot({path:'/tmp/pt-hub-lab-'+width+'.png'});}await p.setViewportSize({width:1440,height:1000});
await p.goto(base+'apps/daily-nexus/');await p.locator('[data-view=check]').click();await p.frameLocator('#checkFrame').locator('#query').waitFor();assert.equal(await p.locator('#view-check').evaluate(e=>e.classList.contains('active')),true);assert.equal(await p.frameLocator('#checkFrame').locator('#backHome').isVisible(),false);assert.equal(await p.locator('#tsugiFrame').getAttribute('src'),null,'other embedded tabs stay lazy');
await p.locator('[data-view=tools]').click();assert.equal(await p.locator('#cardLabEntry').getAttribute('href'),'../card-lab/?v=20261008-3');
assert.deepEqual(errors,[]);console.log('Content hub browser passed: maps/order/archive, progress/checkboxes, spoiler collapse, refresh badges, existing shelf, evidence provenance/archive/comparison, notes-only preservation and out-of-order responses, combat/edit/simulation/assets, responsive overflow, lazy Daily Nexus tab');await ctx.close();
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await browser?.close();server.close();});
