const {chromium}=require('playwright'), assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../../apps/self-learning'),read=f=>JSON.parse(fs.readFileSync(path.join(root,'data',f),'utf8'));
const manifest=read('manifest.json'),sources=read('sources.json'),courseIds=['systems','security','hci','games','finance'];
assert.deepEqual(manifest.courses.map(c=>c.id),courseIds);assert.equal(new Set(sources.map(s=>s.id)).size,sources.length);const sourceIds=new Set(sources.map(s=>s.id));
let chapters=0;for(const m of manifest.courses){const c=read(m.file);assert.equal(c.lessons.length,m.chapterCount);chapters+=c.lessons.length;for(const l of c.lessons){assert.ok(l.body.length>=2);assert.ok(l.sections?.length>=4,l.id+' needs full sections');assert.ok(l.textCharacters>=1100,l.id+' too short');assert.ok(l.walkthrough?.steps.length===3);assert.ok(l.check?.question&&l.check?.answer);assert.ok(l.sections.every(s=>s.paragraphs.length>=2));assert.ok(l.body.join('').length>=160,l.id+' lacks teaching');assert.ok(l.example.length>=50);assert.equal(l.steps.length,3);assert.ok(l.criteria&&l.answer&&l.pitfall);for(const r of l.refs){assert.ok(sourceIds.has(r.id),r.id);assert.ok(r.section)}}}assert.equal(chapters,80);assert.equal(read('finance.json').history.resume,4);
let server;
(async()=>{let base=process.env.TEST_BASE;
if(!base){const repo=path.resolve(__dirname,'../..');server=require('node:http').createServer((req,res)=>{let file=path.join(repo,decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(repo+path.sep)&&file!==repo){res.writeHead(403).end();return}try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');const ext=path.extname(file);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml'})[ext]||'text/plain');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port+'/';}
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}: {})});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:"reduce",permissions:["clipboard-read","clipboard-write"],acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await context.route('**/api/**',r=>r.fulfill({contentType:'application/json',body:'{}'}));await context.route('**/pt-analytics.js*',r=>r.fulfill({body:''}));
await page.goto(base+'apps/self-learning/');await page.locator('.course-card').first().waitFor();assert.equal(await page.locator('.course-card').count(),5);assert.match(await page.locator('.summary').innerText(),/80/);
await page.getByRole('link',{name:'接续第 4 章'}).click();await page.locator('#note').waitFor();assert.match(await page.locator('h1').innerText(),/商业模式/);assert.equal(await page.locator('#done').isChecked(),false);
await page.locator('#note').fill('库存与SBC，<img src=x onerror=alert(1)>');await page.locator('#response').fill('ROIC=15/100=15%');await page.locator('#done').check();await page.reload();await page.locator('#note').waitFor();assert.equal(await page.locator('#note').inputValue(),'库存与SBC，<img src=x onerror=alert(1)>');assert.equal(await page.locator('#done').isChecked(),true);assert.equal(await page.locator('.reader img').count(),0);
await page.getByRole('link',{name:'下一章节',exact:true}).click();await page.locator('h1').filter({hasText:'PE'}).waitFor();assert.match(await page.locator('h1').innerText(),/PE/);
await page.goto(base+'apps/self-learning/#/');await page.locator('.resume').waitFor();assert.match(await page.locator('.resume').innerText(),/第 5 章/);
for(const m of manifest.courses){for(const n of Array.from({length:m.chapterCount},(_,i)=>i+1)){await page.goto(base+'apps/self-learning/#/course/'+m.id+'/'+String(n).padStart(2,'0'));await page.waitForFunction(()=>document.querySelector('.chapter-link.active')?.getAttribute('href')===location.hash);assert.equal(await page.locator('.chapter-link.active').count(),1);assert.ok(await page.locator('.ref a').count());assert.ok(await page.locator('.teaching-section').count()>=4);assert.equal(await page.locator('.worked-case li').count(),3);assert.ok((await page.locator('.full-lecture').innerText()).length>500);const route=page.url();if(!await page.locator('.chapter-toc').evaluate(el=>el.open))await page.locator('.chapter-toc summary').click();await page.locator('[data-jump="worked-case"]').click();assert.equal(page.url(),route);assert.equal(await page.evaluate(()=>document.activeElement.id),'worked-case');await page.locator('.lab summary').click();assert.equal(await page.locator('.lab details').evaluate(el=>el.open),true);}}
await page.goto(base+'apps/self-learning/#/references');await page.locator('#ref-results .ref').first().waitFor();assert.equal(await page.locator('#ref-results .ref').count(),sources.length);await page.locator('#ref-course').selectOption('systems');await page.waitForFunction(()=>document.querySelectorAll('#ref-results .ref').length<35);await page.locator('#ref-search').fill('Quake');await page.waitForFunction(()=>document.querySelectorAll('#ref-results .ref').length===1);assert.match(await page.locator('#ref-results').innerText(),/2025-06-06/);
await page.goto(base+'apps/self-learning/#/course/finance/04');await page.locator('#note').waitFor();await page.locator('#copy-context').click();const copied=await page.evaluate(()=>navigator.clipboard.readText());assert.match(copied,/护城河要落到机制与证据/);assert.match(copied,/本章阅读/);assert.ok(copied.length>2200);const download=await Promise.all([page.waitForEvent('download'),page.locator('#export').click()]).then(x=>x[0]);const filepath=await download.path(),backup=JSON.parse(fs.readFileSync(filepath,'utf8'));assert.equal(backup.lessons['finance-04'].response,'ROIC=15/100=15%');
await page.evaluate(()=>localStorage.removeItem('pt-learning.v1'));await page.reload();await page.locator('#note').waitFor();assert.equal(await page.locator('#note').inputValue(),'');await page.locator('#import').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForFunction(()=>JSON.parse(localStorage.getItem('pt-learning.v1')).lessons['finance-04']?.done);assert.equal(await page.locator('#note').inputValue(),'库存与SBC，<img src=x onerror=alert(1)>');
const saved=await page.evaluate(()=>localStorage.getItem('pt-learning.v1'));await page.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":1,"lessons":{"__proto__":{"done":true}}}')});await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('导入失败'));assert.equal(await page.evaluate(()=>localStorage.getItem('pt-learning.v1')),saved);
await page.screenshot({path:'/workspace/scratch/06d2f2aed6d1/self-learning-desktop.png',fullPage:true});
for(const width of [360,768,1440]){await page.setViewportSize({width,height:900});for(const route of ['#/','#/course/systems/01','#/references']){await page.goto(base+'apps/self-learning/'+route);await page.waitForFunction(()=>!document.querySelector('.loading'));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'overflow '+width+' '+route);}}
await page.setViewportSize({width:390,height:844});await page.goto(base+'apps/self-learning/#/course/games/05');await page.locator('#note').waitFor();await page.screenshot({path:'/workspace/scratch/06d2f2aed6d1/self-learning-mobile.png',fullPage:true});
await page.setViewportSize({width:1440,height:1000});await page.goto(base+'#/category/learning');await page.locator('#favoriteGrid [data-launch="self-learning"]').waitFor();await page.locator('#favoriteGrid [data-launch="self-learning"]').click();await page.waitForURL('**/apps/self-learning/');await page.locator('.course-card').first().waitFor();assert.equal(await page.locator('.course-card').count(),5);await page.goto(base+'#/app/self-learning');await page.waitForURL('**/apps/self-learning/');await page.locator('.course-card').first().waitFor();
assert.deepEqual(errors,[]);await browser.close();if(server)server.close();console.log('PASS: 5 courses, 80 complete chapters, references, 80 expanded reading flows, finance continuity, notes/progress, export/import, invalid import protection, responsive layouts, PT navigation integration.');})().catch(e=>{console.error(e);process.exit(1)});
