const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../../apps/self-learning'),read=f=>JSON.parse(fs.readFileSync(path.join(root,'data',f),'utf8'));
const manifest=read('manifest.json'),sources=read('sources.json'),courses=manifest.courses.map(m=>read(m.file));
assert.deepEqual(manifest.courses.map(c=>c.id),['systems','security','hci','games','finance']);
assert.equal(courses.reduce((a,c)=>a+c.lessons.length,0),80);assert.equal(read('finance.json').history.resume,4);
const sourceIds=new Set(sources.map(s=>s.id));assert.equal(sourceIds.size,sources.length);
for(const c of courses)for(const l of c.lessons){assert.ok(l.guide.question);assert.ok(l.guide.terms.length>=2);assert.ok(l.sections.length>=4);assert.ok(l.sections.every(s=>s.paragraphs.length>=2&&s.keyPoint));assert.equal(l.walkthrough.steps.length,3);assert.ok(l.textCharacters>=1100);for(const r of l.refs)assert.ok(sourceIds.has(r.id));}
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'explorers.js'),'utf8'),sandbox);
const models=sandbox.window.LearningExplorers.models;assert.equal(Object.keys(models).length,6);
assert.equal(models['unit-economics'].calculate({customers:2000,price:100,cost:30,fixed:70000}).values[2][1],'70,000 元');
assert.match(models['unit-economics'].calculate({customers:2000,price:30,cost:30,fixed:70000}).explanation,/不为正/);
assert.equal(models.dcf.calculate({rate:10,growth:2}).values[1][1],'12.21');assert.ok(models.dcf.calculate({rate:4,growth:5}).error);
assert.equal(models['draw-probability'].calculate({deck:25,keys:2,draw:5}).values[0][1],'36.67%');assert.ok(models['draw-probability'].calculate({deck:5,keys:6,draw:3}).error);
assert.equal(models.queue.calculate({arrival:12,capacity:10,seconds:60}).values[1][1],'120 个');
assert.equal(models.contrast.calculate({foreground:'#000000',background:'#ffffff'}).values[0][1],'21.00:1');assert.equal(models.contrast.calculate({foreground:'#ffffff',background:'#ffffff'}).values[1][1],'未达到4.5:1');
for(const s of [false,true])for(const o of [false,true])for(const a of [false,true])assert.equal(models.authorization.calculate({sameTenant:s,owner:o,admin:a}).values[0][1],s&&(o||a)?'允许':'拒绝');
let server,browser;
(async()=>{
 let base=process.env.TEST_BASE;if(!base){const repo=path.resolve(__dirname,'../..');server=require('node:http').createServer((req,res)=>{let file=path.join(repo,decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(repo+path.sep)&&file!==repo){res.writeHead(403).end();return}try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port+'/';}
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}: {})});
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',permissions:['clipboard-read','clipboard-write'],acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await context.route('**/api/**',r=>r.fulfill({contentType:'application/json',body:'{}'}));await context.route('**/pt-analytics.js*',r=>r.fulfill({body:''}));
 const visit=async(id,n)=>{await page.goto(base+'apps/self-learning/#/course/'+id+'/'+String(n).padStart(2,'0'));await page.waitForFunction(()=>document.querySelector('.chapter-link.active')?.getAttribute('href')===location.hash);};
 const jump=async(unit)=>{if(!await page.locator('.chapter-toc').evaluate(e=>e.open))await page.locator('.chapter-toc summary').click();await page.locator('[data-unit-jump="'+unit+'"]').click();};
 await page.goto(base+'apps/self-learning/');await page.locator('.course-card').first().waitFor();assert.equal(await page.locator('.course-card').count(),5);
 await page.getByRole('link',{name:'接续第 4 章'}).click();await page.locator('[data-unit="0"]').waitFor();assert.equal(await page.locator('.learning-unit:visible').count(),1);assert.equal(await page.locator('#done').isChecked(),false);assert.match(await page.locator('h1').innerText(),/商业模式/);
 await page.locator('#unit-next').click();assert.equal(await page.locator('[data-unit="1"]').isVisible(),true);await page.reload();await page.locator('[data-unit="1"]').waitFor();assert.equal(await page.locator('.learning-unit:visible').count(),1);
 await page.locator('#show-terms').click();await page.locator('#term-dialog').waitFor();assert.match(await page.locator('#term-dialog').innerText(),/获客成本/);await page.keyboard.press('Escape');assert.equal(await page.locator('#term-dialog').isVisible(),false);
 await jump(2);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'/workspace/scratch/06d2f2aed6d1/self-learning-tutorial-desktop.png',fullPage:true});await page.locator('[data-term]').filter({visible:true}).first().click();await page.locator('#close-terms').click();await page.locator('[data-explorer="unit-economics"]').waitFor();await page.getByRole('spinbutton',{name:'付费客户数（名）'}).fill('2000');assert.match(await page.locator('.model-values').innerText(),/70,000 元/);await page.locator('.explorer-reset').click();assert.match(await page.locator('.model-values').innerText(),/100,000 元/);
 await page.locator('[data-mode="full"]').click();assert.equal(await page.locator('.learning-unit:visible').count(),11);
 await page.locator('#note').fill('库存与SBC，<img src=x onerror=alert(1)>');await page.locator('#response').fill('ROIC=15/100=15%');await page.locator('#self-check').fill('利润率高仍需检查竞争机制。');await page.locator('#done').check();await page.locator('#open-notes').click();await page.locator('[data-mode="guided"]').click();await page.reload();await page.locator('[data-unit="9"]').waitFor();assert.equal(await page.locator('#note').inputValue(),'库存与SBC，<img src=x onerror=alert(1)>');assert.equal(await page.locator('#done').isChecked(),true);assert.equal(await page.locator('.reader img').count(),0);
 await page.locator('#copy-context').click();const copied=await page.evaluate(()=>navigator.clipboard.readText());assert.match(copied,/护城河要落到机制与证据/);assert.match(copied,/本章阅读/);assert.match(copied,/CAC：/);assert.match(copied,/我的自检回答：利润率高/);for(const section of read('finance.json').lessons[3].sections)for(const paragraph of section.paragraphs)assert.ok(copied.includes(paragraph));
 await page.locator('.record-menu summary').click();const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#export').click()]);const backup=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(backup.lessons['finance-04'].unit,9);assert.equal(backup.lessons['finance-04'].selfCheck,'利润率高仍需检查竞争机制。');
 await page.evaluate(()=>localStorage.removeItem('pt-learning.v1'));await page.reload();await page.locator('[data-unit="0"]').waitFor();await page.locator('#import').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.locator('[data-unit="9"]').waitFor();assert.equal(await page.locator('#note').inputValue(),'库存与SBC，<img src=x onerror=alert(1)>');
 const saved=await page.evaluate(()=>localStorage.getItem('pt-learning.v1'));
 for(const data of ['{"version":1,"lessons":{"__proto__":{"done":true}}}',JSON.stringify({...backup,lessons:{'finance-04':{...backup.lessons['finance-04'],unit:99}}})]){await page.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(data)});await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('导入失败'));assert.equal(await page.evaluate(()=>localStorage.getItem('pt-learning.v1')),saved);}
 const legacy={version:1,lessons:{'systems-01':{done:true,note:'旧版笔记',response:'旧版练习',updatedAt:Date.now()}},last:{courseId:'systems',lessonId:'systems-01'}};
 await page.locator('#import').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});await page.locator('h1').filter({hasText:'Python'}).waitFor();assert.equal(await page.locator('#note').inputValue(),'旧版笔记');assert.equal(await page.locator('#done').isChecked(),true);assert.equal(await page.locator('[data-unit="0"]').isVisible(),true);
 for(const c of courses){for(const l of c.lessons){await visit(c.id,l.number);await jump(0);const route=page.url();assert.equal(await page.locator('.chapter-toc button').count(),l.sections.length+5);for(let unit=0;unit<l.sections.length+5;unit++){assert.equal(await page.locator('.learning-unit:visible').count(),1,l.id+' unit '+unit);assert.equal(await page.locator('[data-unit="'+unit+'"]').isVisible(),true);if(unit>0)assert.equal(await page.evaluate(()=>document.activeElement.id),await page.locator('[data-unit="'+unit+'"] h2').first().getAttribute('id'));if(unit===l.sections.length+2){await page.locator('.lab summary').click();assert.equal(await page.locator('.lab details').evaluate(el=>el.open),true);}if(unit<l.sections.length+4)await page.locator('#unit-next').click();}assert.equal(page.url(),route);assert.equal(await page.locator('.worked-case li').count(),3);assert.ok(await page.locator('.ref a').count());assert.equal(await page.locator('#unit-next').isDisabled(),true);}
 console.log('Verified '+c.id+' learning flow');}
 await visit('finance',6);await jump(3);assert.match(await page.locator('.model-values').innerText(),/12.21/);await page.getByRole('spinbutton',{name:'折现率（%）'}).fill('4');await page.getByRole('spinbutton',{name:'永续增长率（%）'}).fill('5');assert.match(await page.locator('.model-error').innerText(),/大于/);
 await visit('games',5);await jump(1);assert.match(await page.locator('.model-values').innerText(),/44.74%/);await page.getByRole('spinbutton',{name:'卡组总张数'}).fill('25');assert.match(await page.locator('.model-values').innerText(),/36.67%/);
 await visit('systems',7);await jump(2);await page.getByRole('spinbutton',{name:'每秒到达任务数'}).fill('12');assert.match(await page.locator('.model-values').innerText(),/120 个/);
 await visit('security',5);await jump(1);await page.getByRole('checkbox',{name:'用户是自己租户的管理员'}).check();assert.match(await page.locator('.model-values').innerText(),/允许/);await page.getByRole('checkbox',{name:'记录属于用户所在租户'}).uncheck();assert.match(await page.locator('.model-values').innerText(),/拒绝/);
 await visit('hci',8);await jump(1);await page.locator('[data-field="foreground"]').fill('#ffffff');assert.match(await page.locator('.model-values').innerText(),/未达到/);
 await page.goto(base+'apps/self-learning/#/references');await page.locator('#ref-results .ref').first().waitFor();assert.equal(await page.locator('#ref-results .ref').count(),sources.length);await page.locator('#ref-course').selectOption('systems');await page.locator('#ref-search').fill('Quake');await page.waitForFunction(()=>document.querySelectorAll('#ref-results .ref').length===1);
 for(const width of [360,768,1440]){await page.setViewportSize({width,height:900});for(const route of ['#/','#/course/finance/04','#/course/systems/01','#/references']){await page.goto(base+'apps/self-learning/'+route);await page.waitForFunction(()=>!document.querySelector('.loading'));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'overflow '+width+' '+route);}}
 await page.setViewportSize({width:1440,height:1000});await visit('finance',4);await jump(2);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'/workspace/scratch/06d2f2aed6d1/self-learning-tutorial-desktop.png',fullPage:true});
 await page.locator('[data-mode="full"]').click();assert.equal(await page.locator('.learning-unit:visible').count(),11);await page.locator('[data-mode="guided"]').click();
 await page.setViewportSize({width:390,height:844});await visit('finance',4);await jump(0);assert.equal(await page.locator('.course-menu').evaluate(el=>el.open),false);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'/workspace/scratch/06d2f2aed6d1/self-learning-tutorial-mobile.png',fullPage:true});
 await page.locator('#show-terms').click();await page.locator('#close-terms').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'show-terms');await page.locator('#theme').click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'dark');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'/workspace/scratch/06d2f2aed6d1/self-learning-tutorial-dark.png',fullPage:true});await page.locator('#theme').click();
 await page.evaluate(()=>{window.print=()=>{window.printUnits=document.querySelectorAll('.learning-unit:not([hidden])').length;window.printAnswers=[...document.querySelectorAll('.learning-unit details')].every(d=>d.open);};});await page.locator('#print').click();assert.equal(await page.evaluate(()=>window.printUnits),11);assert.equal(await page.evaluate(()=>window.printAnswers),true);assert.equal(await page.locator('.learning-unit:visible').count(),1);
 await page.setViewportSize({width:1440,height:1000});await page.goto(base+'#/category/learning');await page.locator('#favoriteGrid [data-launch="self-learning"]').waitFor();await page.locator('#favoriteGrid [data-launch="self-learning"]').click();await page.waitForURL('**/apps/self-learning/');await page.locator('.course-card').first().waitFor();assert.equal(await page.locator('.course-card').count(),5);
 assert.deepEqual(errors,[]);console.log('PASS: 80 guided learning flows, 173 terms, six interactive models, notes/self-check/reading position, old/new imports, responsive layouts, keyboard/modal, print, PT integration.');
})().then(async()=>{await browser?.close();server?.close();}).catch(async e=>{console.error(e);await browser?.close();server?.close();process.exitCode=1;});
