import {upsertPaper,canonical,importExtraction,evidenceStatus} from './model.mjs?v=2';
import {config} from './sync.mjs?v=2';
const API='https://pt-universe-api.summer07-nanjolno.workers.dev';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toLocaleDateString('en-CA');
const before=days=>new Date(Date.now()-days*86400000).toLocaleDateString('en-CA');
const pickLabel={deep:'建议精读',skim:'快速浏览',skip:'暂不优先'};
export function createResearchFlow(ctx){
 let active=localStorage.getItem('research-workbench.active')||'',busy='',error='',step=1;
 const sessions=()=>ctx.state().researchSessions.filter(s=>!s.deleted).sort((a,b)=>b.updatedAt-a.updatedAt);
 const session=()=>sessions().find(s=>s.id===active);
 step=session()?.step||1;
 function save(updates,id=active){const next=structuredClone(ctx.state()),s=next.researchSessions.find(s=>s.id===id);if(!s)throw Error('研究记录不存在');Object.assign(s,updates,{updatedAt:ctx.stamp()});if(!ctx.change(next))throw Error('保存失败，请先导出备份');return s}
 const paper=id=>ctx.state().papers.find(p=>p.id===id&&!p.deleted);
 const linkPaper=id=>{const p=paper(id);return p?`<button class="quiet source-ref" data-open-paper="${esc(id)}">${esc(p.title)}</button>`:''};
 const points=list=>`<ul>${(list||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
 async function ai(task,data){
  const cfg=config();if(!cfg)throw Error('请先在“备份与同步”中连接你原有的 PT Universe 配对码，再使用 AI。');
  const r=await fetch(`${API}/api/workbench/ai/${encodeURIComponent(cfg.id)}`,{method:'POST',cache:'no-store',headers:{'content-type':'application/json',authorization:'Bearer '+cfg.token},signal:AbortSignal.timeout(90000),body:JSON.stringify({task,...data})});
  const result=await r.json().catch(()=>null);if(!r.ok||!result?.output)throw Error(result?.error||'研究服务暂不可用，请稍后手动重试');return result;
 }
 function usage(r,sid=active){const s=sessions().find(x=>x.id===sid);if(s)save({usage:[...(s.usage||[]),{task:busy,model:r.model,tokens:r.usage?.totalTokenCount||0,cached:r.cached,at:r.generatedAt}].slice(-50)},sid)}
 async function run(label,fn){if(busy)return;busy=label;error='';ctx.render();try{await fn()}catch(e){error=e.name==='TimeoutError'?'请求超时；已保存前面的结果，稍后可以继续。':e.message;ctx.toast(error)}finally{busy='';ctx.render()}}
 function begin(form){const f=new FormData(form),topic=String(f.get('topic')||'').trim(),from=String(f.get('from')||''),to=String(f.get('to')||'');if(!topic)throw Error('请输入研究主题');if(from&&to&&from>to)throw Error('起始日期不能晚于结束日期');const next=structuredClone(ctx.state()),existing=session(),row={id:existing?.id||crypto.randomUUID(),topic,goal:String(f.get('goal')||'').trim(),from,to,keywords:String(f.get('keywords')||'').trim()||topic,direction:'',step:1,candidates:[],selectedIds:[],usage:[],updatedAt:ctx.stamp(),deleted:false};
 if(existing&&existing.topic===row.topic&&existing.goal===row.goal&&existing.from===row.from&&existing.to===row.to){save({keywords:row.keywords});return session()}
 next.researchSessions.push(row);if(!ctx.change(next))throw Error('研究记录保存失败');active=row.id;localStorage.setItem('research-workbench.active',active);step=1;return row;
 }
 const scoped=s=>({topic:s.topic,goal:s.goal+(s.direction?'；方向：'+s.direction:'')+(s.directionDetails?'；'+s.directionDetails:''),from:s.from,to:s.to});
 async function search(s,start=0){
  const id=s.id,params=new URLSearchParams({q:s.keywords,from:s.from,to:s.to,start:String(start)});
  const r=await fetch(API+'/api/workbench/discover?'+params,{cache:'no-store',signal:AbortSignal.timeout(45000)}),data=await r.json().catch(()=>null);if(!r.ok||!data?.items)throw Error(data?.error||'论文搜索暂不可用，请重试');
  const old=start?s.candidates:[],items=[...old,...data.items.map(p=>({...p,id:p.arxivId||canonical(p.title)}))],unique=[...new Map(items.map(p=>[p.id,p])).values()].slice(0,40);
  save({candidates:unique,selectedIds:start?s.selectedIds:[],screening:null,report:null,search:{...data,items:undefined},step:2},id);step=2;
 }
 function render(){
  const s=session(),current=s?step:1;const disabled=busy?'disabled':'';
  return `<div class="research-flow"><div class="flow-heading"><div><h2>这次想研究什么？</h2><p class="muted">从一个问题开始，逐步找到值得读的论文和可用的结论。</p></div><button data-flow-new ${disabled}>新建研究</button></div><nav class="flow-steps" aria-label="研究步骤">${[['确定方向','主题 · 时间范围'],['筛选论文','搜索 · AI 初筛'],['研究纲要','总结 · 比较'],['深入研究','原文 · 证据 · 归档']].map(([a,b],i)=>`<button data-flow-step="${i+1}" class="${current===i+1?'active':''}" ${disabled||(!s&&i>0?'disabled':'')}><span>${i+1}</span><div>${a}<small>${b}</small></div></button>`).join('')}</nav>${busy?`<div class="flow-progress" role="status"><span class="spinner"></span>${esc(busy)}<small>完成后自动保存；每次点击只执行当前任务。</small></div>`:''}${error?`<div class="flow-error" role="alert">${esc(error)}<button data-flow-dismiss>关闭</button></div>`:''}${current===1?focus(s,disabled):current===2?shortlist(s,disabled):current===3?reportPanel(s,disabled):deepPanel(s,disabled)}${sessions().length?`<section class="panel flow-history"><div class="section-head"><h3>继续之前的研究</h3><span class="meta">结果保存在本设备，并复用现有加密同步</span></div><div class="session-list">${sessions().slice(0,12).map(x=>`<button data-flow-session="${x.id}" ${disabled}><strong>${esc(x.topic)}</strong><small>${esc(x.from||'不限')} — ${esc(x.to||'不限')} · ${x.candidates?.length||0} 篇 · ${x.report?'已生成纲要':x.screening?'已筛选':'进行中'}</small></button>`).join('')}</div></section>`:''}<p class="help flow-footnote">Gemini 3.5 Flash-Lite · 仅点击 AI 按钮时调用。搜索不使用 LLM；刷新、切换页面和同步不会生成内容。${s?.usage?.length?`本研究 ${s.usage.filter(x=>!x.cached).length} 次生成 · ${s.usage.reduce((n,x)=>n+(x.cached?0:x.tokens||0),0).toLocaleString()} Token（记录值）`:''}</p></div>`;
 }
 function focus(s,disabled){return `<section class="panel flow-focus"><form id="research-focus"><fieldset ${disabled}><label>研究主题<input name="topic" required maxlength="120" value="${esc(s?.topic||'')}" placeholder="例如 GraphRAG 的评估、Agent 失败恢复、低成本 RAG"></label><div class="two"><label>开始日期<input name="from" type="date" value="${esc(s?.from||before(365))}"></label><label>结束日期<input name="to" type="date" value="${esc(s?.to||today())}"></label></div><div class="row date-presets">${[['30','近 30 天'],['90','近 3 个月'],['365','近一年'],['all','不限时间']].map(([v,l])=>`<button type="button" data-flow-dates="${v}">${l}</button>`).join('')}</div><label>你想解决的问题 <span class="meta">可选</span><textarea name="goal" rows="2" maxlength="1000" placeholder="例如：比较 GraphRAG 和向量 RAG，重点看可靠性与评估成本。">${esc(s?.goal||'')}</textarea></label><details><summary>自己指定搜索关键词</summary><label>英文短语，用 | 分隔同义词<input name="keywords" maxlength="400" value="${esc(s?.keywords||'')}" placeholder="graph retrieval | GraphRAG"></label></details><div class="row actions"><button class="primary" name="action" value="refine">AI 帮我明确方向 <small>1 次调用</small></button><button name="action" value="search">直接搜索论文</button></div><p class="help">按首次提交日期筛选 arXiv。AI 建议英文检索词，你可以调整后再搜索。</p></fieldset></form></section>${s?.refinement?`<section class="flow-directions"><div class="section-head"><h3>选一个更具体的方向</h3><span class="meta">可以修改检索词和研究问题</span></div><p>${esc(s.refinement.overview)}</p><div class="direction-grid">${s.refinement.directions.map((d,i)=>`<article class="panel"><span class="flow-kicker">方向 ${i+1}</span><h3>${esc(d.name)}</h3><p>${esc(d.question)}</p><p class="help"><strong>关注</strong> ${esc(d.include)}<br><strong>暂不考虑</strong> ${esc(d.exclude)}</p><label>搜索词<input data-direction-keywords="${i}" maxlength="400" value="${esc(d.keywords.join(' | '))}"></label><button class="primary" data-flow-direction="${i}" ${disabled}>按此方向搜论文</button></article>`).join('')}</div></section>`:''}`}
 function shortlist(s,disabled){if(!s)return '';const ranked=new Map((s.screening?.papers||[]).map(r=>[r.id,r]));const list=[...s.candidates].sort((a,b)=>(ranked.get(b.id)?.score||0)-(ranked.get(a.id)?.score||0));return `<section class="panel"><div class="section-head"><div><h3>${esc(s.direction||s.topic)}</h3><p class="meta">${esc(s.from||'不限')} — ${esc(s.to||'不限')} · ${esc(s.keywords)}</p></div><button data-flow-step="1" ${disabled}>调整方向</button></div>${s.directionDetails?`<p class="help">${esc(s.directionDetails)}</p>`:''}<div class="flow-toolbar"><button class="primary" data-flow-screen ${disabled||(!s.candidates.length?'disabled':'')}>${s.screening?'重新 AI 筛选':'AI 筛选这些论文'} <small>1 次调用</small></button><button data-flow-step="3" ${disabled||(!s.selectedIds.length?'disabled':'')}>生成研究纲要 · 已选 ${s.selectedIds.length}/12</button><button data-flow-search ${disabled}>重新搜索</button>${s.candidates.length<40&&s.search?.total>s.search?.nextStart?`<button data-flow-more ${disabled}>再看 20 篇</button>`:''}</div><p class="help">当前检索到 ${s.candidates.length} 篇${s.search?.total?'，arXiv 匹配约 '+s.search.total+' 篇':''}。初筛基于标题和摘要；相关度不等于论文质量。选中的论文会在生成纲要时自动加入 Library。</p>${s.screening?`<div class="notice">${esc(s.screening.summary)}</div>`:''}${s.candidates.length?`<div class="candidate-list">${list.map(p=>{const r=ranked.get(p.id);return `<article class="candidate"><label class="candidate-select"><input type="checkbox" data-flow-select="${esc(p.id)}" ${s.selectedIds.includes(p.id)?'checked':''} ${disabled}><span class="sr-only">选择 ${esc(p.title)}</span></label><div><div class="row">${r?`<span class="badge ${r.recommendation==='deep'?'teal':''}">${esc(pickLabel[r.recommendation])} · ${r.score}</span>`:''}<span class="meta">${esc(p.published)} · arXiv</span></div><h3><a href="${esc(p.url)}" target="_blank" rel="noopener">${esc(p.title)}</a></h3><p class="meta">${esc(p.authors?.slice(0,4).join(', '))}</p>${r?`<p>${esc(r.reason)}</p><p class="focus-line"><strong>重点读</strong> ${esc(r.focus)}</p>${r.caveat?`<p class="help">需核查：${esc(r.caveat)}</p>`:''}`:''}<details><summary>查看摘要</summary><p>${esc(p.abstract||'此来源没有摘要')}</p></details></div></article>`}).join('')}</div>`:`<div class="empty"><h3>这个范围内没有找到论文</h3><p>扩大日期范围，或者改用更宽泛的英文检索词。</p><button data-flow-step="1">调整检索</button></div>`}</section>`}
 function reportHTML(r){return `<div class="research-report"><section><h3>主题总结</h3><p>${esc(r.overview)}</p></section><section><h3>按这个纲要理解</h3>${(r.outline||[]).map((x,i)=>`<article class="outline-item"><span>${i+1}</span><div><h4>${esc(x.title)}</h4><p>${esc(x.explanation)}</p><div class="row">${(x.paperIds||[]).map(linkPaper).join('')}</div></div></article>`).join('')}</section><section><h3>建议阅读顺序</h3>${(r.readingOrder||[]).map((x,i)=>`<div class="reading-item"><span>${i+1}</span><div>${linkPaper(x.paperId)}<p>${esc(x.why)}</p><small>重点：${esc(x.focus)}</small></div></div>`).join('')}</section>${r.comparison?.length?`<section><h3>方法比较</h3><p class="help">只有摘要或已提取字段支持的比较；“待核查”不能视为验证完成。</p><div class="comparison-table"><table><thead><tr><th>维度</th><th>论文与结论</th></tr></thead><tbody>${r.comparison.map(d=>`<tr><th>${esc(d.dimension)}</th><td>${d.items.map(x=>`<div class="comparison-item">${linkPaper(x.paperId)}<p>${esc(x.value)}</p>${x.quote?`<details><summary>${x.matched?'引文匹配 · 待核查':'引文不匹配 · 请核查'}</summary><blockquote>${esc(x.quote)}</blockquote></details>`:'<small class="muted">无逐字引用 · 待核查</small>'}</div>`).join('')}</td></tr>`).join('')}</tbody></table></div></section>`:''}<section><h3>关键结论与下一步</h3>${points(r.takeaways)}<h4>可以继续研究的问题（AI 建议）</h4>${points(r.openQuestions)}</section></div>`}
 function reportPanel(s,disabled){const chosen=s?.candidates.filter(p=>s.selectedIds.includes(p.id))||[];return `<section class="panel"><div class="section-head"><div><h3>研究纲要与比较</h3><p class="help">选 ${chosen.length} 篇论文，从问题、方法、证据到下一步串成完整的阅读路线。</p></div><button data-flow-step="2" ${disabled}>返回选论文</button></div><div class="row"><button class="primary" data-flow-synthesize ${disabled||(!chosen.length?'disabled':'')}>${s?.report?'更新总结与比较':'生成总结、纲要与比较'} <small>1 次调用</small></button>${s?.report?`<button data-flow-step="4" ${disabled}>开始深读</button><button data-flow-export>导出研究总结</button><button data-topic="${esc(s.direction||s.topic)}">打开 Topic Space</button>`:''}</div>${s?.report?`<p class="help">已自动归档所选论文、主题总结和候选知识关系。当前总结依据摘要与已提取证据；深读后可点击更新。</p>${reportHTML(s.report)}`:`<div class="flow-preview">${chosen.length?chosen.map(p=>`<p>${esc(p.title)}</p>`).join(''):'先到“筛选论文”选择你关心的内容。'}</div>`}</section>`}
 function deepPanel(s,disabled){const ps=(s?.candidates||[]).filter(p=>s.selectedIds.includes(p.id));return `<section class="panel"><div class="section-head"><div><h3>把纲要变成自己的研究理解</h3><p class="help">打开论文，读取全文，再点击 AI 深读。核查关键结果后，回到这里更新总结。</p></div><button data-flow-step="3" ${disabled}>更新研究总结</button></div>${ps.map(c=>{const p=paper(c.libraryId);return `<article class="deep-card"><div><h3>${esc(c.title)}</h3><p class="help">${p?.aiRead?'已生成 AI 深读 · '+(p.aiRead.coverage?.abstractOnly?'摘要级解读':p.aiRead.coverage?.included+' 段原文'):p?'已保存到 Library，待深读':'待保存到 Library'}</p></div>${p?`<button class="primary" data-open-paper="${p.id}">阅读与核查证据</button>`:`<button data-flow-step="3">先生成纲要并归档</button>`}</article>`}).join('')}<div class="row actions"><button data-view="library">打开 Library</button><button data-topic="${esc(s?.direction||s?.topic||'')}">打开 Topic Space</button><button data-view="graph">查看 Knowledge Graph</button></div><p class="help">知识图谱自动聚合论文、主题及提取的研究对象；AI 生成的关系标为候选，不自动当作已确认的引用网络。</p></section>`}
 function archive(s){let next=structuredClone(ctx.state());const candidates=structuredClone(s.candidates);for(const c of candidates.filter(c=>s.selectedIds.includes(c.id))){const added=upsertPaper(next,c);next=added.state;const p=added.paper||added.duplicate;c.libraryId=p.id;const target=next.papers.find(x=>x.id===p.id);target.status=target.status==='deep'?'deep':'saved';target.topics=[...new Set([...target.topics,(s.direction||s.topic).slice(0,120)])];target.updatedAt=ctx.stamp()}
 const record=next.researchSessions.find(x=>x.id===s.id);record.candidates=candidates;record.updatedAt=ctx.stamp();if(!ctx.change(next))throw Error('论文归档失败');return session();
 }
 function archiveReport(s,r){const next=structuredClone(ctx.state()),name=(s.direction||s.topic).slice(0,120),now=ctx.stamp();let t=next.topics.find(t=>!t.deleted&&t.name===name);if(!t){t={id:crypto.randomUUID(),name,notes:'',questions:'',deleted:false};next.topics.push(t)}t.synthesis=r;t.updatedAt=now;
 for(const e of r.entities||[]){let entity=next.entities.find(n=>!n.deleted&&n.type===e.type&&canonical(n.name)===canonical(e.name));if(!entity){entity={id:crypto.randomUUID(),name:e.name,type:e.type,paperId:e.paperIds[0],paragraphId:'',deleted:false,updatedAt:now};next.entities.push(entity)}for(const id of e.paperIds){const type={Method:'uses',Model:'uses',Dataset:'evaluated_on',Benchmark:'evaluated_on',Metric:'measured_by'}[e.type];if(!next.relations.some(x=>!x.deleted&&x.from===id&&x.to===entity.id&&x.type===type))next.relations.push({id:crypto.randomUUID(),from:id,to:entity.id,type,paperId:id,paragraphId:'',inferred:true,deleted:false,updatedAt:now})}}
 if(!ctx.change(next))throw Error('主题与图谱保存失败');
 }
 function bind(){const form=document.querySelector('#research-focus');if(form)form.onsubmit=e=>{e.preventDefault();if(busy)return;try{const s=begin(form),action=e.submitter?.value;run(action==='search'?'搜索论文…':'AI 正在梳理研究方向…',async()=>{if(action==='search')await search(s);else{const r=await ai('refine',scoped(s));usage(r,s.id);save({refinement:r.output,step:1},s.id);step=1}})}catch(e){error=e.message;ctx.render()}};
 }
 async function click(e){const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(!Object.keys(d).some(k=>k.startsWith('flow')))return;if(busy&&d.flowDismiss===undefined)return;
 if('flowDismiss'in d){error='';ctx.render();return}if('flowNew'in d){active='';step=1;error='';localStorage.removeItem('research-workbench.active');ctx.render();return}
 if(d.flowStep){step=+d.flowStep;ctx.render();return}if(d.flowSession){active=d.flowSession;localStorage.setItem('research-workbench.active',active);step=session()?.step||1;error='';ctx.render();return}
 if(d.flowDates){const f=document.querySelector('#research-focus');f.elements.from.value=d.flowDates==='all'?'':before(+d.flowDates);f.elements.to.value=d.flowDates==='all'?'':today();return}
 const s=session();if(!s)return;
 if(d.flowDirection!==undefined){const direction=s.refinement.directions[+d.flowDirection],keywords=document.querySelector(`[data-direction-keywords="${d.flowDirection}"]`).value.trim();save({direction:direction.name.slice(0,120),directionDetails:[direction.question,'关注：'+direction.include,'排除：'+direction.exclude].join('；'),keywords});await run('按所选方向搜索论文…',()=>search(session()));return}
 if('flowSearch'in d||'flowMore'in d){await run('查询 arXiv 论文…',()=>search(s,'flowMore'in d?s.search.nextStart:0));return}
 if('flowScreen'in d){await run('AI 正在筛选论文并建议阅读重点…',async()=>{const r=await ai('screen',{...scoped(s),papers:s.candidates});usage(r,s.id);save({screening:r.output,selectedIds:r.output.papers.filter(p=>p.recommendation==='deep').sort((a,b)=>b.score-a.score).slice(0,5).map(p=>p.id),step:2},s.id)});return}
 if('flowSynthesize'in d){await run('生成研究纲要、方法比较，并整理到主题和图谱…',async()=>{const stored=archive(s),ps=stored.candidates.filter(c=>stored.selectedIds.includes(c.id)).map(c=>paper(c.libraryId)).filter(Boolean);const r=await ai('synthesize',{...scoped(stored),papers:ps});usage(r,stored.id);save({report:r.output,step:3},stored.id);archiveReport(stored,r.output);step=3});return}
 if('flowExport'in d){const sources=s.candidates.filter(c=>s.selectedIds.includes(c.id));ctx.download('research-summary.md',exportReport(s.topic,s.report)+'\n\n## Sources\n'+sources.map(p=>'- '+p.title+': '+p.url+' (ID: '+p.libraryId+')').join('\n'),'text/markdown')}
 }
 function selection(e){const id=e.target.dataset.flowSelect;if(!id)return;const s=session(),ids=new Set(s.selectedIds);if(e.target.checked&&ids.size>=12){e.target.checked=false;ctx.toast('最多选择 12 篇论文；建议先选 3–5 篇。');return}e.target.checked?ids.add(id):ids.delete(id);save({selectedIds:[...ids],report:null,step:2});ctx.render()}
 async function deep(p){await run('AI 正在解读论文与提取原文证据…',async()=>{const r=await ai('deep',{topic:p.topics[0]||p.title,goal:session()?.goal||'',paper:p});usage(r);const latest=paper(p.id);if(!latest)throw Error('论文已被删除');const extraction=importExtraction(latest,r.output),fields={...latest.fields};for(const [k,f] of Object.entries(extraction.fields)){const old=latest.fields[k];if(!old?.value||(!old.confirmed&&old.origin!=='manual'))fields[k]=f}ctx.updatePaper(p.id,{fields,aiRead:{...r.output,model:r.model,usage:r.usage,generatedAt:r.generatedAt},status:'deep'});ctx.toast('AI 深读已保存；请核查证据，之后可更新主题总结。')})}
 async function synthesizePapers(ps,name,task='compare'){await run(task==='compare'?'AI 正在比较所选论文…':'AI 正在整理主题…',async()=>{const r=await ai(task,{topic:name,papers:ps});if(task==='topic'){usage(r)}if(task==='topic'){const next=structuredClone(ctx.state()),t=next.topics.find(x=>!x.deleted&&x.name===name)||{id:crypto.randomUUID(),name,notes:'',questions:'',deleted:false};t.synthesis=r.output;t.updatedAt=ctx.stamp();if(!next.topics.includes(t))next.topics.push(t);ctx.change(next)}else{const next=structuredClone(ctx.state()),s={id:crypto.randomUUID(),topic:name,goal:'',from:'',to:'',keywords:name,direction:'',step:3,candidates:ps.map(p=>({...p,id:p.id,libraryId:p.id})),selectedIds:ps.map(p=>p.id),report:r.output,usage:[{tokens:r.usage?.totalTokenCount||0,cached:r.cached,model:r.model}],updatedAt:ctx.stamp(),deleted:false};next.researchSessions.push(s);ctx.change(next);active=s.id;localStorage.setItem('research-workbench.active',active);step=3;ctx.navigate('discover')}archiveReport({direction:name,topic:name},r.output)})}
 function readerHTML(p){const r=p.aiRead;return `<div class="ai-reader-controls"><button class="primary" data-llm-deep ${busy?'disabled':''}>${r?'更新 AI 深读':'AI 深读与证据提取'} <small>1 次调用</small></button><button data-view="discover">返回本次研究</button></div>${busy?`<p class="help" role="status">${esc(busy)}</p>`:''}${error?`<div class="flow-error">${esc(error)}</div>`:''}${r?`<section class="ai-reading-guide"><div class="row"><span class="badge teal">AI 阅读路线</span><span class="meta">${r.coverage?.abstractOnly?'摘要级解读':r.coverage?.included+' / '+r.coverage?.total+' 段原文'} · 引用需核查</span></div><h3>先理解这篇在解决什么</h3><p>${esc(r.summary)}</p>${(r.readingGuide||[]).map((g,i)=>`<article class="outline-item"><span>${i+1}</span><div><h4>${esc(g.title)}</h4><p>${esc(g.explanation)}</p><div class="row">${g.paragraphIds.map(id=>`<button class="quiet" data-source="${esc(id)}">查看 ${esc(id)} 原文</button>`).join('')}</div></div></article>`).join('')}<h4>带着这些问题核查</h4>${points(r.questions)}</section>`:'<p class="help">先读取 arXiv 全文或粘贴重点章节，再让 AI 解释方法、生成阅读路线和提取引用。仅有摘要时会明确标注。</p>'}`}
 return {render,bind,click,selection,deep,readerHTML,reportHTML,synthesizePapers,isBusy:()=>!!busy};
}
export function exportReport(topic,r){if(!r)return '';return `# ${topic}\n\n## 主题总结\n${r.overview}\n\n## 阅读纲要\n`+(r.outline||[]).map(x=>`### ${x.title}\n${x.explanation}\n关联论文 ID：${x.paperIds.join(', ')}`).join('\n\n')+'\n\n## 方法比较\n'+(r.comparison||[]).map(d=>'### '+d.dimension+'\n'+d.items.map(x=>`- ${x.paperId}: ${x.value}\n  原文：${x.quote||'无引用'} (${x.matched?'匹配，待核查':'待核查'})`).join('\n')).join('\n\n')+'\n\n## 下一步问题\n'+(r.openQuestions||[]).map(x=>'- '+x).join('\n');}
