import {upsertPaper,canonical,importExtraction,evidenceStatus,FIELDS} from './model.mjs?v=5';
import {config} from './sync.mjs?v=5';
const API='https://pt-universe-api.summer07-nanjolno.workers.dev';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toLocaleDateString('en-CA');
const before=days=>new Date(Date.now()-days*86400000).toLocaleDateString('en-CA');
const pickLabel={deep:'建议精读',skim:'快速浏览',skip:'暂不优先'};
export function createResearchFlow(ctx){
 let active=localStorage.getItem('research-workbench.active')||'',busy='',error='',step=1;
 const sessions=()=>ctx.state().researchSessions.filter(s=>!s.deleted).sort((a,b)=>b.updatedAt-a.updatedAt);
 const session=()=>sessions().find(s=>s.id===active);
 step=session()?.step||1;
 function save(updates,id=active){const next=structuredClone(ctx.state()),s=next.researchSessions.find(s=>s.id===id);if(!s)throw Error('研究记录不存在');Object.assign(s,updates,{updatedAt:ctx.stamp()});if(!ctx.change(next))throw Error('保存失败，请先导出备份');return s}
 const paper=id=>ctx.state().papers.find(p=>p.id===id&&!p.deleted);
 const linkPaper=id=>{const c=session()?.candidates.find(c=>c.id===id||c.libraryId===id),p=paper(c?.libraryId||id);return p?`<button class="quiet source-ref" data-open-paper="${esc(p.id)}">${esc(p.title)}</button>`:c?`<a class="source-ref" href="${esc(c.url)}" target="_blank" rel="noopener">${esc(c.title)}</a>`:''};
 const points=list=>`<ul>${(list||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
 async function ai(task,data){
  const cfg=config();if(!cfg)throw Error('请先在“备份与同步”中连接你原有的 PT Universe 配对码，再使用 AI。');
  const r=await fetch(`${API}/api/workbench/ai/${encodeURIComponent(cfg.id)}`,{method:'POST',cache:'no-store',headers:{'content-type':'application/json',authorization:'Bearer '+cfg.token},signal:AbortSignal.timeout(90000),body:JSON.stringify({task,...data})});
  const result=await r.json().catch(()=>null);if(!r.ok||!result?.output)throw Error(result?.error||'研究服务暂不可用，请稍后手动重试');return result;
 }
 function usage(r,sid=active){const s=sessions().find(x=>x.id===sid);if(s)save({usage:[...(s.usage||[]),{task:busy,model:r.model,tokens:r.usage?.totalTokenCount||0,cached:r.cached,at:r.generatedAt}].slice(-50)},sid)}
 async function run(label,fn){if(busy)return;busy=label;error='';ctx.render();try{await fn()}catch(e){error=e.name==='TimeoutError'?'请求超时；已保存前面的结果，稍后可以继续。':e.message;ctx.toast(error)}finally{busy='';ctx.render()}}
 function begin(form){const f=new FormData(form),topic=String(f.get('topic')||'').trim(),from=String(f.get('from')||''),to=String(f.get('to')||'');if(!topic)throw Error('请输入研究主题');if(from&&to&&from>to)throw Error('起始日期不能晚于结束日期');const next=structuredClone(ctx.state()),existing=session(),row={id:crypto.randomUUID(),topic,goal:String(f.get('goal')||'').trim(),from,to,keywords:String(f.get('keywords')||'').trim()||topic,direction:'',step:1,candidates:[],selectedIds:[],usage:[],updatedAt:ctx.stamp(),deleted:false};
 if(existing&&existing.topic===row.topic&&existing.goal===row.goal&&existing.from===row.from&&existing.to===row.to){save({keywords:row.keywords});return session()}
 next.researchSessions.push(row);if(!ctx.change(next))throw Error('研究记录保存失败');active=row.id;localStorage.setItem('research-workbench.active',active);step=1;return row;
 }
 const scoped=s=>({topic:s.topic,goal:s.goal+(s.direction?'；方向：'+s.direction:'')+(s.directionDetails?'；'+s.directionDetails:''),from:s.from,to:s.to});
 async function search(s,start=0){
  const id=s.id,params=new URLSearchParams({q:s.keywords,from:s.from,to:s.to,start:String(start)});
  const r=await fetch(API+'/api/workbench/discover?'+params,{cache:'no-store',signal:AbortSignal.timeout(45000)}),data=await r.json().catch(()=>null);if(!r.ok||!data?.items)throw Error(data?.error||'论文搜索暂不可用，请重试');
  const old=start?s.candidates:[],items=[...old,...data.items.map(p=>({...p,id:p.arxivId||canonical(p.title)}))],unique=[...new Map(items.map(p=>[p.id,p])).values()].slice(0,40);
  save({candidates:unique,selectedIds:start?s.selectedIds:[],screening:null,report:null,roundSummary:null,organizedAt:0,search:{...data,items:undefined},step:2},id);step=2;
 }
 function render(){
  const s=session(),current=s?step:1;const disabled=busy?'disabled':'';
  return `<div class="research-flow"><div class="flow-heading"><div><h2>这次想研究什么？</h2><p class="muted">从一个问题开始，快速提炼关键结论，保留证据，整理成以后可复用的研究记忆。</p></div><button data-flow-new ${disabled}>新建研究</button></div><nav class="flow-steps" aria-label="研究步骤">${[['确定方向','主题 · 时间范围'],['筛选论文','搜索 · AI 初筛'],['文章要点','总结 · 纲要 · 比较'],['本轮总报告','完整汇总 · 证据附录']].map(([a,b],i)=>`<button data-flow-step="${i+1}" class="${current===i+1?'active':''}" ${disabled||(!s&&i>0?'disabled':'')}><span>${i+1}</span><div>${a}<small>${b}</small></div></button>`).join('')}</nav>${busy?`<div class="flow-progress" role="status"><span class="spinner"></span>${esc(busy)}<small>完成后自动保存；当前流程完成后自动保存关键结果。</small></div>`:''}${error?`<div class="flow-error" role="alert">${esc(error)}<button data-flow-dismiss>关闭</button></div>`:''}${current===1?focus(s,disabled):current===2?shortlist(s,disabled):current===3?reportPanel(s,disabled):deepPanel(s,disabled)}${sessions().length?`<section class="panel flow-history"><div class="section-head"><h3>继续之前的研究</h3><span class="meta">结果保存在本设备，并复用现有加密同步</span></div><div class="session-list">${sessions().slice(0,12).map(x=>`<button data-flow-session="${x.id}" ${disabled}><strong>${esc(x.topic)}</strong><small>${esc(x.from||'不限')} — ${esc(x.to||'不限')} · ${x.candidates?.length||0} 篇 · ${x.roundSummary?'总报告已完成':x.report?'要点已提炼':x.screening?'已筛选':'进行中'}</small></button>`).join('')}</div></section>`:''}<p class="help flow-footnote">Gemini 3.5 Flash-Lite · 确认选文后自动提炼；其余 AI 任务按按钮调用。搜索不使用 LLM；刷新、切换页面和同步不会生成内容。${s?.usage?.length?`本研究 ${s.usage.filter(x=>!x.cached).length} 次生成 · ${s.usage.reduce((n,x)=>n+(x.cached?0:x.tokens||0),0).toLocaleString()} Token（记录值）`:''}</p></div>`;
 }
 function focus(s,disabled){return `<section class="panel flow-focus"><form id="research-focus"><fieldset ${disabled}><label>研究主题<input name="topic" required maxlength="120" value="${esc(s?.topic||'')}" placeholder="例如 GraphRAG 的评估、Agent 失败恢复、低成本 RAG"></label><div class="two"><label>开始日期<input name="from" type="date" value="${esc(s?.from??before(365))}"></label><label>结束日期<input name="to" type="date" value="${esc(s?.to??today())}"></label></div><div class="row date-presets">${[['30','近 30 天'],['90','近 3 个月'],['365','近一年'],['all','不限时间']].map(([v,l])=>`<button type="button" data-flow-dates="${v}">${l}</button>`).join('')}</div><label>你想解决的问题 <span class="meta">可选</span><textarea name="goal" rows="2" maxlength="1000" placeholder="例如：比较 GraphRAG 和向量 RAG，重点看可靠性与评估成本。">${esc(s?.goal||'')}</textarea></label><details><summary>自己指定搜索关键词</summary><label>英文关键词，用 | 分隔同义词<input name="keywords" maxlength="400" value="${esc(s?.keywords||'')}" placeholder="graph retrieval | GraphRAG"></label></details><div class="row actions"><button class="primary" name="action" value="refine">AI 帮我明确方向 <small>1 次调用</small></button><button name="action" value="search">直接搜索论文</button></div><p class="help">按首次提交日期筛选 arXiv。AI 建议英文检索词；词组按关键词组合匹配，用双引号才会按完整短语匹配。</p></fieldset></form></section>${s?.refinement?`<section class="flow-directions"><div class="section-head"><h3>选一个更具体的方向</h3><span class="meta">可以修改检索词和研究问题</span></div><p>${esc(s.refinement.overview)}</p><div class="direction-grid">${s.refinement.directions.map((d,i)=>`<article class="panel"><span class="flow-kicker">方向 ${i+1}</span><h3>${esc(d.name)}</h3><p>${esc(d.question)}</p><p class="help"><strong>关注</strong> ${esc(d.include)}<br><strong>暂不考虑</strong> ${esc(d.exclude)}</p><label>搜索词<input data-direction-keywords="${i}" maxlength="400" value="${esc(d.keywords.join(' | '))}"></label><button class="primary" data-flow-direction="${i}" ${disabled}>按此方向搜论文</button></article>`).join('')}</div></section>`:''}`}
 function shortlist(s,disabled){if(!s)return '';const ranked=new Map((s.screening?.papers||[]).map(r=>[r.id,r]));const list=[...s.candidates].sort((a,b)=>(ranked.get(b.id)?.score||0)-(ranked.get(a.id)?.score||0));return `<section class="panel"><div class="section-head"><div><h3>${esc(s.direction||s.topic)}</h3><p class="meta">${esc(s.from||'不限')} — ${esc(s.to||'不限')} · ${esc(s.keywords)}</p></div><button data-flow-step="1" ${disabled}>调整方向</button></div>${s.directionDetails?`<p class="help">${esc(s.directionDetails)}</p>`:''}<div class="flow-toolbar"><button class="primary" data-flow-screen ${disabled||(!s.candidates.length?'disabled':'')}>${s.screening?'重新 AI 筛选':'AI 筛选这些论文'} <small>1 次调用</small></button><button data-flow-synthesize ${disabled||(!s.selectedIds.length?'disabled':'')}>选好了，自动提炼 · ${s.selectedIds.length}/12 篇</button><button data-flow-search ${disabled}>重新搜索</button>${s.candidates.length<40&&s.search?.total>s.search?.nextStart?`<button data-flow-more ${disabled}>再看 20 篇</button>`:''}</div><p class="help">当前检索到 ${s.candidates.length} 篇${s.search?.total?'，arXiv 匹配约 '+s.search.total+' 篇':''}。关键词组合匹配，不要求连续出现。初筛基于标题和摘要；相关度不等于论文质量。选好后自动读取可用关键段落，生成单篇要点、纲要与比较；再由你点击整理保存到 Library。</p>${s.screening?`<div class="notice">${esc(s.screening.summary)}</div>`:''}${s.candidates.length?`<div class="candidate-list">${list.map(p=>{const r=ranked.get(p.id);return `<article class="candidate"><label class="candidate-select"><input type="checkbox" data-flow-select="${esc(p.id)}" ${s.selectedIds.includes(p.id)?'checked':''} ${disabled}><span class="sr-only">选择 ${esc(p.title)}</span></label><div><div class="row">${r?`<span class="badge ${r.recommendation==='deep'?'teal':''}">${esc(pickLabel[r.recommendation])} · ${r.score}</span>`:''}<span class="meta">${esc(p.published)} · arXiv</span></div><h3><a href="${esc(p.url)}" target="_blank" rel="noopener">${esc(p.title)}</a></h3><p class="meta">${esc(p.authors?.slice(0,4).join(', '))}</p>${r?`<p>${esc(r.reason)}</p><p class="focus-line"><strong>重点读</strong> ${esc(r.focus)}</p>${r.caveat?`<p class="help">需核查：${esc(r.caveat)}</p>`:''}`:''}<details><summary>查看摘要</summary><p>${esc(p.abstract||'此来源没有摘要')}</p></details></div></article>`}).join('')}</div>`:`<div class="empty"><h3>这个范围内没有找到论文</h3><p>可能是关键词过细，或这个时间范围内没有匹配。可先放宽关键词，再调整日期。</p><button data-flow-broaden ${disabled||(broaderKeywords(s.keywords)===s.keywords?'disabled':'')}>放宽关键词重搜（保留时间范围）</button><button data-flow-step="1" ${disabled}>修改关键词与日期</button></div>`}</section>`}
 function reportHTML(r){return `<div class="research-report"><section class="takehome"><h3>Take home messages</h3>${points(r.takeaways)}</section><section><h3>研究结论</h3><p>${esc(r.overview)}</p></section><section><h3>按这个纲要理解</h3>${(r.outline||[]).map((x,i)=>`<article class="outline-item"><span>${i+1}</span><div><h4>${esc(x.title)}</h4><p>${esc(x.explanation)}</p><div class="row">${(x.paperIds||[]).map(linkPaper).join('')}</div></div></article>`).join('')}</section><details><summary>可选：阅读与核查顺序</summary>${(r.readingOrder||[]).map((x,i)=>`<div class="reading-item"><span>${i+1}</span><div>${linkPaper(x.paperId)}<p>${esc(x.why)}</p><small>重点：${esc(x.focus)}</small></div></div>`).join('')}</details>${r.comparison?.length?`<section><h3>方法比较</h3><p class="help">依据摘要、关键原文或已存证据的比较；“待核查”不能视为验证完成。</p><div class="comparison-table"><table><thead><tr><th>维度</th><th>论文与结论</th></tr></thead><tbody>${r.comparison.map(d=>`<tr><th>${esc(d.dimension)}</th><td>${d.items.map(x=>`<div class="comparison-item">${linkPaper(x.paperId)}<p>${esc(x.value)}</p>${x.quote?`<details><summary>${x.matched?'引文匹配 · 待核查':'引文不匹配 · 请核查'}</summary><blockquote>${esc(x.quote)}</blockquote></details>`:'<small class="muted">无逐字引用 · 待核查</small>'}</div>`).join('')}</td></tr>`).join('')}</tbody></table></div></section>`:''}<section><h3>可以继续研究的问题（AI 建议）</h3>${points(r.openQuestions)}</section></div>`}
 function paperDigestHTML(s){return (s.report?.paperSummaries||[]).map(d=>`<article class="digest-card"><div class="section-head"><h3>${linkPaper(d.paperId)}</h3><span class="badge">${d.coverage?.abstractOnly?'仅摘要':'关键原文段落'}</span></div><p>${esc(d.summary)}</p>${points(d.takeaways)}<details><summary>证据摘录 · ${d.evidence?.length||0} 条${d.coverage&&!d.coverage.abstractOnly?' · '+d.coverage.included+'/'+d.coverage.total+' 段':''}</summary>${evidenceHTML(d)}</details></article>`).join('')}
 function evidenceHTML(d){return (d.evidence||[]).map(e=>`<article class="evidence-snippet"><div class="row"><strong>${esc(FIELDS.find(x=>x[0]===e.kind)?.[1]||e.kind)}</strong><span class="badge ${e.matched?'teal':''}">${e.matched?(e.confirmed?'人工已核查':'引文匹配 · 未人工核查'):'引文不匹配 · 待核查'}</span></div><p>${esc(e.value)}</p><blockquote>${esc(e.quote||'未提供引文')}</blockquote><small>${esc(e.section)} · 来源段落 ${esc(e.paragraphId||'未知')}</small></article>`).join('')||'<p class="help">没有足够证据支持额外提取。</p>'}
 function reportPanel(s,disabled){const chosen=s?.candidates.filter(p=>s.selectedIds.includes(p.id))||[];return `<section class="panel"><div class="section-head"><div><h3>所选文章的关键要点</h3><p class="help">先看 take home messages，再按需要展开证据和比较。</p></div><button data-flow-step="2" ${disabled}>调整选文</button></div><div class="row"><button data-flow-synthesize ${disabled||(!chosen.length?'disabled':'')}>${s?.report?'重新提炼要点':'生成文章要点'} <small>1 次调用</small></button>${s?.report?`<button class="primary" data-flow-organize ${disabled}>${s.organizedAt?'再次整理关键结果':'整理进 Library / Topic Space / 图谱'}</button><button data-flow-round ${disabled}>下一步：生成本轮总报告</button><button data-flow-export>导出当前结果</button>`:''}</div>${s?.report?`<p class="help">${s.organizedAt?'关键结果已整理，可在各空间找回。':'关键结果已保存在本轮记录；点击整理后加入相关研究空间。'} 自动获取的全文仅用于提炼，保留要点与引用摘录。引用匹配不代表结论已核实。</p><div class="digest-list">${paperDigestHTML(s)}</div>${reportHTML(s.report)}`:`<div class="flow-preview">${chosen.map(p=>`<p>${esc(p.title)}</p>`).join('')||'先到“筛选论文”选择你关心的内容。'}</div>`}</section>`}
 function deepPanel(s,disabled){return `<section class="panel"><div class="section-head"><div><h3>本轮研究完整汇总</h3><p class="help">回答研究问题，整合跨篇结论、差异与适用条件，并附上这轮证据提取。</p></div><button data-flow-step="3" ${disabled}>返回文章要点</button></div><div class="row"><button class="primary" data-flow-round ${disabled||(!s?.report?'disabled':'')}>${s?.roundSummary?'更新本轮总报告':'生成本轮总报告'} <small>1 次调用</small></button>${s?.roundSummary?`<button data-flow-organize ${disabled}>整理总报告与关键结果</button><button data-flow-export>导出总报告与证据</button>`:''}</div>${s?.roundSummary?`${reportHTML(s.roundSummary)}<section class="evidence-appendix"><h3>证据提取附录</h3><p class="help">总报告使用每篇最多 4 条关键证据与字段；完整提取随附录保存。缺失或不匹配的引用保留为待核查。</p>${(s.roundSummary.evidenceAppendix||[]).map(d=>`<details><summary>${linkPaper(d.paperId)||esc(d.title||d.paperId)} · ${d.evidence?.length||0} 条证据</summary>${evidenceHTML(d)}</details>`).join('')}</section>`:`<div class="empty"><p>${s?.report?'文章要点已经准备好，生成总报告即可完成这轮研究。':'先完成选文与要点提炼。'}</p></div>`}<details class="optional-reading"><summary>需要时再读原文或人工核查</summary><p class="help">从 Library 打开原文或粘贴章节，再做深读；更新总报告会纳入已提取字段。</p>${(s?.candidates||[]).filter(c=>s.selectedIds.includes(c.id)&&paper(c.libraryId)).map(c=>`<p>${linkPaper(c.id)}</p>`).join('')}<div class="row"><button data-view="library">Library</button><button data-topic="${esc(s?.direction||s?.topic||'')}">Topic Space</button><button data-view="graph">Knowledge Graph</button></div></details></section>`}
 async function digest(s){
  const chosen=s.candidates.filter(c=>s.selectedIds.includes(c.id));if(!chosen.length)throw Error('请先选择论文');
  const inputs=[];for(let i=0;i<chosen.length;i+=3){const batch=await Promise.all(chosen.slice(i,i+3).map(async c=>{const p=paper(c.libraryId),out={id:c.id,title:c.title,published:c.published,abstract:(c.abstract||'').slice(0,3000),paragraphs:[{id:'abstract',section:'Abstract',text:(c.abstract||'').slice(0,3000)}],sourceTotal:1,abstractOnly:true};
   if(p?.paragraphs.length>1)return {...out,paragraphs:keyPassages(p.paragraphs,Math.floor(85000/chosen.length)),sourceTotal:p.paragraphs.length,abstractOnly:false};
   if(c.arxivId){try{const r=await fetch(API+'/api/workbench/fulltext?q='+encodeURIComponent(c.arxivId),{signal:AbortSignal.timeout(45000)}),data=await r.json();if(r.ok&&data.paragraphs?.length>1)return {...out,paragraphs:keyPassages(data.paragraphs,Math.floor(85000/chosen.length)),sourceTotal:data.paragraphs.length,abstractOnly:false}}catch{}}
   return out;
  }));inputs.push(...batch)}
  const r=await ai('digest',{...scoped(s),papers:inputs});usage(r,s.id);save({report:r.output,roundSummary:null,organizedAt:0,step:3},s.id);step=3;
 }
 function organize(s){const stored=archive(s),r=stored.roundSummary||stored.report,next=structuredClone(ctx.state());for(const d of stored.report?.paperSummaries||[]){const c=stored.candidates.find(c=>c.id===d.paperId),p=next.papers.find(p=>p.id===c?.libraryId);if(p){p.aiDigest={...d,topic:stored.direction||stored.topic};p.updatedAt=ctx.stamp()}}if(!ctx.change(next))throw Error('关键要点保存失败');archiveReport(stored,r);save({organizedAt:ctx.stamp()},stored.id);ctx.toast('关键要点、证据与研究结论已整理，可随时取用。')}
 async function round(s){if(!s.report)throw Error('先生成文章要点');const ps=s.candidates.filter(c=>s.selectedIds.includes(c.id)).map(c=>({...c,fields:paper(c.libraryId)?.fields||{},digest:s.report.paperSummaries?.find(d=>d.paperId===c.id)}));const r=await ai('round',{...scoped(s),papers:ps.map(p=>roundInput(p,paper(p.libraryId)))});usage(r,s.id);
  const evidenceAppendix=ps.map(p=>{const extra=Object.entries(p.fields).filter(([,f])=>f?.value).map(([kind,f])=>({...f,kind,matched:['matched','confirmed'].includes(evidenceStatus(f,paper(p.libraryId)))}));return {paperId:p.id,title:p.title,url:p.url,coverage:p.digest?.coverage,evidence:[...(p.digest?.evidence||[]),...extra]}});
  save({roundSummary:{...r.output,evidenceAppendix,scope:{topic:s.topic,goal:s.goal,from:s.from,to:s.to}},step:4},s.id);step=4;
 }
 function archive(s){let next=structuredClone(ctx.state());const candidates=structuredClone(s.candidates);for(const c of candidates.filter(c=>s.selectedIds.includes(c.id))){const added=upsertPaper(next,c);next=added.state;const p=added.paper||added.duplicate;c.libraryId=p.id;const target=next.papers.find(x=>x.id===p.id);target.status=target.status==='deep'?'deep':'saved';target.topics=[...new Set([...target.topics,(s.direction||s.topic).slice(0,120)])];target.updatedAt=ctx.stamp()}
 const record=next.researchSessions.find(x=>x.id===s.id);record.candidates=candidates;record.updatedAt=ctx.stamp();if(!ctx.change(next))throw Error('论文归档失败');return session();
 }
 function archiveReport(s,r){const mapping=new Map((s.candidates||[]).map(c=>[c.id,c.libraryId||c.id]));r=remapReport(r,mapping);const next=structuredClone(ctx.state()),name=(s.direction||s.topic).slice(0,120),now=ctx.stamp();let t=next.topics.find(t=>!t.deleted&&t.name===name);if(!t){t={id:crypto.randomUUID(),name,notes:'',questions:'',deleted:false};next.topics.push(t)}t.synthesis=r;t.updatedAt=now;
 for(const e of r.entities||[]){let entity=next.entities.find(n=>!n.deleted&&n.type===e.type&&canonical(n.name)===canonical(e.name));if(!entity){entity={id:crypto.randomUUID(),name:e.name,type:e.type,paperId:e.paperIds[0],paragraphId:'',deleted:false,updatedAt:now};next.entities.push(entity)}for(const id of e.paperIds){const type={Method:'uses',Model:'uses',Dataset:'evaluated_on',Benchmark:'evaluated_on',Metric:'measured_by'}[e.type];if(!next.relations.some(x=>!x.deleted&&x.from===id&&x.to===entity.id&&x.type===type))next.relations.push({id:crypto.randomUUID(),from:id,to:entity.id,type,paperId:id,paragraphId:'',inferred:true,deleted:false,updatedAt:now})}}
 if(!ctx.change(next))throw Error('主题与图谱保存失败');
 }
 function bind(){const form=document.querySelector('#research-focus');if(form)form.onsubmit=e=>{e.preventDefault();if(busy)return;try{const s=begin(form),action=e.submitter?.value;run(action==='search'?'搜索论文…':'AI 正在梳理研究方向…',async()=>{if(action==='search')await search(s);else{const r=await ai('refine',scoped(s));usage(r,s.id);save({refinement:r.output,step:1},s.id);step=1}})}catch(e){error=e.message;ctx.render()}};
 }
 async function click(e){const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(!Object.keys(d).some(k=>k.startsWith('flow')))return;if(busy&&d.flowDismiss===undefined)return;
 if('flowDismiss'in d){error='';ctx.render();return}if('flowNew'in d){active='';step=1;error='';localStorage.removeItem('research-workbench.active');ctx.render();return}
 if(d.flowStep){step=+d.flowStep;if(session())save({step});ctx.render();return}if(d.flowSession){if(location.hash.slice(1)!=='discover')ctx.navigate('discover');active=d.flowSession;localStorage.setItem('research-workbench.active',active);step='flowResult'in d?(session()?.roundSummary?4:3):session()?.step||1;error='';ctx.render();return}
 if(d.flowDates){const f=document.querySelector('#research-focus');f.elements.from.value=d.flowDates==='all'?'':before(+d.flowDates);f.elements.to.value=d.flowDates==='all'?'':today();return}
 const s=session();if(!s)return;
 if(d.flowDirection!==undefined){const direction=s.refinement.directions[+d.flowDirection],keywords=document.querySelector(`[data-direction-keywords="${d.flowDirection}"]`).value.trim();save({direction:direction.name.slice(0,120),directionDetails:[direction.question,'关注：'+direction.include,'排除：'+direction.exclude].join('；'),keywords});await run('按所选方向搜索论文…',()=>search(session()));return}
 if('flowBroaden'in d){const keywords=broaderKeywords(s.keywords);save({keywords});await run('保留时间范围，放宽关键词搜索…',()=>search(session()));return}
 if('flowSearch'in d||'flowMore'in d){await run('查询 arXiv 论文…',()=>search(s,'flowMore'in d?s.search.nextStart:0));return}
 if('flowScreen'in d){await run('AI 正在筛选论文并建议阅读重点…',async()=>{const r=await ai('screen',{...scoped(s),papers:s.candidates});usage(r,s.id);save({screening:r.output,report:null,roundSummary:null,organizedAt:0,selectedIds:r.output.papers.filter(p=>p.recommendation==='deep').sort((a,b)=>b.score-a.score).slice(0,5).map(p=>p.id),step:2},s.id)});return}
 if('flowSynthesize'in d){await run('自动读取关键段落并提炼所选文章…',()=>digest(s));return}
 if('flowOrganize'in d){await run('整理关键结果到 Library、主题与图谱…',()=>organize(s));return}
 if('flowRound'in d){await run('汇总本轮研究并附上证据提取…',()=>round(s));return}
 if('flowExport'in d){const sources=s.candidates.filter(c=>s.selectedIds.includes(c.id));ctx.download('research-summary.md',exportReport(s.topic,s.roundSummary||s.report)+'\n\n## 研究范围\n'+[s.goal,s.from+' — '+s.to].join('\n')+'\n\n## Sources\n'+sources.map(p=>'- '+p.title+': '+p.url+' (ID: '+p.id+')').join('\n'),'text/markdown')}

 }
 function selection(e){const id=e.target.dataset.flowSelect;if(!id)return;const s=session(),ids=new Set(s.selectedIds);if(e.target.checked&&ids.size>=12){e.target.checked=false;ctx.toast('最多选择 12 篇论文；建议先选 3–5 篇。');return}e.target.checked?ids.add(id):ids.delete(id);save({selectedIds:[...ids],report:null,roundSummary:null,organizedAt:0,step:2});ctx.render()}
 async function deep(p){await run('AI 正在解读论文与提取原文证据…',async()=>{const r=await ai('deep',{topic:p.topics[0]||p.title,goal:session()?.goal||'',paper:p});usage(r);const latest=paper(p.id);if(!latest)throw Error('论文已被删除');const extraction=importExtraction(latest,r.output),fields={...latest.fields};for(const [k,f] of Object.entries(extraction.fields)){const old=latest.fields[k];if(!old?.value||(!old.confirmed&&old.origin!=='manual'))fields[k]=f}ctx.updatePaper(p.id,{fields,aiRead:{...r.output,model:r.model,usage:r.usage,generatedAt:r.generatedAt},status:'deep'});ctx.toast('AI 深读已保存；请核查证据，之后可更新主题总结。')})}
 async function synthesizePapers(ps,name,task='compare'){await run(task==='compare'?'AI 正在比较所选论文…':'AI 正在整理主题…',async()=>{const r=await ai(task,{topic:name,papers:ps});if(task==='topic'){usage(r)}if(task==='topic'){const next=structuredClone(ctx.state()),t=next.topics.find(x=>!x.deleted&&x.name===name)||{id:crypto.randomUUID(),name,notes:'',questions:'',deleted:false};t.synthesis=r.output;t.updatedAt=ctx.stamp();if(!next.topics.includes(t))next.topics.push(t);ctx.change(next)}else{const next=structuredClone(ctx.state()),s={id:crypto.randomUUID(),topic:name,goal:'',from:'',to:'',keywords:name,direction:'',step:3,candidates:ps.map(p=>({...p,id:p.id,libraryId:p.id})),selectedIds:ps.map(p=>p.id),report:r.output,usage:[{tokens:r.usage?.totalTokenCount||0,cached:r.cached,model:r.model}],updatedAt:ctx.stamp(),deleted:false};next.researchSessions.push(s);ctx.change(next);active=s.id;localStorage.setItem('research-workbench.active',active);step=3;ctx.navigate('discover')}archiveReport({direction:name,topic:name},r.output)})}
 function readerHTML(p){const r=p.aiRead;return `<div class="ai-reader-controls"><button class="primary" data-llm-deep ${busy?'disabled':''}>${r?'更新 AI 深读':'AI 深读与证据提取'} <small>1 次调用</small></button><button data-view="discover">返回本次研究</button></div>${busy?`<p class="help" role="status">${esc(busy)}</p>`:''}${error?`<div class="flow-error">${esc(error)}</div>`:''}${p.aiDigest?`<section class="digest-card"><h3>已保存的 Take home messages</h3><p>${esc(p.aiDigest.summary)}</p>${points(p.aiDigest.takeaways)}<details><summary>已存证据摘录</summary>${evidenceHTML(p.aiDigest)}</details></section>`:''}${r?`<section class="ai-reading-guide"><div class="row"><span class="badge teal">AI 阅读路线</span><span class="meta">${r.coverage?.abstractOnly?'摘要级解读':r.coverage?.included+' / '+r.coverage?.total+' 段原文'} · 引用需核查</span></div><h3>先理解这篇在解决什么</h3><p>${esc(r.summary)}</p>${(r.readingGuide||[]).map((g,i)=>`<article class="outline-item"><span>${i+1}</span><div><h4>${esc(g.title)}</h4><p>${esc(g.explanation)}</p><div class="row">${g.paragraphIds.map(id=>`<button class="quiet" data-source="${esc(id)}">查看 ${esc(id)} 原文</button>`).join('')}</div></div></article>`).join('')}<h4>带着这些问题核查</h4>${points(r.questions)}</section>`:'<p class="help">先读取 arXiv 全文或粘贴重点章节，再让 AI 解释方法、生成阅读路线和提取引用。仅有摘要时会明确标注。</p>'}`}
 return {render,bind,click,selection,deep,readerHTML,reportHTML,evidenceHTML,synthesizePapers,isBusy:()=>!!busy};
}
export function exportReport(topic,r){if(!r)return '';return `# ${topic}\n\n## 主题总结\n${r.overview}\n\n## 阅读纲要\n`+(r.outline||[]).map(x=>`### ${x.title}\n${x.explanation}\n关联论文 ID：${x.paperIds.join(', ')}`).join('\n\n')+'\n\n## 方法比较\n'+(r.comparison||[]).map(d=>'### '+d.dimension+'\n'+d.items.map(x=>`- ${x.paperId}: ${x.value}\n  原文：${x.quote||'无引用'} (${x.matched?'匹配，待核查':'待核查'})`).join('\n')).join('\n\n')+'\n\n## Take home messages\n'+(r.takeaways||[]).map(x=>'- '+x).join('\n')+'\n\n## 下一步问题\n'+(r.openQuestions||[]).map(x=>'- '+x).join('\n')+'\n\n## 证据提取附录\n'+(r.evidenceAppendix||r.paperSummaries||[]).map(d=>'### '+(d.title||d.paperId)+'\n'+(d.url?'来源：'+d.url+'\n':'')+(d.evidence||[]).map(e=>'- '+e.kind+': '+e.value+'\n  原文：'+e.quote+'\n  来源段落：'+e.paragraphId+' · '+(e.matched?'引文匹配，未人工核查':'引用不匹配，待核查')).join('\n')).join('\n\n');}

export function keyPassages(paras,budget=16000){const ranked=paras.map((p,i)=>({p,i,score:/conclusion|results|limitation|discussion|table|ablation/i.test(p.section||'')?3:/abstract|method|approach|introduction/i.test(p.section||'')?2:1})).sort((a,b)=>b.score-a.score||a.i-b.i);let chars=0;const kept=[];for(const x of ranked){if(chars+x.p.text.length>budget)continue;chars+=x.p.text.length;kept.push(x)}return kept.sort((a,b)=>a.i-b.i).map(x=>x.p)}
function remapReport(r,map){const copy=structuredClone(r);for(const x of copy.outline||[])x.paperIds=x.paperIds.map(id=>map.get(id)||id);for(const x of copy.readingOrder||[])x.paperId=map.get(x.paperId)||x.paperId;for(const d of copy.comparison||[])for(const x of d.items)x.paperId=map.get(x.paperId)||x.paperId;for(const e of copy.entities||[])e.paperIds=e.paperIds.map(id=>map.get(id)||id);for(const x of [...copy.paperSummaries||[],...copy.evidenceAppendix||[]])x.paperId=map.get(x.paperId)||x.paperId;return copy}

export function roundInput(p,original){const fields=Object.fromEntries(Object.entries(p.fields||{}).filter(([,f])=>f?.value).sort(([a],[b])=>(['results','idea','limitations','compute','dataset','baseline','metrics','question'].indexOf(a)+1||999)-(['results','idea','limitations','compute','dataset','baseline','metrics','question'].indexOf(b)+1||999)).slice(0,4).map(([k,f])=>[k,{value:f.value.slice(0,600),quote:['matched','confirmed'].includes(evidenceStatus(f,original))?f.quote.slice(0,600):'',paragraphId:f.paragraphId,matched:['matched','confirmed'].includes(evidenceStatus(f,original))}]));const d=p.digest;return {id:p.id,title:p.title,published:p.published,abstract:(p.abstract||'').slice(0,3000),fields,digest:d?{summary:d.summary?.slice(0,500),takeaways:(d.takeaways||[]).slice(0,2).map(x=>x.slice(0,400)),coverage:d.coverage,evidence:(d.evidence||[]).slice(0,4).map(e=>({...e,value:(e.value||'').slice(0,600),quote:(e.quote||'').slice(0,600)})),scope:'本轮总结使用每篇前 4 条证据和字段，完整提取保存在附录'}:undefined}}

export function broaderKeywords(value){return [...new Set(value.split('|').map(t=>{const words=t.replace(/["“”]/g,'').trim().split(/\s+/).filter(w=>!/^(and|or|for|the|of|in|on|with|a|an|to|by|using)$/i.test(w));const core=words.filter(w=>!/^(evaluation|evaluating|robustness|benchmarking|benchmarks?|performance|latency|efficiency|comparison|comparative)$/i.test(w));const chosen=core.length?core:words;return chosen.slice(0,/[A-Z]{2}|[a-z][A-Z]/.test(chosen[0]||'')?1:2).join(' ')}).filter(Boolean))].join(' | ')}
