import {sourceManager,cachedSources} from '../_decision/collector.js';
import {inferSignal} from '../_decision/signal-ingest.mjs';
import {$,esc,link,fmt,stamp,read,save,field,area,select,data,id,marketData,ask,backupBar,setupPage,hookSync,toast,num} from '../_decision/core.js';
import {signalResult,signalSummary,fresh} from '../_decision/models.mjs';
setupPage();const host=$('#decision-app');let market={symbols:{}},error='',filter='all';const signals=()=>read('signals');
function rows(){return signals().map(s=>({signal:s,result:signalResult(s,market)}))}
function render(){const all=rows(),summary=signalSummary(all);const filtered=all.filter(x=>filter==='all'||filter==='active'&&!x.signal.archived||filter==='complete'&&x.result.state==='complete'||filter==='unscored'&&['missing','unscored'].includes(x.result.state));host.innerHTML=`<div class="d-note">统一口径：信号发出后的下一个完整交易日开盘入场，固定 1／5／20 个交易日收盘观察；只评估股票现货方向，不模拟期权、盘中止盈止损或 bot 宣称的成交。收益为未扣费用的观察值。</div><div class="d-statgrid"><div class="d-stat"><b>${summary.total}</b><span>已解析信号（包括归档）</span></div><div class="d-stat"><b>${summary.completed}</b><span>前瞻录入 · 已完成</span></div><div class="d-stat"><b>${summary.retrospective}</b><span>事后补录 · 单列</span></div><div class="d-stat"><b>${summary.unscored}</b><span>缺数据／不评分</span></div></div><details class="d-panel" id="signal-manual"><summary>手动补录 / 核对待确认原文</summary><div><div class="d-row"><h2>补录或核对信号</h2><button id="signal-refresh">↻ 读取行情并重算</button></div><p class="d-muted">支持 $NVDA 等代码辅助提取，发布者、时间与方向仍需你核对。覆盖 Stock Alert 当前 ${Object.keys(market.symbols).length} 个标的；其他标的保留为缺数据，不捏造成绩。</p>${error?`<p class="d-error">${esc(error)}</p>`:''}<p class="d-muted">行情快照 ${stamp(market.generatedAt)} · ${fresh(market.generatedAt,96)?'已加载':'尚未取得新鲜行情；不据此认定当前交易结果'}</p><form id="signal-form" class="d-form">${area('original','原始推文／bot 信号全文','','required maxlength="12000" placeholder="粘贴后点辅助提取；保存后原文和规则锁定。"')}<div class="d-actions d-wide"><button id="signal-extract" type="button">辅助提取代码与方向</button><span id="signal-extract-note" class="d-muted"></span></div>${field('bot','发布者／bot 名称','text','','required maxlength="100"')}${field('symbol','标的代码','text','','required maxlength="20" pattern="[A-Za-z0-9.^-]+"')}${select('direction','方向',[['long','看多'],['short','看空']])}${field('sourceURL','原文链接（可空）','url','','maxlength="2000"')}${field('publishedAt','发出时间 UTC','datetime-local',new Date().toISOString().slice(0,16),'required')}${select('horizon','固定观察窗口',[['5','5 个交易日'],['1','1 个交易日'],['20','20 个交易日']])}${select('method','评估方式',[['next-open','次一完整交易日开盘 → 固定窗口'],['observe','仅观察（期权／条件信号／盘中）']])}${area('condition','原信号入场、止损或期限说明（保留背景，不参与统一评分）','','maxlength="2000"')}<div class="d-actions d-wide"><button class="d-primary">核对并保存原始记录</button></div></form></div></details><section class="d-panel"><h2>发布者比较</h2><p class="d-muted">按方向和观察窗口分组；归档记录仍计入。事后录入不进入前瞻均值。均值不是资金加权组合收益，也不代表未来预测能力。</p>${scoreboard(all)}</section><section class="d-panel"><div class="d-row"><h2>全部信号</h2><select id="signal-filter" aria-label="筛选信号"><option value="all">全部（含归档）</option><option value="active">未归档</option><option value="complete">窗口已完成</option><option value="unscored">不评分／缺数据</option></select></div>${filtered.slice().reverse().map(card).join('')||'<div class="d-empty">还没有符合条件的信号。在上方连接来源后自动积累；明确方向自动评估，歧义内容留在待核对原文中。</div>'}<div id="signal-backup"></div></section>`;
 $('#signal-filter').value=filter;$('#signal-filter').onchange=e=>{filter=e.target.value;render()};$('#signal-refresh').onclick=load;$('#signal-extract').onclick=extract;$('#signal-form').onsubmit=e=>{e.preventDefault();const v=data(e.target),publishedAt=new Date(v.publishedAt+'Z').toISOString();if(Date.parse(publishedAt)>Date.now()+300000){toast('发出时间不能在未来');return}const s={...v,...(e.target.dataset.sourceId?{autoSourceId:e.target.dataset.sourceId,sourceKey:e.target.dataset.sourceKey}:{}),id:id(),symbol:v.symbol.trim().toUpperCase(),publishedAt,recordedAt:new Date().toISOString(),horizon:Number(v.horizon),archived:false,annotations:[]};if(signals().some(x=>x.bot===s.bot&&x.symbol===s.symbol&&x.publishedAt===s.publishedAt&&x.original===s.original)){toast('这条信号已经录入');return}if(save('signals',[...signals(),s])){render();toast('原始记录已锁定；以后可追加备注，不改写原信号')}};
 host.querySelectorAll('[data-s-archive]').forEach(b=>b.onclick=()=>{const all=signals(),s=all.find(x=>x.id===b.dataset.sArchive);s.archived=!s.archived;save('signals',all);render()});
 host.querySelectorAll('[data-s-note]').forEach(b=>b.onclick=()=>{const el=b.closest('article'),text=$('textarea',el).value.trim();if(!text){toast('请先填写备注');return}const all=signals(),s=all.find(x=>x.id===b.dataset.sNote);s.annotations.push({at:new Date().toISOString(),text});save('signals',all);render()});
 host.querySelectorAll('[data-s-ask]').forEach(b=>b.onclick=()=>ask('交易信号验证',all.find(x=>x.signal.id===b.dataset.sAsk),'请检查这条信号的证据、评估口径和失效条件，不要把事后成绩当作可交易承诺。'));
 backupBar($('#signal-backup'),['signals'],(_,v)=>v.every(s=>s&&typeof s.id==='string'&&typeof s.bot==='string'&&typeof s.symbol==='string'&&typeof s.original==='string'&&['long','short'].includes(s.direction)&&[1,5,20].includes(s.horizon)&&['next-open','observe'].includes(s.method)&&Array.isArray(s.annotations)&&Number.isFinite(Date.parse(s.recordedAt))&&Number.isFinite(Date.parse(s.publishedAt))));
}
function extract(){const form=$('#signal-form'),text=form.elements.original.value,symbols=[...new Set([...text.matchAll(/\$([A-Za-z][A-Za-z0-9.-]{0,9})\b/g)].map(x=>x[1].toUpperCase()))];if(symbols.length===1)form.elements.symbol.value=symbols[0];if(/\b(short|bearish)\b|看空|做空/i.test(text))form.elements.direction.value='short';else if(/\b(long|bullish|buy)\b|看多|做多/i.test(text))form.elements.direction.value='long';const source=text.match(/https?:\/\/[^\s<>]+/);if(source)form.elements.sourceURL.value=source[0];$('#signal-extract-note').textContent=(symbols.length===1?'提取到 '+symbols[0]:symbols.length>1?'发现多个代码，请手动选择':'未发现唯一 $代码，请手动填写')+'；请核对方向与 UTC 时间。';}
function scoreboard(all){if(!all.length)return '<div class="d-empty">积累记录后展示同口径比较。</div>';const groups=new Map();for(const row of all){const s=row.signal,key=[s.bot,s.direction,s.horizon,s.method].join('|');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row)}return `<div class="d-table"><table><thead><tr><th>发布者 / 口径</th><th>全部</th><th>前瞻完成</th><th>正收益 / 完成</th><th>平均方向收益</th><th>补录</th><th>跟踪中</th><th>不评分</th></tr></thead><tbody>${[...groups.values()].map(rs=>{const s=rs[0].signal,g=signalSummary(rs);return `<tr><td>${esc(s.bot)} · ${s.direction==='long'?'多':'空'} · ${s.horizon}日${s.method==='observe'?' · 仅观察':''}</td><td>${g.total}</td><td>${g.completed}</td><td>${g.wins} / ${g.completed}</td><td>${g.average===null?'—':fmt(g.average)+'%'}</td><td>${g.retrospective}</td><td>${g.pending}</td><td>${g.unscored}</td></tr>`}).join('')}</tbody></table></div>`}
function card({signal:s,result:r}){return `<article class="d-inset"><div class="d-row"><h3>${esc(s.bot)} · ${esc(s.symbol)} · ${s.direction==='long'?'看多':'看空'}</h3><span class="d-pill ${r.state}">${esc(r.text)}${s.archived?' · 已归档':''}</span></div><small>发出 ${stamp(s.publishedAt)} · 录入 ${stamp(s.recordedAt)} · ${s.horizon} 交易日${r.retrospective?' · 事后补录（不计前瞻成绩）':''}</small>${r.entry?`<p>观察入场 ${r.entryDate} / $${fmt(r.entry)} → ${r.exitDate} / $${fmt(r.exit)}<br>方向收益 <b>${fmt(r.returnPct)}%</b> · 最大不利变动 ${fmt(r.adverse)}%<br><small>同期 SPY 买入持有 ${r.benchmarkReturn===null?'无完整同期数据':fmt(r.benchmarkReturn)+'%'}；看空信号不直接拿 SPY 多头收益当超额收益。</small></p>`:''}<details><summary>原文与固定规则（只读）</summary><pre>${esc(s.original)}</pre><p>${esc(s.condition||'未另附条件')}</p>${s.sourceURL?link(s.sourceURL,'原文'):''}<p class="d-muted">${s.autoSourceId?'原文由订阅源自动收集，按首次抓取保留；来源身份以订阅源为准，未核验 X 账号。':'手动提交原文，未核验作者。'}</p></details><div class="d-actions"><button data-s-ask="${s.id}">带证据问 GPT ↗</button><button data-s-archive="${s.id}">${s.archived?'取消归档':'归档（保留统计）'}</button></div><details><summary>追加备注 · ${s.annotations.length}</summary>${s.annotations.map(n=>`<p>${esc(n.text)}<br><small>${stamp(n.at)}</small></p>`).join('')}<textarea aria-label="追加备注" maxlength="2000" placeholder="记录补充证据或说明，不修改原始信号"></textarea><button data-s-note="${s.id}">追加备注</button></details></article>`}
async function load(){const b=$('#signal-refresh');if(b)b.disabled=true;try{market=await marketData();error=''}catch(e){error=e.message}render()}

function ingest(remote){const all=signals();let changed=false;for(const source of remote.filter(x=>x.kind==='feed'))for(const item of source.data?.items||[]){if(all.some(s=>s.autoSourceId===source.id&&s.sourceKey===item.key))continue;const inferred=inferSignal(item,source);if(inferred){all.push({...inferred,id:id()});changed=true}}if(changed)save('signals',all);if(!document.querySelector('#signal-form')?.contains(document.activeElement))render();pending(remote);}
function pending(remote){let el=document.querySelector('#signal-pending');if(!el){el=document.createElement('section');el.id='signal-pending';el.className='d-panel';host.after(el)}const rows=remote.filter(s=>s.kind==='feed').flatMap(source=>(source.data?.items||[]).filter(item=>!signals().some(s=>s.autoSourceId===source.id&&s.sourceKey===item.key)).map(item=>({source,item})));el.innerHTML='<h2>待核对原文 · '+rows.length+'</h2><p class="d-muted">多标的、条件句、期权或方向不明的内容不自动打分，也不从样本中隐藏。自动识别只覆盖明确的单标的方向，不能据此评价整个 bot。</p>'+rows.slice(-50).reverse().map((r,i)=>'<details><summary>'+esc(r.source.name+' · '+r.item.title)+'</summary><pre>'+esc(r.item.text)+'</pre>'+link(r.item.url,'原文')+'<button data-pending="'+i+'">带入核对</button></details>').join('');const shown=rows.slice(-50).reverse();el.querySelectorAll('[data-pending]').forEach(b=>b.onclick=()=>{const {source,item}=shown[Number(b.dataset.pending)],form=$('#signal-form');$('#signal-manual').open=true;form.dataset.sourceId=source.id;form.dataset.sourceKey=item.key;form.elements.original.value=item.title+'\n'+item.text;form.elements.bot.value=source.name;form.elements.sourceURL.value=item.url;if(item.publishedAt)form.elements.publishedAt.value=item.publishedAt.slice(0,16);form.elements.method.value='observe';extract();form.scrollIntoView({behavior:'smooth'});});}
render();load();hookSync(render);sourceManager('feed',ingest);

