type Source={id:string;owner:string;kind:string;url:string;selector:string;name:string;paused:number;checked_at:string|null;next_at:number;error:string|null};
type Snapshot={at:string;text?:string;items?:any[];products?:any[]};
const table='decision_sources';
async function schema(env:Env){await env.DB.prepare("CREATE TABLE IF NOT EXISTS decision_sources(id TEXT PRIMARY KEY,owner TEXT NOT NULL,kind TEXT NOT NULL,url TEXT NOT NULL,selector TEXT NOT NULL DEFAULT '',name TEXT NOT NULL,paused INTEGER NOT NULL DEFAULT 0,checked_at TEXT,next_at INTEGER NOT NULL DEFAULT 0,error TEXT)").run();}
export function publicURL(value:string){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.port&&!['443'].includes(u.port)||!u.hostname.includes('.')||/[:\[\]]/.test(u.hostname)||/^\d+\.\d+\.\d+\.\d+$/.test(u.hostname)||/(^|\.)(localhost|local|internal|test|invalid|onion)$/.test(u.hostname)||u.hostname.endsWith('.workers.dev'))throw Error('仅支持公开 HTTPS 网站，不支持内网、IP、带密码或 Worker 地址');u.hash='';return u;}
async function upstream(value:string):Promise<{body:string;url:string;type:string}>{let u=publicURL(value);for(let i=0;i<4;i++){const r=await fetch(u,{redirect:'manual',signal:AbortSignal.timeout(12000),headers:{'user-agent':'PT-Universe-Monitor/1.0','accept':'text/html,application/rss+xml,application/atom+xml,application/json,text/plain'}});if(r.status>=300&&r.status<400){await r.body?.cancel();u=publicURL(new URL(r.headers.get('location')||'',u).href);continue}if(!r.ok)throw Error('来源返回 HTTP '+r.status);if(Number(r.headers.get('content-length'))>1000000){await r.body?.cancel();throw Error('页面超过 1 MB')}const reader=r.body?.getReader();let total=0,body='',decoder=new TextDecoder();if(!reader)throw Error('页面为空');while(true){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>1000000){await reader.cancel();throw Error('页面超过 1 MB')}body+=decoder.decode(value,{stream:true})}body+=decoder.decode();return {body,url:u.href,type:r.headers.get('content-type')||''}}throw Error('重定向过多')}
function plain(s:string){return s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim()}
function tag(s:string,key:string){return s.match(new RegExp('<'+key+'(?:\\s[^>]*)?>([\\s\\S]*?)<\\/'+key+'>','i'))?.[1]||''}
export function feedItems(body:string,base:string,at:string){if(/<!ENTITY/i.test(body))throw Error('不支持 XML 实体声明');const entries=body.match(/<(?:item|entry)(?:\s[^>]*)?>[\s\S]*?<\/(?:item|entry)>/gi);if(!entries){if(/<(rss|feed)\b/i.test(body))return [];throw Error('来源不是 RSS/Atom，不能把 X 网页当作订阅源')}
return entries.slice(0,100).map(e=>{const link=plain(tag(e,'link'))||e.match(/<link\b[^>]*href=["']([^"']+)["']/i)?.[1]||'',title=plain(tag(e,'title')),text=plain(tag(e,'content:encoded')||tag(e,'content')||tag(e,'description')||tag(e,'summary'));let url='';try{url=publicURL(new URL(link,base).href).href}catch{}const date=plain(tag(e,'pubDate')||tag(e,'published')||tag(e,'updated'));return {key:plain(tag(e,'guid')||tag(e,'id'))||url||title,title,text:text.slice(0,12000),url,publishedAt:Number.isFinite(Date.parse(date))?new Date(date).toISOString():null,firstSeenAt:at};}).filter(e=>e.key&&e.title);}
async function pageText(body:string,selector:string){let text='',found=false;const cleaned=await new HTMLRewriter().on('script,style,noscript,nav,header,footer,[hidden],[aria-hidden="true"]',{element(e){e.remove()}}).transform(new Response(body)).text();await new HTMLRewriter().on(selector||'body',{element(){found=true},text(t){text+=t.text+(t.lastInTextNode?'\n':'')}}).transform(new Response(cleaned)).text();text=text.split('\n').map(x=>plain(x)).filter(Boolean).join('\n');if(!found||text.length<2)throw Error('没有可读取正文；请检查内容选择器，登录页和纯 JS 页面不支持');if(/just a moment|verify you are human|checking your browser|enable javascript and cookies/i.test(text)&&text.length<3000)throw Error('来源需要人工验证，未保存为新观察');if(text.length>60000)throw Error('正文超过 60000 字，请指定内容区域');return text}
async function products(body:string){let chunks:string[]=[],current='';await new HTMLRewriter().on('script[type="application/ld+json"]',{element(e){current='';e.onEndTag(()=>{chunks.push(current)})},text(t){current+=t.text}}).transform(new Response(body)).text();const out:any[]=[];function walk(v:any,depth=0){if(!v||depth>12)return;if(Array.isArray(v)){v.forEach(x=>walk(x,depth+1));return}if(typeof v!=='object')return;if([v['@type']].flat().includes('Product')){for(const offer of [v.offers].flat().filter(Boolean)){const price=Number(offer.price);if(Number.isFinite(price)&&price>0&&/^[A-Z]{3}$/.test(offer.priceCurrency||''))out.push({name:String(v.name||''),sku:String(v.sku||''),price,currency:offer.priceCurrency,availability:String(offer.availability||''),url:String(offer.url||'')})}}for(const [k,x] of Object.entries(v))if(k!=='offers')walk(x,depth+1)}for(const c of chunks){try{walk(JSON.parse(c))}catch{}}if(!out.length)throw Error('页面没有明确的 Product/Offer 价格；未猜测页面中的数字');return out.slice(0,30)}
async function collect(env:Env,s:Source){const at=new Date().toISOString(),key='decision:'+s.id;try{const old=await env.PT_UNIVERSE_DATA.get<{snapshots:Snapshot[];items?:any[];products?:any[];checkedAt?:string}>(key,'json')||{snapshots:[]},r=await upstream(s.url);let snapshot:Snapshot={at},items=old.items||[];
if(s.kind==='feed'){const incoming=feedItems(r.body,r.url,at),byKey=new Map(items.map(x=>[x.key,x]));for(const item of incoming){const prior=byKey.get(item.key);if(!prior)byKey.set(item.key,item);else if(prior.text!==item.text||prior.title!==item.title)byKey.set(item.key,{...prior,editedAt:at,latestText:item.text,latestTitle:item.title})}items=[...byKey.values()].slice(-300);snapshot.items=incoming.map(x=>({key:x.key,title:x.title}));}
else if(s.kind==='product')snapshot.products=await products(r.body);
else snapshot.text=r.type.includes('text/plain')?r.body.trim().slice(0,60000):await pageText(r.body,s.selector);
const previous=old.snapshots.at(-1),changed=JSON.stringify({...snapshot,at:0})!==JSON.stringify({...previous,at:0});const snapshots=changed?[...old.snapshots,snapshot].slice(-20):old.snapshots;
await env.PT_UNIVERSE_DATA.put(key,JSON.stringify({snapshots,items,products:snapshot.products||old.products,checkedAt:at,url:r.url}),{expirationTtl:60*86400});
await env.DB.prepare('UPDATE decision_sources SET checked_at=?,error=NULL WHERE id=?').bind(at,s.id).run();
}catch(e){await env.DB.prepare('UPDATE decision_sources SET checked_at=?,error=? WHERE id=?').bind(at,String(e instanceof Error?e.message:e).slice(0,300),s.id).run();}}
async function claim(env:Env,s:Source){const result=await env.DB.prepare('UPDATE decision_sources SET next_at=? WHERE id=? AND next_at<=? AND paused=0').bind(Date.now()+3600000,s.id,Date.now()).run();if(result.meta.changes)await collect(env,s);return !!result.meta.changes;}
export async function decisionTick(env:Env){await schema(env);const {results}=await env.DB.prepare('SELECT * FROM decision_sources WHERE paused=0 AND next_at<=? ORDER BY next_at LIMIT 20').bind(Date.now()).all<Source>();for(let i=0;i<results.length;i+=3)await Promise.all(results.slice(i,i+3).map(s=>claim(env,s)));}
export async function decisionRoute(request:Request,env:Env,authenticate:(r:Request,e:Env,id:string)=>Promise<boolean>){const u=new URL(request.url),m=u.pathname.match(/^\/api\/decision\/([\w-]{36})\/sources(?:\/([\w-]{36}))?(?:\/(check))?$/);if(!m)return null;if(!await authenticate(request,env,m[1]))return {status:401,body:{error:'请重新连接后台账号'}};await schema(env);const owner=m[1],sourceId=m[2];
if(request.method==='GET'){const {results}=await env.DB.prepare('SELECT * FROM decision_sources WHERE owner=? ORDER BY rowid').bind(owner).all<Source>();const sources=await Promise.all(results.map(async s=>({...s,data:await env.PT_UNIVERSE_DATA.get('decision:'+s.id,'json')})));return {body:{sources}}}
if(request.method!=='POST')return {status:405,body:{error:'Method not allowed'}};
if(Number(request.headers.get('content-length'))>10000)return {status:413,body:{error:'请求过大'}};
const body=await request.json<any>();if(JSON.stringify(body).length>10000)return {status:413,body:{error:'请求过大'}};
if(sourceId){const s=await env.DB.prepare('SELECT * FROM decision_sources WHERE owner=? AND id=?').bind(owner,sourceId).first<Source>();if(!s)return {status:404,body:{error:'来源不存在'}};
if(m[3]){const ran=await claim(env,s);return {body:{ok:true,checked:ran,cooldown:!ran}}}
if(body.action==='remove'){await env.DB.prepare('DELETE FROM decision_sources WHERE id=? AND owner=?').bind(sourceId,owner).run();await env.PT_UNIVERSE_DATA.delete('decision:'+sourceId);return {body:{ok:true}}}
if(body.action==='pause'||body.action==='resume'){await env.DB.prepare('UPDATE decision_sources SET paused=? WHERE id=? AND owner=?').bind(body.action==='pause'?1:0,sourceId,owner).run();return {body:{ok:true}}}
return {status:400,body:{error:'未知操作'}}}
const row=await env.DB.prepare('SELECT COUNT(*) AS n FROM decision_sources WHERE owner=?').bind(owner).first<{n:number}>();if((row?.n||0)>=20)return {status:400,body:{error:'每个账号最多 20 个自动来源'}};
if(!['page','feed','product'].includes(body.kind))throw Error('来源类型无效');const url=publicURL(String(body.url||'')).href;if(url.length>2000)throw Error('网址过长');const selector=String(body.selector||'').trim();if(selector.length>200)throw Error('选择器过长');if(selector)new HTMLRewriter().on(selector,{element(){}});
const duplicate=await env.DB.prepare('SELECT id FROM decision_sources WHERE owner=? AND kind=? AND url=? AND selector=?').bind(owner,body.kind,url,selector).first<{id:string}>();if(duplicate)return {body:{id:duplicate.id}};
const id=crypto.randomUUID(),name=String(body.name||new URL(url).hostname).slice(0,120);await env.DB.prepare('INSERT INTO decision_sources(id,owner,kind,url,selector,name) VALUES(?,?,?,?,?,?)').bind(id,owner,body.kind,url,selector,name).run();const s={id,owner,kind:body.kind,url,selector,name,paused:0,next_at:0,checked_at:null,error:null};await claim(env,s);return {status:201,body:{id}}}
