/** Fixed research upstreams. No arbitrary proxy, private URLs, or remote HTML execution. */
const UA='PT-Universe-Research/1.0 (+https://github.com/XiminHu66/PT-Universe)';
const SOURCES=new Set(['arxiv.org','export.arxiv.org','rss.arxiv.org','api.semanticscholar.org','github.com','api.github.com','huggingface.co','openai.com','www.anthropic.com','www.deepmind.com','deepmind.google','research.google','ai.meta.com','microsoft.com','www.microsoft.com','bair.berkeley.edu','lilianweng.github.io','huggingface.co','hnrss.org','news.ycombinator.com','www.technologyreview.com']);
const clean=(v:string)=>v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#(?:39|x27);/g,"'").replace(/&nbsp;/g,' ').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Math.min(Number(n),0x10ffff))).replace(/\s+/g,' ').trim();
function safeUrl(value:string){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||(u.port&&u.port!=='443')||!SOURCES.has(u.hostname))throw Error('该来源暂不支持自动抓取；可用手动导入保存 URL 和原文');return u}
async function fetchText(value:string,max=1_500_000){let u=safeUrl(value);for(let i=0;i<3;i++){const r=await fetch(u,{headers:{'user-agent':UA,accept:'application/json,application/atom+xml,text/html,*/*'},redirect:'manual',signal:AbortSignal.timeout(18000)});if(r.status>=300&&r.status<400){u=safeUrl(new URL(r.headers.get('location')||'',u).href);continue}if(!r.ok)throw Error(`研究来源 HTTP ${r.status}，请重试或手动导入`);if(Number(r.headers.get('content-length'))>max)throw Error('原文过大；请粘贴重点章节');const reader=r.body?.getReader();if(!reader)throw Error('来源返回空内容');const chunks:Uint8Array[]=[];let length=0;try{while(true){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>max)throw Error('原文过大；请粘贴重点章节');chunks.push(value)}}finally{await reader.cancel()}const all=new Uint8Array(length);let offset=0;for(const c of chunks){all.set(c,offset);offset+=c.length}return new TextDecoder().decode(all)}throw Error('来源重定向过多')}
function tag(xml:string,name:string){return clean(xml.match(new RegExp('<'+name+'(?:\\s[^>]*)?>([\\s\\S]*?)<\\/'+name+'>','i'))?.[1]||'')}
function links(xml:string){return [...xml.matchAll(/<link\b([^>]+)\/?\s*>/g)].map(m=>({href:m[1].match(/href=["']([^"']+)/)?.[1]||'',rel:m[1].match(/rel=["']([^"']+)/)?.[1]||'',title:m[1].match(/title=["']([^"']+)/)?.[1]||''}))}
export function parseArxiv(xml:string){return [...xml.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/g)].map(m=>{const x=m[1],url=tag(x,'id').replace('http:','https:'),ls=links(x),id=url.split('/abs/')[1]?.replace(/v\d+$/,'')||'';return {title:tag(x,'title'),abstract:tag(x,'summary'),authors:[...x.matchAll(/<author>([\s\S]*?)<\/author>/g)].map(a=>tag(a[1],'name')),published:tag(x,'published').slice(0,10),arxivId:id,url,pdf:(ls.find(l=>l.title==='pdf')?.href||'https://arxiv.org/pdf/'+id).replace('http:','https:'),source:'arXiv',repo:''}}).filter(x=>x.title&&x.arxivId)}
export function parseFulltext(html:string){const stripped=html.replace(/<(script|style|nav|header|footer)\b[^>]*>[\s\S]*?<\/\1>/gi,'');const source=stripped.match(/<article\b[^>]*>([\s\S]*?)<\/article>/i)?.[1]||stripped;let section='';const paragraphs:{id:string;section:string;text:string}[]=[];for(const match of source.matchAll(/<(h[1-6]|p|table|figcaption)\b[^>]*>([\s\S]*?)<\/\1>/gi)){const t=clean(match[2]);if(!t)continue;if(match[1].startsWith('h'))section=t;else if(t.length>25)paragraphs.push({id:'p'+(paragraphs.length+1),section,text:t.slice(0,6000)});if(paragraphs.length>=500||paragraphs.reduce((n,p)=>n+p.text.length,0)>110000)break}return paragraphs}
export function parseFeed(xml:string){const rows=[...xml.matchAll(/<(entry|item)\b[^>]*>([\s\S]*?)<\/\1>/gi)].slice(0,40).map(m=>{const x=m[2],ls=links(x),raw=tag(x,'link')||ls.find(l=>l.rel==='alternate'||!l.rel)?.href||tag(x,'id');let url='';try{const u=new URL(raw);if(u.protocol==='https:'||u.protocol==='http:')url=u.href}catch{}const arxiv=url.match(/arxiv\.org\/(?:abs|pdf)\/(\d{4}\.\d{4,5})(?:v\d+)?/)?.[1]||'';return {title:tag(x,'title'),url,abstract:tag(x,'summary')||tag(x,'description')||tag(x,'content'),authors:[],published:tag(x,'published')||tag(x,'pubDate')||tag(x,'updated'),source:'RSS',arxivId:arxiv,pdf:arxiv?'https://arxiv.org/pdf/'+arxiv:''}});return rows.filter(r=>r.title&&r.url)}
async function arxiv(input:string){const id=input.trim().replace(/^https?:\/\/(?:export\.)?arxiv.org\/(?:abs|pdf|html)\//,'').replace(/\.pdf$/,'').split(/[?#]/)[0];if(!/^(?:\d{4}\.\d{4,5}|[a-z-]+(?:\.[A-Z]{2})?\/\d{7})(?:v\d+)?$/i.test(id))throw Error('无效 arXiv ID');const items=parseArxiv(await fetchText('https://export.arxiv.org/api/query?id_list='+encodeURIComponent(id)));if(!items.length)throw Error('没有找到该 arXiv ID');return {paper:items[0]}}
async function github(input:string){const u=safeUrl(input),match=u.pathname.match(/^\/([^/]+)\/([^/]+)/);if(u.hostname!=='github.com'||!match||!/^[-\w.]+$/.test(match[1])||!/^[-\w.]+$/.test(match[2]))throw Error('请输入 GitHub 仓库 URL');const slug=match[1]+'/'+match[2].replace(/\.git$/,'');const repo=JSON.parse(await fetchText('https://api.github.com/repos/'+slug));return {repo:{url:repo.html_url,title:repo.full_name,description:repo.description||'',stars:repo.stargazers_count,updatedAt:repo.pushed_at,issues:repo.open_issues_count,language:repo.language,license:repo.license?.spdx_id||'',installation:'https://github.com/'+slug+'#readme',commits:'https://github.com/'+slug+'/commits',releases:'https://github.com/'+slug+'/releases',issueURL:'https://github.com/'+slug+'/issues'},paper:{title:repo.full_name,abstract:repo.description||'',repo:repo.html_url,url:repo.html_url,authors:[repo.owner.login],published:repo.created_at.slice(0,10),source:'GitHub'}}}
export async function workbenchRoute(request:Request):Promise<any|null>{const url=new URL(request.url);if(!url.pathname.startsWith('/api/workbench/'))return null;if(request.method!=='GET')throw Error('仅支持 GET');const q=(url.searchParams.get('q')||'').trim();if(q.length>2000)throw Error('输入过长');switch(url.pathname){case '/api/workbench/import':{if(/^(?:\d{4}\.\d{4,5}|[a-z-]+(?:\.[A-Z]{2})?\/\d{7})(v\d+)?$/i.test(q)||/arxiv.org\/(abs|pdf|html)/.test(q))return arxiv(q);const u=safeUrl(q);if(u.hostname==='github.com')return github(q);if(u.hostname==='huggingface.co'){const match=u.pathname.match(/^\/([^/]+)\/([^/]+)\/?$/);if(!match)throw Error('请输入 Hugging Face 模型仓库地址');const raw=JSON.parse(await fetchText('https://huggingface.co/api/models/'+match[1]+'/'+match[2]));return {paper:{title:raw.id,url:u.href,abstract:raw.cardData?.model_summary||'模型卡可在来源页面阅读。',authors:[raw.author||match[1]],published:raw.createdAt||'',source:'Hugging Face',repo:u.href},metadata:{downloads:raw.downloads,likes:raw.likes}}}const html=await fetchText(u.href);const title=clean(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'');if(!title)throw Error('来源没有返回标题，请手动导入');const paragraphs=parseFulltext(html);return {paper:{title,url:u.href,abstract:paragraphs.slice(0,2).map(p=>p.text).join('\n'),paragraphs,authors:[],published:'',source:u.hostname}}}case '/api/workbench/discover':{
 if(q.length<2||q.length>400)throw Error('请输入 2–400 字符的研究关键词');
 const startDate=url.searchParams.get('from')||'',endDate=url.searchParams.get('to')||'';
 const validDate=(d:string)=>/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;
 if((startDate&&!validDate(startDate))||(endDate&&!validDate(endDate))||(startDate&&endDate&&startDate>endDate))throw Error('请选择有效的起止日期');
 const terms=q.split('|').map(t=>t.trim()).filter(Boolean).slice(0,6);
 const keywords=terms.map(t=>t.replace(/[^\p{L}\p{N} ._-]/gu,' ').trim()).filter(Boolean);
 if(!keywords.length)throw Error('请输入可检索的英文关键词');
 const query='('+keywords.map(t=>'all:"'+t+'"').join(' OR ')+')'+((startDate||endDate)?' AND submittedDate:['+(startDate||'1991-01-01').replaceAll('-','')+'0000 TO '+(endDate||new Date().toISOString().slice(0,10)).replaceAll('-','')+'2359]':'');
 const start=Math.min(200,Math.max(0,Number(url.searchParams.get('start'))||0));
 const xml=await fetchText('https://export.arxiv.org/api/query?'+new URLSearchParams({search_query:query,start:String(start),max_results:'20',sortBy:'relevance',sortOrder:'descending'}));
 const items=parseArxiv(xml).filter(p=>(!startDate||p.published>=startDate)&&(!endDate||p.published<=endDate));
 return {items,checkedAt:new Date().toISOString(),source:'arXiv',query,total:Number(tag(xml,'opensearch:totalResults'))||items.length,start,nextStart:start+20,dateBasis:'first submission'};
 }case '/api/workbench/fulltext':{const id=q;if(!/^\d{4}\.\d{4,5}(?:v\d+)?$/.test(id))throw Error('全文 HTML 暂支持新格式 arXiv ID；其他来源可粘贴原文');const paragraphs=parseFulltext(await fetchText('https://arxiv.org/html/'+id,3_000_000));if(!paragraphs.length)throw Error('这篇论文没有可用 HTML 版本，请粘贴 PDF 中的原文');return {paragraphs,source:'https://arxiv.org/html/'+id}}case '/api/workbench/rss':{const xml=await fetchText(safeUrl(q).href);const items=parseFeed(xml);if(!items.length)throw Error('没有找到有效 RSS/Atom 条目');return {items,checkedAt:new Date().toISOString()}}case '/api/workbench/repo':return github(q);case '/api/workbench/semantic':{if(!q||q.length>160)throw Error('请输入论文名称');const data=JSON.parse(await fetchText('https://api.semanticscholar.org/graph/v1/paper/search?query='+encodeURIComponent(q)+'&limit=10&fields=title,abstract,authors,year,url,externalIds,openAccessPdf'));return {items:(data.data||[]).map((p:any)=>({title:p.title,abstract:p.abstract||'',authors:p.authors?.map((a:any)=>a.name)||[],published:String(p.year||''),url:p.url,pdf:p.openAccessPdf?.url||'',arxivId:p.externalIds?.ArXiv||'',doi:p.externalIds?.DOI||'',source:'Semantic Scholar'}))}}default:throw Error('研究接口不存在')}}
