const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const {chromium}=require(process.env.PT_PLAYWRIGHT||'playwright');
const root=path.resolve(__dirname,'../..'),mime={'.mjs':'text/javascript','.js':'text/javascript','.html':'text/html','.css':'text/css','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost'),file=path.join(root,url.pathname,url.pathname.endsWith('/')?'index.html':'');try{res.setHeader('content-type',mime[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end('missing')}});
const fixture={title:'Graph Retrieval for Research Questions',arxivId:'2404.16130',url:'https://arxiv.org/abs/2404.16130',pdf:'https://arxiv.org/pdf/2404.16130',abstract:'We propose graph retrieval for multi-hop question answering. We evaluate on HotpotQA. Our method improves F1 by 4.6 points.',authors:['Research Author'],source:'arXiv',published:'2024-04-24'},accounts=new Map(),errors=[];
let browser;
async function mock(ctx){await ctx.route('https://fonts.googleapis.com/**',r=>r.abort());await ctx.route('https://pt-universe-api.summer07-nanjolno.workers.dev/**',async route=>{const req=route.request(),url=new URL(req.url()),send=(value,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)});if(url.pathname.startsWith('/api/workbench/')){if(url.pathname.endsWith('/fulltext'))return send({paragraphs:[{id:'p1',section:'Method',text:fixture.abstract},{id:'p2',section:'Table 3',text:'On HotpotQA, Method A achieves 65.5 EM; baseline achieves 60.9 EM under identical evaluation.'}]});return send(url.pathname.endsWith('/import')?{paper:url.searchParams.get('q')==='2404.00001'?{...fixture,title:'Second Graph Research Study',arxivId:'2404.00001',url:'https://arxiv.org/abs/2404.00001'}:fixture}:{items:[fixture]})}const data=req.postDataJSON();if(url.pathname.endsWith('/register')){accounts.set(data.id,{token:data.token,ciphertext:null,revision:0});return send({ok:true},201)}const account=accounts.get(url.pathname.split('/')[3]);if(!account||req.headers().authorization!=='Bearer '+account.token)return send({error:'invalid'},401);if(req.method()==='GET')return send({ciphertext:account.ciphertext,revision:account.revision});if(data.baseRevision!==account.revision)return send({error:'conflict'},409);account.ciphertext=data.ciphertext;return send({revision:++account.revision})})}
async function saved(p){await p.waitForFunction(()=>document.querySelector('#save-status').textContent.startsWith('已加密同步'))}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+'/apps/research-workbench/';browser=await chromium.launch({headless:true,...(process.env.PT_CHROMIUM?{executablePath:process.env.PT_CHROMIUM,args:['--no-sandbox','--no-proxy-server','--disable-gpu','--no-zygote','--use-gl=disabled','--disable-software-rasterizer']}: {})});const ctx=await browser.newContext({viewport:{width:1440,height:1050}});await mock(ctx);await ctx.addInitScript(()=>{document.modelContext={registerTool(tool){(window.researchTools??={})[tool.name]=tool}}});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base);
assert.equal(await p.locator('#page-title').textContent(),'Research Inbox');await p.locator('#import-open').click();await p.locator('#import-url').fill('2404.16130');await p.locator('#url-form button.primary').click();await p.locator('.reader-heading h2').waitFor();await saved(p);assert.equal(await p.locator('.paper-card').count(),1);
await p.locator('[data-extract]').click();assert.ok(await p.locator('.extract-card').count()>5);await p.locator('[data-edit-field="idea"]').click();await p.locator('#field-form [name=confirmed]').check();await p.locator('#field-form button.primary').click();assert.ok((await p.locator('.reader-content').textContent()).includes('人工已核查'));await p.locator('[data-source="p1"]').first().click();assert.ok((await p.locator('#source-p1').textContent()).includes('graph retrieval'));await p.locator('#source-dialog [data-close]').click();
await p.locator('[data-reader-tab="overview"]').click();await p.locator('[data-fulltext]').click();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('research-workbench.v1')).papers[0].paragraphs.length===2);await p.locator('[data-reader-tab="extraction"]').click();assert.equal(await p.locator('.reader-content .badge.teal').count(),0);
await p.locator('[data-edit-field="results"]').click();await p.locator('#field-form [name=value]').fill('Result A');await p.locator('#field-form [name=quote]').fill('No such text');await p.locator('#field-form [name=confirmed]').check();await p.locator('#field-form button.primary').click();assert.ok((await p.locator('#field-error').textContent()).includes('逐字匹配'));await p.locator('#field-dialog [data-close]').click();
await p.locator('[data-reader-tab="notes"]').click();await p.locator('#paper-notes').fill('Do not use this method under our current compute budget.');await p.locator('[data-save-notes]').click();await p.locator('#decision-input').fill('Rejected because compute cost exceeds budget.');await p.locator('[data-add-decision]').click();await saved(p);
await p.locator('#import-open').click();await p.locator('#manual-open').click();await p.locator('#manual-form [name=title]').fill('A Vector Retrieval Baseline');await p.locator('#manual-form [name=abstract]').fill('We present a vector retrieval baseline for question answering.');await p.locator('#manual-form button.primary').click();await saved(p);assert.equal(await p.locator('.paper-card').count(),2);
await p.locator('#nav [data-view=compare]').click();await p.locator('[data-compare-id]').nth(0).check();await p.locator('[data-compare-id]').nth(1).check();assert.equal(await p.locator('table thead th').count(),3);await p.locator('#dimension-form input').fill('Rerank');await p.locator('#dimension-form button').click();await p.locator('[data-custom-paper]').first().fill('Cross-encoder');await p.locator('[data-custom-paper]').first().blur();await saved(p);await p.reload();await p.locator('[data-compare-id]').nth(0).check();await p.locator('[data-compare-id]').nth(1).check();assert.equal(await p.locator('[data-custom-paper]').first().inputValue(),'Cross-encoder');const downloadPromise=p.waitForEvent('download');await p.locator('#compare-export').click();assert.equal((await downloadPromise).suggestedFilename(),'paper-comparison.md');
await p.locator('#nav [data-view=graph]').click();await p.locator('[data-add-entity]').click();await p.locator('#entity-form [name=name]').fill('HotpotQA');await p.locator('#entity-type').selectOption('Dataset');await p.locator('#entity-paper').selectOption({label:fixture.title});await p.locator('#entity-form button.primary').click();await p.locator('[data-add-relation]').click();await p.locator('#relation-form [name=type]').selectOption('evaluated_on');await p.locator('#relation-form [name=to]').selectOption({label:'Dataset · HotpotQA'});await p.locator('#relation-form button.primary').click();assert.ok(await p.locator('.graph-node').count()>4);await p.locator('#nav [data-view=topics]').click();await p.locator('[data-topic=GraphRAG]').click().catch(()=>p.locator('[data-topic=RAG]').click());await p.locator('#topic-notes').fill('Research synthesis');await p.locator('[data-topic-save]').click();await saved(p);
await p.locator('#global-search').fill('compute');assert.ok((await p.locator('#workspace').textContent()).includes('Rejected because'));await p.locator('#global-search').fill('');await p.locator('#nav [data-view=library]').click();await p.locator('[data-paper]').first().click();await p.screenshot({path:'/tmp/pt-research-desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});await p.screenshot({path:'/tmp/pt-research-mobile.png',fullPage:true});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('[data-back-list]').click();assert.ok(await p.locator('.paper-list').isVisible());
const result=await p.evaluate(async()=>{const tools=window.researchTools;let bad=false;try{await tools.import_research_paper.execute({url:''})}catch{bad=true}return {bad,names:Object.keys(tools),matches:tools.search_research_records.execute({query:'compute'}).length}});assert.equal(result.bad,true);assert.ok(result.matches>=1);assert.equal(result.names.length,2);
await p.locator('#sync-open').click();await p.locator('#sync-now').click();await saved(p);const code=await p.locator('#current-code').inputValue();assert.ok(code.length>70);const ctx2=await browser.newContext({viewport:{width:1440,height:1050}});await mock(ctx2);const q=await ctx2.newPage();q.on('pageerror',e=>errors.push(e.message));await q.goto(base);await q.locator('#sync-open').click();await q.locator('#pair-code').fill(code);await q.locator('#connect-code').click();await q.waitForFunction(()=>document.querySelector('#pair-status').textContent.startsWith('已连接'));await q.locator('#sync-dialog [data-close]').click();await q.locator('#nav [data-view=library]').click();assert.equal(await q.locator('.paper-card').count(),2);await q.reload();assert.equal(await q.locator('.paper-card').count(),2);const imported=await p.evaluate(()=>window.researchTools.import_research_paper.execute({url:'2404.00001'}));assert.equal(imported.saved,true);assert.equal(imported.duplicate,false);await p.locator('#sync-dialog [data-close]').click();await p.locator('#nav [data-view=library]').click();assert.equal(await p.locator('.paper-card').count(),3);assert.deepEqual(errors,[]);await ctx2.close();await ctx.close();console.log('Research browser passed: import, extraction, evidence, compare/export/persistence, graph, topics, memory, mobile, WebMCP and cross-device encryption');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();server.close()});
